export const locale = {
  lang: 'de',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE:
        'Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      USERNAME_NOT_FOUND_EXCEPTION: 'Benutzername konnte nicht gefunden werden',
      USER_LOGIN_EXCEPTION: 'Benutzername oder Passwort sind ungültig',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION:
        'Ungültige E-Mail oder ungültiges Passwort',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'Benutzer existiert bereits in der Organisation',
      USER_REGISTRATION_EXCEPTION:
        'Fehler bei der Benutzerregistrierung aufgetreten',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Fehler bei der Generierung des Links zum Zurücksetzen des Passworts aufgetreten',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'Das Konto mit diesen Informationen wurde noch nicht aktiviert. Passwort zurücksetzen kann nicht aktiviert werden',
      PASSWORD_RESET_EXCEPTION:
        'Fehler beim Zurücksetzen des Passworts aufgetreten',
      MAIL_SEND_EXCEPTION: 'Fehler beim Senden einer E-Mail aufgetreten',
      UPDATE_PASSWORD_EXCEPTION: 'Ungültiges aktuelles Passwort',
      TOKEN_REFRESH_EXCEPTION:
        'Ihr Autorisierungs-Token konnte nicht aktualisiert werden',
      USER_LOGOUT_EXCEPTION: 'Fehler beim Abmelden aufgetreten',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'Sie sind nicht berechtigt, auf diese Ressource zuzugreifen',
      FORBIDDEN_EXCEPTION:
        'Sie sind nicht berechtigt, auf diese Ressource zuzugreifen',
      UNAUTHORIZED_EXCEPTION:
        'Sie sind nicht berechtigt, auf diese Ressource zuzugreifen',
      IP_BLOCKED_EXCEPTION:
        'Sie wurden wegen mehrfacher Anmeldeversuche vorübergehend gesperrt',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'Die von Ihnen angegebene E-Mail-Adresse ist bereits in Gebrauch',
      FILE_GENERIC_EXCEPTION:
        'Datei-Fehler. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Das Argument ist nicht gültig. Bitte kontaktieren Sie den Support oder versuchen Sie es später erneut',
      APP_EXCEPTION:
        'Ein Fehler ist aufgetreten. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal.',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'Die Ressource wird bereits verwendet. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Ressource nicht gefunden. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      FILE_NOT_FOUND_EXCEPTION:
        'Datei nicht gefunden. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      BAD_REQUEST_EXCEPTION:
        'Fehlerhafte Anfrage. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Medientyp nicht akzeptabel. Bitte kontaktieren Sie den Support oder versuchen Sie es später noch einmal',
      SESSION_EXPIRED_EXCEPTION:
        'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'Sie sind in keiner Organisation aktiv. Dies bedeutet, dass einer der Administratoren Ihrer Organisation Sie deaktiviert hat. Bitte kontaktieren Sie diese direkt',
      PASSWORD_MISMATCH_EXCEPTION: 'Die Kennwörter stimmen nicht überein.',
      ORGANIZATION_NAME_CONFLICT:
        'Es gibt bereits eine Organisation mit diesem Namen.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'Es gibt bereits eine Organisation mit dieser Website.',
      ORGANIZATION_PHONE_CONFLICT:
        'Es gibt bereits eine Organisation mit diesem Telefon.',
      ORGANIZATION_EMAIL_CONFLICT:
        'Es gibt bereits eine Organisation mit dieser E-Mail.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        'Sie können keinen Angehörigen der Gesundheitsberufe einladen. Sie haben das Limit für Ihr Abonnement erreicht.',
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        'Sie können keinen Begünstigten einladen. Sie haben das Limit für Ihr Abonnement erreicht.',
      ORGANIZATION_VAT_CONFLICT:
        'Es gibt bereits eine Organisation mit dieser Mehrwertsteuer.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'Die Organisation hat das Abonnement nicht angenommen.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'Die Organisation hat kein aktives oder schwebendes Abonnement.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'Die Organisation ist nicht aktiv.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'Der Benutzer ist nicht in der Organisation verifiziert',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'Für diese Termine besteht bereits ein Abonnement.',
      ASSESSMENT_NOT_IN_ORGANIZATION:
        'Sie können für diese Bewertung keine Aktionen ausführen, weil sie nicht von Ihrer Organisation erstellt wurde.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'Sie können diesen Fragebogen nicht bearbeiten, da er nicht von Ihrer Organisation erstellt wurde.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'Für diesen Benutzer gibt es bereits einen Fragebogen.',
      QUESTIONNAIRE_IS_EMPTY:
        'Um einen Fragebogen zuzuordnen, müssen Sie mindestens eine Frage erstellen.',
      SESSION_ALREADY_IN_USE:
        'Es scheint einen gleichzeitigen Anmeldeversuch gegeben zu haben, der eine Sicherheitsabmeldung zur Folge hatte. Bitte melden Sie sich erneut an, um den sicheren Zugriff auf Ihr Konto fortzusetzen.',
    },
    ROUTES_TITLE: {
      HOME: 'Startseite',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'System Admins',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      BENEFICIARIES: 'Begünstigte',
      MEMBERS: 'Mitglieder',
      MEMBER_PROFILE: 'Mitgliedsprofil',
      GUESTS: 'Gäste',
      GUEST_PROFILE: 'Gastprofil',
      MY_PROFILE: 'My profile',
      USER_PROFILE: 'User profile',
      ORGANIZATIONS: 'Organizations',
      ORGANIZATION_PROFILE: 'Organization Profile',
      GAMES: 'Games',
      GAME_MANAGEMENT: 'Game Management',
      GAME_OVERVIEW: 'Spielübersicht',
      SESSION_TEMPLATES: 'Session templates',
      SESSIONS_BY_ELIGENCE: 'Sitzungen von Eligence',
      SESSION_TEMPLATE: 'Session template',
      QUESTIONNAIRE_TEMPLATES: 'Fragebogen Vorlagen',
      QUESTIONNAIRES_BY_ELIGENCE: 'Fragebogen by Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Fragebogen Vorlage',
      ASSIGNED_SESSION: 'Assigned Session',
      ASSIGNED_QUESTIONNAIRE: 'Zugewiesener Fragebogen',
      ADD_SESSION: 'Add Session',
      CREATE_BENEFICIARY: 'Begünstigten Erstellen',
      SUBSCRIPTIONS_MANAGEMENT: 'Αbonnementverwaltung ',
      ELIGENCE_SESSION_TEMPLATES: 'Sitzungen',
      RESELLERS: 'Wiederverkäufer',
      RESELLER_PROFILE: 'Wiederverkäuferprofil',
      GROUPS: 'Gruppen',
      CREATE_GROUP: 'Gruppe erstellen',
      CREATE_MEMBER: 'Mitglied erstellen',
      CREATE_GUEST: 'Gast erstellen',
      GROUP_PROFILE: 'Gruppenprofil',
      ADD_MEETING: 'Neues Meeting starten',
      EDIT_GROUP: 'Gruppe bearbeiten',
      GAME_VARIATIONS: 'Spiel Variationen',
    },
    CONFIRM: {
      DELETE: 'Sind Sie sicher, dass Sie diesen {{name}} löschen wollen?',
      CREATE:
        'Sind Sie sicher, dass Sie einen neuen {{name}} erstellen möchten?',
      EDIT: 'Sind Sie sicher, dass Sie diesen {{name}} bearbeiten wollen?',
      CHANGE: 'Sind Sie sicher, dass Sie die Änderungen speichern möchten?',
      ACTIVATE: 'Sind Sie sicher, dass Sie diesen Benutzer aktivieren wollen?',
      ACTIVATE_ORGANIZATION:
        'Sind Sie sicher, dass Sie diese Organisation aktivieren wollen?',
      DEACTIVATE:
        'Sind Sie sicher, dass Sie diesen Benutzer deaktivieren möchten?',
      DEACTIVATE_ORGANIZATION:
        'Sind Sie sicher, dass Sie diese Organisation deaktivieren möchten?',
      INVITATION:
        'Sind Sie sicher, dass Sie die Einladung für diesen Benutzer erneut senden möchten?',
      INVITATION_ORGANIZATION:
        'Sind Sie sicher, dass Sie die Einladung für diese Organisation erneut versenden möchten?',
      BOOK: 'Sind Sie sicher, dass Sie diesen {{name}} buchen möchten?',
      CANCEL_BOOKING:
        'Sind Sie sicher, dass Sie die Buchung mit diesem Benutzer stornieren möchten?',
      UPDATE_MAIL_WARNING:
        'Sind Sie sicher, dass Sie Ihre E-Mail-Adresse ändern möchten? Denken Sie daran, dass Ihr Benutzername Ihre neue E-Mail-Adresse sein wird.',
      ACTIVATE_GAME:
        'Sind Sie sicher, dass Sie dieses Spiel aktivieren wollen?',
      ACTIVATE_GAME_TEMPLATE:
        'Sind Sie sicher, dass Sie diese Kategorie von Spielen aktivieren möchten?',
      DEACTIVATE_GAME:
        'Sind Sie sicher, dass Sie dieses Spiel deaktivieren wollen?',
      DEACTIVATE_GAME_WARNING:
        'Dieses Spiel ist derzeit in {{sessions}} Sitzungen, {{beneficiaries}} Begünstigten, {{sessionTemplates}} Sitzungsvorlagen zugewiesen, {{systemAssignedSessions}} Sitzungen von Eligence, {{systemSessionTemplates}} Sitzungsvorlagen von Eligence, {{groupAssignedSessions}} Gruppensitzungen. Sind Sie sicher, dass Sie es deaktivieren möchten?',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'Diese Spielekategorie ist derzeit in {{sessions}} Sitzungen, {{beneficiaries}} Begünstigten, {{sessionTemplates}} Sitzungsvorlagen zugewiesen, {{systemAssignedSessions}} Sitzungen von Eligence, {{systemSessionTemplates}} Sitzungsvorlagen von Eligence, {{groupAssignedSessions}} Gruppensitzungen. Sind Sie sicher, dass Sie es deaktivieren möchten?',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'Dieses Spiel ist derzeit in {{sessions}} aktiven Sitzungen zugewiesen, {{systemAssignedSessions}} Sitzungen von Eligence, {{groupAssignedSessions}} Gruppensitzungen. Sind Sie sicher, dass Sie es deaktivieren möchten?',
      REMOVE_PATIENT:
        'Sind Sie sicher, dass Sie diesen Begünstigten aus dem Kreis der Angehörigen der Gesundheitsberufe entfernen wollen?',
      CLOSE_SESSION: 'Sind Sie sicher, dass Sie diese Sitzung beenden möchten?',
      DELETE_SESSION:
        'Sind Sie sicher, dass Sie diese Sitzung löschen möchten?',
      DELETE_QUESTIONNAIRE:
        'Sind Sie sicher, dass Sie diesen Fragebogen löschen möchten?',
      REMOVE_HEALTH_PROFESSIONAL:
        'Sind Sie sicher, dass Sie diesen Angehörigen der Gesundheitsberufe aus diesem Begünstigten entfernen möchten?',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        'Sind die Spiele in der bevorzugten Reihenfolge des Erscheinens? Haben Sie den gewünschten Schwierigkeitsgrad pro Spiel gewählt?',
      CANCEL:
        'Sind Sie sicher, dass Sie diesen Vorgang stornieren möchten {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Durch das Löschen eines Abschnitts werden auch alle Fragen in diesem Abschnitt gelöscht. Bist du dir sicher, dass du weitermachen willst?',
    },
    SUCCESS: {
      CREATE: '{{name}} erfolgreich erstellt',
      EDIT: '{{name}} erfolgreich bearbeitet',
      UPDATE: '{{name}} erfolgreich aktualisiert',
      DELETE: '{{name}} erfolgreich gelöscht',
      ADD: '{{name}} erfolgreich hinzugefügt',
      ASSIGN: '{{name}} erfolgreich zugewiesen',
      ACTIVATE: '{{name}} erfolgreich aktiviert',
      REQUEST: '{Anfrage erfolgreich gesendet',
      DEACTIVATE: '{{name}} erfolgreich deaktiviert',
      REGISTER:
        'Sie haben sich erfolgreich registriert. Sie erhalten eine E-Mail an Ihre E-Mail-Adresse, um Ihr Passwort festzulegen.',
      CLONE: '{{name}} erfolgreich geklont',
      CLOSE: '{{name}} erfolgreich geschlossen',
      CANCEL: '{{name}} erfolgreich gelöscht',
      INVITE: '{{name}} erfolgreich eingeladen',
      RESET: 'Ihr Passwort wurde erfolgreich zurückgesetzt',
      FORGOT:
        'Es wurde eine E-Mail an Ihre E-Mail-Adresse gesendet. Folgen Sie den Anweisungen, um Ihr Passwort zurückzusetzen',
      REMOVE: '{{name}} erfolgreich entfernt',
      PASSWORD_CHANGE: 'Ihr Passwort wurde erfolgreich geändert',
      AMEND: '{{name}} erfolgreich geändert',
      RESEND: '{{name}} erfolgreich zurückgesendet',
      RESET_OTP: 'Einmaliges Passwort erfolgreich zurückgesetzt.',
      UPGRADE: '{{name}} erfolgreich aktualisiert',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Organisation hinzufügen',
      ADD_PATIENT: 'Begünstigten hinzufügen',
      ADD_HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft hinzufügen',
      ADD_ORGANIZATION_ADMIN: 'Organisation hinzufügen Verwaltung',
      ADD_MEMBER: 'Mitglied hinzufügen',
      INVITE_MEMBER: 'Mitglied einladen',
      ADD_GUEST: 'Gast hinzufügen',
      ORGANIZATION: 'Organisation',
      HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft',
      ASSIGN_PATIENTS: 'Begünstigte zuweisen',
      ASSIGN_HEALTH_PROFESSIONALS: 'Gesundheitsfachkräfte zuweisen',
      ASSIGN_MEMBERS: 'Mitglieder Zuweisen',
      ASSIGN_GUESTS: 'Gäste Zuweisen',
      PATIENT: 'Begünstigter',
      EDIT_PROFILE: 'Edit Profile',
      SELECT_ORGANIZATION: 'Organisation auswählen',
      UPLOAD_FILE: 'Hochladen einer Datei für',
      GAME_FILE: 'Spiel-Datei',
      ALLOWED_FILE_TYPES: 'Erlaubte Dateitypen: zip',
      UPDATE_PASSWORD: 'Passwort aktualisieren',
      CREATE_SESSION: 'Sitzung erstellen',
      ASSIGN_SESSION_TEMPLATE: 'Sitzungsvorlage zuweisen',
      SUBSCRIPTION_DETAILS: 'Details zum Abonnement',
      INACTIVE_SUBSCRIPTION: 'Inaktives Abonnement',
      EDIT_INFORMATION: 'Informationen bearbeiten',
      INVOICE_INFO: 'Rechnungsinformationen',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Fragebogen-Vorlage hinzufügen',
      QUESTIONNAIRE_TEMPLATE: 'Fragebogen vorlage',
      WARNING: 'Warning',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'Um einen Fragebogen zuzuordnen, müssen Sie mindestens eine Frage erstellen.',
      ADD_NOTE: 'Create Note',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Fragebogen Vorlage zuweisen',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'Um einen Fragebogen in der Vorschau anzuzeigen, muss er mindestens einen Abschnitt und eine Frage enthalten.',
      RESET_PASSWORD: 'Einmaliges Passwort neu generieren',
      GENERATE_REPORT: 'Bericht erstellen',
      ACTIVITY_DISPLAY_OPTIONS: 'Optionen für die Aktivitätsanzeige',
      UPGRADE_ORGANIZATION: 'Organisationsupgrade',
      ADD_RESELLER_ADMIN: 'Verwaltung hinzufügen',
      GAME_VARIATIONS: 'Spiel Variationen',
      ASSIGN_PRIVATE_GAME: 'Privates Spiel zuweisen',
      ASSIGN_PUBLIC_GAME: 'Öffentliches Spiel zuweisen',
      MEETING_MEMBERS: 'Meeting Members',
    },
    ERROR: {
      IMAGE: 'Die von Ihnen ausgewählte Datei ist kein Bild',
      RESOURCE:
        'Sie können auf diese Ressource nicht zugreifen, wenn Sie bereits eingeloggt sind',
      GENERAL:
        'Es wurden leider einige Fehler entdeckt, bitte versuchen Sie es erneut.',
      FILE: 'Die von Ihnen ausgewählte Datei wird nicht unterstützt',
      PAGE_NOT_FOUND: 'Seite nicht gefunden',
      PAGE_NOT_FOUND_BODY: 'Die angeforderte URL wurde nicht gefunden',
    },
    BUTTONS: {
      CREATE: 'Neu erstellen',
      CONFIRM_ACTION: 'Bestätigen Sie die Aktion',
      ADD_EXERCISES: 'Spiele hinzufügen',
      DELETE: 'Löschen',
      VIEW: 'Siehe',
      APPLY: 'Bewerbung',
      EDIT: 'bearbeiten',
      BACK: 'Zurück',
      CANCEL: 'Abbrechen',
      CONTINUE: 'Weiter',
      LOGIN: 'Anmeldung',
      REGISTER: 'Register',
      SAVE: 'Speichern',
      SUBMIT: 'Einreichen',
      ACTIVATE: 'Aktivieren',
      DEACTIVATE: 'Deaktivieren',
      PLAY: 'Spielen',
      CONFIRM: 'Bestätigen Sie',
      ACCEPT: 'Akzeptieren',
      DECLINE: 'Rückgang',
      NEXT_STEP: 'Nächster Schritt',
      PREVIOUS_STEP: 'Vorherige',
      ADD: 'Neu hinzufügen',
      RESET: 'Zurücksetzen',
      UPLOAD_PHOTO: 'Foto hochladen',
      EDIT_PHOTO: 'Foto bearbeiten',
      RESEND_INVITATION: 'Einladung erneut senden',
      ASSIGN: 'zuweisen',
      EDIT_PROFILE: 'Profil bearbeiten',
      DISCARD: 'Ablegen',
      DONE: 'Erledigt',
      ADD_ORGANIZATION: 'Organisation hinzufügen',
      ADD_PATIENT: 'Begünstigten hinzufügen',
      ADD_MEMBER: 'Mitglied hinzufügen',
      ADD_GUEST: 'Gast hinzufügen',
      ADD_HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft hinzufügen',
      ADD_ORGANIZATION_ADMIN: 'Organisation hinzufügen Verwaltung',
      ADD_SESSION: 'Sitzung hinzufügen',
      ASSIGN_PATIENTS: 'Begünstigte zuweisen',
      ASSIGN_HEALTH_PROFESSIONALS: 'Gesundheitsfachkräfte zuweisen',
      ASSIGN_MEMBERS: 'Mitglieder Zuweisen',
      ASSIGN_GUESTS: 'Gäste Zuweisen',
      ACTIONS: 'Aktionen',
      LOADING: 'Laden...',
      GO_TO_HOMEPAGE: 'Zur Homepage gehen',
      ASSIGN_NEW_SESSION: 'Neue Session Zuweisen',
      ASSIGN_NEW_QUESTIONNAIRE: 'Neuen Fragebogen zuweisen',
      CLOSE: 'Schließen Sie',
      SHOW_MORE: 'Mehr anzeigen',
      SHOW_LESS: 'Weniger anzeigen',
      CONFIRM_SUBSCRIPTION: 'Bestätigen Sie Ihr Abonnement',
      REJECT_SUBSCRIPTION: 'Abonnement ablehnen',
      NEW_SUBSCRIPTION: 'Neues Abonnement',
      ADD_QUESTIONNAIRE: 'Fragebogen hinzufügen',
      PREVIEW: 'Vorschauen',
      ADD_ANSWER: 'Option Hinzufügen',
      GOT_IT: 'Verstanden',
      ADD_NOTE: 'Anmerkung Hinzufügen',
      EXPORT_RESULTS: 'Ergebnisse Exportieren',
      SAVE_AND_CONTINUE: 'Speichern und Weiter',
      RESET_PASSWORD: 'Einmaliges Passwort neu generieren',
      RESET_ONE_TIME_PASSWORD: 'Einmaliges Passwort neu generieren',
      CREATE_BENEFICIARY: 'Begünstigten Erstellen',
      CREATE_MEMBER: 'Mitglied erstellen',
      CREATE_GUEST: 'Gast erstellen',
      CHANGE_PASSWORD: 'Passwort ändern',
      COMPLETE: 'Beenden',
      GENERATE_REPORT: 'Bericht erstellen',
      START_NOW: 'Jetzt anfangen!',
      REPLAY: 'Wiederholen Sie',
      START_SESSION: 'Sitzung beginnen',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Verwaltung hinzufügen',
      CREATE_GROUP: 'Gruppe erstellen',
      ADD_MEETING: 'Neues Meeting starten',
      STOP: 'Sitzung beenden',
      START_MEETING: 'Treffen einleiten',
    },
    INPUT: {
      NAME: 'Name',
      EMAIL: 'E-Mail',
      EMAIL_USERNAME: 'E-Mail (Benutzername)',
      PLACE: 'Ort',
      VAT: 'MEHRWERTSTEUER',
      FIRST_NAME: 'Vorname',
      STREET_ADDRESS: 'Straße und Hausnummer',
      LAST_NAME: 'Nachname',
      FULL_NAME: 'Vollständiger Name',
      PASSWORD: 'Passwort',
      PATIENT_LIST: 'Liste der Begünstigten',
      HEALTH_PROFESSIONAL_LIST: 'Liste der Angehörigen der Gesundheitsberufe',
      ORGANIZATION_NAME: 'Name der Organisation',
      ORGANIZATION_EMAIL: 'Unternehmen Rechnungskontakt E-Mail',
      ORGANIZATION_ACTIVITY: 'Tätigkeit',
      CONFIRM_PASSWORD: 'Bestätigen Sie Ihr Passwort',
      CITY: 'Stadt',
      HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft',
      POSTAL_CODE: 'Postleitzahl',
      COUNTRY: 'Land',
      ADDRESS: 'Adresse',
      COMPANY: 'Unternehmen',
      BIRTH_DATE: 'Geburtsdatum',
      WEBSITE: 'Website',
      PHONE: 'Rufnummer',
      ROLE: 'Rolle',
      SERVICE: 'Dienst',
      PREFERRED_LANGUAGE: 'Bevorzugte Sprache',
      PREFERRED_ACCOUNT_TYPE: 'Bevorzugter Kontotyp',
      ADDRESS_INFO: 'Adresse Info',
      COMPANY_NAME: 'Name des Unternehmens',
      DESCRIPTION: 'Beschreibung',
      TYPE: 'Typ',
      PRICE: 'Preis',
      FEATURES: 'Eigenschaften',
      TITLE: 'Titel',
      TAGS: 'Tags',
      ACCOUNT_STATUS: 'Konto-Status',
      IMAGE: 'Bild',
      VERSION: 'Version',
      ACTIVITY: 'Tätigkeit',
      OLD_PASSWORD: 'Altes Passwort',
      NEW_PASSWORD: 'Neues Passwort',
      CONFIRM_NEW_PASSWORD: 'Neues Passwort bestätigen',
      SESSION_NAME: 'Session Name',
      INFO: 'Info',
      HEALTH_PROFESSIONAL_INFO: 'Infos für Gesundheitsfachkräfte',
      PATIENT_INFO: 'Informationen für den Begünstigten',
      AGREE_THE: 'Ich akzeptiere die',
      TERMS_AND_CONDITIONS: 'Bedingungen und Konditionen',
      SESSION_TEMPLATE_LIST: 'Session Template List',
      SAVE_AS_TEMPLATE: 'Als Vorlage speichern',
      BIRTH_YEAR: 'Geburtsjahr',
      SEX: 'Geschlecht',
      ACCOUNT_TYPE: 'Konto-Typ',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      BENEFICIARIES: 'Begünstigte',
      SUBSCRIPTION_DURATION: 'Dauer des Abonnements',
      START_DATE: 'Startdatum',
      EXTENSION_DURATION: 'Verlängerung Dauer',
      STARTING_LICENSE: 'Startlizenz',
      ANNUAL_FEE: 'Jährliche Gebühr',
      SUPPORT_SERVICES: 'Unterstützungsdienste',
      MONTHLY_COST_PER_BENEFICIARY: 'Monatliche Kosten pro Begünstigtem',
      NOTES: 'Einige Informationen für uns',
      LATEST_OCCUPATION: 'Letze Beruf',
      EDUCATION_YEARS: 'Ausbildungsjahre',
      QUESTIONNAIRE_NAME: 'Name des Fragebogens',
      WRITE_YOUR_ANSWER: 'Schreibe deine Antwort',
      REQUIRED: 'Erforderlich',
      SECTION_NAME: 'Abteilungsname',
      QUESTION: 'Frage',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Schriftliche antwort...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'Die Antwort musst nur Zahlen enthalten.',
      HEALTH_PROFESSIONAL_NOTES: 'Health Professional notes',
      NOTE_TEXT: 'Note text',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Fragebogen Vorlage Liste',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'Einmaliges Passwort',
      CREATE_BENEFICIARY_CONSENT:
        'Ich habe das Einverständnis des Begünstigten, mit der Registrierung seiner persönlichen Daten und seiner Anmeldung auf der Eligence-Plattform fortzufahren',
      I_HAVE_THE_BENEFICIARY_CONSENT:
        'Ich habe die Zustimmung des Begünstigten zur Änderung seines Passworts',
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Beschreiben Sie Ihre derzeitige Lebenssituation',
      SELECT_TIME_PERIOD: 'Zeitspanne',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Zeitspanne',
      CURRENT_PASSWORD: 'Aktuelles Passwort',
      ACTIVITY_DISPLAY_OPTION: 'Option Aktivitätsanzeige',
      GROUP_NAME: 'Gruppenname',
      MEETING_NAME: 'Name des Treffens',
    },
    PLACEHOLDERS: {
      ALL: 'Alle',
      TOTAL_ELEMENTS: 'Elemente insgesamt',
      SELECT_RESELLERS: 'Wählen Sie Wiederverkäufer',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Suche',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'Vorname',
      NOTES: 'Anmerkungen',
      LAST_NAME: 'Nachname',
      PATIENTS: 'Begünstigte',
      SESSIONS: 'Sitzungen',
      USER: 'Benutzer',
      EMAIL: 'E-Mail',
      JOINED_DATE: 'Datum des Beitritts',
      COMPANY: 'Unternehmen',
      NAME: 'Name',
      STATUS: 'Status',
      EXECUTIONS: 'Vollstreckungen',
      COMPLETE_SESSIONS: 'Abgeschlossene Sitzungen',
      LAST_LOGIN: 'Letzte Anmeldung',
      ACCOUNT_TYPE: 'Konto-Typ',
      ID: 'Id',
      CATEGORY: 'Kategorie',
      PRODUCT: 'Produkt',
      ACTIONS: 'Aktionen',
      DESCRIPTION: 'Beschreibung',
      CREATED: 'Erstellt',
      COMPLETED: 'Abgeschlossen',
      COUNTRY: 'Land',
      LANGUAGE: 'Sprache',
      ROLE: 'Rolle',
      ADDRESS: 'Adresse',
      POSTAL_CODE: 'Postleitzahl',
      CITY: 'Stadt',
      ESCORT: 'Begleitung',
      ADMIN: 'Verwaltung',
      DATE: 'Date',
      TIME: 'Zeit',
      DURATION: 'Dauer',
      ADDED: 'Hinzugefügt',
      ORGANIZATION: 'Organisation',
      EXERCISE: 'Spiel',
      VERSION: 'Version',
      LEVELS: 'Ebenen',
      COGNITIVE: 'Kognitive Fähigkeiten',
      CATEGORIES: 'Kategorien',
      ENGINE: 'Motor',
      HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft',
      ASSIGNED_PATIENTS: 'Zugewiesene Begünstigte',
      PATIENT: 'Begünstigter',
      OPEN_SESSIONS: 'Open Sessions',
      SESSION: 'Sitzung',
      ORDER: 'Bestellung',
      GAMES: 'Spiele',
      LAST_EDIT: 'Letzte Bearbeitung',
      CREATOR: 'Schöpfer',
      ADDED_EXERCISES: 'Zusätzliche Spiele',
      DIFFICULTY: 'Schwierigkeitsgrad',
      ASSIGNED_BY: 'Zugewiesen von',
      GAME: 'Spiel',
      SCORE: 'Punktzahl',
      PROGRESS: 'Fortschritt',
      BENEFICIARIES: 'Begünstigte',
      LATEST_EXECUTION: 'Letzte Ausführung',
      COGNITIVES: 'Kognitive',
      TYPE: 'Typ',
      STARTED: 'Gestartet',
      ENDS: 'Ends',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      QUESTIONNAIRE: 'Fragebogen',
      DATE_ASSIGNED: 'Date Assigned',
      DATE_COMPLETED: 'Date Completed',
      SECTIONS: 'Sections',
      START_DATE: 'Startdatum',
      EXTENSION_DAYS: 'Verlängerungstage',
      END_DATE: 'Enddatum',
      EXTENSION_DATE: 'Verlängerungsdatum',
      TOTAL_COST_OF_SUBSCRIPTION: 'Gesamtkosten des Abonnements',
      DURATION_OF_SUBSCRIPTION: 'Laufzeit des Abonnements',
      TERMINATION_DATE: 'Kündigungsdatum',
      INVITATION_SENT: 'Einladung gesendet',
      SUBSCRIPTION_SENT: 'Abonnement gesendet',
      ACTIVITY_DISPLAY_OPTION: 'Option für die Aktivitätsanzeige',
      INVITED_BY: 'Εingeladen von',
      GROUP: 'Gruppe',
      MEMBERS: 'Mitglieder',
      GUESTS: 'Gäste',
      MEETINGS: 'Sitzungen',
      MEETING: 'Treffen',
      VARIATIONS: 'Variationen',
      ACTIVATED: 'Aktivierte',
      ASSIGNMENT: 'Zuweisung',
      INDIVIDUAL_EXECUTIONS: 'Vollstreckungen (individuell)',
      GROUP_EXECUTIONS: 'Vollstreckungen (Gruppen)',
    },
    VALIDATION: {
      INVALID: '{{name}} ist ungültig',
      REQUIRED: '{{name}} ist erforderlich',
      MIN_LENGTH: '{{name}} sollte mindestens 3 Symbole haben',
      MAX_LENGTH: '{{name}} sollte maximal 256 Symbole haben',
      MAX_LENGTH_NOTES: '{{name}} sollte maximal 480 Symbole haben',
      MIN_LENGTH_PASS: '{{name}} sollte mindestens 8 Symbole haben',
      AGREEMENT_REQUIRED:
        'Das Akzeptieren der Geschäftsbedingungen ist erforderlich',
      NOT_FOUND: 'Der angeforderte {{name}} wird nicht gefunden',
      INVALID_LOGIN: 'Die Anmeldedaten sind falsch',
      REQUIRED_FIELD: 'Erforderliches Feld',
      MIN_LENGTH_FIELD: 'Minimale Feldlänge:',
      MAX_LENGTH_FIELD: 'Maximale Feldlänge:',
      INVALID_FIELD: 'Feld ist nicht gültig',
      MUST_MATCH:
        'Die Felder Passwort und Passwortbestätigung stimmen nicht überein',
      MUST_MATCH_PIN: 'Die Felder Pin und Confirm Pin stimmen nicht überein',
      NO_PRIMARY: 'Sie haben keinen primären {{name}} festgelegt',
      NO_STATUS: 'Sie haben den Status {{name}} nicht gesetzt',
      MANY_PRIMARY: 'Sie haben mehr als einen primären {{name}} eingestellt',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Dashboard',
        SYSTEM: 'System',
      },
      HOME: 'Startseite',
      USER_PROFILE: 'Mein Profil',
      ACCOUNT_SETTINGS: 'Kontoeinstellungen',
      LANGUAGE: 'Sprache',
      LOGOUT: 'Abmeldung',
      NOTIFICATIONS: 'Benachrichtigungen',
      SUBSCRIPTIONS: 'Abonnements',
      ORGANIZATION: 'Organisation',
      SESSIONS: 'Sitzungen',
      GAMES: 'Spiele',
      GAMES_MANAGEMENT: 'Spiele Management',
      PATIENTS: 'Begünstigte',
      GUESTS: 'Gäste',
      MEMBERS: 'Mitglieder',
      ORGANIZATIONS: 'Organisationen',
      MY_ORGANIZATION: 'Organisationsmanagement',
      ADMINS: 'Admins',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      SIGN_OUT: 'Abmelden',
      QUESTIONNAIRES: 'Fragebögen',
      ELIGENCE_SESSION_TEMPLATES: 'Sitzungen',
      TEMPLATES: 'Vorlagen',
      BY_ELIGENCE: 'Von Eligence',
      RESELLERS: 'Wiederverkäufer',
      HELP: 'Hilfe',
      GROUPS: 'Gruppen',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Datenschutzbestimmungen',
      TERMS_AND_CONDITIONS: 'Bedingungen und Konditionen',
      COOKIE_POLICY: 'Cookie Policy',
      CONTACT: 'Kontakt',
    },
    GAME_DIFFICULTY: {
      EASY: 'Einfach',
      INTERMEDIATE: 'Zwischenbericht',
      HARD: 'Schwierig',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Individuell',
      GROUP_MEETING: 'Gruppentreffen',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Heute',
      THIS_WEEK: 'Diese Woche',
      THIS_MONTH: 'Dieser Monat',
      LAST_7_DAYS: 'Letzte 7 Tage',
      LAST_30_DAYS: 'Letzte 30 Tage',
      CUSTOM: 'Benutzerdefiniert',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Gedächtnis',
      LANGUAGE: 'Sprache',
      ATTENTION: 'Achtung',
      CONSTRUCTIVE_ABILITY: 'Konstruktive Fähigkeit',
      EXECUTIVE_FUNCTIONS: 'Exekutive Funktionen',
      LOGICAL_REASONING: 'Logisches Denken',
      ORIENTATION: 'Orientierung',
      CHALLENGE: 'Herausforderung',
      FOR_TWO: 'Für zwei',
      GROUPS: 'Gruppen',
      INTERGENERATION: 'Generationenübergreifend',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Gäste',
      NON_GUEST: 'Mitglieder',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Konto-Typ',
      ACCOUNT_TYPE_DESCRIPTION: 'Wählen Sie Ihren Kontotyp',
      ORGANIZATION_INFO: 'Organisation Info',
      ORGANIZATION_INFO_DESCRIPTION: 'Organisationsinformationen einrichten',
      INVOICING_DETAILS: 'Details zur Rechnungsstellung',
      INVOICING_DETAILS_DESCRIPTION: 'Rechnungsdetails einrichten',
      SETUP_ACCOUNT: 'Konto einrichten',
      SETUP_ACCOUNT_DESCRIPTION: 'Einrichten Ihrer Kontodaten',
      COMPLETED: 'Abgeschlossen',
      CHOOSE_ACCOUNT_TYPE: 'Kontotyp wählen',
      SMALL_ORGANIZATION: 'Kleine Organisation',
      SMALL_ORG_HEALTH_PROF_PATIENTS:
        '1 Gesundheitsfachkraft / 1-10 Leistungsempfänger',
      MEDIUM_ORGANIZATION: 'Mittlere Organisation',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS:
        '1-10 Angehörige der Gesundheitsberufe / 1-50 Leistungsempfänger',
      BIG_ORGANIZATION: 'Große Organisation',
      BIG_ORG_HEALTH_PROF_PATIENTS:
        '1-50 Angehörige der Gesundheitsberufe / 1-200 Leistungsempfänger',
      REGISTRATION:
        'Eine E-Mail wurde an den Nutzer geschickt, um sein Konto zu aktivieren.',
      DONE: 'Ihr Konto wurde aktiviert.',
      DONE_DESCRIPTION:
        'Bitte klicken Sie auf die Schaltfläche unten, um sich einzuloggen!',
      MERGE_DONE:
        'Sie sind bereits bei einer anderen Organisation registriert. Jedes Mal, wenn Sie sich anmelden, können Sie wählen, mit welcher Organisation Sie interagieren möchten',
      SESSION_INFO: 'Session Info',
      SESSION_INFO_STEPPER: 'Benennen Sie Ihre Sitzung',
      EXERCISES: 'Spiele',
      EXERCISES_STEPPER: 'Spiele hinzufügen',
      COMPLETION: 'Fertigstellung',
      COMPLETION_STEPPER: 'Einpacken!',
      SESSION_INFO_DESCRIPTION:
        'Benennen Sie Ihre Sitzung und machen Sie sich Notizen, wenn Sie möchten!',
      SESSION_EXERCISES: 'Übungen',
      SESSION_EXERCISES_DESCRIPTION:
        'Spiele zu Ihrer Sitzung hinzufügen und sie verändern',
      ADD_EXERCISES: 'Spiele hinzufügen',
      ADDED_EXERCISES: 'Zusätzliche Spiele',
      CREATE_SESSION_COMPLETION: 'Ein letzter Schritt!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Einpacken!',
      OVERVIEW: 'Übersicht',
      OVERVIEW_BENEFICIARIES: 'Übersicht der Begünstigten',
      OVERVIEW_SESSIONS: 'Übersicht der Sitzungen',
      HEALTH_PROFESSIONAL_INFO: 'Infos für Gesundheitsfachkräfte',
      PATIENT_INFO: 'Informationen für den Begünstigten',
      SESSION_NOTES: 'Anmerkungen',
      SESSION_NOTES_DESCRIPTION: 'Fügen Sie einige Informationen hinzu!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Wählen Sie Ihren Kontotyp',
      SUBSCRIPTION_DETAILS: 'Details zum Abonnement',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Details zum Abonnement einrichten',
      NOTES: 'Anmerkungen',
      NOTES_DESCRIPTION: 'Notizen hinzufügen',
      OVERVIEW_DESCRIPTION: 'Ein letzter Blick',
      GROUP_INFO: 'Infos zur Gruppe',
      BENEFICIARIES: 'Begünstigte',
      GROUP_INFO_DESCRIPTION:
        'Gebt eurer Gruppe einen Namen und macht euch Notizen, wenn ihr wollt!',
      GROUP_BENEFICIARIES_DESCRIPTION:
        'Füge Begünstigte zu deiner Gruppe hinzu',
      ADD_BENEFICIARIES: 'Begünstigte hinzufügen',
      ADDED_BENEFICIARIES: 'Begünstigte hinzugefügt',
      CREATE_GROUP_COMPLETION: 'Ein letzter Schritt!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Einpacken!',
      MEETING_INFO: 'Meetinginformationen',
      MEMBERS: 'Mitglieder',
      SESSIONS: 'Sitzungen',
      MEETING_INFO_DESCRIPTION:
        'Benennen Sie Ihr Treffen und machen Sie sich Notizen, wenn Sie möchten! ',
      MEETING_SESSIONS_DESCRIPTION: 'Beschreibung der Sitzungen des Meetings',
      ADD_SESSIONS: 'Sitzungen hinzufügen',
      ADDED_SESSIONS: 'Hinzugefügte Sitzungen',
      GAMES: 'Spiele',
      ASSIGN_GAMES: 'Spiele zuweisen',
    },
    INFO: {
      INFO: 'Wenn Sie weitere Informationen benötigen, besuchen Sie bitte',
      HELP: 'Hilfe-Seite',
    },
    ACTIONS: {
      ACTIONS: 'Aktionen',
      VIEW: 'Siehe',
      VIEW_PROFILE: 'Profil ansehen',
      VIEW_SESSION: 'Sitzung ansehen',
      ACTIVATE: 'Aktivieren',
      DEACTIVATE: 'Deaktivieren',
      DELETE: 'Löschen',
      ASSIGN_PATIENTS: 'Begünstigte zuweisen',
      ASSIGN_HEALTH_PROFESSIONALS: 'Gesundheitsfachkräfte zuweisen',
      RESEND_INVITATION: 'Einladung erneut senden',
      PREVIEW: 'Vorschau',
      UPLOAD_FILE: 'Spiel hochladen',
      REMOVE_PATIENT: 'Begünstigten entfernen',
      SET_TO_ACTIVE: 'Auf Aktiv setzen',
      EDIT: 'bearbeiten',
      REMOVE: 'entfernen',
      FROM_TEMPALTE: 'Von Vorlage',
      CREATE_NEW: 'Neu erstellen',
      CLONE: 'Klonen',
      CLOSE: 'Schließen Sie',
      CANNOT:
        'Sie können für diese Sitzung keine Aktionen durchführen, da sie von einer anderen medizinischen Fachkraft zugewiesen wurde.',
      AMENDMENT: 'Abänderung',
      TERMINATE: 'Beenden Sie',
      NEW_SUBSCRIPTION: 'Neues Abonnement',
      RESEND_EMAIL: 'E-Mail erneut senden',
      REMOVE_HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft entfernen',
      RENEW: 'Renew',
      ASSIGN: 'Zuweisen',
      UNASSIGN: 'Aufheben der Zuweisung',
      CANCEL: 'Cancel',
      INVITE: 'Invite',
      CREATE: 'Create',
      RESET_PASSWORD: 'Einmaliges Passwort neu generieren',
      ACTIVITY_DISPLAY_OPTIONS: 'Optionen für die Aktivitätsanzeige',
      UPGRADE: 'Aktualisierung',
      VIEW_MEMBERS: 'Mitglieder anzeigen',
      START_MEETING: 'Treffen beginnen',
    },
    AUTH: {
      SIGN_IN: 'Eintragen',
      NEW_HERE: 'Neu hier?',
      SIGNUP: 'Anmeldung',
      FORGOT_BUTTON: 'Passwort vergessen?',
      ABOUT: 'Über',
      CONTACT: 'Kontakt',
      CONTACT_US: 'Kontakt',
      FORGOT_PASSWORD: 'Passwort vergessen',
      RESET_PASSWORD: 'Passwort zurücksetzen',
      SET_PASSWORD: 'Passwort festlegen',
      SETUP_YOUR_NEW_PASSWORD: 'Richten Sie Ihr neues Passwort ein',
      AN_EMAIL_IS_REQUIRED: 'Eine E-Mail ist erforderlich.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'Wenn Ihr Konto mit einem Benutzernamen erstellt wurde, wenden Sie sich bitte an Ihren medizinischen Betreuer oder den Administrator Ihrer Organisation.',
    },
    PROFILE: {
      OVERVIEW: 'Übersicht',
      SETTINGS: 'Einstellungen',
      NOTES: 'Anmerkungen',
      EDIT_PROFILE: 'Edit Profile',
      DETAILS: 'Einzelheiten',
      INFORMATION: 'Information',
      NAME: 'Name',
      FULL_NAME: 'Vollständiger Name',
      ROLE: 'Rolle',
      CONTACT_PHONE: 'Kontakt Telefon',
      EMAIL: 'E-Mail',
      COUNTRY: 'Land',
      POSTAL_CODE: 'Postleitzahl',
      ADDRESS: 'Adresse',
      TAX_ID: 'Steuer-ID',
      STATUS: 'Status',
      EDIT: 'bearbeiten',
      PASSWORD_RESET: 'Passwort zurücksetzen',
      RESEND_PASSWORD_INVITATION: 'Einladung zum erneuten Senden des Passworts',
      ASSIGNED_PATIENTS: 'Zugewiesene Begünstigte',
      ACCOUNT_ID: 'Konto-ID',
      BILLING_EMAIL: 'E-Mail für die Rechnungsstellung',
      LAST_EDIT: 'Letzte Bearbeitung',
      CREATED_BY: 'Erstellt von',
      BILLING_ADDRESS: 'Rechnungsadresse',
      ADMINS: 'Admins',
      PAYMENT_RECORDS: 'Zahlungsaufzeichnungen',
      PAYMENT_METHODS: 'Zahlungsarten',
      PERFORMANCE: 'Leistung',
      FIRST_NAME: 'Vorname',
      LAST_NAME: 'Nachname',
      PHONE_NUMBER: 'Rufnummer',
      PREFERRED_LANGUAGE: 'Bevorzugte Sprache',
      VAT: 'MEHRWERTSTEUER',
      ACTIVITY: 'Tätigkeit',
      WEBSITE: 'Website',
      CREATED_SESSIONS: 'Erstellte Sitzungen',
      EMAIL_UPDATE_TOOLTIP:
        'Beachten Sie, dass Ihr Benutzername Ihre neue E-Mail-Adresse sein wird.',
      CHANGE_PASSWORD: 'Passwort ändern',
      SESSIONS: 'Sitzungen',
      ADDED_EXERCISES: 'Zusätzliche Spiele',
      SESSION_EXECUTIONS_TOOLTIP:
        'Diese Sitzung wurde {{Anzahl}} Mal ausgeführt',
      BIRTH_YEAR: 'Geburtsjahr',
      SEX: 'Geschlecht',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Zugewiesene Gesundheitsfachkräfte',
      ASSIGNED_MEMBERS: 'Zugewiesene Mitglieder',
      ASSIGNED_GUESTS: 'Zugewiesene Gäste',
      SUBSCRIPTIONS: 'Abonnements',
      CURRENT_SUBSCRIPTION: 'Aktuelles Abonnement',
      SUBSCRIPTIONS_HISTORY: 'Geschichte der Abonnements',
      SUBSCRIPTION: 'Abonnement',
      UPCOMING_SUBSCRIPTION: 'Bevorstehendes Abonnement',
      EMAIL_USERNAME: 'Email (Username)',
      LATEST_OCCUPATION: 'Latest Occupation',
      EDUCATION_YEARS: 'Education in Years',
      INVOICE_INFO: 'Invoice Info',
      EXECUTIONS: 'Executions',
      MEMBER_SINCE: 'Member Since',
      QUESTIONNAIRES: 'Fragebögen',
      ASSIGNED: 'Assigned',
      COMPLETED: 'Completed',
      ANSWERS: 'Answers',
      PASSWORD: 'Passwort',
      USERNAME: 'Username',
      STAYING_STATUS: 'Beschreiben Sie Ihre derzeitige Lebenssituation',
      ACTIVITY_DISPLAY_OPTION: 'Option Aktivitätsanzeige',
      GAMES: 'Spiele',
      MEETINGS: 'Sitzungen',
      MEMBERS: 'Mitglieder',
      PUBLIC: 'Öffentlich',
      PRIVATE: 'Privat',
    },
    GENERAL: {
      USER: 'Benutzer',
      PATIENT: 'Begünstigter',
      MEMBER: 'Mitglied',
      GUEST: 'Gast',
      HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft',
      GAME: 'Spiel',
      PROFILE: 'Profil',
      ORGANIZATION: 'Organisation',
      ORGANIZATION_ADMIN: 'Organisation Verwaltung',
      NO_ENTRIES: 'Keine Einträge gefunden',
      SESSION: 'Sitzung',
      GAMES: 'Spiele',
      SESSION_TEMPLATE: 'Sitzungsvorlage',
      SUBSCRIPTION: 'Abonnement',
      SUBSCRIPTION_EMAIL: 'E-Mail-Abonnement',
      ASSIGNED_QUESTIONNAIRE: 'Fragebogen Zugewiesen',
      QUESTIONNAIRE_TEMPLATE: 'Fragebogen Vorlage',
      NOTE: 'Note',
      COPIED: 'Kopiert!',
      CONGRATULATIONS: 'Herzlichen Glückwunsch',
      DESCRIPTION: 'Beschreibung',
      SAME_COGNITIVE_GAMES:
        'Spiele, die die gleiche kognitive Fähigkeit trainieren',
      SELECT_DIFFICULTY: 'Schwierigkeitsgrad auswählen',
      GROUP: 'Grup',
      MEETING: 'Sitzung',
    },
    GRAPHS: {
      SCORE: 'Punktzahl',
      TIME: 'Zeit',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Ausführungen pro Spielkategorie & Schwierigkeitsgrad',
      EXECUTIONS_PER_GAME_TITLE: 'Ausführungen pro Spiel',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Durchschnittliche Punktzahl pro Spiel',
      EXECUTIONS_PER_DAY_TITLE: 'Exekutionen pro Tag',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE:
        'Verlauf der durchschnittlichen Leistung',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Gesamte Aktivitätszeit pro Tag (minuten)',
      GAME: 'Spiel',
      TOTAL: 'Insgesamt',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Aktivitätsprotokolle',
      EXECUTED_GAME: 'Ausgeführtes Spiel',
      ADDED: 'Hinzugefügt: ',
      EXECUTED_SESSION: 'Durchgeführte Sitzung',
    },
    SESSION: {
      MY_SESSIONS: 'Meine Sitzungen',
      SESSION_COMPLETE: 'Sie haben die Sitzung abgeschlossen',
      ABANDONED: 'Verlassen',
      SKIPPED: 'Übersprungen',
      PLAYED: 'Gespielt',
      PENDING: 'Anhängig',
      ASSIGNED_SESSIONS: 'Zugewiesene Sitzungen',
      DEFAULT_PUBLIC_INFO:
        'Hallo! Dieser Fragebogen ist nur für Sie bestimmt! Bitte füllen Sie sie aus oder wenden Sie sich an Ihren Arzt, wenn Sie weitere Fragen haben.',
      DOCTOR_NOTES: 'Notizen des Arztes',
      SAMPLE_DOCTOR_NOTES:
        'Lieber {{name}}, dies ist eine Sitzung, die nur für Sie erstellt wurde! Bitte fülle sie aus oder wende dich an deinen Heilpraktiker, wenn du weitere Fragen hast.',
    },
    STATUS: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
      INVITED: 'Eingeladen',
    },
    SESSION_STATUS: {
      ACTIVE: 'Aktiv',
      ASSIGNED: 'Zugewiesen',
      CLOSED: 'Geschlossen',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Wiederverkäufer',
      DEMO: 'Demo',
      PAID: 'Bezahlt',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'System Admin',
      ROLE_ORGANIZATION_OWNER: 'Eigentümer der Organisation',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Organisation Verwaltung',
      ROLE_HEALTH_PROFESSIONAL: 'Gesundheitsfachkraft',
      ROLE_PATIENT: 'Begünstigter',
      ROLE_INTERNAL_CONTACT: 'Interner Kontakt',
      ROLE_EXTERNAL_CONTACT: 'Externer Kontakt',
      ROLE_HEALTH_PROFESSIONAL_OWNER:
        'Organisationseigentümer/Gesundheitsfachmann',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Organisation Verwaltung/Gesundheitsdienstleister',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Male',
      FEMALE: 'Weiblich',
      OTHER: 'Andere',
      NO_ANSWER: 'Lieber nicht angeben',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Hallo Admin',
      OVERVIEW_DESCRIPTION: 'Werfen Sie einen Blick auf Ihre Zahlen',
      EXECUTIONS: 'Vollstreckungen',
      HOURS: 'Stunden',
      BENEFICIARIES: 'Begünstigte',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      MOST_PLAYED: 'Meistgespielt',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Letzte Updates zu Spielen',
      LEAST_PLAYED: 'Am wenigsten gespielt',
      ACTIVE_LAST_30_DAYS: 'Aktiv in den letzten 30 Tagen',
      GAMES_ACTIVITY: 'Spiele Aktivität',
      GAMES_ACTIVITY_DESCRIPTION: 'Gesamtausführungen pro Spiel und kognitiv',
      AVERAGE: 'Insgesamt',
      LAST_UPDATE: 'Letzte Aktualisierung:',
      HOUR_SHORT: 'h',
      MINUTE_SHORT: 'm',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS:
        'Anzahl der Angehörigen der Gesundheitsberufe',
      NUMBER_OF_BENEFICIARIES: 'Anzahl der Begünstigten',
      DURATION: 'Dauer',
      START_DATE: 'Startdatum',
      EXTENSION_DAYS: 'Verlängerungstage',
      END_DATE: 'Enddatum',
      EXTENSION_DATE: 'Extension Date',
      STARTING_LICENSE: 'Startlizenz',
      ANNUAL_FEE: 'Jährliche Gebühr',
      SUPPORT_SERVICES: 'Unterstützungsdienste',
      MONTHLY_COST_PER_BENEFICIARY: 'Monatliche Kosten pro Begünstigtem',
      TOTAL_COST_OF_BENEFICIARIES: 'Gesamtkosten der Begünstigten',
      TOTAL_COST_OF_SUBSCRIPTION: 'Gesamtkosten des Abonnements',
      ORGANIZATION_TYPE: 'Organisationstyp',
      SUBSCRIPTION_TYPE: 'Abonnement Typ',
      MONTHS: 'Monate',
      DAYS: 'Tage',
      REMAINING_DAYS: 'Verbleibende Tage',
      HEALTH_PROFESSIONALS: 'Gesundheitspersonal',
      BENEFICIARIES: 'Begünstigte',
      NOTES: 'Anmerkungen',
      DURATION_OF_SUBSCRIPTION: 'Dauer des Abonnements',
      COSTS_VAT_DISCLAIMER:
        'Alle Kosten verstehen sich zuzüglich der gegebenenfalls anfallenden Mehrwertsteuer.',
      ACCEPT_MODAL_FOOTER:
        'Wenn Sie das Abonnement nicht bestätigen möchten, ignorieren Sie es bitte oder senden Sie uns eine E-Mail für weitere Informationen an',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        'Sie können nicht auf Eligence zugreifen, da das Abonnement Ihrer Organisation nicht aktiv ist. Für weitere Informationen wenden Sie sich bitte an das Eligence-Team.',
      DAYS_LEFT: 'days left',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'Neu',
      AMENDMENT: 'Abänderung',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Aktiv',
      EXPIRED: 'Expired',
      PENDING_CONSENT: 'Anhängige Zustimmung',
      PENDING_AUTOMATION: 'Anstehende Automatisierung',
      REJECTED: 'Abgelehnt',
      TERMINATED: 'Beendet',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Fragebögen zuweisen',
      SECTION: 'Abschnitt',
      QUESTION: 'Frage',
      NOTE: 'Anmerken',
      BY: 'von',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Plattform Generiert',
      USER_GENERATED: 'Benutzergeneriert',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Zugewiesen',
      IN_PROGRESS: 'im Gange',
      COMPLETED: 'Vollendet',
      CANCELLED: 'Abgesagt',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Freier Text',
      INTEGER: 'Numerisch',
      CHECKBOX: 'Mehrfachauswahl',
      RADIO: 'Einzelwahl',
      DROPDOWN: 'Dropdown',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Der Fragebogen ist ein empfohlenes Instrument, das Ihnen von der Eligence-Plattform zur Verfügung gestellt wird. Mit dem Fragebogen können Sie Informationen über einen Begünstigten sammeln oder um Informationen bitten, um den Status des Begünstigten zu beurteilen.',
      PROMPT:
        'Wenn der Fragebogen dem Begünstigten zugewiesen wird, werden alle kostenlosen Spiele und Sitzungen deaktiviert, bis der Begünstigte ihn ausfüllt.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Begünstigten erstellen',
      TITLE_MEMBER: 'Mitglied erstellen',
      TITLE_GUEST: 'Gast erstellen',
      CREDENTIALS: 'Benutzeranmeldedaten',
      PERSONAL_DETAILS: 'Persönliche Daten',
      COMPLETION: 'Fertigstellung',
      CHECK_AVAILABILITY: 'Verfügbarkeit prüfen',
      USERNAME_AVAILABLE: 'Username verfügbar',
      USERNAME_UNAVAILABLE: 'Nicht verfügbar, erneut versuchen',
      OTP_SAVE_WARNING: 'Speichern Sie das Passwort zur späteren Verwendung.',
      DONE: 'Sie sind fertig!',
      DONE_DESCRIPTION:
        'Es wurde ein neues Begünstigtenkonto erstellt. Bei der ersten Anmeldung wird der Begünstigte aufgefordert, das erstellte Passwort zu ändern.',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'Für Gruppen',
      FOR_TWO: 'Für Zwei',
      INTERGENERATION: 'Generationsübergreifend',
      CHALLENGING: 'Anspruchsvoll',
    },
    GAMES: {
      MY_GAMES: 'Meine Spiele',
      ALL_GAMES: 'Alle',
    },
    STAYING_STATUS: {
      ALONE: 'Ich lebe allein',
      WITH_HUSBAND_WIFE: 'Ich lebe mit meinem Partner zusammen',
      WITH_KIDS_GRANDKIDS: 'Ich lebe mit meinen Kindern/Enkeln zusammen',
      WITH_CARER: 'Ich lebe mit meinem Betreuer zusammen',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'Alle anzeigen',
      ONLY_SESSIONS: 'Nur Sitzungen',
      ONLY_GAMES: 'Nur Spiele',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Zugewiesen',
      UNASSIGNED: 'Nicht zugewiesen',
    },
    GAME_ACCESS: {
      PUBLIC: 'Öffentlich',
      PRIVATE: 'Privat',
    },
    PRIVACY_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Datenschutzbestimmungen</h2><br><h2>1. Einleitung</h2><p>Der Softwaredienst "Eligence" ("Dienst") wird von "Maggioli SPA - Greek Branch" ("Anbieter") auf von "Maggioli SPA - Greek Branch" bereitgestellten Ressourcen betrieben.</p><p>"Maggioli SPA - Greek Branch" ("Anbieter") ist ein privates Softwareunternehmen mit dem vollständigen Namen Maggioli SPA - Greek Branch, das am 21. September 2020 in Marousi gegründet wurde und seinen Hauptsitz in Andrea Papandreou 19 Marousi, 15124, Attika, Griechenland hat.</p><p>Der Schutz Ihrer persönlichen Daten ist uns sehr wichtig. Unsere Datenschutzrichtlinie soll Ihnen helfen zu verstehen, warum wir Ihre persönlichen Daten sammeln und wie wir sie verwenden. Sie enthält detaillierte Informationen darüber, wann und warum wir Ihre personenbezogenen Daten erfassen, wie wir sie verwenden und verarbeiten, wie lange wir sie aufbewahren und schließlich, unter welchen Bedingungen wir sie an andere weitergeben können.</p><h2>2. Geltungsbereich</h2><p>Diese Richtlinie gilt für alle, die auf unseren Dienst zugreifen und ihn nutzen.</p><p>Diese Datenschutzrichtlinie gilt ausschließlich für personenbezogene Daten und Informationen, die der Dienst durch seine Nutzung oder durch elektronische Kommunikation des Nutzers mit dem Anbieter erfasst, wie auf dem Dienst angegeben (im Folgenden als "personenbezogene Daten" bezeichnet).</p><p>Wir können auch auf andere Weise Informationen von Ihnen erfassen, einschließlich Informationen, die bei Kontakten mit dem technischen Support gesammelt werden. Wenn wir bei der Erfassung personenbezogener Daten einen separaten oder ergänzenden Hinweis geben, hat dieser Hinweis im Falle eines Konflikts Vorrang.</p><h2>3. Erfasste Informationen</h2><p>Der Dienst verwaltet verschiedene Arten von Daten, die alle mit der geltenden europäischen Datenschutzgesetzgebung übereinstimmen. Alle Daten, die den Nutzer betreffen, werden gesammelt, um es dem Anbieter zu ermöglichen, die Dienstleistungen zu erbringen.</p><h2>a. Erforderliche Daten</h2><h2>Personenbezogene Daten</h2><p>Die Bereitstellung des Dienstes erfordert die Verarbeitung bestimmter personenbezogener Daten. Ihre personenbezogenen Daten, die wir verarbeiten:</p><ul><li>Name</li><li>Adresse</li><li>E-Mail-Adresse</li><li>Telefonnummer</li></ul><h2>Cookies</h2><p>Alle Cookies oder andere Tracking-Tools, die von diesem Dienst oder von anderen Anbietern von Drittdiensten, die von oder über diesen Dienst genutzt werden, verwendet werden, dienen dem Zweck, den vom Nutzer gewünschten Dienst bereitzustellen, zusätzlich zu allen anderen Zwecken, die im vorliegenden Dokument und in der spezifischen Richtlinie für Cookies, falls ein solches Dokument zur Verfügung gestellt wird, beschrieben sind.</p><h2>4. Verwendung personenbezogener Daten</h2><p>Der Dienst verwendet personenbezogene Daten für folgende Zwecke:</p><ul><li><b>Erfüllung von Anfragen:</b> Der Dienst verwendet personenbezogene Daten, um Anfragen zu bearbeiten, sich bei Diensten Dritter anzumelden, mit dem Nutzer in Kontakt zu treten, Benachrichtigungen zuzustellen, dem Nutzer Gebühren zu berechnen und in Rechnung zu stellen usw.</li><li><b>Betrieb des Dienstes:</b> Der Dienst verwendet Cookies, um Benutzer zu identifizieren, Informationen über den Standort und das Client-Gerät zu erhalten, um seine Fähigkeiten anzupassen/zu gewähren, Zugang zu bestimmten Bereichen des Dienstes zu gewähren, Zugang zu relevanten Informationen zu gewähren, Inhalte zu filtern usw.</li><li><b>Statistische Analyse:</b> Aggregierte Daten über die Nutzung des Dienstes (die keinen bestimmten Benutzer identifizieren), wie z. B. die Anzahl der Benutzer, die bestimmte Seiten des Dienstes besucht haben, oder wie lange die Benutzer auf einer bestimmten Seite verweilen, werden verwendet, um Statistiken über die Nutzung des Dienstes zu liefern.</li><li><b>Interne Geschäftszwecke:</b> Der Anbieter verwendet die gesammelten Informationen für interne Geschäftszwecke, z. B. für Audits oder um die Nutzung und das Verhalten von Servicefunktionen zu verfolgen, um die Nutzung von Ressourcen und die Finanzierung zu rechtfertigen, um Geschäftskennzahlen zu ermitteln usw.</li><li><b>Dienstleistungs- und Produktdesign:</b> Aggregierte und personenbezogene Daten werden vom Anbieter verwendet, um Verbesserungen, Anpassungen und Verfeinerungen vorzunehmen sowie neue Dienste und Produkte zu entwerfen, die allgemeinen oder benutzerspezifischen Bedürfnissen entsprechen.</li><li><b>Anzeigen von Benutzerinformationen:</b> Die den Benutzer betreffenden Daten werden vom Dienst präsentiert, um den Benutzern die Möglichkeit zu geben, das Eigentum, die Herkunft und die Zuweisung verschiedener Ressourcen zu identifizieren.</li></ul><p>Unser Dienst garantiert, dass Ihre personenbezogenen Daten nicht für andere Zwecke als die in dieser Richtlinie dargelegten verwendet werden, ohne vorherige Ankündigung und wenn Ihre Zustimmung erforderlich ist.</p><p>Die Datenverarbeitung erfolgt mit Hilfe von Computern und/oder IT-gestützten Instrumenten, wobei organisatorische Verfahren und Modalitäten befolgt werden, die strikt mit den angegebenen Zwecken zusammenhängen.</p><p>Der Anbieter betrachtet die personenbezogenen Daten der Nutzer als einen unverkäuflichen Vermögenswert und wird die personenbezogenen Daten der Nutzer niemals an Dritte verkaufen.</p><h2>5. Empfänger personenbezogener Daten</h2><p>Der Zugriff auf personenbezogene Daten und Transaktionsinformationen ist nur Mitarbeitern, verbundenen Unternehmen und Dritten gestattet, die die oben genannten Daten nach dem Ermessen des Anbieters verarbeiten, und nur, wenn und soweit dies für die oben genannten Zwecke erforderlich ist. Personenbezogene Daten dürfen zum Zwecke der oben genannten Verarbeitung nur an bestimmte Empfänger, die Mitarbeiter und im Allgemeinen verbundene Unternehmen sowie mit dem Anbieter verbundene Dritte sind, übermittelt werden. Darüber hinaus kann der Provider Ihre Daten ohne vorherige Ankündigung an die zuständigen Justiz- und/oder Verwaltungsbehörden weitergeben, soweit dies durch geltende Gesetze und Vorschriften oder durch gerichtliche Entscheidungen und/oder Verwaltungsakte vorgeschrieben ist.</p><p>Der Provider bemüht sich, bei der Auswahl seiner verbundenen Unternehmen, an die er die personenbezogenen Daten der Betroffenen weitergibt, zu kontrollieren und zu bewerten. Es besteht eine schriftliche Vereinbarung zwischen dem Provider und jedem Dritten, wonach die Verarbeitung personenbezogener Daten unter der Kontrolle des Providers und nur in seinem Auftrag erfolgt und der gleichen Datenschutzpolitik unterliegt.</p><h2>6. Dauer der Datenspeicherung</h2><p>Die Dauer der Datenspeicherung richtet sich gegebenenfalls nach den folgenden spezifischen Kriterien:</p><ul><li>Wenn die Verarbeitung aufgrund von Bestimmungen des geltenden Rechtsrahmens erforderlich ist, werden Ihre personenbezogenen Daten so lange gespeichert, wie es die einschlägigen Bestimmungen erfordern</li><li>Bei einer Verarbeitung auf Vertragsbasis werden Ihre personenbezogenen Daten so lange gespeichert, wie es für die Erfüllung des Vertrags und für die Begründung, Ausübung und/oder Unterstützung von Rechtsansprüchen aus dem Vertrag erforderlich ist.</li><li>Für andere Zwecke werden Ihre personenbezogenen Daten aufbewahrt, bis Sie Ihre Einwilligung widerrufen. Dies kann jederzeit geschehen. Durch den Widerruf der Einwilligung wird die Rechtmäßigkeit der auf der Einwilligung beruhenden Verarbeitung für den Zeitraum vor dem Widerruf nicht berührt. Sie können Ihre Einwilligung jederzeit widerrufen, indem Sie den Link in den E-Mails anklicken, die wir Ihnen schicken.</li></ul><h2>7. Ihre Rechte und Wahlmöglichkeiten</h2><p>Wie in der Verordnung (EU) 2016/679 (Datenschutz-Grundverordnung) festgelegt, hat der Nutzer (betroffene Person) folgende Rechte:</p><ul><li><b>Recht auf Auskunft</b> über die personenbezogenen Daten, die der Anbieter über Sie gespeichert hat - welche Daten wir erhoben haben, zu welchem Zweck, wie sie verarbeitet werden und wie lange sie gespeichert werden (Artikel 15).</li><li><b>Recht auf Berichtigung</b> (Artikel 16). Sie haben das Recht, vom Anbieter die Berichtigung unrichtiger personenbezogener Daten zu verlangen und unvollständige personenbezogene Daten vervollständigen zu lassen.</li><li><b>Recht auf Löschung</b> ("Recht auf Vergessenwerden") (Artikel 17). Sie haben das Recht, vom Anbieter die Löschung der Sie betreffenden personenbezogenen Daten zu verlangen.</li><li><b>Recht auf Einschränkung der Verarbeitung</b> (Artikel 18). Sie haben das Recht, vom Anbieter die Einschränkung der Verarbeitung zu verlangen, wenn einer der folgenden Fälle zutrifft: (a) die Richtigkeit der personenbezogenen Daten wird bestritten (b) die Verarbeitung ist unrechtmäßig (c) der Anbieter benötigt die personenbezogenen Daten nicht mehr für die Zwecke der Verarbeitung.</li><li><b>Benachrichtigungspflicht über die Berichtigung oder Löschung personenbezogener Daten oder die Einschränkung der Verarbeitung durch den Verantwortlichen</b> (Artikel 19). Der Provider teilt die Berichtigung oder Löschung personenbezogener Daten oder die Einschränkung der Verarbeitung jedem Empfänger mit, dem die personenbezogenen Daten offengelegt wurden, es sei denn, dies erweist sich als unmöglich oder ist mit einem unverhältnismäßigen Aufwand verbunden. Der Anbieter informiert Sie über diese Empfänger, wenn Sie dies verlangen.</li><li><b>Recht auf Datenübertragbarkeit</b> (Artikel 20). Sie haben das Recht, die Sie betreffenden personenbezogenen Daten in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten und haben das Recht, diese Daten ohne Behinderung durch den Anbieter an eine andere Partei zu übermitteln.</li><li><b>Recht auf Widerspruch</b> (Artikel 21). Sie haben das Recht, der Verarbeitung Ihrer personenbezogenen Daten zu widersprechen. Der Provider verarbeitet die personenbezogenen Daten nicht mehr, es sei denn, er kann zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die die Interessen, Rechte und Freiheiten der betroffenen Person überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.</li></ul><p>Bevor wir Ihnen Informationen zur Verfügung stellen oder Unrichtigkeiten berichtigen können, bitten wir Sie möglicherweise, Ihre Identität zu überprüfen und/oder andere Angaben zu machen, die uns helfen, Ihre Anfrage zu beantworten.</p><p>Der Provider behält sich das Recht vor, auf Anfragen, die über Anwendungen Dritter oder automatisierte Prozesse ohne direkte Validierung der Anfragen durch die betroffenen Personen unter Verwendung der vom Dienst für die Ausübung dieser Rechte bereitgestellten Ressourcen, wie in dieser Richtlinie beschrieben, gestellt werden, nicht zu antworten.</p><h2>8. Datensicherheit</h2><p>Der Provider achtet auf die Sicherheit Ihrer personenbezogenen Daten. Wir wenden angemessene physische, technische und organisatorische Maßnahmen an, die geeignet sind, personenbezogene Daten vor versehentlicher oder unrechtmäßiger Zerstörung, Verlust, Änderung, unberechtigter Weitergabe oder unberechtigtem Zugriff sowie vor allen anderen unrechtmäßigen Formen der Verarbeitung zu schützen. Wir unterhalten ein Sicherheitsprogramm, das in einem angemessenen Verhältnis zu den mit der Verarbeitung verbundenen Risiken steht.</p><h2>9. Ort der Speicherung personenbezogener Daten</h2><p>Der Dienst wird über seine projektverwaltete Instanz bereitgestellt, deren Server sich in Griechenland befinden und von "Maggioli SPA - Greek Branch" bereitgestellt werden.</p><h2>10. Strafverfolgung - Einhaltung von Gesetzen</h2><p>Der Provider kann personenbezogene Daten verwenden oder an Dritte weitergeben, (a) wenn dies gesetzlich vorgeschrieben ist; (b) um rechtlichen Verfahren nachzukommen oder auf Anfragen von staatlichen oder öffentlichen Behörden zu reagieren; (c) um Straftaten oder Angriffe auf die technische Integrität des Dienstes oder des Netzwerks zu verhindern, zu untersuchen, aufzudecken oder zu verfolgen; (d) um die Allgemeinen Geschäftsbedingungen durchzusetzen; oder (e) um die Rechte, die Privatsphäre, das Eigentum, das Geschäft oder die Sicherheit des Providers, seiner Geschäftspartner, Mitarbeiter, Mitglieder, Dienstnutzer oder der Öffentlichkeit zu schützen. Sofern dies nicht durch geltendes Recht untersagt ist, informiert der Anbieter den Nutzer, wenn ein Dritter Zugang zu den personenbezogenen Daten des Nutzers beantragt.</p><h2>11. Änderung der Richtlinie</h2><p>Diese Datenschutzrichtlinie kann geändert werden. Wir werden Sie über etwaige Änderungen auf dem Laufenden halten, aber in jedem Fall laden wir Sie ein, unsere Website regelmäßig zu besuchen, wo die aktuellste Datenschutzrichtlinie veröffentlicht wird.</p><h2>12. Ausübung Ihrer Rechte, Anfragen, Einwände, Beschwerden</h2><p>Für die Ausübung Ihrer Rechte oder für Fragen, Kommentare, Einwände oder Beschwerden in Bezug auf diese Datenschutzrichtlinie oder die angewandten Praktiken zum Schutz der Privatsphäre, der Sicherheit oder des Datenschutzes wenden Sie sich bitte per E-Mail an den Anbieter über den von ihm benannten Datenschutzbeauftragten (dpo@eligence.eu).</p><p>Wir behandeln Ihre Anfragen mit äußerster Sorgfalt, um sicherzustellen, dass Ihre Rechte geschützt werden. Für alle Anfragen, die die Annahme oder Weitergabe personenbezogener Daten erfordern, muss der Nutzer legitime Gründe für die jeweiligen Anfragen nachweisen und die Identität des Nutzers hinreichend belegen.</p><p>In manchen Fällen können wir Ihre Anfrage nicht direkt bearbeiten. In jedem Fall werden wir Sie jedoch innerhalb eines Monats nach Einreichung Ihrer ursprünglichen Anfrage über den Stand der Bearbeitung Ihrer Anfrage informieren.</p><p>Sie haben jederzeit das Recht, sich bei der "Griechischen Datenschutzbehörde (www.dpa.gr)" zu beschweren, wenn Sie Bedenken haben, wie wir Ihre personenbezogenen Daten verarbeitet haben.</p>',
    },
    TERMS: {
      TEST: '<h1>Eligence</h1><h2>Nutzungsbedingungen</h2><br><h2>Haftungsausschluss</h2><p>Willkommen bei "Eligence". "Eligence" (im Folgenden als "Service" bezeichnet) ist eine Web-Plattform mit speziellen Inhalten (Spielen), die darauf abzielen, die geistigen Fähigkeiten und kognitiven Funktionen zu stärken. In Zusammenarbeit mit medizinischem Fachpersonal können Übungen für Menschen im Frühstadium der Demenz sowie für Zwecke der Logotherapie oder Ergotherapie angeboten werden. </p><p>Bitte lesen und verstehen Sie diese Bedingungen (die "Bedingungen"), bevor Sie diesen Dienst nutzen. Durch die Nutzung dieses Dienstes akzeptieren Sie die folgenden Bedingungen und erklären sich damit einverstanden, an diese gebunden zu sein und sie einzuhalten. Wenn Sie mit diesen Bedingungen nicht einverstanden sind, sollten Sie nicht auf diesen Dienst zugreifen oder ihn nutzen.  </p><p>Nutzer sind Personen, die den Dienst nutzen und betreiben.</p><p>Um den Dienst nutzen zu können, müssen Sie 1) volljährig und voll geschäftsfähig sein, oder 2) als Minderjähriger (<18 Jahre) die schriftliche Zustimmung Ihrer Eltern oder Ihres gesetzlichen Vertreters erhalten haben, oder 3) bei fehlender Geschäftsfähigkeit die Zustimmung Ihres gesetzlichen Vertreters haben/vorlegen.</p><p>"Eligence" behält sich das Recht vor, Dokumente, Informationen oder andere Inhalte, die in diesen Bedingungen enthalten sind, von Zeit zu Zeit ohne vorherige Ankündigung und nach eigenem Ermessen zu ändern, zu bearbeiten oder zu löschen. Alle Änderungen treten unmittelbar nach ihrer Veröffentlichung in Kraft und gelten für jeden Zugriff auf und jede Nutzung des Dienstes in der Folgezeit. Jedes Mal, wenn Sie den Dienst nutzen möchten, überprüfen Sie bitte diese Bedingungen, um sicherzustellen, dass Sie die Bedingungen verstehen, die zu diesem Zeitpunkt für Sie gelten.</p><p>Dieser Dienst wird von "Maggioli SPA - Greek Branch" ("Anbieter") auf von Maggioli bereitgestellten Ressourcen betrieben. Elemente des Dienstes ("Dienstelemente"), wie Technologie, Algorithmen, Dokumente, Daten, andere Dienste, Prozesse und andere Ressourcen, können vom Anbieter oder von Dritten ("andere Anbieter") bereitgestellt worden sein oder werden derzeit bereitgestellt. Der Anbieter und die anderen Anbieter werden gemeinsam als "Anbieter" bezeichnet.</p><p>Der Dienst selbst sowie alle Daten oder Informationen oder andere Elemente, die über den Dienst zugänglich werden, werden auf einer "as is" und "as available" Grundlage. Der Anbieter ist bemüht, die Richtigkeit, Vollständigkeit oder Authentizität der durch den Dienst verwalteten und bereitgestellten Prozesse, Daten und Informationen zu gewährleisten.</p><p>Der Anbieter behält sich das Recht vor, jeden Teil dieses Dienstes nach eigenem Ermessen zu ändern, zu beschränken oder einzustellen. Dies gilt auch für andere Anbieter, sofern nicht ausdrücklich etwas anderes erklärt wird. </p><p>Der Provider erhebt keinen Anspruch auf Eigentum und übernimmt keine Verantwortung für Daten, Informationen, Inhalte, Kommentare, Codes, Prozesse oder andere Elemente, die von anderen Nutzern in den Dienst hochgeladen oder eingebettet werden, sofern der Dienst solche Funktionalitäten anbietet. Die Nutzer sind dafür verantwortlich, ihr Vermögen und ihre persönlichen Daten vor solchen Elementen zu schützen, die im Dienst vorhanden sind.</p><p>Nach bestem Wissen und Gewissen des Providers werden angemessene Sicherheitsmaßnahmen ergriffen, die den für den Bereich des Dienstbetriebs geltenden Praktiken entsprechen, um die unter seiner Kontrolle stehenden sensiblen Informationen vor Verlust, Missbrauch und Veränderung zu schützen. Der Provider kann jedoch nicht für die Sicherheit der physischen Standorte, der Hardware, der Software und der Netzwerke, der Mittel, mit denen vertrauliche Informationen gehandhabt und zwischen Computern und Anwendungen übertragen werden, oder für alle vertraulichen Informationen, die über den Dienst oder in Verbindung mit ihm empfangen werden, garantieren. </p><h2>Urheberrecht</h2><p>Der Provider behält sich alle Rechte an den von ihm zur Verfügung gestellten Elementen vor.</p><p>Elemente des Dienstes ("Dienstelemente") wurden von Dritten ("Andere Anbieter") ohne Einschränkung der Rechte zur Verfügung gestellt.</p><p>Die GODOT Software wird bereitgestellt."as is"ohne jegliche ausdrückliche oder stillschweigende Garantie, einschließlich, aber nicht beschränkt auf die Garantie der Marktgängigkeit, der Eignung für einen bestimmten Zweck und der Nichtverletzung von Rechten Dritter. In keinem Fall haften die Autoren oder die Inhaber der Urheberrechte für Ansprüche, Schäden oder sonstige Haftungen, sei es aus Vertrag, unerlaubter Handlung oder anderweitig, die sich aus der Software oder der Nutzung oder dem sonstigen Umgang mit der Software ergeben.</p><h2>Lizenz</h2><p>Nutzer, denen der Zugang über das vom Provider eingerichtete Verfahren gewährt wird, erhalten eine Lizenz zur Nutzung des Dienstes gemäß den Bedingungen der Lizenz.</p><p>Der Provider gewährt seinen Nutzern eine Lizenz zur freien Nutzung dieses Dienstes gemäß den Bedingungen dieses Dokuments. Der Zugang zum Dienst kann jedoch aufgrund der Verfügbarkeit der zugrunde liegenden Ressourcen eingeschränkt sein. Der Provider kann diese Lizenz nach eigenem Ermessen ohne vorherige Benachrichtigung der Nutzer widerrufen oder ihre Bedingungen ändern.  Der Provider bemüht sich nach besten Kräften, die Nutzer, die auf den Dienst zugreifen, rechtzeitig vor einer solchen Maßnahme zu informieren, kann dies jedoch nicht garantieren.</p><p>Die Nutzer sind verpflichtet, bei allen Produkten oder Dienstleistungen, die auf der Grundlage der Ergebnisse oder der Nutzung dieses Dienstes erstellt werden, einen eindeutigen Verweis auf die Nutzung des Dienstes anzubringen.</p><p>Der Provider kann jederzeit und ohne Vorankündigung den Zugang zu dem Dienst auf eine Person, ein geografisches Gebiet oder eine Gerichtsbarkeit beschränken, die er nach eigenem Ermessen auswählt.</p><h2>Nutzung des Dienstes</h2><p>Der Provider sichert nicht zu oder gewährleistet nicht, dass der Dienst für die Nutzung in einer bestimmten Gerichtsbarkeit geeignet oder verfügbar ist. Nutzer, die den Dienst abonnieren, tun dies auf eigene Initiative und auf eigenes Risiko und sind für die Einhaltung aller für sie geltenden lokalen Gesetze, Regeln und Vorschriften verantwortlich.</p><p>Durch die Nutzung des Dienstes erklärt sich der Nutzer mit allen Bedingungen des Dokuments "Nutzungsbedingungen" einverstanden, das zu einem beliebigen Zeitpunkt erstellt werden kann und gilt. </p><p>Durch die Nutzung des Dienstes erklären sich die Nutzer damit einverstanden, dass sie berechtigt sind, den Dienst unter den Bedingungen zu nutzen, die der Anbieter bei der Anfrage nach Zugang zum Dienst vorlegt oder die ausdrücklich im Abschnitt des Dokuments "Lizenz" dargelegt werden können.</p><p>Unter keinen Umständen darf ein Nutzer den Dienst für die Durchführung von böswilligen Aktivitäten nutzen, was sich indikativ, aber nicht ausschließlich, auf Folgendes beziehen kann: Zugang zu oder Offenlegung von persönlichen oder vertraulichen Daten anderer Parteien oder Nutzer, Übermittlung von böswilligem Code an andere Nutzer oder Systeme, absichtliche Überlastung des Dienstes oder der Ressourcen des Anbieters, jede Handlung, die eine Dienstverweigerung für den Dienst oder einen Dienst oder eine Ressource eines Dritten verursacht, Nachahmung des Anbieters, seines Personals oder eines Nutzers, Beeinträchtigung des finanziellen oder sozialen Status des Anbieters, seines Personals oder der Nutzer usw.</p><p>Der Nutzer verpflichtet sich, die vom Dienst zur Verfügung gestellten Ressourcen und den Dienst selbst zu keinem anderen Zweck und mit keinen anderen Mitteln als den vom Dienst vorgesehenen zu nutzen. Die Nutzer verpflichten sich, bei Unsicherheiten über die Zulässigkeit einer Nutzung weitere Informationen beim Anbieter anzufordern, bevor sie eine solche Nutzung vornehmen.</p><p>Die Nutzer verpflichten sich, den Anbieter unverzüglich über alle Schwachstellen oder Probleme zu informieren, die sie bei der Nutzung des Dienstes festgestellt haben oder über die sie informiert wurden.</p><p>Die Nutzer verpflichten sich, den Anbieter unverzüglich über alle bösartigen oder anderweitig unangemessenen Daten, Informationen, Kommentare, Codes, Prozesse oder andere Elemente zu informieren, die über den Dienst zur Verfügung gestellt werden und von denen sie Kenntnis erlangen.</p><p>Die Nutzer sind für die Verwaltung ihrer eigenen Anmeldedaten und die Sicherheit ihres Kontos verantwortlich. Die Nutzer sind verpflichtet, den Anbieter zu benachrichtigen, sobald sie von einer unbefugten Nutzung ihres Kontos Kenntnis erlangen.</p><p>Der Anbieter behält sich das Recht vor, bei einem Missbrauch des Dienstes rechtliche Schritte einzuleiten, um seine eigenen Interessen und die seiner Nutzer zu schützen. Der Anbieter kann das Konto eines Nutzers und den damit verbundenen Zugang zum Dienst ohne Vorwarnung proaktiv beenden, um den Dienst, seine Ressourcen oder andere Nutzer vor mutmaßlich fehlerhaften oder böswilligen Handlungen des Nutzers oder einer Person, die sich für den Nutzer ausgibt, zu schützen.</p><p>Der Anbieter kann die "Nutzungsbedingungen" des Dienstes ohne vorherige Ankündigung ändern. Der Anbieter bemüht sich nach besten Kräften, den Nutzer über wesentliche Änderungen in diesem Dokument oder in Dokumenten, die von ihm angesprochen werden, zu informieren, kann dies jedoch nicht garantieren.</p><p>Der Nutzer ist verpflichtet, den Anbieter zu entschädigen, wenn sich aus der Verletzung einer Bestimmung dieser "Nutzungsbedingungen" durch den Nutzer Ansprüche an den Anbieter ergeben. Eine solche Entschädigung kann u.a. Strafen, Schadensersatzansprüche Dritter, ethische und finanzielle Schäden des Providers, Aufwand und Rechtskosten des Providers und andere damit verbundene Kosten umfassen.</p><h2>Wirksamkeit</h2><p>Sollte ein Teil dieser "Nutzungsbedingungen" aus irgendeinem Grund unwirksam sein (z.B. rechtswidrig oder durch ein anderes Dokument außer Kraft gesetzt), bleibt der Rest der Vereinbarung mit Ausnahme des unwirksamen Teils gültig.</p><p>Diese "Nutzungsbedingungen" gelten zwischen dem Anbieter und dem Nutzer und können vom Nutzer unter keinen Umständen auf Dritte übertragen werden.</p><p>Weder der Nutzer noch der Anbieter können für eine Verletzung der Bedingungen dieser Lizenz haftbar gemacht werden, die aufgrund von Umständen außerhalb ihrer jeweiligen zumutbaren Kontrolle ("Höhere Gewalt") eintritt.</p><p>Der Anbieter kann von der Ausübung von Rechten aus diesen "Nutzungsbedingungen" aus jedem beliebigen Grund, zu jeder Situation und zu jedem Zeitpunkt absehen. Dies gilt nicht als Verzicht auf das Recht, die entsprechenden Rechte in Zukunft in gleichen, ähnlichen oder anderen Fällen auszuüben.</p><h2>Ihr Einverständnis mit den Bedingungen</h2><p><b><u>Ihr Zugang oder Ihre Nutzung des Dienstes oder/und jeglicher Ressourcen, die von diesem bereitgestellt werden oder auf die über diesen zugegriffen wird, bedeutet, dass Sie die Bedingungen dieses Dokuments gelesen und verstanden haben und damit einverstanden sind.</u></b></p>',
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Cooke Policy</h2><br><h2>Cookie List</h2><p>A cookie is a small piece of data (text file) that a website – when visited by a user – asks your browser to store on your device in order to remember information about you, such as your language preference or login information. Those cookies are set by us and called first-party cookies. We also use third-party cookies – which are cookies from a domain different than the domain of the website you are visiting – for our advertising and marketing efforts.</p><h2>Manage cookie settings</h2><p>On any page of the site, by clicking on the button on the bottom left corner the cookie banner will open and it will be possible to modify and reset your preferences; selecting “accept all cookies” you give the consent to use of all types of cookies, while you can withdraw your consent by clicking on “Refuse all cookies”. By deciding to close the banner, the preferences previously given will be kept until further modification. Opening the banner you can manage consents for the various types of cookies on the basis your preferences.</p><h2>Necessary Cookies</h2><p>These cookies are necessary for the website to function and cannot be switched off in our systems. Any Cookies or other tracking tools used by this Service, or by Other Providers of third-party services used by or through this Service, serve the purpose of providing the service required by the User, in addition to any other purposes described in the Privacy Policy.</p><h2>Analytics cookies</h2><p>Analytics cookies are cookies that track how users navigate and interact with this Service. The information collected is used to help the Service ‘s owner improve the Service.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
