import { privacy_policy_GR } from './terms-policy/policy.junior.el';
import { terms_GR } from './terms-policy/terms.junior.el';

export const locale = {
  lang: 'el',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE:
        'Παρακαλούμε επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      USERNAME_NOT_FOUND_EXCEPTION: 'Το όνομα χρήστη δε μπορεί να βρεθεί',
      USER_LOGIN_EXCEPTION: 'Τo όνομα χρήστη ή ο κωδικός δεν είναι έγκυρα',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION: 'Μη έγκυρο email ή κωδικός',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'Ο χρήστης υπάρχει ήδη στον οργανισμό',
      USER_REGISTRATION_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά την εγγραφή του χρήστη',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά τη δημιουργία συνδέσμου επαναφοράς του κωδικού πρόσβασης',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'Ο λογαριασμός με αυτές τις πληροφορίες δεν έχει ενεργοποιηθεί ακόμα. Η επαναφορά του κωδικού πρόσβασης δεν μπορεί να ενεργοποιηθεί',
      PASSWORD_RESET_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά την επαναφορά του κωδικού πρόσβασής σας',
      MAIL_SEND_EXCEPTION: 'Παρουσιάστηκε σφάλμα κατά την αποστολή email',
      UPDATE_PASSWORD_EXCEPTION: 'Μη έγκυρος τρέχων κωδικός πρόσβασης',
      TOKEN_REFRESH_EXCEPTION:
        'Δεν ήταν δυνατή η ανανέωση του authorization token',
      USER_LOGOUT_EXCEPTION: 'Παρουσιάστηκε σφάλμα κατά την αποσύνδεσή σας',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      FORBIDDEN_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      UNAUTHORIZED_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      IP_BLOCKED_EXCEPTION:
        'Έχετε αποκλειστεί προσωρινά λόγω πολλαπλών προσπαθειών σύνδεσης',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'Η διεύθυνση email που καταχωρίσατε χρησιμοποιείται ήδη',
      FILE_GENERIC_EXCEPTION:
        'Σφάλμα αρχείου. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Το επιχείρημα δεν είναι έγκυρο. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      APP_EXCEPTION:
        'Κάτι πήγε λάθος. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'Ο πόρος χρησιμοποιείται ήδη. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Ο πόρος δεν βρέθηκε. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      FILE_NOT_FOUND_EXCEPTION:
        'Το αρχείο δεν βρέθηκε. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      BAD_REQUEST_EXCEPTION:
        'Λάθος αίτημα. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Ο τύπος μέσου δεν είναι αποδεκτός. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      SESSION_EXPIRED_EXCEPTION:
        'Ο χρόνος παραμονής σας έχει λήξει. Παρακαλώ συνδεθείτε ξανά',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'Ο χρήστης δεν είναι ενεργός σε κάποιον οργανισμό. Αυτό σημαίνει ότι ένας από τους διαχειριστές του οργανισμού σας, σας έχει απενεργοποιήσει. Επικοινωνήστε απευθείας μαζί τους',
      PASSWORD_MISMATCH_EXCEPTION: 'Οι κωδικοί πρόσβασης δεν ταιριάζουν.',
      ORGANIZATION_NAME_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το όνομα.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτή την ιστοσελίδα.',
      ORGANIZATION_PHONE_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το τηλέφωνο επικοινωνίας.',
      ORGANIZATION_EMAIL_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το email.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        "You cannot invite a Health Professional. You have reached your subscription's limit.",
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        "You cannot invite a Student. You have reached your subscription's limit.",
      ORGANIZATION_VAT_CONFLICT: 'Υπάρχει ήδη ένας οργανισμός με αυτό το ΑΦΜ.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'The organization has not accepted the subscription.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'The organization does not have active or pending subscription.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'The organization is inactive.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'The user is not verified in the organization',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'Υπάρχει ήδη μια συνδρομή για αυτές τις ημερομηνίες.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'You cannot perform actions on this assessment because it was not created by your organization.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'Υπάρχει ήδη ένα ερωτηματολόγιο για αυτό το χρήστη.',
      QUESTIONNAIRE_IS_EMPTY:
        'Για να αναθέσετε το ερωτηματολόγιο, χρειάζεται η δημιουργία μίας τουλάχιστον ερώτησης.',
      SESSION_ALREADY_IN_USE:
        'Παρατηρήθηκε μία ταυτόχρονη προσπάθεια σύνδεσης από άλλη συσκευή και για λόγους ασφαλείας έχετε αποσυνδεθεί. Παρακαλούμε πραγματοποιήστε νέα είσοδο για να ανακτήσετε πρόσβαση στο λογαριασμό σας και να συνεχίσετε τη δραστηριότητά σας.',
    },
    ROUTES_TITLE: {
      HOME: 'Αρχική',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'Διαχειριστές Συστήματος',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      BENEFICIARIES: 'Παιδιά',
      MEMBERS: 'Μέλη',
      MEMBER_PROFILE: 'Προφίλ Μέλους',
      GUESTS: 'Επισκέπτες',
      GUEST_PROFILE: 'Προφίλ Επισκέπτη',
      MY_PROFILE: 'Το προφίλ μου',
      USER_PROFILE: 'Προφίλ Χρήστη',
      ORGANIZATIONS: 'Οργανισμοί',
      ORGANIZATION_PROFILE: 'Προφίλ Οργανισμού',
      GAMES: 'Δραστηριότητες',
      GAME_MANAGEMENT: 'Διαχείριση Δραστηριοτήτων',
      GAME_OVERVIEW: 'Επισκόπηση Παιχνιδιού',
      SESSION_TEMPLATES: 'Περιπέτειες',
      SESSIONS_BY_ELIGENCE: 'Περιπέτειες από Eligence',
      SESSION_TEMPLATE: 'Περιπέτεια',
      QUESTIONNAIRE_TEMPLATES: 'Ερωτηματολόγια',
      QUESTIONNAIRES_BY_ELIGENCE: 'Ερωτηματολόγια από Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Ερωτηματολόγιο',
      ASSIGNED_SESSION: 'Ανατεθείσα Περιπέτεια',
      ASSIGNED_QUESTIONNAIRE: 'Ερωτηματολόγιο',
      ADD_SESSION: 'Προσθήκη Περιπέτειας',
      CREATE_BENEFICIARY: 'Δημιουργία Λογαριασμού Παιδιού',
      ELIGENCE_SESSION_TEMPLATES: 'Περιπέτειες',
      RESELLERS: 'Μεταπωλητές',
      RESELLER_PROFILE: 'Προφίλ Mεταπωλητή',
      GROUPS: 'Ομάδες',
      CREATE_GROUP: 'Δημιουργία Ομάδας',
      CREATE_MEMBER: 'Δημιουργία Μέλους',
      CREATE_GUEST: 'Δημιουργία Επισκέπτη',
      GROUP_PROFILE: 'Προφίλ Ομάδας',
      ADD_MEETING: 'Νέα Συνάντηση',
      EDIT_GROUP: 'Επεξεργασία Ομάδας',
      GAME_VARIATIONS: 'Παραλλαγές Παιχνιδιού',
    },
    CONFIRM: {
      DELETE: 'Είστε βέβαιοι ότι θέλετε να διαγράψετε την {{name}};',
      CREATE: 'Είστε βέβαιοι ότι θέλετε να δημιουργήσετε το νέο {{name}};',
      EDIT: 'Είστε βέβαιοι ότι θέλετε να επεξεργαστείτε το {{name}};',
      CHANGE: 'Είστε βέβαιοι ότι θέλετε να αποθηκεύσετε τις αλλαγές;',
      ACTIVATE: 'Είστε βέβαιοι ότι θέλετε να ενεργοποιήσετε αυτόν τον χρήστη;',
      ACTIVATE_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να ενεργοποιήσετε αυτόν τον οργανισμό;',
      DEACTIVATE:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτόν τον χρήστη;',
      DEACTIVATE_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτόν τον οργανισμό;',
      INVITATION:
        'Είστε βέβαιοι ότι θέλετε να στείλετε ξανά την πρόσκληση για αυτόν τον χρήστη;',
      INVITATION_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να στείλετε ξανά την πρόσκληση για αυτόν τον οργανισμό;',
      BOOK: 'Είστε βέβαιοι ότι θέλετε να κάνετε κράτηση για τον/την {{name}};',
      CANCEL_BOOKING:
        'Είστε βέβαιοι ότι θέλετε να ακυρώσετε την κράτηση με αυτόν τον χρήστη;',
      UPDATE_MAIL_WARNING:
        'Είστε σίγουροι ότι θέλετε να αλλάξετε το email σας; Λάβετε υπόψη ότι το όνομα χρήστη σας θα είναι το νέο σας email.',
      ACTIVATE_GAME:
        'Είστε σίγουροι ότι θέλετε να ενεργοποιήσετε αυτό το παιχνίδι;',
      ACTIVATE_GAME_TEMPLATE:
        'Είστε σίγουροι ότι θέλετε να ενεργοποιήσετε τη συγκεκριμένη κατηγορία παιχνιδιών;',
      DEACTIVATE_GAME:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτό το δραστηριότητα;',
      DEACTIVATE_GAME_WARNING:
        'Το παιχνίδι είναι ανατεθειμένο σε {{sessions}} συνεδρίες, {{beneficiaries}} επωφελούμενους, {{sessionTemplates}} πρότυπα συνεδριών, {{systemAssignedSessions}} συνεδρίες από Eligence, {{systemSessionTemplates}} πρότυπα συνεδριών από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να το απενεργοποιήσετε;',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'H συγκεκριμένη κατηγορία παιχνιδιών είναι ανατεθειμένη σε {{sessions}} συνεδρίες, {{beneficiaries}} επωφελούμενους, {{sessionTemplates}} πρότυπα συνεδριών, {{systemAssignedSessions}} συνεδρίες από Eligence, {{systemSessionTemplates}} πρότυπα συνεδριών από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να την απενεργοποιήσετε;',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'Το παιχνίδι είναι ανατεθειμένο σε {{sessions}} ενεργές συνεδρίες, {{systemAssignedSessions}} συνεδρίες από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να το απενεργοποιήσετε;',
      REMOVE_PATIENT:
        'Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτόν το Παιδί από τον συγκεκριμένο Παιδαγωγό;',
      DELETE_PATIENT: 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το {{name}}',
      CLOSE_SESSION: 'Σίγουρα θέλετε να κλείσετε αυτή τη περιπέτεια;',
      DELETE_SESSION: 'Σίγουρα θέλετε να διαγράψετε αυτή τη περιπέτεια;',
      DELETE_QUESTIONNAIRE:
        'Σίγουρα θέλετε να διαγράψετε αυτή την Ερωτηματολόγιο;',
      REMOVE_HEALTH_PROFESSIONAL:
        'Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτόν τον Παιδαγωγό από τον συγκεκριμένο Παιδί;',
      DELETE_HEALTH_PROFESSIONAL:
        'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτόν τον Παιδαγωγό;',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        'Είναι οι δραστηριότητες στη σειρά που θέλετε να εμφανιστούν στο παιδί; Έχετε επιλέξει το επιθυμητό επίπεδο δυσκολίας για κάθε δραστηριότητα;',
      CANCEL:
        'Είστε σίγουροι ότι θέλετε να απενεργοποιήσετε αυτή την {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Αν διαγράψετε αυτή την ενότητα, θα διαγραφούν όλες οι ερωτήσεις της. Είστε σίγουροι ότι θέλετε να συνεχίσετε?',
    },
    SUCCESS: {
      CREATE: '{{name}} δημιουργήθηκε με επιτυχία',
      EDIT: '{{name}} επεξεργάστηκε με επιτυχία',
      UPDATE: '{{name}} ενημερώθηκε με επιτυχία',
      DELETE: '{{name}} διαγράφτηκε με επιτυχία',
      ADD: '{{name}} προστέθηκε με επιτυχία',
      ASSIGN: '{{name}} ανατέθηκε με επιτυχία',
      ACTIVATE: '{{name}} ενεργοποιήθηκε με επιτυχία',
      REQUEST: '{{name}} αίτημα απεστάλη με επιτυχία',
      DEACTIVATE: '{{name}} απενεργοποιήθηκε με επιτυχία',
      REGISTER:
        'Εγγραφήκατε με επιτυχία. Θα σταλεί ένα email στη διεύθυνση email σας για να ορίσετε τον κωδικό πρόσβασής σας',
      CLONE: '{{name}} αντιγράφτηκε με επιτυχία',
      CLOSE: '{{name}} ακυρώθηκε με επιτυχία',
      CANCEL: '{{name}} ακυρώθηκε με επιτυχία',
      INVITE: '{{name}} προσκλήθηκε με επιτυχία',
      RESET: 'Ο κωδικός πρόσβασής σας επαναφέρθηκε με επιτυχία',
      FORGOT:
        'Ένα email έχει σταλεί στη διεύθυνση email σας. Ακολουθήστε τις οδηγίες για να επαναφέρετε τον κωδικό πρόσβασής σας',
      REMOVE: '{{name}} αφαιρέθηκε με επιτυχία',
      PASSWORD_CHANGE: 'Ο κωδικός πρόσβασής σας άλλαξε με επιτυχία',
      AMEND: '{{name}} τροποποιήθηκε με επιτυχία',
      RESEND: '{{name}} στάλθηκε με επιτυχία',
      RESET_OTP: 'Κωδικός Πρόσβασης μιας χρήσης δημιουργήθηκε με επιτυχία.',
      UPGRADE: '{{name}} αναβαθμίστηκε με επιτυχία',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Προσθήκη Οργανισμού',
      ADD_PATIENT: 'Προσθήκη Παιδιού',
      ADD_HEALTH_PROFESSIONAL: 'Προσθήκη Παιδαγωγού',
      ADD_ORGANIZATION_ADMIN: 'Προσθήκη Διαχειριστή Οργανισμού',
      ADD_MEMBER: 'Προσθήκη Μέλους',
      INVITE_MEMBER: 'Πρόσκληση Μέλους',
      ADD_GUEST: 'Προσθήκη Επισκέπτη',
      ORGANIZATION: 'Οργανισμός',
      HEALTH_PROFESSIONAL: 'Παιδαγωγός',
      ASSIGN_PATIENTS: 'Ανάθεση Παιδιού',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Παιδαγωγού',
      ASSIGN_MEMBERS: 'Ανάθεση Μελών',
      ASSIGN_GUESTS: 'Ανάθεση Επισκεπτών',
      PATIENT: 'Παιδί',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      SELECT_ORGANIZATION: 'Επέλεξε Οργανισμό',
      UPLOAD_FILE: 'Ανεβάστε ένα αρχείο για ',
      GAME_FILE: 'Αρχείο Δραστηριότητας',
      ALLOWED_FILE_TYPES: 'Επιτρεπτoί τύποι αρχείων: zip',
      UPDATE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      CREATE_SESSION: 'Δημιουργία Περιπέτειας',
      ASSIGN_SESSION_TEMPLATE: 'Ανάθεση Περιπέτειας',
      SUBSCRIPTION_DETAILS: 'Στοιχεία Συνδρομής',
      INACTIVE_SUBSCRIPTION: 'Ανενεργή Συνδρομή',
      EDIT_INFORMATION: 'Επεξεργασία Πληροφοριών',
      INVOICE_INFO: 'Στοιχεία Τιμολόγησης',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Προσθήκη Ερωτηματολογίου',
      QUESTIONNAIRE_TEMPLATE: 'Προτύπο Ερωτηματολογίου',
      WARNING: 'Ενημέρωση',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'Για να αναθέσετε το Ερωτηματολόγιο, χρειάζεται η δημιουργία μίας τουλάχιστον ερώτησης.',
      ADD_NOTE: 'Δημιουργία Σημείωσης',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Ανάθεση προτύπου Ερωτηματολογίου',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'Για να δείτε την προεπισκόπηση ενός ερωτηματολογίου, θα πρέπει να έχει τουλάχιστον μία ενότητα και μία ερώτηση.',
      RESET_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      GENERATE_REPORT: 'Δημιουργία Αναφοράς',
      ACTIVITY_DISPLAY_OPTIONS: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      UPGRADE_ORGANIZATION: 'Αναβάθμιση Οργανισμού',
      ADD_RESELLER_ADMIN: 'Προσθήκη Διαχειριστή',
      GAME_VARIATIONS: 'Παραλλαγές Παιχνιδιού',
      ASSIGN_PRIVATE_GAME: 'Ανάθεση Ιδιωτικού Παιχνιδιού',
      ASSIGN_PUBLIC_GAME: 'Ανάθεση Δημόσιου Παιχνιδιού',
      MEETING_MEMBERS: 'Μέλη Συνάντησης',
    },
    ERROR: {
      IMAGE: 'Το αρχείο που επιλέξατε δεν είναι εικόνα',
      RESOURCE:
        'Δεν μπορείτε να αποκτήσετε πρόσβαση σε αυτόν τον πόρο όταν είστε ήδη συνδεδεμένοι',
      GENERAL:
        'Λυπούμαστε, φαίνεται πως εντοπίστηκαν κάποια σφάλματα. Δοκιμάστε ξανά.',
      FILE: 'Το αρχείο που επιλέξατε δεν υποστηρίζεται.',
      PAGE_NOT_FOUND: 'Η σελίδα δεν βρέθηκε',
      PAGE_NOT_FOUND_BODY: 'Η διεύθυνση URL που ζητήθηκε δεν βρέθηκε',
    },
    BUTTONS: {
      CREATE: 'Δημιουργία Νέου',
      CONFIRM_ACTION: 'Επιβεβαίωση Ενέργειας',
      ADD_EXERCISES: 'Προσθήκη Παιχνιδιών',
      DELETE: 'Διαγραφή',
      VIEW: 'Προβολή',
      APPLY: 'Εφαρμογή',
      EDIT: 'Επεξεργασία',
      BACK: 'Επιστροφή',
      CANCEL: 'Ακύρωση',
      CONTINUE: 'Συνέχεια',
      LOGIN: 'Σύνδεση',
      REGISTER: 'Εγγραφή',
      SAVE: 'Αποθήκευση',
      SUBMIT: 'Υποβολή',
      ACTIVATE: 'Ενεργοποίηση',
      DEACTIVATE: 'Απενεργοποίηση',
      PLAY: 'Παίξε',
      CONFIRM: 'Επιβεβαίωση',
      ACCEPT: 'Αποδοχή',
      DECLINE: 'Απόρριψη',
      NEXT_STEP: 'Επόμενο βήμα',
      PREVIOUS_STEP: 'Προηγούμενο Βήμα',
      ADD: 'Προσθήκη Νέου',
      RESET: 'Επαναφορά',
      UPLOAD_PHOTO: 'Ανέβασμα Φωτογραφίας',
      EDIT_PHOTO: 'Επεξεργασία Φωτογραφίας',
      RESEND_INVITATION: 'Επαναποστολή Πρόσκλησης',
      ASSIGN: 'Ανάθεση',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      DISCARD: 'Σβήσιμο',
      DONE: 'Ολοκλήρωση',
      ADD_ORGANIZATION: 'Προσθήκη Οργανισμού',
      ADD_PATIENT: 'Προσθήκη Παιδιού',
      ADD_MEMBER: 'Προσθήκη Μέλους',
      ADD_GUEST: 'Προσθήκη Επισκέπτη',
      ADD_HEALTH_PROFESSIONAL: 'Προσθήκη Παιδαγωγού',
      ADD_ORGANIZATION_ADMIN: 'Προσθήκη Διαχειριστή Οργανισμού',
      ADD_SESSION: 'Προσθήκη Περιπέτειας',
      ASSIGN_PATIENTS: 'Ανάθεση Παιδιού',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Παιδαγωγών',
      ASSIGN_MEMBERS: 'Ανάθεση Μελών',
      ASSIGN_GUESTS: 'Ανάθεση Επισκεπτών',
      ACTIONS: 'Ενέργειες',
      LOADING: 'Φόρτωση...',
      GO_TO_HOMEPAGE: 'Πηγαίνετε Στην Αρχική Σελίδα',
      ASSIGN_NEW_SESSION: 'Ανάθεση Νέας Περιπέτειας',
      ASSIGN_NEW_QUESTIONNAIRE: 'Ανάθεση Νέου Ερωτηματολογίου',
      CLOSE: 'Κλείσιμο',
      SHOW_MORE: 'Show More',
      SHOW_LESS: 'Show Less',
      CONFIRM_SUBSCRIPTION: 'Επιβεβαίωση Συνδρομής',
      REJECT_SUBSCRIPTION: 'Απόρριψη Συνδρομής',
      NEW_SUBSCRIPTION: 'Νέα Συνδρομή',
      ADD_QUESTIONNAIRE: 'Προσθήκη Ερωτηματολογίου',
      PREVIEW: 'Προεπισκόπηση',
      ADD_ANSWER: 'Προσθήκη επιλογής',
      GOT_IT: 'Κατάλαβα',
      ADD_NOTE: 'Προσθήκη Σημείωσης',
      EXPORT_RESULTS: 'Εξαγωγή Αποτελεσμάτων',
      SAVE_AND_CONTINUE: 'Αποθήκευση και Συνέχεια',
      RESET_ONE_TIME_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      CREATE_BENEFICIARY: 'Δημιουργία Λογαριασμού Παιδιού',
      CREATE_MEMBER: 'Δημιουργία Μέλους',
      CREATE_GUEST: 'Δημιουργία Επισκέπτη',
      CHANGE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      COMPLETE: 'Ολοκλήρωση',
      GENERATE_REPORT: 'Δημιουργία Αναφοράς',
      START_NOW: 'Άρχισε Τώρα!',
      REPLAY: 'Ξαναπαίξε',
      START_SESSION: 'Έναρξη περιπέτειας',
      START_QUESTIONNAIRE: 'Έναρξη',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Προσθήκη Διαχειριστή',
      CREATE_GROUP: 'Δημιουργία Ομάδας',
      ADD_MEETING: 'Νέα Συνάντηση',
      STOP: 'Τέλος Συνάντησης',
      START_MEETING: 'Έναρξη Συνάντησης',
    },
    INPUT: {
      NAME: 'Όνομα',
      EMAIL: 'Email',
      EMAIL_USERNAME: 'Email ( Όνομα χρήστη )',
      PLACE: 'Τόπος',
      VAT: 'ΑΦΜ',
      FIRST_NAME: 'Όνομα',
      STREET_ADDRESS: 'Διεύθυνση',
      LAST_NAME: 'Επώνυμο',
      FULL_NAME: 'Ονοματεπώνυμο',
      PASSWORD: 'Κωδικός Πρόσβασης',
      PATIENT_LIST: 'Λίστα Παιδιών',
      HEALTH_PROFESSIONAL_LIST: 'Λίστα Παιδαγωγών',
      ORGANIZATION_NAME: 'Όνομα Οργανισμού',
      ORGANIZATION_EMAIL: 'Email επικοινωνίας χρέωσης της εταιρείας',
      ORGANIZATION_ACTIVITY: 'Δραστηριότητα',
      CONFIRM_PASSWORD: 'Επιβεβαίωση κωδικού πρόσβασης',
      CITY: 'Πόλη',
      HEALTH_PROFESSIONAL: 'Παιδαγωγός',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      COUNTRY: 'Χώρα',
      ADDRESS: 'Διεύθυνση',
      COMPANY: 'Εταιρεία',
      BIRTH_DATE: 'Ημερομηνία Γέννησης',
      WEBSITE: 'Ιστοσελίδα',
      PHONE: 'Τηλέφωνο Επικοινωνίας',
      ROLE: 'Ρόλος',
      SERVICE: 'Υπηρεσία',
      PREFERRED_LANGUAGE: 'Προτεινόμενη Γλώσσα',
      PREFERRED_ACCOUNT_TYPE: 'Προτιμώμενος Τύπος Λογαριασμού',
      ADDRESS_INFO: 'Πληροφορίες Διεύθυνσης',
      COMPANY_NAME: 'Όνομα Εταιρείας',
      DESCRIPTION: 'Περιγραφή',
      TYPE: 'Τύπος',
      PRICE: 'Τιμή',
      FEATURES: 'Χαρακτηριστικά',
      TITLE: 'Τίτλος',
      TAGS: 'Ετικέτες',
      ACCOUNT_STATUS: 'Κατάσταση Λογαριασμού',
      IMAGE: 'Εικόνα',
      VERSION: 'Έκδοση',
      ACTIVITY: 'Δραστηριότητα',
      OLD_PASSWORD: 'Προηγούμενος Κωδικός Πρόσβασης',
      NEW_PASSWORD: 'Νέος Κωδικός Πρόσβασης',
      CONFIRM_NEW_PASSWORD: 'Επαλήθευση Νέου Κωδικού Πρόσβασης',
      SESSION_NAME: 'Όνομα Περιπέτειας',
      INFO: 'Πληροφορίες',
      HEALTH_PROFESSIONAL_INFO: 'Πληροφορίες Παιδαγωγού',
      PATIENT_INFO: 'Πληροφορίες Παιδιού',
      AGREE_THE: 'Δέχομαι τους',
      TERMS_AND_CONDITIONS: 'όρους και τις προϋποθέσεις',
      SESSION_TEMPLATE_LIST: 'Λίστα Πρότυπων Αποστολών',
      SAVE_AS_TEMPLATE: 'Αποθήκευση ως Πρότυπο',
      BIRTH_YEAR: 'Έτος Γέννησης',
      SEX: 'Φύλο',
      ACCOUNT_TYPE: 'Τύπος Λογαριασμού',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      BENEFICIARIES: 'Παιδιά',
      SUBSCRIPTION_DURATION: 'Διάρκεια Συνδρομής',
      START_DATE: 'Hμερομηνία Έναρξης',
      EXTENSION_DURATION: 'Διάρκεια Παράτασης',
      STARTING_LICENSE: 'Έναρξη Άδειας',
      ANNUAL_FEE: 'Ετήσια Άδεια',
      SUPPORT_SERVICES: 'Υπηρεσίες Υποστήριξης',
      MONTHLY_COST_PER_BENEFICIARY: 'Μηνιαίο Κόστος ανά Παιδί',
      NOTES: 'Μερικές πληροφορίες για εμάς',
      LATEST_OCCUPATION: 'Τελευταίο Επάγγελμα',
      EDUCATION_YEARS: 'Έτη Εκπαίδευσης',
      QUESTIONNAIRE_NAME: 'Όνομα Ερωτηματολογίου',
      WRITE_YOUR_ANSWER: 'Γράψτε την απάντησή σας',
      REQUIRED: 'Υποχρεωτικό',
      SECTION_NAME: 'Όνομα Ενότητας',
      QUESTION: 'Ερώτηση',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Γραπτή απάντηση...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'Η απάντηση πρέπει να περιέχει μόνο νούμερα..',
      HEALTH_PROFESSIONAL_NOTES: 'Σημειώσεις Παιδαγωγού',
      NOTE_TEXT: 'Κείμενο σημείωσης',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Λίστα πρότυπων ερωτηματολογίου',
      PATIENT: 'Παιδί',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'Κωδικός μιας χρήσης',
      CREATE_BENEFICIARY_CONSENT:
        'Έχω τη συναίνεση του γονέα/κηδεμόνα του παιδιού να προχωρήσω στην καταχώρηση των προσωπικών του δεδομένων και την εγγραφή του στην πλατφόρμα Junior Eligence.',
      I_HAVE_THE_BENEFICIARY_CONSENT:
        'Έχω τη συναίνεση του επωφελούμενου να προχωρήσω στην αλλαγή του κωδικού του',
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Μένω',
      SELECT_TIME_PERIOD: 'Χρονική Περίοδος',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Χρονική Περίοδος',
      CURRENT_PASSWORD: 'Τρέχων Κωδικός Πρόσβασης',
      ACTIVITY_DISPLAY_OPTION: 'Επιλογή Χρήσης Δραστηριοτήτων',
      GROUP_NAME: 'Όνομα Ομάδας',
      MEETING_NAME: 'Όνομα Συνάντησης',
    },
    PLACEHOLDERS: {
      ALL: 'Όλα',
      TOTAL_ELEMENTS: 'Συνολικά Στοιχεία',
      SELECT_RESELLERS: 'Επιλέξτε Μεταπωλητή',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Αναζήτηση',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'Ονομα',
      NOTES: 'Σημειωσεις',
      LAST_NAME: 'Επωνυμο',
      PATIENTS: 'Παιδιά',
      SESSIONS: 'Περιπέτειες',
      USER: 'Χρηστης',
      EMAIL: 'Email',
      JOINED_DATE: 'Ημερομηνια Ενταξης',
      COMPANY: 'Εταιρεια',
      NAME: 'Ονομα',
      STATUS: 'Κατάσταση',
      EXECUTIONS: 'Εκτελέσεις',
      COMPLETE_SESSIONS: 'Ολοκληρωμενες Περιπέτειες',
      LAST_LOGIN: 'Τελευταία Είσοδος',
      ACCOUNT_TYPE: 'Τυπος Λογαριασμου',
      ID: 'ID',
      CATEGORY: 'Κατηγορία',
      PRODUCT: 'Προϊόν',
      ACTIONS: 'Ενέργειες',
      DESCRIPTION: 'Περιγραφή',
      CREATED: 'Δημιουργήθηκε',
      COMPLETED: 'Ολοκληρώθηκε',
      COUNTRY: 'Χώρα',
      LANGUAGE: 'Γλώσσα',
      ROLE: 'Ρόλος',
      ADDRESS: 'Διεύθυνση',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      CITY: 'Πόλη',
      ESCORT: 'Συνοδεία',
      ADMIN: 'Διαχειριστής',
      DATE: 'Ημερομηνία',
      TIME: 'Χρόνος',
      DURATION: 'Διάρκεια',
      ADDED: 'Προστέθηκε',
      ORGANIZATION: 'Οργάνωση',
      EXERCISE: 'Παιχνίδι',
      VERSION: 'Έκδοση',
      LEVELS: 'Επίπεδα',
      COGNITIVE: 'Νοητική Ικανότητα',
      CATEGORIES: 'Κατηγορίες',
      ENGINE: 'Μηχανή',
      HEALTH_PROFESSIONAL: 'Παιδαγωγός',
      ASSIGNED_PATIENTS: 'Ανατιθέμενα Παιδιά',
      PATIENT: 'Παιδί',
      OPEN_SESSIONS: 'Ανοιχτές Περιπέτειες',
      SESSION: 'Περιπέτεια',
      ORDER: 'α/α',
      GAMES: 'Δραστηριότητες',
      LAST_EDIT: 'Τελευταία Επεξεργασία',
      CREATOR: 'Δημιουργός',
      DIFFICULTY: 'Δυσκολία',
      ADDED_EXERCISES: 'Προστιθέμενα Παιχνίδια',
      ASSIGNED_BY: 'Ανατέθηκε Από',
      GAME: 'Δραστηριότητα',
      SCORE: 'Επίδοση',
      PROGRESS: 'Πρόοδος',
      BENEFICIARIES: 'Παιδιά',
      LATEST_EXECUTION: 'Τελευταία Εκτέλεση',
      TYPE: 'Τύπος',
      STARTED: 'Έναρξη',
      ENDS: 'Λήξη',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Ανατιθέμενοι Παιδαγωγοί',
      QUESTIONNAIRE: 'Ερωτηματολόγιο',
      DATE_ASSIGNED: 'Ημερομηνία Ανάθεσης',
      DATE_COMPLETED: 'Ημερομηνία Ολοκλήρωσης',
      SECTIONS: 'Ενότητες',
      START_DATE: 'Ημερομηνία Έναρξης',
      EXTENSION_DAYS: 'Ημέρες Παράτασης',
      END_DATE: 'Ημερομηνία Λήξης',
      EXTENSION_DATE: 'Ημερομηνία Παράτασης',
      TOTAL_COST_OF_SUBSCRIPTION: 'Συνολικό Κόστος Συνδρομής',
      DURATION_OF_SUBSCRIPTION: 'Διάρκεια',
      TERMINATION_DATE: 'Ημερομηνία Οριστικής Λήξης',
      INVITATION_SENT: 'Πρόσκληση Απεστάλη',
      SUBSCRIPTION_SENT: 'Συνδρομή Απεστάλη',
      ACTIVITY_DISPLAY_OPTION: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      INVITED_BY: 'Προσκλήθηκε Από',
      GROUP: 'Ομάδα',
      MEMBERS: 'Μέλη',
      GUESTS: 'Επισκέπτες',
      MEETINGS: 'Συναντήσεις',
      MEETING: 'Συνάντηση',
      VARIATIONS: 'Παραλλαγές',
      ACTIVATED: 'Ενεργοποιημένα',
      ASSIGNMENT: 'Ανάθεση',
      INDIVIDUAL_EXECUTIONS: 'Εκτελέσεις (Ατομικό)',
      GROUP_EXECUTIONS: 'Εκτελέσεις (Ομαδικό)',
    },
    VALIDATION: {
      INVALID: '{{name}} είναι άκυρο',
      REQUIRED: '{{name}} απαιτείται',
      MIN_LENGTH: '{{name}} πρέπει να έχει τουλάχιστον 3 σύμβολα',
      MAX_LENGTH: '{{name}} πρέπει να έχει το πολύ 256 σύμβολα',
      MAX_LENGTH_NOTES: '{{name}} πρέπει να έχει το πολύ 480 σύμβολα',
      MIN_LENGTH_PASS: '{{name}} πρέπει να έχει τουλάχιστον 8 σύμβολα',
      AGREEMENT_REQUIRED: 'Απαιτείται η αποδοχή των όρων και προϋποθέσεων',
      NOT_FOUND: 'Το ζητούμενο {{name}} δεν βρέθηκε',
      INVALID_LOGIN: 'Η λεπτομέρεια σύνδεσης είναι εσφαλμένη',
      REQUIRED_FIELD: 'Υποχρεωτικό πεδίο',
      MIN_LENGTH_FIELD: 'Ελάχιστο μήκος πεδίου:',
      MAX_LENGTH_FIELD: 'Μέγιστο μήκος πεδίου:',
      INVALID_FIELD: 'Το πεδίο δεν είναι έγκυρο',
      MUST_MATCH:
        "Τα πεδία 'Κωδικός Πρόσβασης' και 'Επιβεβαίωση Κωδικού Πρόσβασης' δεν ταιριάζουν",
      MUST_MATCH_PIN: "Τα πεδία 'Pin' και 'Επιβεβαίωση Pin' δεν ταιριάζουν",
      NO_PRIMARY: 'Δεν έχετε ορίσει ένα πρωτεύον {{name}}',
      NO_STATUS: 'Δεν έχετε ορίσει κατάσταση {{name}}',
      MANY_PRIMARY: 'Έχετε ορίσει περισσότερα από ένα πρωτεύοντα {{name}}',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Πινακας Επισκοπησης',
        SYSTEM: 'Συστημα',
      },
      HOME: 'Αρχική',
      USER_PROFILE: 'Το προφίλ μου',
      ACCOUNT_SETTINGS: 'Ρυθμίσεις Λογαριασμού',
      LANGUAGE: 'Γλώσσα',
      LOGOUT: 'Αποσύνδεση',
      NOTIFICATIONS: 'Ειδοποιήσεις',
      SUBSCRIPTIONS: 'Συνδρομές',
      ORGANIZATION: 'Οργάνωση',
      GAMES: 'Δραστηριότητες',
      GAMES_MANAGEMENT: 'Διαχείριση Παιχνιδιών',
      SESSIONS: 'Περιπέτειες',
      PATIENTS: 'Παιδιά',
      GUESTS: 'Επισκέπτες ',
      MEMBERS: 'Μέλη',
      ORGANIZATIONS: 'Οργανισμοί',
      MY_ORGANIZATION: 'Διαχείριση Οργανισμού',
      ADMINS: 'Διαχειριστές',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      SIGN_OUT: 'Έξοδος',
      QUESTIONNAIRES: 'Ερωτηματολόγια',
      ELIGENCE_SESSION_TEMPLATES: 'Περιπέτειες',
      TEMPLATES: 'Πρότυπα',
      BY_ELIGENCE: 'Από Eligence',
      RESELLERS: 'Μεταπωλητές',
      HELP: 'Βοήθεια',
      GROUPS: 'Ομάδες',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Πολιτική Απορρήτου',
      CONTACT: 'Επικοινωνία',
      TERMS_AND_CONDITIONS: 'Όροι και Προϋποθέσεις',
      COOKIE_POLICY: 'Πολιτική Cookie',
      PURCHASE: 'Αγορά',
    },
    GAME_DIFFICULTY: {
      EASY: 'Εύκολο',
      INTERMEDIATE: 'Μεσαίο',
      HARD: 'Δύσκολο',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Ατομικά',
      GROUP_MEETING: 'Ομαδική Συνάντηση',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Σήμερα',
      THIS_WEEK: 'Αυτή την εβδομάδα',
      THIS_MONTH: 'Αυτό τον μήνα',
      LAST_7_DAYS: 'Τελευταίες 7 Μέρες',
      LAST_30_DAYS: 'Τελευταίες 30 Μέρες',
      CUSTOM: 'Επιλογή',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Μνήμη',
      LANGUAGE: 'Λόγος',
      ATTENTION: 'Προσοχή',
      CONSTRUCTIVE_ABILITY: 'Κατασκευαστικές Ικανότητες',
      EXECUTIVE_FUNCTIONS: 'Επιτελικές Ικανότητες',
      LOGICAL_REASONING: 'Λογική',
      ORIENTATION: 'Προσανατολισμός',
      SPATIAL_AWARENESS: 'Αντίληψη χώρου',
      MOTOR_SKILLS: 'Κινητικότητα',
      COORDINATION: 'Συντονισμός',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Επισκέπτες',
      NON_GUEST: 'Μέλη',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Τύπος Λογαριασμού',
      ACCOUNT_TYPE_DESCRIPTION: 'Επιλέξτε τον τύπο λογαριασμού σας',
      ORGANIZATION_INFO: 'Πληροφορίες Οργανισμού',
      ORGANIZATION_INFO_DESCRIPTION: 'Εισάγετε τα στοιχεία του Οργανισμού σας',
      INVOICING_DETAILS: 'Στοιχεία Τιμολόγησης',
      INVOICING_DETAILS_DESCRIPTION: 'Συμπληρώστε τα στοιχεία τιμολόγησής σας',
      SETUP_ACCOUNT: 'Συμπληρώστε το Λογαριασμό σας',
      SETUP_ACCOUNT_DESCRIPTION: 'Συμπληρώστε τα στοιχεία του Λογαριασμού σας',
      COMPLETED: 'Ολοκληρώθηκε',
      CHOOSE_ACCOUNT_TYPE: 'Επιλέξτε Τύπο Λογαριασμού',
      SMALL_ORGANIZATION: 'Μικρός Οργανισμός',
      SMALL_ORG_HEALTH_PROF_PATIENTS: '1 παιδαγωγός / 1-10 Παιδιά',
      MEDIUM_ORGANIZATION: 'Μεσαίος Οργανισμός',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS: '1-10 παιδαγωγοί / 1-50 Παιδιά',
      BIG_ORGANIZATION: 'Μεγάλος Οργανισμός',
      BIG_ORG_HEALTH_PROF_PATIENTS: '1-50 Παιδαγωγοί / 1-200 Παιδιά',
      REGISTRATION:
        'Έχει αποσταλεί ηλεκτρονικό μήνυμα στον χρήστη προκειμένου να ενεργοποιήσει τον λογαριασμό του.',
      DONE: 'Ο λογαριασμός σας έχει ενεργοποιηθεί.',
      DONE_DESCRIPTION: 'Είστε έτοιμοι να συνδεθείτε!',
      MERGE_DONE:
        'Είστε ήδη εγγεγραμμένος σε άλλον οργανισμό. Κάθε φορά που συνδέεστε, μπορείτε να επιλέγετε με ποιον οργανισμό θέλετε να περιηγηθείτε',
      SESSION_INFO: 'Πληροφορίες Περιπέτειας',
      SESSION_INFO_STEPPER: 'Ονομάστε την περιπέτεια σας',
      EXERCISES: 'Παιχνίδια',
      EXERCISES_STEPPER: 'Προσθήκη Παιχνιδιών',
      COMPLETION: 'Ολοκλήρωση',
      COMPLETION_STEPPER: 'Ανακεφαλαιώστε!',
      SESSION_INFO_DESCRIPTION:
        'Ονομάστε την περιπέτεια και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      SESSION_EXERCISES: 'Παιχνίδια',
      SESSION_EXERCISES_DESCRIPTION:
        'Προσθέστε παιχνίδια στην περιπέτεια και τροποποιήστε την',
      ADD_EXERCISES: 'Προσθέστε παιχνίδια',
      ADDED_EXERCISES: 'Προστιθέμενες Παιχνίδια',
      CREATE_SESSION_COMPLETION: 'Ένα τελευταίο βήμα!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Ανακεφαλαιώστε!',
      OVERVIEW: 'Επισκόπηση',
      OVERVIEW_BENEFICIARIES: 'Επισκόπηση Παιδιών',
      OVERVIEW_SESSIONS: 'Επισκόπηση Συνεδριών',
      HEALTH_PROFESSIONAL_INFO: 'Πληροφορίες Παιδαγωγού',
      PATIENT_INFO: 'Πληροφορίες Παιδιού',
      SESSION_NOTES: 'Σημειώσεις',
      SESSION_NOTES_DESCRIPTION: 'Προσθέστε μερικές πληροφορίες!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Επίλεξε Τύπο Λογαριασμού',
      SUBSCRIPTION_DETAILS: 'Πληροφορίες Συνδρομής',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Δημιούργησε Πληροφορίες Συνδρομής ',
      NOTES: 'Σημειώσεις',
      NOTES_DESCRIPTION: 'Πρόσθεσε σημειώσεις',
      OVERVIEW_DESCRIPTION: 'Μια τελευταία ματιά',
      GROUP_INFO: 'Πληροφορίες Ομάδας',
      BENEFICIARIES: 'Επωφελούμενοι',
      GROUP_INFO_DESCRIPTION:
        'Ονομάστε την ομάδα σας και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      GROUP_BENEFICIARIES_DESCRIPTION:
        'Προσθέστε Επωφελούμενους στην ομάδα σας',
      ADD_BENEFICIARIES: 'Προσθήκη Επωφελούμενων',
      ADDED_BENEFICIARIES: 'Προστιθέμενοι Επωφελούμενοι',
      CREATE_GROUP_COMPLETION: 'Ένα τελευταίο βήμα!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Ανακεφαλαιώστε!',
      MEETING_INFO: 'Πληροφορίες Συνάντησης',
      MEMBERS: 'Μέλη',
      SESSIONS: 'Συνεδρίες',
      MEETING_INFO_DESCRIPTION:
        'Ονομάστε τη συνάντησή σας και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      MEETING_SESSIONS_DESCRIPTION: 'Προσθέστε συνεδρίες στην συνάντηση.',
      ADD_SESSIONS: 'Προσθήκη Συνεδριών',
      ADDED_SESSIONS: 'Προστιθέμενες Συνεδρίες',
      GAMES: 'Παιχνίδια',
      ASSIGN_GAMES: 'Ανάθεση Παιχνιδιών',
    },
    INFO: {
      INFO: 'Αν χρειάζεστε περισσότερες πληροφορίες, παρακαλούμε ελέγξτε',
      HELP: 'Σελίδα Bοήθειας',
    },
    ACTIONS: {
      ACTIONS: 'Ενέργειες',
      VIEW: 'Προβολή',
      VIEW_PROFILE: 'Προβολή Προφίλ',
      ACTIVATE: 'Ενεργοποίηση',
      DEACTIVATE: 'Απενεργοποίηση',
      DELETE: 'Διαγραφή',
      ASSIGN_PATIENTS: 'Ανάθεση Παιδιών',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Παιδαγωγών',
      RESEND_INVITATION: 'Επαναποστολή Πρόσκλησης',
      PREVIEW: 'Προεπισκόπηση',
      UPLOAD_FILE: 'Ανέβασμα Δραστηριότητας',
      REMOVE_PATIENT: 'Αφαίρεση Παιδιού',
      SET_TO_ACTIVE: 'Ορισμός σε ενεργό',
      EDIT: 'Επεξεργασία',
      REMOVE: 'Κατάργηση',
      FROM_TEMPALTE: 'Από Πρότυπο',
      CREATE_NEW: 'Δημιουργία Νέας',
      CLONE: 'Κλωνοποίηση',
      CLOSE: 'Κλείσιμο',
      CANNOT:
        'Δεν μπορείτε να εκτελέσετε ενέργειες σε αυτή τη περιπέτεια, καθώς έχει ανατεθεί από άλλον Παιδαγωγό',
      REMOVE_HEALTH_PROFESSIONAL: 'Αφαίρεση Παιδαγωγού',
      AMENDMENT: 'Τροποποίηση',
      TERMINATE: 'Τερματισμός',
      NEW_SUBSCRIPTION: 'Νέα Συνδρομή',
      RESEND_EMAIL: 'Επαναποστολή email',
      RENEW: 'Ανανέωση',
      ASSIGN: 'Ανάθεση',
      UNASSIGN: 'Κατάργηση Ανάθεσης',
      CANCEL: 'Κλείσιμο',
      INVITE: 'Πρόσκληση',
      CREATE: 'Δημιουργία',
      RESET_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      ACTIVITY_DISPLAY_OPTIONS: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      UPGRADE: 'Αναβάθμιση',
      VIEW_MEMBERS: 'Προβολή Μελών',
      START_MEETING: 'Έναρξη Συνάντησης',
    },
    AUTH: {
      SIGN_IN: 'Σύνδεση',
      NEW_HERE: 'Νέος Εδώ;',
      SIGNUP: 'Εγγραφείτε',
      FORGOT_BUTTON: 'Ξεχάσατε τον κωδικό πρόσβασης;',
      ABOUT: 'Πληροφορίες',
      CONTACT: 'Επικοινωνία',
      CONTACT_US: 'Επικοινωνήστε μαζί μας',
      FORGOT_PASSWORD: 'Ξέχασα τον κωδικό πρόσβασης',
      RESET_PASSWORD: 'Επαναφορά κωδικού πρόσβασης',
      SET_PASSWORD: 'Ορισμός κωδικού πρόσβασης',
      SETUP_YOUR_NEW_PASSWORD: 'Ρύθμιση νέου κωδικού πρόσβασης',
      AN_EMAIL_IS_REQUIRED: 'Απαιτείται η ύπαρξη ηλεκτρονικής διεύθυνσης.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'Αν ο λογαριασμός σας δημιουργήθηκε με Όνομα Χρήστη, παρακαλούμε επικοινωνήστε με τον παιδαγωγό σας ή τον διαχειριστή.',
    },
    REGISTRATION: {
      SETUP_ACCOUNT: 'Συμπληρώστε τα στοιχεία του λογαριασμού σας',
    },
    PROFILE: {
      OVERVIEW: 'Επισκόπηση',
      SETTINGS: 'Ρυθμίσεις',
      NOTES: 'Σημειώσεις',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      DETAILS: 'Λεπτομέρειες',
      INFORMATION: 'Πληροφορίες',
      NAME: 'Όνομα',
      FULL_NAME: 'Πλήρες Όνομα',
      ROLE: 'Ρόλος',
      CONTACT_PHONE: 'Τηλέφωνο Επικοινωνίας',
      EMAIL: 'Email',
      COUNTRY: 'Χώρα',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      ADDRESS: 'Διεύθυνση',
      TAX_ID: 'ΑΦΜ',
      STATUS: 'Κατάσταση',
      EDIT: 'Επεξεργασία',
      PASSWORD_RESET: 'Επαναφορά Κωδικού Πρόσβασης',
      RESEND_PASSWORD_INVITATION: 'Πρόσκληση Επαναποστολής Κωδικού Πρόσβασης',
      ASSIGNED_PATIENTS: 'Εκχωρημένα Παιδιά',
      ASSIGNED_MEMBERS: 'Εκχωρημένα Μέλη',
      ASSIGNED_GUESTS: 'Εκχωρημένοι Επισκέπτες',
      ACCOUNT_ID: 'Αναγνωριστικό Λογαριασμού',
      BILLING_EMAIL: 'Email Χρέωσης',
      LAST_EDIT: 'Τελευταία Επεξεργασία',
      CREATED_BY: 'Δημιουργήθηκε Από',
      BILLING_ADDRESS: 'Διεύθυνση Χρέωσης',
      ADMINS: 'Διαχειριστές',
      PAYMENT_RECORDS: 'Εγγραφές Πληρωμών',
      PAYMENT_METHODS: 'Μέθοδοι Πληρωμής',
      PERFORMANCE: 'Απόδοση',
      FIRST_NAME: 'Όνομα',
      LAST_NAME: 'Επώνυμο',
      PHONE_NUMBER: 'Αριθμός Τηλεφώνου',
      PREFERRED_LANGUAGE: 'Προτιμώμενη Γλώσσα',
      VAT: 'ΑΦΜ',
      ACTIVITY: 'Δραστηριότητα',
      WEBSITE: 'Ιστοσελίδα',
      CREATED_SESSIONS: 'Δημιουργημένες Περιπέτειες',
      EMAIL_UPDATE_TOOLTIP:
        'Πρέπει να γνωρίζετε ότι το όνομα χρήστη σας θα είναι το νέο σας email',
      CHANGE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      SESSIONS: 'Περιπέτειες',
      ADDED_EXERCISES: 'Παιχνίδια',
      SESSION_EXECUTIONS_TOOLTIP:
        'Αυτή η περιπέτεια έχει εκτελεστεί {{number}} φορές',
      BIRTH_YEAR: 'Έτος Γέννησης',
      SEX: 'Φύλο',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Εκχωρημένοι Παιδαγωγοί',
      SUBSCRIPTIONS: 'Συνδρομές',
      CURRENT_SUBSCRIPTION: 'Τρέχουσα Συνδρομή',
      SUBSCRIPTIONS_HISTORY: 'Ιστορικό Συνδρομών',
      SUBSCRIPTION: 'Συνδρομή',
      UPCOMING_SUBSCRIPTION: 'Επόμενη Συνδρομή',
      LATEST_OCCUPATION: 'Τελευταίο Επάγγελμα',
      EDUCATION_YEARS: 'Έτη Εκπαίδευσης',
      EMAIL_USERNAME: 'Email ( Όνομα χρήστη )',
      INVOICE_INFO: 'Στοιχεία Τιμολόγησης',
      EXECUTIONS: 'Εκτελέσεις',
      MEMBER_SINCE: 'Μέλος από',
      QUESTIONNAIRES: 'Ερωτηματολόγια',
      ASSIGNED: 'Ανατέθηκε',
      COMPLETED: 'Ολοκληρώθηκε',
      ANSWERS: 'Απαντήσεις',
      PASSWORD: 'Κωδικός Πρόσβασης',
      USERNAME: 'Username',
      STAYING_STATUS: 'Μένω',
      ACTIVITY_DISPLAY_OPTION: 'Επιλογή Χρήσης Δραστηριοτήτων',
      GAMES: 'Παιχνίδια',
      MEETINGS: 'Συναντήσεις',
      MEMBERS: 'Μέλη',
      PUBLIC: 'Δημόσιο',
      PRIVATE: 'Ιδιωτικό',
    },
    GENERAL: {
      USER: 'Χρήστης',
      PATIENT: 'Παιδί',
      MEMBER: 'Μέλος',
      GUEST: 'Επισκέπτης',
      HEALTH_PROFESSIONAL: 'Παιδαγωγός',
      GAME: 'Δραστηριότητα',
      PROFILE: 'Προφίλ',
      ORGANIZATION: 'Οργανισμός',
      ORGANIZATION_ADMIN: 'Διαχειριστής Οργανισμού',
      NO_ENTRIES: 'Δεν βρέθηκαν καταχωρήσεις',
      SESSION: 'Περιπέτεια',
      GAMES: 'Δραστηριότητες',
      SESSION_TEMPLATE: 'Περιπέτειες',
      SUBSCRIPTION: 'Subscription',
      SUBSCRIPTION_EMAIL: 'Subscription email',
      ASSIGNED_QUESTIONNAIRE: 'Ερωτηματολόγιο',
      QUESTIONNAIRE_TEMPLATE: 'Ερωτηματολόγιο',
      NOTE: 'Σημείωση',
      COPIED: 'Αντιγράφηκε!',
      CONGRATULATIONS: 'Συγχαρητήρια',
      DESCRIPTION: 'Περιγραφή',
      SAME_COGNITIVE_GAMES: 'Παιχνίδια που εξασκούν την ίδια νοητική ικανότητα',
      SELECT_DIFFICULTY: 'Επιλέξτε επίπεδο δυσκολίας',
      GROUP: 'Ομάδα',
      MEETING: 'Συνάντηση',
    },
    GRAPHS: {
      SCORE: 'Επίδοση',
      TIME: 'Χρόνος',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Εκτελέσεις ανά Νοητική Ικανότητα & Δυσκολία',
      EXECUTIONS_PER_GAME_TITLE: 'Εκτελέσεις ανά Δραστηριότητα',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Μέσος όρος Επίδοσης ανά Δραστηριότητα',
      EXECUTIONS_PER_DAY_TITLE: 'Εκτελέσεις ανά Ημέρα',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE:
        'Εξέλιξη Μέσου Όρου Επίδοσης',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Χρόνος δραστηριότητας ανά Ημέρα (λεπτά)',
      GAME: 'Δραστηριότητα',
      TOTAL: 'Σύνολο',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Ημερολόγια δραστηριοτήτων',
      EXECUTED_GAME: 'Εκτελεσμένο δραστηριότητα',
      ADDED: 'Προστέθηκε: ',
      EXECUTED_SESSION: ' Εκτελεσμένη Περιπέτεια',
    },
    SESSION: {
      MY_SESSIONS: 'Οι Περιπέτειές μου',
      SESSION_COMPLETE: 'Ολοκληρώσατε τη περιπέτεια',
      ABANDONED: 'Εγκαταλείφθηκε',
      SKIPPED: 'Παραλείφθηκε',
      PLAYED: 'Παίχτηκε',
      PENDING: 'Εκκρεμεί',
      ASSIGNED_SESSIONS: 'Ανατεθείσες Περιπέτειες',
      DEFAULT_PUBLIC_INFO:
        'Γειά σου! Αυτή είναι μια περιπέτεια που δημιουργήθηκε μόνο για εσένα! Παρακαλώ ολοκλήρωσέ την ή επικοινώνησε με τον παιδαγωγό σου εάν έχεις περαιτέρω ερωτήσεις.',
      DOCTOR_NOTES: 'Μήνυμα',
      SAMPLE_DOCTOR_NOTES:
        'Αγαπητέ {{name}}, αυτή είναι μια περιπέτεια που δημιουργήθηκε μόνο για εσένα! Παρακαλώ ολοκλήρωσέ την ή επικοινώνησε με τον παιδαγωγό σου εάν έχεις περαιτέρω ερωτήσεις.',
      QUESTS: 'Περιπέτειες',
    },
    STATUS: {
      ACTIVE: 'Ενεργοποιημένος',
      INACTIVE: 'Απενεργοποιημένος',
      INVITED: 'Προσκεκλημένος',
    },
    SESSION_STATUS: {
      ACTIVE: 'Ενεργή',
      ASSIGNED: 'Ανατεθείσα',
      CLOSED: 'Ανενεργή',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Μεταπωλητής',
      DEMO: 'Demo',
      PAID: 'Επί Πληρωμή',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'Διαχειριστής Συστήματος',
      ROLE_ORGANIZATION_OWNER: 'Ιδιοκτήτης Οργανισμού',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Διαχειριστής Οργανισμού',
      ROLE_HEALTH_PROFESSIONAL: 'Παιδαγωγός',
      ROLE_PATIENT: 'Παιδί',
      ROLE_INTERNAL_CONTACT: 'Εσωτερική Επαφή',
      ROLE_EXTERNAL_CONTACT: 'Εξωτερική Επαφή ',
      ROLE_HEALTH_PROFESSIONAL_OWNER: 'Ιδιοκτήτης Οργανισμού/Παιδαγωγός',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Διαχειριστής Οργανισμού/Παιδαγωγός',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Άνδρας',
      FEMALE: 'Γυναίκα',
      OTHER: 'Άλλο',
      NO_ANSWER: 'Δεν επιθυμώ να δηλώσω',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Καλώς όρισες Admin',
      OVERVIEW_DESCRIPTION: 'Ρίξε μια ματιά στους αριθμούς σου',
      EXECUTIONS: 'Εκτελέσεις',
      HOURS: 'Ώρες',
      BENEFICIARIES: 'Παιδιά',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      MOST_PLAYED: 'Περισσότερο Παιγμένα',
      MOST_LEAST_PLAYED_DESCRIPTION:
        'Τελευταίες Ενημερώσεις για τα Δραστηριότητες',
      LEAST_PLAYED: 'Λιγότερο Παιγμένα',
      ACTIVE_LAST_30_DAYS: 'Ενεργοί τις τελευταίες 30 μέρες',
      GAMES_ACTIVITY: 'Δραστηριότητα Δραστηριοτήτων',
      GAMES_ACTIVITY_DESCRIPTION:
        'Συνολικές Εκτελέσεις ανά Δραστηριότητα και Κατηγορία',
      AVERAGE: 'Σύνολο',
      LATEST_UPDATE: 'Τελευταία Ενημέρωση: ',
      HOUR_SHORT: 'ω',
      MINUTE_SHORT: 'λ',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Αριθμός Παιδαγωγών',
      NUMBER_OF_BENEFICIARIES: 'Αριθμός Παιδιών',
      DURATION: 'Διάρκεια',
      START_DATE: 'Ημερομηνία Έναρξης',
      EXTENSION_DAYS: 'Ημέρες Παράτασης',
      END_DATE: 'Ημερομηνία Λήξης',
      EXTENSION_DATE: 'Ημερομηνία Παράτασης',
      STARTING_LICENSE: 'Άδεια Έναρξης',
      ANNUAL_FEE: 'Ετήσια Άδεια',
      SUPPORT_SERVICES: 'Υπηρεσίες Υποστήριξης',
      MONTHLY_COST_PER_BENEFICIARY: 'Μηνιαίο Κόστος ανά Παιδί',
      TOTAL_COST_OF_BENEFICIARIES: 'Συνολικό Κόστος Παιδιών',
      TOTAL_COST_OF_SUBSCRIPTION: 'Συνολικό Κόστος Συνδρομής',
      ORGANIZATION_TYPE: 'Τύπος Χρήστη',
      SUBSCRIPTION_TYPE: 'Τύπος Συνδρομής',
      MONTHS: 'Μήνες',
      DAYS: 'Ημέρες',
      REMAINING_DAYS: 'Ημέρες έως τη λήξη',
      HEALTH_PROFESSIONALS: 'Παιδαγωγοί',
      BENEFICIARIES: 'Παιδιά',
      NOTES: 'Σημειώσεις',
      DURATION_OF_SUBSCRIPTION: 'Διάρκεια',
      COSTS_VAT_DISCLAIMER:
        'Στα παραπάνω κόστη δε συμπεριλαμβάνεται ο ΦΠΑ, όπου ισχύει.',
      ACCEPT_MODAL_FOOTER:
        'Αν δεν επιθυμείτε να επιβεβαιώσετε τη συνδρομή, παρακαλούμε αγνοήστε το ή επικοινωνήστε μαζί μας στην ηλεκτρονική διεύθυνση ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        'Η συνδρομή του οργανισμού σας στην πλατφόρμα Eligence δεν είναι ενεργή και δεν έχετε πρόσβαση. Για περισσότερες πληροφορίες παρακαλούμε επικοινωνήστε με τον διαχειριστή του οργανισμού σας.',
      DAYS_LEFT: 'μέρες που απομένουν',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'Νέα Συνδρομή',
      AMENDMENT: 'Ανανέωση',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Ενεργή',
      EXPIRED: 'Expired',
      PENDING_CONSENT: 'Αναμονή Έγκρισης',
      PENDING_AUTOMATION: 'Αναμονή Ενεργοποίησης',
      REJECTED: 'Απόρριψη',
      TERMINATED: 'Λήξη',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Ανατεθειμένα Ερωτηματολόγια',
      SECTION: 'Ενότητα',
      QUESTION: 'Ερώτηση',
      NOTE: 'Σημείωση',
      BY: 'από',
      NEW_MISSION: 'Γεια σου και πάλι!',
      QUESTIONNAIRE_NOTE:
        'Πριν συνεχίζεις να παίζεις, θα ήθελα να με ακολουθήσεις σε μια ειδική αποστολή!',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Platform Generated',
      USER_GENERATED: 'User Generated',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Ανατεθέν',
      IN_PROGRESS: 'In Progress',
      COMPLETED: 'Ολοκληρώθηκε',
      CANCELLED: 'Ανενεργή',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Free Text',
      INTEGER: 'Numeric',
      CHECKBOX: 'Multiple Choice',
      RADIO: 'Single Choice',
      DROPDOWN: 'Dropdown',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Το Ερωτηματολόγιο είναι ένα προτεινόμενο εργαλείο που σας παρέχει η πλατφόρμα Junior Eligence. Μέσω του Ερωτηματολογίου μπορείτε να συλλέξετε πληροφορίες σχετικά με το συγκεκριμένο παιδί ή να λάβετε πληροφορίες για να αξιολογήσετε την κατάστασή του.',
      PROMPT:
        'Όταν το ερωτηματολόγιο ανατεθεί στο παιδί όλες οι δωρεάν δραστηριότητες και οι Περιπέτειες θα απενεργοποιηθούν έως ότου το παιδί το ολοκληρώσει.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Δημιουργία Λογαριασμού Παιδιού',
      TITLE_MEMBER: 'Δημιουργία Μέλους',
      TITLE_GUEST: 'Δημιουργία Επισκέπτη',
      CREDENTIALS: 'Στοιχεία χρήστη',
      PERSONAL_DETAILS: 'Πληροφορίες',
      COMPLETION: 'Ολοκλήρωση',
      CHECK_AVAILABILITY: 'Έλεγχος διαθεσιμότητας',
      USERNAME_AVAILABLE: 'Username διαθέσιμο',
      USERNAME_UNAVAILABLE: 'Μη διαθέσιμο, προσπαθήστε ξανά',
      OTP_SAVE_WARNING: 'Αποθηκεύστε ασφαλώς τον κωδικό για μελλοντική χρήση.',
      DONE: 'Είστε έτοιμοι!',
      DONE_DESCRIPTION:
        'Ένας νέος λογαριασμός χρήστη έχει δημιουργηθεί. Κατά τη διάρκεια της πρώτης σύνδεσης, θα ζητηθεί από τον γονέα/κηδεμόνα του παιδιού η αλλαγή κωδικού για την προστασία των προσωπικών του δεδομένων.',
    },
    GAMES: {
      MY_GAMES: 'Οι Δραστηριότητές μου',
      ALL_GAMES: 'Όλα',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'For Groups',
      FOR_TWO: 'For Two',
      INTERGENERATION: 'Intergen',
      CHALLENGING: 'Challenging',
    },
    STAYING_STATUS: {
      ALONE: 'Μόνος/μόνη μου',
      WITH_HUSBAND_WIFE: 'Με σύζυγο/σύντροφό μου',
      WITH_KIDS_GRANDKIDS: 'Με τα παιδιά/εγγόνια μου',
      WITH_CARER: 'Με φροντιστή',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'Προβολή όλων',
      ONLY_SESSIONS: 'Μόνο περιπέτειες',
      ONLY_GAMES: 'Μόνο παιχνίδια',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Ανατεθείσα',
      UNASSIGNED: 'Μη Ανατεθείσα',
    },
    GAME_ACCESS: {
      PUBLIC: 'Δημόσιο',
      PRIVATE: 'Ιδιωτικό',
    },
    PRIVACY_POLICY: {
      CONTENT: privacy_policy_GR,
    },
    TERMS: {
      TEST: terms_GR,
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h2>Πολιτική Cookie</h2><br><h2>ΛΙΣΤΑ COOKIES</h2><p>Ένα cookie είναι ένα μικρό κομμάτι δεδομένων (αρχείο κειμένου) που ένας ιστότοπος – που επισκέπτεται ένα χρήστης – ζητά από το πρόγραμμα περιήγησής σας την άδεια να αποθηκεύσει στην συσκευή σας, για να σας θυμάται, πληροφορίες σχετικές με εσάς, όπως η προτίμηση γλώσσας, ή τα στοιχεία – πληροφορίες σύνδεσης. Αυτά τα cookies ορίζονται από εμάς και ονομάζονται cookies προβαλλόμενου ιστότοπου (κύριας σελίδας). Χρησιμοποιούμε επίσης cookies τρίτων – τα οποία είναι cookies από έναν τομέα διαφορετικό από αυτόν του ιστότοπου που επισκέπτεστε – για τις διαφημιστικές και εμπορικές μας προσπάθειες.</p><h2>ΔΙΑΧΕΙΡΙΣΗ ΡΥΘΜΙΣΕΩΝ COOKIE</h2><p>Σε οποιαδήποτε σελίδα του ιστότοπου, κάνοντας κλικ στο κουμπί στην αριστερή κάτω γωνία, θα ανοίξει το banner cookie και θα είναι δυνατή η τροποποίηση και επαναφορά των προτιμήσεών σας. Επιλέγοντας «αποδοχή όλων των cookies» δίνετε την συγκατάθεσή σας για την χρήση όλων των τύπων cookies, ενώ μπορείτε να αποσύρετε την συγκατάθεσή σας κάνοντας κλικ στο «Απόρριψη όλων των cookies». Αποφασίζοντας να κλείσετε το banner, οι προτιμήσεις που δόθηκαν προηγουμένως θα διατηρηθούν μέχρι περαιτέρω τροποποίηση. Ανοίγοντας το banner μπορείτε να διαχειριστείτε τις συναινέσεις για διάφορους τύπους cookies, με βάση τις προτιμήσεις σας.</p><h2>ΑΠΑΡΑΙΤΗΤΑ  COOKIES</h2><p>Αυτά τα cookies είναι απαραίτητα για την λειτουργία του ιστότοπου και δεν μπορούν να απενεργοποιηθούν στα συστήματά μας. Τυχόν cookies ή άλλα εργαλεία παρακολούθησης που χρησιμοποιούνται από αυτή την Υπηρεσία ή Άλλους Παρόχους υπηρεσιών τρίτων, που χρησιμοποιούνται από ή μέσω αυτής της Υπηρεσίας, εξυπηρετούν τον σκοπό να παρέχουν την υπηρεσία που απαιτείται στον Χρήστη, πλέον των άλλων σκοπών που περιγράφονται στην Πολιτική Απορρήτου.</p><h2>COOKIES(ANALYTICS) ΑΝΑΛΥΤΙΚΩΝ</h2><p>Τα analyticscookies είναι cookies που παρακολουθούν τον τρόπο πλοήγησης και αλληλεπίδρασης των χρηστών με την Υπηρεσία. Οι πληροφορίες που συλλέγονται, χρησιμοποιούνται για να βοηθήσουν τον κάτοχο της Υπηρεσίας να βελτιώσει την Υπηρεσία.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
