export const locale = {
  lang: 'el',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE:
        'Παρακαλούμε επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      USERNAME_NOT_FOUND_EXCEPTION: 'Το όνομα χρήστη δε μπορεί να βρεθεί',
      USER_LOGIN_EXCEPTION: 'Τo όνομα χρήστη ή ο κωδικός δεν είναι έγκυρα',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION: 'Μη έγκυρο email ή κωδικός',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'Ο χρήστης υπάρχει ήδη στον οργανισμό',
      USER_REGISTRATION_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά την εγγραφή του χρήστη',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά τη δημιουργία συνδέσμου επαναφοράς του κωδικού πρόσβασης',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'Ο λογαριασμός με αυτές τις πληροφορίες δεν έχει ενεργοποιηθεί ακόμα. Η επαναφορά του κωδικού πρόσβασης δεν μπορεί να ενεργοποιηθεί',
      PASSWORD_RESET_EXCEPTION:
        'Παρουσιάστηκε σφάλμα κατά την επαναφορά του κωδικού πρόσβασής σας',
      MAIL_SEND_EXCEPTION: 'Παρουσιάστηκε σφάλμα κατά την αποστολή email',
      UPDATE_PASSWORD_EXCEPTION: 'Μη έγκυρος τρέχων κωδικός πρόσβασης',
      TOKEN_REFRESH_EXCEPTION:
        'Δεν ήταν δυνατή η ανανέωση του authorization token',
      USER_LOGOUT_EXCEPTION: 'Παρουσιάστηκε σφάλμα κατά την αποσύνδεσή σας',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      FORBIDDEN_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      UNAUTHORIZED_EXCEPTION:
        'Δεν έχετε εξουσιοδότηση πρόσβασης σε αυτόν τον πόρο',
      IP_BLOCKED_EXCEPTION:
        'Έχετε αποκλειστεί προσωρινά λόγω πολλαπλών προσπαθειών σύνδεσης',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'Η διεύθυνση email που καταχωρίσατε χρησιμοποιείται ήδη',
      FILE_GENERIC_EXCEPTION:
        'Σφάλμα αρχείου. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Το επιχείρημα δεν είναι έγκυρο. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      APP_EXCEPTION:
        'Κάτι πήγε λάθος. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'Ο πόρος χρησιμοποιείται ήδη. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Ο πόρος δεν βρέθηκε. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      FILE_NOT_FOUND_EXCEPTION:
        'Το αρχείο δεν βρέθηκε. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      BAD_REQUEST_EXCEPTION:
        'Λάθος αίτημα. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Ο τύπος μέσου δεν είναι αποδεκτός. Επικοινωνήστε με την υποστήριξη ή δοκιμάστε ξανά αργότερα',
      SESSION_EXPIRED_EXCEPTION:
        'Ο χρόνος παραμονής σας έχει λήξει. Παρακαλώ συνδεθείτε ξανά',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'Ο χρήστης δεν είναι ενεργός σε κάποιον οργανισμό. Αυτό σημαίνει ότι ένας από τους διαχειριστές του οργανισμού σας, σας έχει απενεργοποιήσει. Επικοινωνήστε απευθείας μαζί τους',
      PASSWORD_MISMATCH_EXCEPTION: 'Οι κωδικοί πρόσβασης δεν ταιριάζουν.',
      ORGANIZATION_NAME_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το όνομα.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτή την ιστοσελίδα.',
      ORGANIZATION_PHONE_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το τηλέφωνο επικοινωνίας.',
      ORGANIZATION_EMAIL_CONFLICT:
        'Υπάρχει ήδη ένας οργανισμός με αυτό το email.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        "You cannot invite a Health Professional. You have reached your subscription's limit.",
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        "You cannot invite a Beneficiary. You have reached your subscription's limit.",
      ORGANIZATION_VAT_CONFLICT: 'Υπάρχει ήδη ένας οργανισμός με αυτό το ΑΦΜ.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'The organization has not accepted the subscription.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'The organization does not have active or pending subscription.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'The organization is inactive.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'The user is not verified in the organization',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'Υπάρχει ήδη μια συνδρομή για αυτές τις ημερομηνίες.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'You cannot perform actions on this assessment because it was not created by your organization.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'Υπάρχει ήδη ένα ερωτηματολόγιο για αυτό το χρήστη.',
      QUESTIONNAIRE_IS_EMPTY:
        'Για να αναθέσετε το ερωτηματολόγιο, χρειάζεται η δημιουργία μίας τουλάχιστον ερώτησης.',
      SESSION_ALREADY_IN_USE:
        'Παρατηρήθηκε μία ταυτόχρονη προσπάθεια σύνδεσης από άλλη συσκευή και για λόγους ασφαλείας έχετε αποσυνδεθεί. Παρακαλούμε πραγματοποιήστε νέα είσοδο για να ανακτήσετε πρόσβαση στο λογαριασμό σας και να συνεχίσετε τη δραστηριότητά σας.',
    },
    ROUTES_TITLE: {
      HOME: 'Αρχική',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'Διαχειριστές Συστήματος',
      HEALTH_PROFESSIONALS: 'Επαγγελματίες Υγείας',
      BENEFICIARIES: 'Επωφελούμενοι',
      MEMBERS: 'Μέλη',
      MEMBER_PROFILE: 'Προφίλ Μέλους',
      GUESTS: 'Επισκέπτες',
      GUEST_PROFILE: 'Προφίλ Επισκέπτη',
      MY_PROFILE: 'Το προφίλ μου',
      USER_PROFILE: 'Προφίλ Χρήστη',
      ORGANIZATIONS: 'Οργανισμοί',
      ORGANIZATION_PROFILE: 'Προφίλ Οργανισμού',
      GAMES: 'Παιχνίδια',
      GAME_MANAGEMENT: 'Διαχείριση Παιχνιδιών',
      GAME_OVERVIEW: 'Επισκόπηση Παιχνιδιού',
      SESSION_TEMPLATES: 'Προτύπα Συνεδρίας',
      SESSIONS_BY_ELIGENCE: 'Συνεδρίες από Eligence',
      SESSION_TEMPLATE: 'Προτύπο Συνεδρίας',
      QUESTIONNAIRE_TEMPLATES: 'Πρότυπα Ερωτηματολογίου',
      QUESTIONNAIRES_BY_ELIGENCE: 'Ερωτηματολόγια από Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Πρότυπο Ερωτηματολογίου',
      ASSIGNED_SESSION: 'Ανατεθείσα Συνεδρία',
      ASSIGNED_QUESTIONNAIRE: 'Ερωτηματολόγιο',
      ADD_SESSION: 'Προσθήκη Συνεδρίας',
      CREATE_BENEFICIARY: 'Δημιουργία Επωφελούμενου',
      SUBSCRIPTIONS_MANAGEMENT: 'Διαχείριση Συνδρομών',
      ELIGENCE_SESSION_TEMPLATES: 'Συνεδρίες',
      RESELLERS: 'Μεταπωλητές',
      RESELLER_PROFILE: 'Προφίλ Mεταπωλητή',
      GROUPS: 'Ομάδες',
      CREATE_GROUP: 'Δημιουργία Ομάδας',
      CREATE_MEMBER: 'Δημιουργία Μέλους',
      CREATE_GUEST: 'Δημιουργία Επισκέπτη',
      GROUP_PROFILE: 'Προφίλ Ομάδας',
      ADD_MEETING: 'Νέα Συνάντηση',
      EDIT_GROUP: 'Επεξεργασία Ομάδας',
      GAME_VARIATIONS: 'Παραλλαγές Παιχνιδιού',
    },
    CONFIRM: {
      DELETE: 'Είστε βέβαιοι ότι θέλετε να διαγράψετε το {{name}};',
      CREATE: 'Είστε βέβαιοι ότι θέλετε να δημιουργήσετε το νέο {{name}};',
      EDIT: 'Είστε βέβαιοι ότι θέλετε να επεξεργαστείτε το {{name}};',
      CHANGE: 'Είστε βέβαιοι ότι θέλετε να αποθηκεύσετε τις αλλαγές;',
      ACTIVATE: 'Είστε βέβαιοι ότι θέλετε να ενεργοποιήσετε αυτόν τον χρήστη;',
      ACTIVATE_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να ενεργοποιήσετε αυτόν τον οργανισμό;',
      DEACTIVATE:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτόν τον χρήστη;',
      DEACTIVATE_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτόν τον οργανισμό;',
      INVITATION:
        'Είστε βέβαιοι ότι θέλετε να στείλετε ξανά την πρόσκληση για αυτόν τον χρήστη;',
      INVITATION_ORGANIZATION:
        'Είστε βέβαιοι ότι θέλετε να στείλετε ξανά την πρόσκληση για αυτόν τον οργανισμό;',
      BOOK: 'Είστε βέβαιοι ότι θέλετε να κάνετε κράτηση για τον/την {{name}};',
      CANCEL_BOOKING:
        'Είστε βέβαιοι ότι θέλετε να ακυρώσετε την κράτηση με αυτόν τον χρήστη;',
      UPDATE_MAIL_WARNING:
        'Είστε σίγουροι ότι θέλετε να αλλάξετε το email σας; Λάβετε υπόψη ότι το όνομα χρήστη σας θα είναι το νέο σας email.',
      ACTIVATE_GAME:
        'Είστε σίγουροι ότι θέλετε να ενεργοποιήσετε αυτό το παιχνίδι;',
      ACTIVATE_GAME_TEMPLATE:
        'Είστε σίγουροι ότι θέλετε να ενεργοποιήσετε τη συγκεκριμένη κατηγορία παιχνιδιών;',
      DEACTIVATE_GAME:
        'Είστε βέβαιοι ότι θέλετε να απενεργοποιήσετε αυτό το παιχνίδι;',
      DEACTIVATE_GAME_WARNING:
        'Το παιχνίδι είναι ανατεθειμένο σε {{sessions}} συνεδρίες, {{beneficiaries}} επωφελούμενους, {{sessionTemplates}} πρότυπα συνεδριών, {{systemAssignedSessions}} συνεδρίες από Eligence, {{systemSessionTemplates}} πρότυπα συνεδριών από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να το απενεργοποιήσετε;',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'H συγκεκριμένη κατηγορία παιχνιδιών είναι ανατεθειμένη σε {{sessions}} συνεδρίες, {{beneficiaries}} επωφελούμενους, {{sessionTemplates}} πρότυπα συνεδριών, {{systemAssignedSessions}} συνεδρίες από Eligence, {{systemSessionTemplates}} πρότυπα συνεδριών από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να την απενεργοποιήσετε;',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'Το παιχνίδι είναι ανατεθειμένο σε {{sessions}} ενεργές συνεδρίες, {{systemAssignedSessions}} συνεδρίες από Eligence, {{groupAssignedSessions}} ομαδικές συνεδρίες. Είστε σίγουροι ότι θέλετε να το απενεργοποιήσετε;',
      REMOVE_PATIENT:
        'Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτόν τον Επωφελούμενο από τον συγκεκριμένο Επαγγελματία Υγείας;',
      CLOSE_SESSION: 'Σίγουρα θέλετε να κλείσετε αυτή τη συνεδρία;',
      DELETE_SESSION: 'Σίγουρα θέλετε να διαγράψετε αυτή τη συνεδρία;',
      DELETE_QUESTIONNAIRE:
        'Σίγουρα θέλετε να διαγράψετε αυτό το ερωτηματολόγιο;',
      REMOVE_HEALTH_PROFESSIONAL:
        'Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτόν τον Επαγγελματία Υγείας από τον συγκεκριμένο Επωφελούμενο;',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        'Είναι τα παιχνίδια στη σειρά που θέλετε να εμφανιστούν στον επωφελούμενο; Έχετε επιλέξει το επιθυμητό επίπεδο δυσκολίας για κάθε παιχνίδι;',
      CANCEL:
        'Είστε σίγουροι ότι θέλετε να απενεργοποιήσετε αυτή την {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Αν διαγράψετε αυτή την ενότητα, θα διαγραφούν όλες οι ερωτήσεις της. Είστε σίγουροι ότι θέλετε να συνεχίσετε?',
    },
    SUCCESS: {
      CREATE: '{{name}} δημιουργήθηκε με επιτυχία',
      EDIT: '{{name}} επεξεργάστηκε με επιτυχία',
      UPDATE: '{{name}} ενημερώθηκε με επιτυχία',
      DELETE: '{{name}} διαγράφτηκε με επιτυχία',
      ADD: '{{name}} προστέθηκε με επιτυχία',
      ASSIGN: '{{name}} ανατέθηκε με επιτυχία',
      ACTIVATE: '{{name}} ενεργοποιήθηκε με επιτυχία',
      REQUEST: '{{name}} αίτημα απεστάλη με επιτυχία',
      DEACTIVATE: '{{name}} απενεργοποιήθηκε με επιτυχία',
      REGISTER:
        'Εγγραφήκατε με επιτυχία. Θα σταλεί ένα email στη διεύθυνση email σας για να ορίσετε τον κωδικό πρόσβασής σας',
      CLONE: '{{name}} αντιγράφτηκε με επιτυχία',
      CLOSE: '{{name}} ακυρώθηκε με επιτυχία',
      CANCEL: '{{name}} ακυρώθηκε με επιτυχία',
      INVITE: '{{name}} προσκλήθηκε με επιτυχία',
      RESET: 'Ο κωδικός πρόσβασής σας επαναφέρθηκε με επιτυχία',
      FORGOT:
        'Ένα email έχει σταλεί στη διεύθυνση email σας. Ακολουθήστε τις οδηγίες για να επαναφέρετε τον κωδικό πρόσβασής σας',
      REMOVE: '{{name}} αφαιρέθηκε με επιτυχία',
      PASSWORD_CHANGE: 'Ο κωδικός πρόσβασής σας άλλαξε με επιτυχία',
      AMEND: '{{name}} τροποποιήθηκε με επιτυχία',
      RESEND: '{{name}} στάλθηκε με επιτυχία',
      RESET_OTP: 'Κωδικός Πρόσβασης μιας χρήσης δημιουργήθηκε με επιτυχία.',
      UPGRADE: '{{name}} αναβαθμίστηκε με επιτυχία',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Προσθήκη Οργανισμού',
      ADD_PATIENT: 'Προσθήκη Επωφελούμενου',
      ADD_HEALTH_PROFESSIONAL: 'Προσθήκη Επαγγελματία Υγείας',
      ADD_ORGANIZATION_ADMIN: 'Προσθήκη Διαχειριστή Οργανισμού',
      ADD_MEMBER: 'Προσθήκη Μέλους',
      INVITE_MEMBER: 'Πρόσκληση Μέλους',
      ADD_GUEST: 'Προσθήκη Επισκέπτη',
      ORGANIZATION: 'Οργανισμός',
      HEALTH_PROFESSIONAL: 'Επαγγελματίας Υγείας',
      ASSIGN_PATIENTS: 'Ανάθεση Επωφελούμενου',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Επαγγελματία Υγείας',
      ASSIGN_MEMBERS: 'Ανάθεση Μελών',
      ASSIGN_GUESTS: 'Ανάθεση Επισκεπτών',
      PATIENT: 'Επωφελούμενος',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      SELECT_ORGANIZATION: 'Επέλεξε Οργανισμό',
      UPLOAD_FILE: 'Ανεβάστε ένα αρχείο για ',
      GAME_FILE: 'Αρχείο Παιχνιδιού',
      ALLOWED_FILE_TYPES: 'Επιτρεπτoί τύποι αρχείων: zip',
      UPDATE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      CREATE_SESSION: 'Δημιουργία Συνεδρίας',
      ASSIGN_SESSION_TEMPLATE: 'Ανάθεση Προτύπου Συνεδρίας',
      SUBSCRIPTION_DETAILS: 'Στοιχεία Συνδρομής',
      INACTIVE_SUBSCRIPTION: 'Ανενεργή Συνδρομή',
      EDIT_INFORMATION: 'Επεξεργασία Πληροφοριών',
      INVOICE_INFO: 'Στοιχεία Τιμολόγησης',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Προσθήκη Προτύπου Ερωτηματολογίου',
      QUESTIONNAIRE_TEMPLATE: 'Προτύπο Ερωτηματολογίου',
      WARNING: 'Ενημέρωση',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'Για να αναθέσετε το ερωτηματολόγιο, χρειάζεται η δημιουργία μίας τουλάχιστον ερώτησης.',
      ADD_NOTE: 'Δημιουργία Σημείωσης',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Ανάθεση προτύπου ερωτηματολογίου',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'Για να δείτε την προεπισκόπηση ενός ερωτηματολογίου, θα πρέπει να έχει τουλάχιστον μία ενότητα και μία ερώτηση.',
      RESET_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      GENERATE_REPORT: 'Δημιουργία Report',
      ACTIVITY_DISPLAY_OPTIONS: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      UPGRADE_ORGANIZATION: 'Αναβάθμιση Οργανισμού',
      ADD_RESELLER_ADMIN: 'Προσθήκη Διαχειριστή',
      GAME_VARIATIONS: 'Παραλλαγές Παιχνιδιού',
      ASSIGN_PRIVATE_GAME: 'Ανάθεση Ιδιωτικού Παιχνιδιού',
      ASSIGN_PUBLIC_GAME: 'Ανάθεση Δημόσιου Παιχνιδιού',
      MEETING_MEMBERS: 'Μέλη Συνάντησης',
    },
    ERROR: {
      IMAGE: 'Το αρχείο που επιλέξατε δεν είναι εικόνα',
      RESOURCE:
        'Δεν μπορείτε να αποκτήσετε πρόσβαση σε αυτόν τον πόρο όταν είστε ήδη συνδεδεμένοι',
      GENERAL:
        'Λυπούμαστε, φαίνεται πως εντοπίστηκαν κάποια σφάλματα. Δοκιμάστε ξανά.',
      FILE: 'Το αρχείο που επιλέξατε δεν υποστηρίζεται.',
      PAGE_NOT_FOUND: 'Η σελίδα δεν βρέθηκε',
      PAGE_NOT_FOUND_BODY: 'Η διεύθυνση URL που ζητήθηκε δεν βρέθηκε',
    },
    BUTTONS: {
      CREATE: 'Δημιουργία Νέου',
      CONFIRM_ACTION: 'Επιβεβαίωση Ενέργειας',
      ADD_EXERCISES: 'Προσθήκη Παιχνιδιών',
      DELETE: 'Διαγραφή',
      VIEW: 'Προβολή',
      APPLY: 'Εφαρμογή',
      EDIT: 'Επεξεργασία',
      BACK: 'Επιστροφή',
      CANCEL: 'Ακύρωση',
      CONTINUE: 'Συνέχεια',
      LOGIN: 'Σύνδεση',
      REGISTER: 'Εγγραφή',
      SAVE: 'Αποθήκευση',
      SUBMIT: 'Υποβολή',
      ACTIVATE: 'Ενεργοποίηση',
      DEACTIVATE: 'Απενεργοποίηση',
      PLAY: 'Παίξε',
      CONFIRM: 'Επιβεβαίωση',
      ACCEPT: 'Αποδοχή',
      DECLINE: 'Απόρριψη',
      NEXT_STEP: 'Επόμενο βήμα',
      PREVIOUS_STEP: 'Προηγούμενο Βήμα',
      ADD: 'Προσθήκη Νέου',
      RESET: 'Επαναφορά',
      UPLOAD_PHOTO: 'Ανέβασμα Φωτογραφίας',
      EDIT_PHOTO: 'Επεξεργασία Φωτογραφίας',
      RESEND_INVITATION: 'Επαναποστολή Πρόσκλησης',
      ASSIGN: 'Ανάθεση',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      DISCARD: 'Σβήσιμο',
      DONE: 'Ολοκλήρωση',
      ADD_ORGANIZATION: 'Προσθήκη Οργανισμού',
      ADD_PATIENT: 'Προσθήκη Επωφελούμενου',
      ADD_HEALTH_PROFESSIONAL: 'Προσθήκη Επαγγελματία Υγείας',
      ADD_ORGANIZATION_ADMIN: 'Προσθήκη Διαχειριστή Οργανισμού',
      ADD_MEMBER: 'Προσθήκη Μέλους',
      ADD_GUEST: 'Προσθήκη Επισκέπτη',
      ADD_SESSION: 'Προσθήκη Συνεδρίας',
      ASSIGN_PATIENTS: 'Ανάθεση Επωφελούμενου',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Επαγγελματιών Υγείας',
      ASSIGN_MEMBERS: 'Ανάθεση Μελών',
      ASSIGN_GUESTS: 'Ανάθεση Επισκεπτών',
      ACTIONS: 'Ενέργειες',
      LOADING: 'Φόρτωση...',
      GO_TO_HOMEPAGE: 'Πηγαίνετε Στην Αρχική Σελίδα',
      ASSIGN_NEW_SESSION: 'Ανάθεση Νέας Συνεδρίας',
      ASSIGN_NEW_QUESTIONNAIRE: 'Ανάθεση Νέου Ερωτηματολογίου',
      CLOSE: 'Κλείσιμο',
      SHOW_MORE: 'Show More',
      SHOW_LESS: 'Show Less',
      CONFIRM_SUBSCRIPTION: 'Επιβεβαίωση Συνδρομής',
      REJECT_SUBSCRIPTION: 'Απόρριψη Συνδρομής',
      NEW_SUBSCRIPTION: 'Νέα Συνδρομή',
      ADD_QUESTIONNAIRE: 'Προσθήκη Ερωτηματολογίου',
      PREVIEW: 'Προεπισκόπηση',
      ADD_ANSWER: 'Προσθήκη επιλογής',
      GOT_IT: 'Κατάλαβα',
      ADD_NOTE: 'Προσθήκη Σημείωσης',
      EXPORT_RESULTS: 'Εξαγωγή Αποτελεσμάτων',
      SAVE_AND_CONTINUE: 'Αποθήκευση και Συνέχεια',
      RESET_ONE_TIME_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      CREATE_BENEFICIARY: 'Δημιουργία Επωφελούμενου',
      CREATE_MEMBER: 'Δημιουργία Μέλους',
      CREATE_GUEST: 'Δημιουργία Επισκέπτη',
      CHANGE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      COMPLETE: 'Ολοκλήρωση',
      GENERATE_REPORT: 'Δημιουργία Report',
      START_NOW: 'Άρχισε Τώρα!',
      REPLAY: 'Ξαναπαίξε',
      START_SESSION: 'Έναρξη συνεδρίας',
      ACTIVITY_DISPLAY_OPTION: 'Επιλογή Χρήσης Δραστηριοτήτων',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Προσθήκη Διαχειριστή',
      CREATE_GROUP: 'Δημιουργία Ομάδας',
      ADD_MEETING: 'Νέα Συνάντηση',
      STOP: 'Τέλος Συνάντησης',
      START_MEETING: 'Έναρξη Συνάντησης',
    },
    INPUT: {
      NAME: 'Όνομα',
      EMAIL: 'Email',
      EMAIL_USERNAME: 'Email ( Όνομα χρήστη )',
      PLACE: 'Τόπος',
      VAT: 'ΑΦΜ',
      FIRST_NAME: 'Όνομα',
      STREET_ADDRESS: 'Διεύθυνση',
      LAST_NAME: 'Επώνυμο',
      FULL_NAME: 'Ονοματεπώνυμο',
      PASSWORD: 'Κωδικός Πρόσβασης',
      PATIENT_LIST: 'Λίστα Επωφελούμενων',
      HEALTH_PROFESSIONAL_LIST: 'Λίστα Επαγγελματιών Υγείας',
      ORGANIZATION_NAME: 'Όνομα Οργανισμού',
      ORGANIZATION_EMAIL: 'Email επικοινωνίας χρέωσης της εταιρείας',
      ORGANIZATION_ACTIVITY: 'Δραστηριότητα',
      CONFIRM_PASSWORD: 'Επιβεβαίωση κωδικού πρόσβασης',
      CITY: 'Πόλη',
      HEALTH_PROFESSIONAL: 'Επαγγελματίας Υγείας',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      COUNTRY: 'Χώρα',
      ADDRESS: 'Διεύθυνση',
      COMPANY: 'Εταιρεία',
      BIRTH_DATE: 'Ημερομηνία Γέννησης',
      WEBSITE: 'Ιστοσελίδα',
      PHONE: 'Τηλέφωνο Επικοινωνίας',
      ROLE: 'Ρόλος',
      SERVICE: 'Υπηρεσία',
      PREFERRED_LANGUAGE: 'Προτεινόμενη Γλώσσα',
      PREFERRED_ACCOUNT_TYPE: 'Προτιμώμενος Τύπος Λογαριασμού',
      ADDRESS_INFO: 'Πληροφορίες Διεύθυνσης',
      COMPANY_NAME: 'Όνομα Εταιρείας',
      DESCRIPTION: 'Περιγραφή',
      TYPE: 'Τύπος',
      PRICE: 'Τιμή',
      FEATURES: 'Χαρακτηριστικά',
      TITLE: 'Τίτλος',
      TAGS: 'Ετικέτες',
      ACCOUNT_STATUS: 'Κατάσταση Λογαριασμού',
      IMAGE: 'Εικόνα',
      VERSION: 'Έκδοση',
      ACTIVITY: 'Δραστηριότητα',
      OLD_PASSWORD: 'Προηγούμενος Κωδικός Πρόσβασης',
      NEW_PASSWORD: 'Νέος Κωδικός Πρόσβασης',
      CONFIRM_NEW_PASSWORD: 'Επαλήθευση Νέου Κωδικού Πρόσβασης',
      SESSION_NAME: 'Όνομα Συνεδρίας',
      INFO: 'Πληροφορίες',
      HEALTH_PROFESSIONAL_INFO: 'Πληροφορίες Επαγγελματία Υγείας',
      PATIENT_INFO: 'Πληροφορίες Επωφελούμενου',
      AGREE_THE: 'Δέχομαι τους',
      TERMS_AND_CONDITIONS: 'όρους και τις προϋποθέσεις',
      SESSION_TEMPLATE_LIST: 'Λίστα Πρότυπων Συνεδριών',
      SAVE_AS_TEMPLATE: 'Αποθήκευση ως Πρότυπο',
      BIRTH_YEAR: 'Έτος Γέννησης',
      SEX: 'Φύλο',
      ACCOUNT_TYPE: 'Τύπος Λογαριασμού',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      BENEFICIARIES: 'Beneficiaries',
      SUBSCRIPTION_DURATION: 'Subscription Duration',
      START_DATE: 'Start Date',
      EXTENSION_DURATION: 'Extension Duration',
      STARTING_LICENSE: 'Starting License',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Support Services',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Beneficiary',
      NOTES: 'Some info for us',
      LATEST_OCCUPATION: 'Τελευταίο Επάγγελμα',
      EDUCATION_YEARS: 'Έτη Εκπαίδευσης',
      QUESTIONNAIRE_NAME: 'Όνομα Ερωτηματολογίου',
      WRITE_YOUR_ANSWER: 'Γράψτε την απάντησή σας',
      REQUIRED: 'Υποχρεωτικό',
      SECTION_NAME: 'Όνομα Ενότητας',
      QUESTION: 'Ερώτηση',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Γραπτή απάντηση...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'Η απάντηση πρέπει να περιέχει μόνο νούμερα..',
      HEALTH_PROFESSIONAL_NOTES: 'Σημειώσεις επαγγελματία υγείας',
      NOTE_TEXT: 'Κείμενο σημείωσης',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Λίστα πρότυπων ερωτηματολογίου',
      PATIENT: 'Επωφελούμενος',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'Κωδικός μιας χρήσης',
      CREATE_BENEFICIARY_CONSENT:
        'Έχω τη συναίνεση του επωφελούμενου να προχωρήσω στην καταχώρηση των προσωπικών του δεδομένων και την εγγραφή του στην πλατφόρμα Eligence.',
      I_HAVE_THE_BENEFICIARY_CONSENT:
        'Έχω τη συναίνεση του επωφελούμενου να προχωρήσω στην αλλαγή του κωδικού του',
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Μένω',
      SELECT_TIME_PERIOD: 'Χρονική Περίοδος',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Χρονική Περίοδος',
      CURRENT_PASSWORD: 'Τρέχων Κωδικός Πρόσβασης',
      ACTIVITY_DISPLAY_OPTION: 'Επιλογή Χρήσης Δραστηριοτήτων',
      GROUP_NAME: 'Όνομα Ομάδας',
      MEETING_NAME: 'Όνομα Συνάντησης',
    },
    PLACEHOLDERS: {
      ALL: 'Όλα',
      TOTAL_ELEMENTS: 'Συνολικά Στοιχεία',
      SELECT_RESELLERS: 'Επιλέξτε Μεταπωλητή',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Αναζήτηση',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'Ονομα',
      NOTES: 'Σημειωσεις',
      LAST_NAME: 'Επωνυμο',
      PATIENTS: 'Επωφελουμενοι',
      SESSIONS: 'Συνεδρίες',
      USER: 'Χρηστης',
      EMAIL: 'Email',
      JOINED_DATE: 'Ημερομηνια Ενταξης',
      COMPANY: 'Εταιρεια',
      NAME: 'Ονομα',
      STATUS: 'Κατάσταση',
      EXECUTIONS: 'Εκτελέσεις',
      COMPLETE_SESSIONS: 'Ολοκληρωμενες Συνεδρειες',
      LAST_LOGIN: 'Τελευταία Είσοδος',
      ACCOUNT_TYPE: 'Τυπος Λογαριασμου',
      ID: 'ID',
      CATEGORY: 'Κατηγορία',
      PRODUCT: 'Προϊόν',
      ACTIONS: 'Ενέργειες',
      DESCRIPTION: 'Περιγραφή',
      CREATED: 'Δημιουργήθηκε',
      COMPLETED: 'Ολοκληρώθηκε',
      COUNTRY: 'Χώρα',
      LANGUAGE: 'Γλώσσα',
      ROLE: 'Ρόλος',
      ADDRESS: 'Διεύθυνση',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      CITY: 'Πόλη',
      ESCORT: 'Συνοδεία',
      ADMIN: 'Διαχειριστής',
      DATE: 'Ημερομηνία',
      TIME: 'Χρόνος',
      DURATION: 'Διάρκεια',
      ADDED: 'Προστέθηκε',
      ORGANIZATION: 'Οργάνωση',
      EXERCISE: 'Παιχνίδι',
      VERSION: 'Έκδοση',
      LEVELS: 'Επίπεδα',
      COGNITIVE: 'Νοητική Ικανότητα',
      CATEGORIES: 'Κατηγορίες',
      ENGINE: 'Μηχανή',
      HEALTH_PROFESSIONAL: 'Επαγγελματίας Υγείας',
      ASSIGNED_PATIENTS: 'Ανατιθέμενοι Επωφελούμενοι',
      PATIENT: 'Επωφελούμενος',
      OPEN_SESSIONS: 'Ανοιχτές Συνεδρίες',
      SESSION: 'Συνεδρία',
      ORDER: 'α/α',
      GAMES: 'Παιχνίδια',
      LAST_EDIT: 'Τελευταία Επεξεργασία',
      CREATOR: 'Δημιουργός',
      DIFFICULTY: 'Δυσκολία',
      ADDED_EXERCISES: 'Προστιθέμενα Παιχνίδια',
      ASSIGNED_BY: 'Ανατέθηκε Από',
      GAME: 'Παιχνίδι',
      SCORE: 'Επίδοση',
      PROGRESS: 'Πρόοδος',
      BENEFICIARIES: 'Επωφελούμενοι',
      LATEST_EXECUTION: 'Τελευταία Εκτέλεση',
      TYPE: 'Τύπος',
      STARTED: 'Έναρξη',
      ENDS: 'Λήξη',
      HEALTH_PROFESSIONALS: 'Επαγγελματιες Υγειας',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Ανατιθέμενοι Επαγγελματιες Υγειας',
      QUESTIONNAIRE: 'Ερωτηματολόγιο',
      DATE_ASSIGNED: 'Ημερομηνία Ανάθεσης',
      DATE_COMPLETED: 'Ημερομηνία Ολοκλήρωσης',
      SECTIONS: 'Ενότητες',
      START_DATE: 'Ημερομηνία Έναρξης',
      EXTENSION_DAYS: 'Ημέρες Παράτασης',
      END_DATE: 'Ημερομηνία Λήξης',
      EXTENSION_DATE: 'Ημερομηνία Παράτασης',
      TOTAL_COST_OF_SUBSCRIPTION: 'Συνολικό Κόστος Συνδρομής',
      DURATION_OF_SUBSCRIPTION: 'Διάρκεια',
      TERMINATION_DATE: 'Ημερομηνία Οριστικής Λήξης',
      INVITATION_SENT: 'Πρόσκληση Απεστάλη',
      SUBSCRIPTION_SENT: 'Συνδρομή Απεστάλη',
      ACTIVITY_DISPLAY_OPTION: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      INVITED_BY: 'Προσκλήθηκε Από',
      GROUP: 'Ομάδα',
      MEMBERS: 'Μέλη',
      GUESTS: 'Επισκέπτες',
      MEETINGS: 'Συναντήσεις',
      MEETING: 'Συνάντηση',
      VARIATIONS: 'Παραλλαγές',
      ACTIVATED: 'Ενεργοποιημένα',
      ASSIGNMENT: 'Ανάθεση',
      INDIVIDUAL_EXECUTIONS: 'Εκτελέσεις (Ατομικό)',
      GROUP_EXECUTIONS: 'Εκτελέσεις (Ομαδικό)',
    },
    VALIDATION: {
      INVALID: '{{name}} είναι άκυρο',
      REQUIRED: '{{name}} απαιτείται',
      MIN_LENGTH: '{{name}} πρέπει να έχει τουλάχιστον 3 σύμβολα',
      MAX_LENGTH: '{{name}} πρέπει να έχει το πολύ 256 σύμβολα',
      MAX_LENGTH_NOTES: '{{name}} πρέπει να έχει το πολύ 480 σύμβολα',
      MIN_LENGTH_PASS: '{{name}} πρέπει να έχει τουλάχιστον 8 σύμβολα',
      AGREEMENT_REQUIRED: 'Απαιτείται η αποδοχή των όρων και προϋποθέσεων',
      NOT_FOUND: 'Το ζητούμενο {{name}} δεν βρέθηκε',
      INVALID_LOGIN: 'Η λεπτομέρεια σύνδεσης είναι εσφαλμένη',
      REQUIRED_FIELD: 'Υποχρεωτικό πεδίο',
      MIN_LENGTH_FIELD: 'Ελάχιστο μήκος πεδίου:',
      MAX_LENGTH_FIELD: 'Μέγιστο μήκος πεδίου:',
      INVALID_FIELD: 'Το πεδίο δεν είναι έγκυρο',
      MUST_MATCH:
        "Τα πεδία 'Κωδικός Πρόσβασης' και 'Επιβεβαίωση Κωδικού Πρόσβασης' δεν ταιριάζουν",
      MUST_MATCH_PIN: "Τα πεδία 'Pin' και 'Επιβεβαίωση Pin' δεν ταιριάζουν",
      NO_PRIMARY: 'Δεν έχετε ορίσει ένα πρωτεύον {{name}}',
      NO_STATUS: 'Δεν έχετε ορίσει κατάσταση {{name}}',
      MANY_PRIMARY: 'Έχετε ορίσει περισσότερα από ένα πρωτεύοντα {{name}}',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Πινακας Επισκοπησης',
        SYSTEM: 'Συστημα',
      },
      HOME: 'Αρχική',
      USER_PROFILE: 'Το προφίλ μου',
      ACCOUNT_SETTINGS: 'Ρυθμίσεις Λογαριασμού',
      LANGUAGE: 'Γλώσσα',
      LOGOUT: 'Αποσύνδεση',
      NOTIFICATIONS: 'Ειδοποιήσεις',
      SUBSCRIPTIONS: 'Συνδρομές',
      ORGANIZATION: 'Οργάνωση',
      GAMES: 'Παιχνίδια',
      GAMES_MANAGEMENT: 'Διαχείριση Παιχνιδιών',
      SESSIONS: 'Συνεδρίες',
      PATIENTS: 'Επωφελούμενοι',
      GUESTS: 'Επισκέπτες ',
      MEMBERS: 'Μέλη',
      ORGANIZATIONS: 'Οργανισμοί',
      MY_ORGANIZATION: 'Διαχείριση Οργανισμού',
      ADMINS: 'Διαχειριστές',
      HEALTH_PROFESSIONALS: 'Επαγγελματίες Υγείας',
      SIGN_OUT: 'Έξοδος',
      QUESTIONNAIRES: 'Ερωτηματολόγια',
      ELIGENCE_SESSION_TEMPLATES: 'Συνεδρίες',
      TEMPLATES: 'Πρότυπα',
      BY_ELIGENCE: 'Από Eligence',
      RESELLERS: 'Μεταπωλητές',
      HELP: 'Βοήθεια',
      GROUPS: 'Ομάδες',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Πολιτική Απορρήτου',
      TERMS_AND_CONDITIONS: 'Όροι και Προϋποθέσεις',
      COOKIE_POLICY: 'Πολιτική Cookies',
      CONTACT: 'Επικοινωνία',
      PURCHASE: 'Αγορά',
    },
    GAME_DIFFICULTY: {
      EASY: 'Εύκολο',
      INTERMEDIATE: 'Μεσαίο',
      HARD: 'Δύσκολο',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Ατομικά',
      GROUP_MEETING: 'Ομαδική Συνάντηση',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Σήμερα',
      THIS_WEEK: 'Αυτή την εβδομάδα',
      THIS_MONTH: 'Αυτό τον μήνα',
      LAST_7_DAYS: 'Τελευταίες 7 Μέρες',
      LAST_30_DAYS: 'Τελευταίες 30 Μέρες',
      CUSTOM: 'Επιλογή',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Μνήμη',
      LANGUAGE: 'Λόγος',
      ATTENTION: 'Προσοχή',
      CONSTRUCTIVE_ABILITY: 'Κατασκευαστικές Ικανότητες',
      EXECUTIVE_FUNCTIONS: 'Επιτελικές Ικανότητες',
      LOGICAL_REASONING: 'Λογική',
      ORIENTATION: 'Αντίληψη Χώρου',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Επισκέπτες',
      NON_GUEST: 'Μέλη',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Τύπος Λογαριασμού',
      ACCOUNT_TYPE_DESCRIPTION: 'Επιλέξτε τον τύπο λογαριασμού σας',
      ORGANIZATION_INFO: 'Πληροφορίες Οργανισμού',
      ORGANIZATION_INFO_DESCRIPTION: 'Εισάγετε τα στοιχεία του Οργανισμού σας',
      INVOICING_DETAILS: 'Στοιχεία Τιμολόγησης',
      INVOICING_DETAILS_DESCRIPTION: 'Συμπληρώστε τα στοιχεία τιμολόγησής σας',
      SETUP_ACCOUNT: 'Συμπληρώστε το Λογαριασμό σας',
      SETUP_ACCOUNT_DESCRIPTION: 'Συμπληρώστε τα στοιχεία του Λογαριασμού σας',
      COMPLETED: 'Ολοκληρώθηκε',
      CHOOSE_ACCOUNT_TYPE: 'Επιλέξτε Τύπο Λογαριασμού',
      SMALL_ORGANIZATION: 'Μικρός Οργανισμός',
      SMALL_ORG_HEALTH_PROF_PATIENTS:
        '1 επαγγελματίας υγείας / 1-10 Επωφελούμενοι',
      MEDIUM_ORGANIZATION: 'Μεσαίος Οργανισμός',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS:
        '1-10 επαγγελματίες υγείας / 1-50 Επωφελούμενοι',
      BIG_ORGANIZATION: 'Μεγάλος Οργανισμός',
      BIG_ORG_HEALTH_PROF_PATIENTS:
        '1-50 Επαγγελματίες Υγείας / 1-200 Επωφελούμενοι',
      REGISTRATION:
        'Έχει αποσταλεί ηλεκτρονικό μήνυμα στον χρήστη προκειμένου να ενεργοποιήσει τον λογαριασμό του.',
      DONE: 'Ο λογαριασμός σας έχει ενεργοποιηθεί.',
      DONE_DESCRIPTION: 'Είστε έτοιμοι να συνδεθείτε!',
      MERGE_DONE:
        'Είστε ήδη εγγεγραμμένος σε άλλον οργανισμό. Κάθε φορά που συνδέεστε, μπορείτε να επιλέγετε με ποιον οργανισμό θέλετε να περιηγηθείτε',
      SESSION_INFO: 'Πληροφορίες Συνεδρίας',
      SESSION_INFO_STEPPER: 'Ονομάστε την συνεδρία σας',
      EXERCISES: 'Παιχνίδια',
      EXERCISES_STEPPER: 'Προσθήκη Παιχνιδιών',
      COMPLETION: 'Ολοκλήρωση',
      COMPLETION_STEPPER: 'Ανακεφαλαιώστε!',
      SESSION_INFO_DESCRIPTION:
        'Ονομάστε τη συνεδρία σας και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      SESSION_EXERCISES: 'Παιχνίδια',
      SESSION_EXERCISES_DESCRIPTION:
        'Προσθέστε παιχνίδια στη συνεδρία σας και τροποποιήστε την',
      ADD_EXERCISES: 'Προσθέστε ασκήσεις',
      ADDED_EXERCISES: 'Προστιθέμενα Παιχνίδια',
      CREATE_SESSION_COMPLETION: 'Ένα τελευταίο βήμα!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Ανακεφαλαιώστε!',
      OVERVIEW: 'Επισκόπηση',
      OVERVIEW_BENEFICIARIES: 'Επισκόπηση Εποφελούμενων',
      OVERVIEW_SESSIONS: 'Επισκόπηση Συνεδριών',
      HEALTH_PROFESSIONAL_INFO: 'Πληροφορίες Επαγγελματία Υγείας',
      PATIENT_INFO: 'Πληροφορίες Επωφελούμενου',
      SESSION_NOTES: 'Σημειώσεις',
      SESSION_NOTES_DESCRIPTION: 'Προσθέστε μερικές πληροφορίες!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Choose your Account type',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Setup Subscription Details',
      NOTES: 'Σημειώσεις',
      NOTES_DESCRIPTION: 'Πρόσθεσε σημειώσεις',
      OVERVIEW_DESCRIPTION: 'Μια τελευταία ματιά',
      GROUP_INFO: 'Πληροφορίες Ομάδας',
      BENEFICIARIES: 'Επωφελούμενοι',
      GROUP_INFO_DESCRIPTION:
        'Ονομάστε την ομάδα σας και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      GROUP_BENEFICIARIES_DESCRIPTION:
        'Προσθέστε Επωφελούμενους στην ομάδα σας',
      ADD_BENEFICIARIES: 'Προσθήκη Επωφελούμενων',
      ADDED_BENEFICIARIES: 'Προστιθέμενοι Επωφελούμενοι',
      CREATE_GROUP_COMPLETION: 'Ένα τελευταίο βήμα!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Ανακεφαλαιώστε!',
      MEETING_INFO: 'Πληροφορίες Συνάντησης',
      MEMBERS: 'Μέλη',
      SESSIONS: 'Συνεδρίες',
      MEETING_INFO_DESCRIPTION:
        'Ονομάστε τη συνάντησή σας και κρατήστε κάποιες σημειώσεις αν θέλετε!',
      MEETING_SESSIONS_DESCRIPTION: 'Προσθέστε συνεδρίες στην συνάντηση.',
      ADD_SESSIONS: 'Προσθήκη Συνεδριών',
      ADDED_SESSIONS: 'Προστιθέμενες Συνεδρίες',
      GAMES: 'Παιχνίδια',
      ASSIGN_GAMES: 'Ανάθεση Παιχνιδιών',
    },
    INFO: {
      INFO: 'Αν χρειάζεστε περισσότερες πληροφορίες, παρακαλούμε ελέγξτε',
      HELP: 'Σελίδα Bοήθειας',
    },
    ACTIONS: {
      ACTIONS: 'Ενέργειες',
      VIEW: 'Προβολή',
      VIEW_PROFILE: 'Προβολή Προφίλ',
      ACTIVATE: 'Ενεργοποίηση',
      DEACTIVATE: 'Απενεργοποίηση',
      DELETE: 'Διαγραφή',
      ASSIGN_PATIENTS: 'Ανάθεση Επωφελούμενων',
      ASSIGN_HEALTH_PROFESSIONALS: 'Ανάθεση Επαγγελματιών Υγείας',
      RESEND_INVITATION: 'Επαναποστολή Πρόσκλησης',
      PREVIEW: 'Προεπισκόπηση',
      UPLOAD_FILE: 'Ανέβασμα Παιχνιδιού',
      REMOVE_PATIENT: 'Αφαίρεση Επωφελούμενου',
      SET_TO_ACTIVE: 'Ορισμός σε ενεργό',
      EDIT: 'Επεξεργασία',
      REMOVE: 'Κατάργηση',
      FROM_TEMPALTE: 'Από Πρότυπο',
      CREATE_NEW: 'Δημιουργία Νέας',
      CLONE: 'Κλωνοποίηση',
      CLOSE: 'Κλείσιμο',
      CANNOT:
        'Δεν μπορείτε να εκτελέσετε ενέργειες σε αυτή τη συνεδρία, καθώς έχει ανατεθεί από άλλον επαγγελματία υγείας',
      REMOVE_HEALTH_PROFESSIONAL: 'Αφαίρεση Επαγγελματία Υγείας',
      AMENDMENT: 'Τροποποίηση',
      TERMINATE: 'Τερματισμός',
      NEW_SUBSCRIPTION: 'Νέα Συνδρομή',
      RESEND_EMAIL: 'Επαναποστολή email',
      RENEW: 'Ανανέωση',
      ASSIGN: 'Ανάθεση',
      UNASSIGN: 'Κατάργηση Ανάθεσης',
      CANCEL: 'Κλείσιμο',
      INVITE: 'Πρόσκληση',
      CREATE: 'Δημιουργία',
      RESET_PASSWORD: 'Δημιουργία Νέου Κωδικού Πρόσβασης μιας χρήσης',
      ACTIVITY_DISPLAY_OPTIONS: 'Ρυθμίσεις Χρήσης Δραστηριοτήτων',
      UPGRADE: 'Αναβάθμιση',
      VIEW_MEMBERS: 'Προβολή Μελών',
      START_MEETING: 'Έναρξη Συνάντησης',
    },
    AUTH: {
      SIGN_IN: 'Σύνδεση',
      NEW_HERE: 'Νέος Εδώ;',
      SIGNUP: 'Εγγραφείτε',
      FORGOT_BUTTON: 'Ξεχάσατε τον κωδικό πρόσβασης;',
      ABOUT: 'Πληροφορίες',
      CONTACT: 'Επικοινωνία',
      CONTACT_US: 'Επικοινωνήστε μαζί μας',
      FORGOT_PASSWORD: 'Ξέχασα τον κωδικό πρόσβασης',
      RESET_PASSWORD: 'Επαναφορά κωδικού πρόσβασης',
      SET_PASSWORD: 'Ορισμός κωδικού πρόσβασης',
      SETUP_YOUR_NEW_PASSWORD: 'Ρύθμιση νέου κωδικού πρόσβασης',
      AN_EMAIL_IS_REQUIRED: 'Απαιτείται η ύπαρξη ηλεκτρονικής διεύθυνσης.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'Αν ο λογαριασμός σας δημιουργήθηκε με Όνομα Χρήστη, παρακαλούμε επικοινωνήστε με τον επαγγελματία υγείας σας ή τον διαχειριστή οργανισμού σας.',
    },
    REGISTRATION: {
      SETUP_ACCOUNT: 'Συμπληρώστε τα στοιχεία του λογαριασμού σας',
    },
    PROFILE: {
      OVERVIEW: 'Επισκόπηση',
      SETTINGS: 'Ρυθμίσεις',
      NOTES: 'Σημειώσεις',
      EDIT_PROFILE: 'Επεξεργασία Προφίλ',
      DETAILS: 'Λεπτομέρειες',
      INFORMATION: 'Πληροφορίες',
      NAME: 'Όνομα',
      FULL_NAME: 'Πλήρες Όνομα',
      ROLE: 'Ρόλος',
      CONTACT_PHONE: 'Τηλέφωνο Επικοινωνίας',
      EMAIL: 'Email',
      COUNTRY: 'Χώρα',
      POSTAL_CODE: 'Ταχυδρομικός Κώδικας',
      ADDRESS: 'Διεύθυνση',
      TAX_ID: 'ΑΦΜ',
      STATUS: 'Κατάσταση',
      EDIT: 'Επεξεργασία',
      PASSWORD_RESET: 'Επαναφορά Κωδικού Πρόσβασης',
      RESEND_PASSWORD_INVITATION: 'Πρόσκληση Επαναποστολής Κωδικού Πρόσβασης',
      ASSIGNED_PATIENTS: 'Εκχωρημένοι Επωφελούμενοι',
      ASSIGNED_MEMBERS: 'Εκχωρημένα Μέλη',
      ASSIGNED_GUESTS: 'Εκχωρημένοι Επισκέπτες',
      ACCOUNT_ID: 'Αναγνωριστικό Λογαριασμού',
      BILLING_EMAIL: 'Email Χρέωσης',
      LAST_EDIT: 'Τελευταία Επεξεργασία',
      CREATED_BY: 'Δημιουργήθηκε Από',
      BILLING_ADDRESS: 'Διεύθυνση Χρέωσης',
      ADMINS: 'Διαχειριστές',
      PAYMENT_RECORDS: 'Εγγραφές Πληρωμών',
      PAYMENT_METHODS: 'Μέθοδοι Πληρωμής',
      PERFORMANCE: 'Απόδοση',
      FIRST_NAME: 'Όνομα',
      LAST_NAME: 'Επώνυμο',
      PHONE_NUMBER: 'Αριθμός Τηλεφώνου',
      PREFERRED_LANGUAGE: 'Προτιμώμενη Γλώσσα',
      VAT: 'ΑΦΜ',
      ACTIVITY: 'Δραστηριότητα',
      WEBSITE: 'Ιστοσελίδα',
      CREATED_SESSIONS: 'Δημιουργημένες Συνεδρίες',
      EMAIL_UPDATE_TOOLTIP:
        'Πρέπει να γνωρίζετε ότι το όνομα χρήστη σας θα είναι το νέο σας email',
      CHANGE_PASSWORD: 'Αλλαγή Κωδικού Πρόσβασης',
      SESSIONS: 'Συνεδρίες',
      ADDED_EXERCISES: 'Παιχνίδια',
      SESSION_EXECUTIONS_TOOLTIP:
        'Αυτή η συνεδρία έχει εκτελεστεί {{number}} φορές',
      BIRTH_YEAR: 'Έτος Γέννησης',
      SEX: 'Φύλο',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Εκχωρημένοι Επαγγελματίες Υγείας',
      SUBSCRIPTIONS: 'Συνδρομές',
      CURRENT_SUBSCRIPTION: 'Τρέχουσα Συνδρομή',
      SUBSCRIPTIONS_HISTORY: 'Ιστορικό Συνδρομών',
      SUBSCRIPTION: 'Συνδρομή',
      UPCOMING_SUBSCRIPTION: 'Επόμενη Συνδρομή',
      LATEST_OCCUPATION: 'Τελευταίο Επάγγελμα',
      EDUCATION_YEARS: 'Έτη Εκπαίδευσης',
      EMAIL_USERNAME: 'Email ( Όνομα χρήστη )',
      INVOICE_INFO: 'Στοιχεία Τιμολόγησης',
      EXECUTIONS: 'Εκτελέσεις',
      MEMBER_SINCE: 'Μέλος από',
      QUESTIONNAIRES: 'Ερωτηματολόγια',
      ASSIGNED: 'Ανατέθηκε',
      COMPLETED: 'Ολοκληρώθηκε',
      ANSWERS: 'Απαντήσεις',
      PASSWORD: 'Κωδικός Πρόσβασης',
      USERNAME: 'Username',
      STAYING_STATUS: 'Μένω',
      ACTIVITY_DISPLAY_OPTION: 'Επιλογή Χρήσης Δραστηριοτήτων',
      GAMES: 'Παιχνίδια',
      MEETINGS: 'Συναντήσεις',
      MEMBERS: 'Μέλη',
      PUBLIC: 'Δημόσιο',
      PRIVATE: 'Ιδιωτικό',
    },
    GENERAL: {
      USER: 'Χρήστης',
      PATIENT: 'Επωφελούμενος',
      MEMBER: 'Μέλος',
      GUEST: 'Επισκέπτης',
      HEALTH_PROFESSIONAL: 'Επαγγελματίας Υγείας',
      GAME: 'Παιχνίδι',
      PROFILE: 'Προφίλ',
      ORGANIZATION: 'Οργανισμός',
      ORGANIZATION_ADMIN: 'Διαχειριστής Οργανισμού',
      NO_ENTRIES: 'Δεν βρέθηκαν καταχωρήσεις',
      SESSION: 'Συνεδρία',
      GAMES: 'Παιχνίδια',
      SESSION_TEMPLATE: 'Πρότυπο Συνεδρίας',
      SUBSCRIPTION: 'Subscription',
      SUBSCRIPTION_EMAIL: 'Subscription email',
      ASSIGNED_QUESTIONNAIRE: 'Ερωτηματολόγιο',
      QUESTIONNAIRE_TEMPLATE: 'Πρότυπο Ερωτηματολογίου',
      NOTE: 'Σημείωση',
      COPIED: 'Αντιγράφηκε!',
      CONGRATULATIONS: 'Συγχαρητήρια',
      DESCRIPTION: 'Περιγραφή',
      SAME_COGNITIVE_GAMES: 'Παιχνίδια που εξασκούν την ίδια νοητική ικανότητα',
      SELECT_DIFFICULTY: 'Επιλέξτε επίπεδο δυσκολίας',
      GROUP: 'Ομάδα',
      MEETING: 'Συνάντηση',
    },
    GRAPHS: {
      SCORE: 'Επίδοση',
      TIME: 'Χρόνος',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Εκτελέσεις ανά Νοητική Ικανότητα & Δυσκολία',
      EXECUTIONS_PER_GAME_TITLE: 'Εκτελέσεις ανά Παιχνίδι',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Μέσος όρος Επίδοσης ανά Παιχνίδι',
      EXECUTIONS_PER_DAY_TITLE: 'Εκτελέσεις ανά Ημέρα',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE:
        'Εξέλιξη Μέσου Όρου Επίδοσης',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Χρόνος δραστηριότητας ανά Ημέρα (λεπτά)',
      GAME: 'Παιχνίδι',
      TOTAL: 'Σύνολο',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Ημερολόγια δραστηριοτήτων',
      EXECUTED_GAME: 'Εκτελεσμένο παιχνίδι',
      ADDED: 'Προστέθηκε: ',
      EXECUTED_SESSION: ' Εκτελεσμένη Συνεδρία',
    },
    SESSION: {
      MY_SESSIONS: 'Οι Συνεδρίες μου',
      SESSION_COMPLETE: 'Ολοκληρώσατε τη συνεδρία',
      ABANDONED: 'Εγκαταλείφθηκε',
      SKIPPED: 'Παραλείφθηκε',
      PLAYED: 'Παίχτηκε',
      PENDING: 'Εκκρεμεί',
      ASSIGNED_SESSIONS: 'Ανατεθείσες Συνεδρίες',
      DEFAULT_PUBLIC_INFO:
        'Γειά σου! Αυτή είναι μια συνεδρία που δημιουργήθηκε μόνο για εσένα! Παρακαλώ ολοκλήρωσέ την ή επικοινώνησε με τον επαγγελματία υγείας σου εάν έχεις περαιτέρω ερωτήσεις.',
      DOCTOR_NOTES: 'Σημειώσεις Επαγγελματία Υγείας',
      SAMPLE_DOCTOR_NOTES:
        'Αγαπητέ {{name}}, αυτή είναι μια συνεδρία που δημιουργήθηκε μόνο για εσένα! Παρακαλώ ολοκλήρωσέ την ή επικοινώνησε με τον επαγγελματία υγείας σου εάν έχεις περαιτέρω ερωτήσεις.',
    },
    STATUS: {
      ACTIVE: 'Ενεργοποιημένος',
      INACTIVE: 'Απενεργοποιημένος',
      INVITED: 'Προσκεκλημένος',
    },
    SESSION_STATUS: {
      ACTIVE: 'Ενεργή',
      ASSIGNED: 'Ανατεθείσα',
      CLOSED: 'Ανενεργή',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Μεταπωλητής',
      DEMO: 'Demo',
      PAID: 'Επί Πληρωμή',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'Διαχειριστής Συστήματος',
      ROLE_ORGANIZATION_OWNER: 'Ιδιοκτήτης Οργανισμού',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Διαχειριστής Οργανισμού',
      ROLE_HEALTH_PROFESSIONAL: 'Επαγγελματίας Υγείας',
      ROLE_PATIENT: 'Επωφελούμενος',
      ROLE_INTERNAL_CONTACT: 'Εσωτερική Επαφή',
      ROLE_EXTERNAL_CONTACT: 'Εξωτερική Επαφή ',
      ROLE_HEALTH_PROFESSIONAL_OWNER:
        'Ιδιοκτήτης Οργανισμού/Επαγγελματίας Υγείας',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Διαχειριστής Οργανισμού/Επαγγελματίας Υγείας',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Άνδρας',
      FEMALE: 'Γυναίκα',
      OTHER: 'Άλλο',
      NO_ANSWER: 'Δεν επιθυμώ να δηλώσω',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Καλώς όρισες Admin',
      OVERVIEW_DESCRIPTION: 'Ρίξε μια ματιά στους αριθμούς σου',
      EXECUTIONS: 'Εκτελέσεις',
      HOURS: 'Ώρες',
      BENEFICIARIES: 'Επωφελούμενοι',
      HEALTH_PROFESSIONALS: 'Επαγγελματίες Υγείας',
      MOST_PLAYED: 'Περισσότερο Παιγμένα',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Τελευταίες Ενημερώσεις για τα Παιχνίδια',
      LEAST_PLAYED: 'Λιγότερο Παιγμένα',
      ACTIVE_LAST_30_DAYS: 'Ενεργοί τις τελευταίες 30 μέρες',
      GAMES_ACTIVITY: 'Δραστηριότητα Παιχνιδιών',
      GAMES_ACTIVITY_DESCRIPTION:
        'Συνολικές Εκτελέσεις ανά Παιχνίδι και Κατηγορία',
      AVERAGE: 'Σύνολο',
      LATEST_UPDATE: 'Τελευταία Ενημέρωση: ',
      HOUR_SHORT: 'ω',
      MINUTE_SHORT: 'λ',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Αριθμός Επαγγελματιών Υγείας',
      NUMBER_OF_BENEFICIARIES: 'Αριθμός Επωφελούμενων',
      DURATION: 'Διάρκεια',
      START_DATE: 'Ημερομηνία Έναρξης',
      EXTENSION_DAYS: 'Ημέρες Παράτασης',
      END_DATE: 'Ημερομηνία Λήξης',
      EXTENSION_DATE: 'Ημερομηνία Παράτασης',
      STARTING_LICENSE: 'Άδεια Έναρξης',
      ANNUAL_FEE: 'Ετήσια Άδεια',
      SUPPORT_SERVICES: 'Υπηρεσίες Υποστήριξης',
      MONTHLY_COST_PER_BENEFICIARY: 'Μηνιαίο Κόστος ανά Επωφελούμενο',
      TOTAL_COST_OF_BENEFICIARIES: 'Συνολικό Κόστος Επωφελούμενων',
      TOTAL_COST_OF_SUBSCRIPTION: 'Συνολικό Κόστος Συνδρομής',
      ORGANIZATION_TYPE: 'Τύπος Χρήστη',
      SUBSCRIPTION_TYPE: 'Τύπος Συνδρομής',
      MONTHS: 'Μήνες',
      DAYS: 'Ημέρες',
      REMAINING_DAYS: 'Ημέρες έως τη λήξη',
      HEALTH_PROFESSIONALS: 'Επαγγελματίες Υγείας',
      BENEFICIARIES: 'Επωφελούμενοι',
      NOTES: 'Σημειώσεις',
      DURATION_OF_SUBSCRIPTION: 'Διάρκεια',
      COSTS_VAT_DISCLAIMER:
        'Στα παραπάνω κόστη δε συμπεριλαμβάνεται ο ΦΠΑ, όπου ισχύει.',
      ACCEPT_MODAL_FOOTER:
        'Αν δεν επιθυμείτε να επιβεβαιώσετε τη συνδρομή, παρακαλούμε αγνοήστε το ή επικοινωνήστε μαζί μας στην ηλεκτρονική διεύθυνση ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        'Η συνδρομή του οργανισμού σας στην πλατφόρμα Eligence δεν είναι ενεργή και δεν έχετε πρόσβαση. Για περισσότερες πληροφορίες παρακαλούμε επικοινωνήστε με τον διαχειριστή του οργανισμού σας.',
      DAYS_LEFT: 'μέρες που απομένουν',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'Νέα Συνδρομή',
      AMENDMENT: 'Ανανέωση',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Ενεργή',
      EXPIRED: 'Expired',
      PENDING_CONSENT: 'Αναμονή Έγκρισης',
      PENDING_AUTOMATION: 'Αναμονή Ενεργοποίησης',
      REJECTED: 'Απόρριψη',
      TERMINATED: 'Λήξη',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Ανατεθειμένα Ερωτηματολόγια',
      SECTION: 'Ενότητα',
      QUESTION: 'Ερώτηση',
      NOTE: 'Σημείωση',
      BY: 'από',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Platform Generated',
      USER_GENERATED: 'User Generated',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Ανατεθέν',
      IN_PROGRESS: 'In Progress',
      COMPLETED: 'Ολοκληρώθηκε',
      CANCELLED: 'Ανενεργή',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Free Text',
      INTEGER: 'Numeric',
      CHECKBOX: 'Multiple Choice',
      RADIO: 'Single Choice',
      DROPDOWN: 'Dropdown',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Το Ερωτηματολόγιο είναι ένα προτεινόμενο εργαλείο που σας παρέχει η πλατφόρμα Eligence. Μέσω του Ερωτηματολογίου μπορείτε να συλλέξετε πληροφορίες σχετικά με τον επωφελούμενο ή να λάβετε πληροφορίες για να αξιολογήσετε την κατάστασή του.',
      PROMPT:
        'Όταν το ερωτηματολόγιο ανατεθεί στον επωφελούμενο, όλα τα ελεύθερα παιχνίδια και οι συνεδρίες θα απενεργοποιηθούν έως ότου το ολοκληρώσει.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Δημιουργία Επωφελούμενου',
      TITLE_MEMBER: 'Δημιουργία Μέλους',
      TITLE_GUEST: 'Δημιουργία Επισκέπτη',
      CREDENTIALS: 'Στοιχεία χρήστη',
      PERSONAL_DETAILS: 'Πληροφορίες',
      COMPLETION: 'Ολοκλήρωση',
      CHECK_AVAILABILITY: 'Έλεγχος διαθεσιμότητας',
      USERNAME_AVAILABLE: 'Username διαθέσιμο',
      USERNAME_UNAVAILABLE: 'Μη διαθέσιμο, προσπαθήστε ξανά',
      OTP_SAVE_WARNING: 'Αποθηκεύστε ασφαλώς τον κωδικό για μελλοντική χρήση.',
      DONE: 'Είστε έτοιμοι!',
      DONE_DESCRIPTION:
        'Ένας νέος λογαριασμός επωφελούμενου έχει δημιουργηθεί. Κατά τη διάρκεια της πρώτης σύνδεσης, θα ζητηθεί από τον επωφελούμενο η αλλαγή κωδικού για την προστασία των προσωπικών του δεδομένων.',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'Ομαδικά Παιχνίδια',
      FOR_TWO: 'Παιχνίδια για δύο',
      INTERGENERATION: 'Παιχνίδια Γενεών',
      CHALLENGING: 'Απαιτητικά Παιχνίδια',
    },
    GAMES: {
      MY_GAMES: 'Τα παιχνίδια μου',
      ALL_GAMES: 'Όλα',
    },
    STAYING_STATUS: {
      ALONE: 'Μόνος/μόνη μου',
      WITH_HUSBAND_WIFE: 'Με σύζυγο/σύντροφό μου',
      WITH_KIDS_GRANDKIDS: 'Με τα παιδιά/εγγόνια μου',
      WITH_CARER: 'Με φροντιστή',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'Προβολή όλων',
      ONLY_SESSIONS: 'Μόνο συνεδρίες',
      ONLY_GAMES: 'Μόνο παιχνίδια',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Ανατεθείσα',
      UNASSIGNED: 'Μη Ανατεθείσα',
    },
    GAME_ACCESS: {
      PUBLIC: 'Δημόσιο',
      PRIVATE: 'Ιδιωτικό',
    },
    PRIVACY_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Πολιτική Απορρήτου</h2><br><h2>Εισαγωγή</h2><p>Το λογισμικό υπηρεσίας "Eligence" ("Υπηρεσία") λειτουργεί από την "Maggioli SPA - Ελληνικό Παράρτημα" ("Πάροχος") σε πόρους που παρέχονται από την "Maggioli SPA - Ελληνικό Παράρτημα". </p><p>Η "Maggioli SPA - Ελληνικό Παράρτημα" ("Πάροχος") είναι μια ιδιωτική εταιρεία λογισμικού με την επωνυμία Maggioli SPA - Ελληνικό Παράρτημα, ιδρύθηκε στη Μαρούσι στις 21 Σεπτεμβρίου 2020 και η έδρα της βρίσκεται στην οδό Ανδρέα Παπανδρέου 19, Μαρούσι, 15124, Αττική, Ελλάδα. </p><p>Η προστασία των προσωπικών σας δεδομένων είναι πολύ σημαντική για εμάς. Η Πολιτική Απορρήτου μας έχει σκοπό να σας βοηθήσει να κατανοήσετε γιατί συλλέγουμε τα προσωπικά σας στοιχεία και πώς τα χρησιμοποιούμε. Παρέχει λεπτομερείς πληροφορίες σχετικά με το πότε και γιατί συλλέγουμε τα προσωπικά σας στοιχεία, πώς τα χρησιμοποιούμε και επεξεργαζόμαστε, πόσο καιρό τα διατηρούμε και τέλος, υπό ποιους όρους μπορούμε να τα μοιραστούμε με άλλους.</p><h2>1. Πεδίο εφαρμογής </h2><p>Αυτή η πολιτική ισχύει για όλους εσάς που έχετε πρόσβαση και χρησιμοποιείτε την υπηρεσία μας.</p><p>Η παρούσα Πολιτική Απορρήτου ισχύει αποκλειστικά για προσωπικά δεδομένα και πληροφορίες που συλλέγονται από την Υπηρεσία μέσω της χρήσης της ή μέσω οποιασδήποτε ηλεκτρονικής επικοινωνίας του Χρήστη με τον Πάροχο, όπως αναφέρεται στην Υπηρεσία (αποκαλούμενα εν συντομία "Προσωπικά Δεδομένα"). </p><p>Μπορούμε επίσης να συλλέγουμε πληροφορίες από εσάς με άλλους τρόπους, συμπεριλαμβανομένων πληροφοριών που συλλέγονται κατά τη διάρκεια της τεχνικής υποστήριξης. Εάν παρέχουμε ξεχωριστή ή συμπληρωματική ειδοποίηση κατά τη συλλογή προσωπικών δεδομένων από εσάς, αυτή η ειδοποίηση θα ισχύει σε περίπτωση σύγκρουσης.</p><h2>2. Συλλογή Πληροφοριών </h2><p>Η Υπηρεσία διαχειρίζεται διάφορα είδη δεδομένων, πάντα σύμφωνα με την ισχύουσα ευρωπαϊκή νομοθεσία περί προστασίας δεδομένων. Οποιαδήποτε Δεδομένα που αφορούν τον Χρήστη συλλέγονται για να επιτρέπουν στον Πάροχο να παρέχει τις υπηρεσίες.</p><h2>Απαιτούμενα Δεδομένα </h2><u>Προσωπικά Δεδομένα </u><br><p>Η παροχή της Υπηρεσίας απαιτεί την επεξεργασία ορισμένων προσωπικών πληροφοριών που μπορούν να αναγνωριστούν. Τα προσωπικά δεδομένα που επεξεργαζόμαστε για εσάς είναι τα εξής: </p><ul><li>όνομα</li><li>διεύθυνση</li><li>διεύθυνση ηλεκτρονικού ταχυδρομείου</li><li>αριθμός τηλεφώνου</li></ul><u>Cookies</u><p>Οποιαδήποτε cookies ή άλλα εργαλεία παρακολούθησης που χρησιμοποιούνται από αυτήν την Υπηρεσία, ή από άλλους παρόχους υπηρεσιών τρίτων που χρησιμοποιούνται μέσω αυτής της Υπηρεσίας, έχουν ως σκοπό την παροχή της απαιτούμενης υπηρεσίας για τον Χρήστη, καθώς και οποιουδήποτε άλλου σκοπού περιγράφεται στο παρόν έγγραφο και στην συγκεκριμένη Πολιτική για τα Cookies, εάν τέτοιο έγγραφο είναι διαθέσιμο.</p><h2>3. Χρήση από παιδιά</h2><p>Εάν είστε ηλικίας 16 ετών ή νεότεροι, παρακαλούμε ζητήστε την άδεια των γονιών/κηδεμόνων σας πριν δώσετε οποιαδήποτε προσωπική πληροφορία σε εμάς. Τα παιδιά μπορούν να χρησιμοποιούν το Eligence με τη συναίνεση των γονιών ή κηδεμόνων τους. </p><p>Όλες οι πληροφορίες που παρέχονται από παιδιά κάτω των 16 ετών θα χειρίζονται με σεβασμό προς τα δικαιώματά τους. </p><p>Αναγνωρίζουμε την ανάγκη παροχής πρόσθετων προστασιών της ιδιωτικότητας όσον αφορά τα προσωπικά στοιχεία των παιδιών που μπορεί να συλλέξουμε. Όταν προτείνουμε να συλλέξουμε πληροφορίες από παιδιά, ακολουθούμε επιπλέον μέτρα για την προστασία της ιδιωτικότητας των παιδιών, συμπεριλαμβανομένων των εξής: </p><ul><li>Σύμφωνα με το ισχύον δίκαιο και τις πρακτικές μας, λαμβάνουμε τη συναίνεση των γονέων για τη συλλογή και χρήση των προσωπικών πληροφοριών των παιδιών τους.</li><li>Ενημέρωση των γονέων σχετικά με τις πρακτικές μας σχετικά με τις πληροφορίες που αφορούν τα παιδιά.</li><li>Περιορισμός της συλλογής των προσωπικών πληροφοριών των παιδιών σε ό,τι είναι απαραίτητο και λογικό.</li><li>Παροχή στους γονείς πρόσβασης ή τη δυνατότητα να ζητήσουν πρόσβαση στις προσωπικές πληροφορίες που έχουμε συλλέξει για τα παιδιά τους και τη δυνατότητα να ζητήσουν αλλαγές ή διαγραφή των προσωπικών πληροφοριών.</li></ul><p>Εάν διαπιστώσουμε ότι έχουμε αθέλητα συλλέξει τις προσωπικές πληροφορίες ενός παιδιού κάτω των 16 ετών, ή της αντίστοιχης ελάχιστης ηλικίας ανάλογα με την νομική δικαιοδοσία, θα λάβουμε μέτρα για να διαγραφούν οι πληροφορίες το συντομότερο δυνατόν.</p><h2>4. Χρήση Προσωπικών Δεδομένων </h2><p>Η Υπηρεσία χρησιμοποιεί τα Προσωπικά Δεδομένα για τους ακόλουθους σκοπούς: </p><ul><li><b>Πλήρωση αιτημάτων:</b> Η Υπηρεσία χρησιμοποιεί τα Προσωπικά Δεδομένα για την επεξεργασία αιτημάτων, την εγγραφή σε υπηρεσίες τρίτων, την επικοινωνία με τον χρήστη, την αποστολή ειδοποιήσεων, την χρέωση και την τιμολόγηση του χρήστη κ.λπ.</li><li><b>Λειτουργία υπηρεσίας:</b> Η υπηρεσία χρησιμοποιεί cookies για την αναγνώριση των χρηστών, την ανάκτηση πληροφοριών σχετικά με την τοποθεσία και τη συσκευή πελάτη, προκειμένου να προσαρμόσει/εξασφαλίσει τις δυνατότητές της, να παρέχει πρόσβαση σε συγκεκριμένες περιοχές της υπηρεσίας, να παρέχει πρόσβαση σε σχετικές πληροφορίες, να φιλτράρει περιεχόμενο κ.λπ.</li><li><b>Στατιστική ανάλυση:</b> Συγκεντρωμένα δεδομένα σχετικά με τη χρήση της υπηρεσίας (τα οποία δεν αναγνωρίζουν έναν συγκεκριμένο χρήστη), όπως ο αριθμός των χρηστών που έχουν επισκεφθεί συγκεκριμένες σελίδες της υπηρεσίας ή πόσο χρόνο αποδίδουν οι χρήστες σε μια συγκεκριμένη σελίδα, χρησιμοποιούνται για τη συγκέντρωση στατιστικών στοιχείων σχετικά με τη χρήση της υπηρεσίας.</li><li><b>Εσωτερικοί επιχειρηματικοί σκοποί:</b> Ο Πάροχος χρησιμοποιεί τις συλλεγμένες πληροφορίες για εσωτερικούς επιχειρηματικούς σκοπούς, όπως για ελέγχους ή για την παρακολούθηση της χρήσης και συμπεριφοράς των λειτουργιών της υπηρεσίας, δικαιολόγηση της χρήσης πόρων και χρηματοδότησης, εξαγωγή επιχειρηματικών ΚΠΔ κ.λπ.</li><li><b>Σχεδιασμός υπηρεσίας και προϊόντων:</b> Ο Πάροχος χρησιμοποιεί συγκεντρωμένα και προσωπικά δεδομένα για να πραγματοποιήσει βελτιώσεις, προσαρμογές και εκσυγχρονίσεις, καθώς και για το σχεδιασμό νέων υπηρεσιών και προϊόντων που ανταποκρίνονται σε γενικές ή εξατομικευμένες ανάγκες των χρηστών.</li><li><b>Παρουσίαση πληροφοριών χρήστη:</b> Τα δεδομένα που αφορούν τον χρήστη παρουσιάζονται από την υπηρεσία για να επιτρέπουν στους χρήστες να αναγνωρίζουν την κυριότητα, την προέλευση και την κατανομή διάφορων πόρων.</li></ul><p>Η υπηρεσία μας εγγυάται ότι τα προσωπικά σας δεδομένα δεν θα χρησιμοποιηθούν για σκοπούς πέρα από αυτούς που ορίζονται στην παρούσα πολιτική, χωρίς προηγούμενη ειδοποίηση και εφόσον απαιτείται η έγκρισή σας. </p><p>Η επεξεργασία των δεδομένων πραγματοποιείται με τη χρήση υπολογιστών και/ή εργαλείων πληροφορικής, ακολουθώντας οργανωτικές διαδικασίες και τρόπους που σχετίζονται αυστηρά με τους προαναφερόμενους σκοπούς. </p><p>Ο πάροχος θεωρεί τα προσωπικά δεδομένα των χρηστών ως ένα ενεργητικό που δεν προορίζεται για πώληση και δεν θα πωληθεί ποτέ σε τρίτους.</p><h2>5. Παραλήπτες προσωπικών δεδομένων </h2><p>Η πρόσβαση σε προσωπικά δεδομένα και πληροφορίες συναλλαγών επιτρέπεται μόνο σε υπαλλήλους, συνεργάτες και τρίτα μέρη που επεξεργάζονται τα προαναφερόμενα δεδομένα κατ\' ευχή του Παρόχου και μόνο όταν και σε όσον απαιτείται για τους προαναφερόμενους σκοπούς. Τα προσωπικά δεδομένα μπορούν να διαβιβαστούν, για τους σκοπούς της παραπάνω επεξεργασίας, μόνο σε συγκεκριμένους παραλήπτες που είναι υπάλληλοι και γενικότερα συνεργάτες καθώς και τρίτα μέρη συνδεδεμένα με τον Πάροχο. Επιπλέον, ο Πάροχος μπορεί, χωρίς προηγούμενη ειδοποίηση, να αποκαλύψει τις πληροφορίες σας στις αρμόδιες δικαστικές και/ή διοικητικές αρχές στο μέτρο που απαιτείται από την ισχύουσα νομοθεσία και κανονιστικά μέτρα, ή με δικαστική απόφαση και/ή διοικητική πράξη.</p><p>Ο Πάροχος καταβάλλει κάθε δυνατή προσπάθεια για τον έλεγχο και την αξιολόγηση κατά την επιλογή των συνεργατών του, στους οποίους διαβιβάζει τα προσωπικά δεδομένα των αναφερόμενων. Υπάρχει ένα γραπτό συμφωνητικό μεταξύ του Παρόχου και κάθε τρίτου μέρους, σύμφωνα με το οποίο η επεξεργασία των προσωπικών δεδομένων πραγματοποιείται υπό τον έλεγχο του Παρόχου και μόνο κατόπιν της εντολής του, και υπόκειται στην ίδια πολιτική προστασίας δεδομένων.</p><h2>6. Χρόνος διατήρησης των δεδομένων </h2><p>Ο χρονικός διάστημα για την αποθήκευση των δεδομένων καθορίζεται με βάση τα ακόλουθα συγκεκριμένα κριτήρια, ανάλογα με την περίπτωση: </p><ul><li>Όταν η επεξεργασία απαιτείται από τις διατάξεις του ισχύοντος νομικού πλαισίου, τα προσωπικά σας δεδομένα θα αποθηκεύονται για όσο χρονικό διάστημα απαιτούν οι σχετικές διατάξεις.</li><li>Όταν η επεξεργασία γίνεται στη βάση σύμβασης, τα προσωπικά σας δεδομένα αποθηκεύονται για όσο χρονικό διάστημα είναι απαραίτητο για την εκτέλεση της σύμβασης και για τη θεμελίωση, άσκηση και/ή υποστήριξη νομικών αξιώσεων σύμφωνα με τη σύμβαση.</li><li>Για άλλους σκοπούς, οι προσωπικές σας πληροφορίες διατηρούνται μέχρι την ανάκληση της συγκατάθεσής σας. Αυτό μπορεί να γίνει οποιαδήποτε στιγμή. Η ανάκληση της συγκατάθεσης δεν επηρεάζει τη νομιμότητα της επεξεργασίας που βασίζεται στη συγκατάθεση κατά την περίοδο πριν από την ανάκλησή της. Μπορείτε να ανακαλέσετε τη συγκατάθεσή σας οποιαδήποτε στιγμή επιλέγοντας τον σύνδεσμο που παρέχεται στα email που σας αποστέλλουμε.</li></ul><p>Πριν μπορέσουμε να σας παρέχουμε οποιαδήποτε πληροφορία ή να διορθώσουμε οποιαδήποτε ανακρίβεια, ενδέχεται να σας ζητήσουμε να επαληθεύσετε την ταυτότητά σας και/ή να παράσχετε άλλες λεπτομέρειες προκειμένου να μας βοηθήσετε να ανταποκριθούμε στο αίτημά σας. </p><p>Ο Πάροχος διατηρεί το δικαίωμα να μην ανταποκρίνεται σε αιτήματα που προέρχονται από εφαρμογές τρίτων ή αυτοματοποιημένες διαδικασίες χωρίς άμεση επικύρωση των αιτημάτων από τους υποκείμενους των δεδομένων χρησιμοποιώντας τους πόρους που παρέχονται από την Υπηρεσία για την άσκηση αυτών των δικαιωμάτων όπως περιγράφονται στην παρούσα Πολιτική.</p><h2>8. Ασφάλεια δεδομένων </h2><p>Ο Πάροχος λαμβάνει μέτρα για τη διασφάλιση της ασφάλειας των προσωπικών σας δεδομένων. Εφαρμόζουμε κατάλληλα φυσικά, τεχνικά και οργανωτικά μέτρα που σχεδιάστηκαν με λογικό τρόπο για την προστασία των προσωπικών δεδομένων από ατυχή ή παράνομη καταστροφή, απώλεια, αλλοίωση, μη εξουσιοδοτημένη αποκάλυψη ή πρόσβαση και από όλες τις άλλες παράνομες μορφές επεξεργασίας. Διατηρούμε ένα πρόγραμμα ασφαλείας που είναι ανάλογο με τους κινδύνους που συνδέονται με την επεξεργασία.</p><h2>9. Τοποθεσία Αποθήκευσης Προσωπικών Δεδομένων </h2><p>Η Υπηρεσία παρέχεται μέσω της επιχείρησης διαχείρισης έργων της, των διακομιστών της οποίας βρίσκονται στην Ελλάδα και παρέχονται από την "Maggioli SPA - Ελληνική Υποκατάστημα".</p><h2>10.  Επιβολή του νόμου - συμμόρφωση </h2><p>Ο Πάροχος μπορεί να χρησιμοποιήσει ή να αποκαλύψει προσωπικά δεδομένα σε οποιονδήποτε τρίτο (α) αν απαιτείται από το νόμο, (β) για να συμμορφωθεί με νομικές διαδικασίες ή να ανταποκριθεί σε αιτήματα από κυβερνητικές ή δημόσιες αρχές, (γ) για την πρόληψη, έρευνα, εντοπισμό ή δίωξη ποινικών αδικημάτων ή επιθέσεων στην τεχνική ακεραιότητα της Υπηρεσίας ή του δικτύου, (δ) για την επιβολή των Όρων και Προϋποθέσεων, ή (ε) για την προστασία των δικαιωμάτων, της ιδιωτικότητας, της ιδιοκτησίας, της επιχείρησης ή της ασφάλειας του Παρόχου, των επιχειρηματικών του συνεργατών, των υπαλλήλων του, των μελών της Υπηρεσίας ή του κοινού. Εκτός εάν απαγορεύεται από το ισχύον δίκαιο, ο Πάροχος θα ενημερώσει τον Χρήστη εάν ένας τρίτος ζητήσει πρόσβαση σε προσωπικά δεδομένα σχετικά με τον Χρήστη.</p><h2>11. Τροποποίηση πολιτικής </h2><p>Αυτή η πολιτική απορρήτου μπορεί να τροποποιηθεί. Θα εξασφαλίσουμε να σας ενημερώνουμε για οποιεσδήποτε αλλαγές, αλλά πάντα σας προσκαλούμε να επισκέπτεστε τον ιστότοπό μας τακτικά, όπου θα δημοσιεύεται η πιο ενημερωμένη Πολιτική Απορρήτου.</p><h2>12. Άσκηση των Δικαιωμάτων σας, Ερωτήσεις, Αντιρρήσεις, Παράπονα </h2><p>Για την άσκηση των δικαιωμάτων σας, ή για οποιεσδήποτε ερωτήσεις, σχόλια, αντιρρήσεις ή παράπονα αναφορικά με αυτήν την Πολιτική Απορρήτου ή τις πρακτικές απορρήτου, ασφάλειας ή προστασίας δεδομένων που εφαρμόζονται, παρακαλούμε επικοινωνήστε με τον Πάροχο μέσω ηλεκτρονικού ταχυδρομείου μέσω του ειδικά διαμορφωμένου Υπεύθυνου Προστασίας Δεδομένων (dpo@eligence.eu). </p><p>Χειριζόμαστε τα αιτήματά σας με τη μεγαλύτερη προσοχή για να εξασφαλίσουμε την προστασία των δικαιωμάτων σας. Για οποιοδήποτε αίτημα που μπορεί να απαιτεί υπόθεση ή αποκάλυψη Προσωπικών Δεδομένων, ο Χρήστης θα πρέπει να επιδείξει νόμιμους λόγους για την υποβολή των αντίστοιχων αιτημάτων, καθώς και να παράσχει επαρκή απόδειξη για την ταυτότητα του Χρήστη.</p><p>Σε ορισμένες περιπτώσεις, ενδέχεται να μην είμαστε σε θέση να επεξεργαστούμε απευθείας το αίτημά σας. Ωστόσο, σε κάθε περίπτωση θα σας ενημερώσουμε για την πρόοδο του αιτήματός σας εντός ενός μήνα από την υποβολή του αρχικού αιτήματός σας. Έχετε πάντα το δικαίωμα να υποβάλετε παράπονο στην "Αρχή Προστασίας Δεδομένων (www.dpa.gr)" εάν ανησυχείτε για τον τρόπο με τον οποίο έχουμε επεξεργαστεί τα προσωπικά σας δεδομένα.</p>',
    },
    TERMS: {
      TEST: '<h1>Eligence</h1><h2>Όροι χρήσης</h2><br><h2>Αποποίηση ευθυνών</h2><p>Καλώς ήρθατε στο “Eligence”. To «Eligence» (εφεξής «Υπηρεσία») είναι μια διαδικτυακή πλατφόρμα με εξειδικευμένο περιεχόμενο (παιχνίδια), που στοχεύει στην ενίσχυση των νοητικών ικανοτήτων και της γνωστικής λειτουργίας. Μαζί με επαγγελματίες υγείας μπορεί να παρέχει εξάσκηση σε άτομα στα αρχικά στάδια της άνοιας, καθώς και για σκοπούς λογοθεραπείας ή εργοθεραπείας.</p><p>Παρακαλώ να διαβάσετε και κατανοήσετε αυτούς τους Όρους (οι «Όροι») πριν χρησιμοποιήσετε αυτήν την Υπηρεσία. Με τη χρήση αυτής της Υπηρεσίας αποδέχεστε και συμφωνείτε να δεσμεύεστε και να συμμορφώνεστε με τους ακόλουθους Όρους. Εάν δεν συμφωνείτε με αυτούς τους Όρους, δεν θα πρέπει να έχετε πρόσβαση ή να χρησιμοποιήσετε αυτήν την Υπηρεσία.</p><p>Χρήστες είναι άτομα που χρησιμοποιούν και διαχειρίζονται την Υπηρεσία.</p><p>Για να κάνετε χρήση της υπηρεσίας πρέπει 1) να είστε ενήλικας με πλήρη δικαιοπρακτική ικανότητα ή 2) ανήλικος (<18 ετών) που έχει λάβει γραπτή συγκατάθεση από τον γονέα ή τον νόμιμο εκπρόσωπό σας ή 3) εάν δεν έχετε πλήρη δικαιοπρακτική ικανότητα να έχετε την έγκριση του δικαστικού  συμπαραστάτη σας.</p><p>Το «Eligence» διατηρεί το δικαίωμα να αλλάξει, να επεξεργαστεί ή να διαγράψει οποιαδήποτε έγγραφα, πληροφορίες ή άλλο περιεχόμενο που εμφανίζεται στους παρόντες Όρους οποτεδήποτε χωρίς προειδοποίηση και κατά την απόλυτη διακριτική του ευχέρεια. Όλες οι αλλαγές τίθενται σε ισχύ αμέσως μόλις δημοσιεύονται και ισχύουν για κάθε πρόσβαση και χρήση αυτής της Υπηρεσίας στη συνέχεια. Κάθε φορά που επιθυμείτε να χρησιμοποιήσετε την Υπηρεσία, ανατρέξτε στους παρόντες Όρους για να βεβαιωθείτε ότι κατανοείτε τους όρους που ενδέχεται να ισχύουν για εσάς σε αυτήν την περίπτωση.</p><p>Αυτή η Υπηρεσία λειτουργεί από την «MaggioliSPA – Ελληνικό Υποκατάστημα» («Πάροχος» ) με πόρους που παρέχονται από τη Maggioli. Στοιχεία της Υπηρεσίας («Στοιχεία υπηρεσίας»), όπως τεχνολογία, αλγόριθμοι, έγγραφα, δεδομένα, άλλες υπηρεσίες, διαδικασίες και άλλοι πόροι, ενδέχεται να έχουν παρασχεθεί ή να παρέχονται επί του παρόντος από τον Πάροχο ή από τρίτα μέρη («Άλλοι Πάροχοι») . Ο Πάροχος και οι Άλλοι Πάροχοι θα ονομάζονται συλλογικά «Πάροχοι» .</p><p>Η ίδια η Υπηρεσία, καθώς και οποιαδήποτε δεδομένα ή πληροφορίες ή άλλα στοιχεία που μπορεί να καταστούν προσβάσιμα μέσω της Υπηρεσίας, παρέχονται σε βάση «ως έχουν» και «όπως είναι διαθέσιμα» . Ο Πάροχος καταβάλλει προσπάθειες για να διασφαλίσει την ακρίβεια, την πληρότητα ή την αυθεντικότητα των διαδικασιών, δεδομένων και πληροφοριών που διαχειρίζεται και παρέχει η Υπηρεσία.</p><p>Ο Πάροχος διατηρεί το δικαίωμα να τροποποιήσει, να περιορίσει ή να διακόψει οποιοδήποτε μέρος αυτής της Υπηρεσίας κατά την κρίση του. Το ίδιο ισχύει και για Άλλους Παρόχους, εκτός εάν δηλώνεται ρητά διαφορετικά. </p><p>Ο Πάροχος δεν διεκδικεί καμία ιδιοκτησία και δεν αναλαμβάνει καμία ευθύνη για δεδομένα, πληροφορίες, περιεχόμενο, σχόλια, κώδικα, διαδικασίες ή άλλα στοιχεία που αναρτώνται ή ενσωματώνονται στην Υπηρεσία από άλλους Χρήστες, εάν τέτοιες λειτουργίες προσφέρονται από την Υπηρεσία.</p><p>Οι Χρήστες είναι υπεύθυνοι για την προστασία των περιουσιακών στοιχείων και των προσωπικών τους δεδομένων από οποιοδήποτε τέτοια Στοιχεία υπάρχουν στην Υπηρεσία.</p><p>Σύμφωνα με τις προθέσεις του Παρόχου, εφαρμόζονται εύλογα μέτρα ασφαλείας σύμφωνα με την πρακτική που ισχύει στον τομέα λειτουργίας της Υπηρεσίας για την προστασία των ευαίσθητων πληροφοριών που βρίσκονται υπό τον έλεγχό του από απώλεια, κακή χρήση και αλλοίωση. Ωστόσο, ο Πάροχος δεν μπορεί να εγγυηθεί την ασφάλεια των φυσικών τοποθεσιών, του υλικού, του λογισμικού και των δικτύων, των μέσων με τα οποία γίνεται ο χειρισμός και η μετάδοση ευαίσθητων πληροφοριών μεταξύ υπολογιστών και εφαρμογών ή τυχόν ευαίσθητων πληροφοριών που ενδέχεται να ληφθούν μέσω ή σε σύνδεση με την Υπηρεσία.</p><h2>Πνευματική ιδιοκτησία</h2><p>Ο Πάροχος διατηρεί όλα τα δικαιώματα των στοιχείων που παρέχει.</p><p> Στοιχεία της Υπηρεσίας («Στοιχεία υπηρεσίας») έχουν παρασχεθεί από τρίτα μέρη («Άλλοι Πάροχοι») χωρίς περιορισμούς σε σχέση με τα δικαιώματα.</p><p>Το λογισμικό GODOT παρασχέθηκε "ως έχει", χωρίς καμία εγγύηση, ρητή ή σιωπηρή, συμπεριλαμβανομένων, ενδεικτικά, των εγγυήσεων εμπορευσιμότητας, καταλληλότητας για συγκεκριμένο σκοπό και μη παραβίασης. Σε καμία περίπτωση οι δημιουργοί ή οι κάτοχοι πνευματικών δικαιωμάτων δεν ευθύνονται για οποιαδήποτε αξίωση, ζημιά ή άλλη ευθύνη, είτε πρόκειται ενέργεια που αφορά σε σύμβαση, αδικοπραξία ή οτιδήποτε άλλο που προκύπτει από, εξαιτίας ή σε σχέση με το λογισμικό ή τη χρήση ή άλλες συναλλαγές του λογισμικού.</p><h2>Άδεια Χρήσης</h2><p>Οι χρήστες στους οποίους εκχωρείται πρόσβαση μέσω της διαδικασίας που έχει θεσπίσει ο Πάροχος, έχουν άδεια χρήσης της Υπηρεσίας σύμφωνα με τους όρους της άδειας.</p><p>Ο Πάροχος χορηγεί άδεια χρήσης αυτής της Υπηρεσίας ελεύθερα στους Χρήστες του, σύμφωνα με τους όρους του παρόντος εγγράφου. Ωστόσο, η πρόσβαση στην Υπηρεσία ενδέχεται να είναι περιορισμένη λόγω της διαθεσιμότητας των υποκείμενων πόρων. Ο Πάροχος μπορεί να ανακαλέσει αυτήν την Άδεια χρήσης ή να αλλάξει τους όρους της κατά τη διακριτική του ευχέρεια χωρίς προηγούμενη ειδοποίηση προς τους Χρήστες. Πρόθεση του Παρόχου είναι να προσπαθήσει να ενημερώσει έγκαιρα τους Χρήστες που έχουν πρόσβαση στην Υπηρεσία πριν από μια τέτοια ενέργεια, ωστόσο αυτό δεν είναι εγγυημένο.</p><p>Οι χρήστες πρέπει να κάνουν σαφή αναφορά στη χρήση της Υπηρεσίας για οποιαδήποτε προϊόντα ή υπηρεσίες που ενδέχεται να δημιουργηθούν επιπλέον των αποτελεσμάτων ή της χρήσης αυτής της Υπηρεσίας.</p><p>Ανά πάσα στιγμή και χωρίς προηγούμενη ειδοποίηση, ο Πάροχος μπορεί να περιορίσει την πρόσβαση στην Υπηρεσία σε οποιοδήποτε πρόσωπο, γεωγραφική περιοχή ή δικαιοδοσία που επιλέγει κατά τη διακριτική του ευχέρεια. </p><h2>Χρήση της Υπηρεσίας</h2><p>Ο Πάροχος δεν δηλώνει ούτε εγγυάται ότι η Υπηρεσία είναι κατάλληλη ή διαθέσιμη για χρήση σε οποιαδήποτε συγκεκριμένη δικαιοδοσία. Οι χρήστες που εγγράφονται στην Υπηρεσία το κάνουν με δική τους πρωτοβουλία και με δική τους ευθύνη και είναι υπεύθυνοι για τη συμμόρφωση με όλους τους τοπικούς νόμους, κανόνες και κανονισμούς που ισχύουν γι\' αυτούς.</p><p>Με τη χρήση της Υπηρεσίας, ο Χρήστης συμφωνεί με όλους τους όρους του εγγράφου «Όροι Χρήσης» , όπως αυτοί  μπορεί να διαμορφωθούν και να ισχύουν ανά πάσα στιγμή.</p><p>Με τη χρήση της Υπηρεσίας, οι Χρήστες συμφωνούν ότι δικαιούνται να χρησιμοποιούν την Υπηρεσία σύμφωνα με τους όρους που παρουσιάζονται από τον Πάροχο κατόπιν αιτήματος για πρόσβαση στην Υπηρεσία ή όπως αυτοί παρουσιάζονται ρητά στην ενότητα του εγγράφου «Άδεια χρήσης» .</p><p>Σε καμία περίπτωση ο Χρήστης δεν θα χρησιμοποιεί την Υπηρεσία για τη διεξαγωγή κακόβουλης δραστηριότητας η οποία μπορεί, ενδεικτικά και όχι αποκλειστικά, να αναφέρεται σε: πρόσβαση ή έκθεση προσωπικών ή εμπιστευτικών δεδομένων άλλων μερών ή χρηστών, παράδοση κακόβουλου κώδικα σε άλλους χρήστες ή συστήματα, σκόπιμη υπερφόρτωση των πόρων της Υπηρεσίας ή των Παρόχων, οποιαδήποτε ενέργεια που προκαλεί άρνηση παροχής υπηρεσίας για την Υπηρεσία ή οποιαδήποτε υπηρεσία ή πόρο τρίτου μέρους, πλαστοπροσωπία του Παρόχου, του προσωπικού του ή οποιωνδήποτε Χρηστών, επηρεάζει την οικονομική ή κοινωνική κατάσταση του Παρόχου, του προσωπικού του ή Χρήστες κ.λπ.</p><p>Ο Χρήστης δεσμεύεται να χρησιμοποιεί τους πόρους που παρέχονται από την Υπηρεσία, και την ίδια την Υπηρεσία για κανέναν άλλο λόγο και με κανένα άλλο μέσο εκτός από αυτά που προορίζονται από την Υπηρεσία. Σε περίπτωση αβεβαιότητας για την εγκυρότητα μιας χρήσης, ο Χρήστης δεσμεύεται να ζητήσει περαιτέρω πληροφορίες από τον Πάροχο πριν πραγματοποιήσει μια τέτοια χρήση.</p><p>Οι Χρήστες δεσμεύονται να ενημερώνουν έγκαιρα τον Πάροχο για τυχόν ευπάθειες ή ζητήματα που έχουν εντοπίσει ή για τα οποία έχουν ενημερωθεί, κατά τη χρήση της Υπηρεσίας.</p><p>Οι Χρήστες δεσμεύονται να ενημερώσουν αμέσως τον Πάροχο για τυχόν κακόβουλα ή άλλως ακατάλληλα δεδομένα, πληροφορίες, σχόλια, κώδικα, διαδικασίες ή άλλα στοιχεία που διατίθενται στην Υπηρεσία και τα οποία μπορεί να υποπέσουν στην αντίληψή τους.</p><p>Οι Χρήστες είναι υπεύθυνοι για τη διαχείριση των δικών τους διαπιστευτηρίων και την ασφάλεια του λογαριασμού τους. Οι Χρήστες θα πρέπει να ειδοποιούν τον Πάροχο μόλις αντιληφθούν μη εξουσιοδοτημένη χρήση του λογαριασμού τους.</p><p>Ο Πάροχος διατηρεί το δικαίωμα να προβεί σε οποιαδήποτε νομική ενέργεια σε περίπτωση κατάχρησης της Υπηρεσίας για την προστασία των συμφερόντων του ίδιου καθώς και των Χρηστών του. Ο Πάροχος μπορεί να τερματίσει προληπτικά τον λογαριασμό ενός Χρήστη και τη σχετική πρόσβαση στην Υπηρεσία χωρίς καμία προειδοποίηση, για να αποτρέψει την Υπηρεσία, τους πόρους της ή άλλους Χρήστες από ύποπτες λανθασμένες ή κακόβουλες ενέργειες από τον Χρήστη ή οποιονδήποτε υποδύεται τον χρήστη.</p><p>Ο Πάροχος μπορεί να τροποποιήσει τους «Όρους Χρήσης» της Υπηρεσίας, χωρίς προηγούμενη ειδοποίηση. Πρόθεση του Παρόχου είναι να ειδοποιήσει τον Χρήστη για ουσιώδεις αλλαγές σε αυτό το έγγραφο ή σε έγγραφα που μπορεί να αναφέρονται σε αυτό, ωστόσο αυτό δεν είναι εγγυημένο.</p><p>Ο Χρήστης θα θεωρηθεί υπεύθυνος για την αποζημίωση του Παρόχου εάν τυχόν αξιώσεις προς τον Πάροχο προκύψουν από παραβίαση οποιουδήποτε όρου αυτού του εγγράφου «Όρων Χρήσης» από τον Χρήστη. Η αποζημίωση μπορεί να περιλαμβάνει, και δεν περιορίζεται σε ποινές που ενδέχεται να ισχύουν, αξιώσεις αποζημίωσης τρίτων, ηθική και οικονομική ζημία του Παρόχου, νομικά έξοδα του Παρόχου και οποιοδήποτε άλλο σχετικό κόστος.</p><h2>Αποτελεσματικότητα</h2><p>Εάν οποιοδήποτε μέρος αυτού του εγγράφου «Όροι Χρήσης» είναι ανενεργό για οποιονδήποτε λόγο (π.χ. παράνομο ή παρακάμπτεται από άλλο έγγραφο), το υπόλοιπο της συμφωνίας παραμένει σε ισχύ, εξαιρουμένου του μη αποτελεσματικού μέρους.</p><p>Αυτό το έγγραφο «Όροι Χρήσης» ισχύει μεταξύ του Παρόχου και του Χρήστη και σε καμία περίπτωση δεν μπορεί να μεταφερθεί σε οποιοδήποτε τρίτο μέρος από τον Χρήστη.</p><p>Ούτε ο Χρήστης ούτε ο Πάροχος μπορεί να θεωρηθούν υπεύθυνοι για οποιαδήποτε παραβίαση των όρων της παρούσας Άδειας Χρήσης εξαιτίας συνθηκών οι οποίες δεν άπτονται στον εύλογο έλεγχό τους («Ανωτέρα Βία»).</p><p>Ο Πάροχος μπορεί να απόσχει από την άσκηση των δικαιωμάτων αυτού του εγγράφου «Όροι Χρήσης» για οποιονδήποτε λόγο επιλέξει ο ίδιος, σε οποιαδήποτε κατάσταση και χρονική στιγμή. Αυτό δεν θα θεωρείται ως παραίτηση από το δικαίωμα άσκησης των αντίστοιχων δικαιωμάτων του στο μέλλον για τις ίδιες, παρόμοιες ή διαφορετικές περιπτώσεις.</p><h2>Η συμφωνία σας με τους Όρους</h2><p><b><u> Η πρόσβασή σας ή η χρήση της Υπηρεσίας ή/και οποιουδήποτε πόρου που παρέχεται ή στον οποίο έχετε πρόσβαση μέσω αυτής, με οποιονδήποτε τρόπο σημαίνει ότι έχετε διαβάσει, κατανοήσει και συμφωνήσει ότι δεσμεύεστε από τους όρους αυτού του εγγράφου.</u></b></p>',
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Πολιτική Cookie</h2><br><h2>Λίστα Cookies</h2><p>Ένα cookie είναι ένα μικρό κομμάτι δεδομένων (αρχείο κειμένου) που ένας ιστότοπος – που επισκέπτεται ένα χρήστης – ζητά από το πρόγραμμα περιήγησής σας την άδεια να αποθηκεύσει στην συσκευή σας, για να σας θυμάται, πληροφορίες σχετικές με εσάς, όπως η προτίμηση γλώσσας, ή τα στοιχεία – πληροφορίες σύνδεσης. Αυτά τα cookies ορίζονται από εμάς και ονομάζονται cookies προβαλλόμενου ιστότοπου (κύριας σελίδας). Χρησιμοποιούμε επίσης cookies τρίτων – τα οποία είναι cookies από έναν τομέα διαφορετικό από αυτόν του ιστότοπου που επισκέπτεστε – για τις διαφημιστικές και εμπορικές μας προσπάθειες.</p><h2>Διαχείριση ρυθμίσεων Cookie</h2><p>Σε οποιαδήποτε σελίδα του ιστότοπου, κάνοντας κλικ στο κουμπί στην αριστερή κάτω γωνία, θα ανοίξει το banner cookie και θα είναι δυνατή η τροποποίηση και επαναφορά των προτιμήσεών σας. Επιλέγοντας «αποδοχή όλων των cookies» δίνετε την συγκατάθεσή σας για την χρήση όλων των τύπων cookies, ενώ μπορείτε να αποσύρετε την συγκατάθεσή σας κάνοντας κλικ στο «Απόρριψη όλων των cookies». Αποφασίζοντας να κλείσετε το banner, οι προτιμήσεις που δόθηκαν προηγουμένως θα διατηρηθούν μέχρι περαιτέρω τροποποίηση. Ανοίγοντας το banner μπορείτε να διαχειριστείτε τις συναινέσεις για διάφορους τύπους cookies, με βάση τις προτιμήσεις σας.</p><h2>Απαραίτητα Cookies</h2><p>Αυτά τα cookies είναι απαραίτητα για την λειτουργία του ιστότοπου και δεν μπορούν να απενεργοποιηθούν στα συστήματά μας. Τυχόν cookies ή άλλα εργαλεία παρακολούθησης που χρησιμοποιούνται από αυτή την Υπηρεσία ή Άλλους Παρόχους υπηρεσιών τρίτων, που χρησιμοποιούνται από ή μέσω αυτής της Υπηρεσίας, εξυπηρετούν τον σκοπό να παρέχουν την υπηρεσία που απαιτείται στον Χρήστη, πλέον των άλλων σκοπών που περιγράφονται στην Πολιτική Απορρήτου.</p><h2>Cookies (analytics) αναλυτικών</h2><p>Τα analyticscookies είναι cookies που παρακολουθούν τον τρόπο πλοήγησης και αλληλεπίδρασης των χρηστών με την Υπηρεσία. Οι πληροφορίες που συλλέγονται, χρησιμοποιούνται για να βοηθήσουν τον κάτοχο της Υπηρεσίας να βελτιώσει την Υπηρεσία.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
