import { privacy_policy_GR } from './terms-policy/policy.junior.el';
import { terms_GR } from './terms-policy/terms.junior.el';

export const locale = {
  lang: 'en',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE: 'Please contact support or try again later',
      USERNAME_NOT_FOUND_EXCEPTION: 'Username could not be found',
      USER_LOGIN_EXCEPTION: 'Username or password are not valid',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION: 'Invalid email or password',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'User already exists in the Organization',
      USER_REGISTRATION_EXCEPTION: 'Error encountered when registrating user',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Error encountered when generating reset password link',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'The account with this information has not been activated yet. Reset password cannot be enabled',
      PASSWORD_RESET_EXCEPTION:
        'Error encountered when resetting your password',
      MAIL_SEND_EXCEPTION: 'Error encountered when sending email',
      UPDATE_PASSWORD_EXCEPTION: 'Invalid current password',
      TOKEN_REFRESH_EXCEPTION: 'Could not refresh your authorization token',
      USER_LOGOUT_EXCEPTION: 'Error encountered when logging you out',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'You are not authorized to access this resource',
      FORBIDDEN_EXCEPTION: 'You are not authorized to access this resource',
      UNAUTHORIZED_EXCEPTION: 'You are not authorized to access this resource',
      IP_BLOCKED_EXCEPTION:
        'You have been temporarily blocked due to multiple login attempts',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'The email address you provided is already in use',
      FILE_GENERIC_EXCEPTION:
        'File error. Please contact support or try again later',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Argument not valid. Please contact support or try again later',
      APP_EXCEPTION:
        'Something went wrong. Please contact support or try again later',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'Resource already in use. Please contact support or try again later',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Resource not found. Please contact support or try again later',
      FILE_NOT_FOUND_EXCEPTION:
        'File not found. Please contact support or try again later',
      BAD_REQUEST_EXCEPTION:
        'Bad request. Please contact support or try again later',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Media type not acceptable. Please contact support or try again later',
      SESSION_EXPIRED_EXCEPTION: 'Your session has expired. Please login again',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'You are not active in any Organizations. This means that one of your Organization Administrators have deactivated you. Please contact them directly',
      PASSWORD_MISMATCH_EXCEPTION: 'Passwords do not match.',
      ORGANIZATION_NAME_CONFLICT:
        'There is already an organization with this name.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'There is already an organization with this website.',
      ORGANIZATION_PHONE_CONFLICT:
        'There is already an organization with this phone.',
      ORGANIZATION_EMAIL_CONFLICT:
        'There is already an organization with this email.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        "You cannot invite a Tutor. You have reached your subscription's limit.",
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        "You cannot invite a Kid. You have reached your subscription's limit.",
      ORGANIZATION_VAT_CONFLICT:
        'There is already an organization with this VAT.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'The organization has not accepted the subscription.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'The organization does not have active or pending subscription.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'The organization is inactive.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'The user is not verified in the organization',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'A subscription already exists for these dates.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'You cannot perform actions on this questionnaire because it was not created by your organization.',
      BENEFICIARY_ALREADY_HAS_QUESTIONNAIRE:
        'There is already a Questionnaire for this Kid.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'There is already a Questionnaire for this user.',
      QUESTIONNAIRE_IS_EMPTY:
        'To assign a questionnaire, you need to create at least one question',
      SESSION_ALREADY_IN_USE:
        'It appears there was a simultaneous login attempt, prompting a security logout. Please log in again to resume accessing your account securely.',
    },
    ROUTES_TITLE: {
      HOME: 'Home',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'System Admins',
      HEALTH_PROFESSIONALS: 'Tutors',
      BENEFICIARIES: 'Kids',
      MEMBERS: 'Members',
      MEMBER_PROFILE: 'Member Profile',
      GUESTS: 'Guests',
      GUEST_PROFILE: 'Guest Profile',
      MY_PROFILE: 'My profile',
      USER_PROFILE: 'User profile',
      ORGANIZATIONS: 'Organizations',
      ORGANIZATION_PROFILE: 'Organization Profile',
      GAMES: 'Games',
      GAME_MANAGEMENT: 'Game Management',
      GAME_OVERVIEW: 'Game Overview',
      SESSION_TEMPLATES: 'Quest templates',
      SESSIONS_BY_ELIGENCE: 'Quests by Eligence',
      SESSION_TEMPLATE: 'Quest template',
      QUESTIONNAIRE_TEMPLATES: 'Questionnaire templates',
      QUESTIONNAIRES_BY_ELIGENCE: 'Questionnaires by Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire template',
      ASSIGNED_SESSION: 'Assigned Quest',
      ASSIGNED_QUESTIONNAIRE: 'Assigned Questionnaire',
      ADD_SESSION: 'Add Quest',
      CREATE_BENEFICIARY: 'Create Kid Account',
      SUBSCRIPTIONS_MANAGEMENT: 'Subscriptions Management',
      ELIGENCE_SESSION_TEMPLATES: 'Sessions',
      RESELLERS: 'Resellers',
      RESELLER_PROFILE: 'Reseller Profile',
      GROUPS: 'Groups',
      CREATE_GROUP: 'Create Group',
      CREATE_MEMBER: 'Create Member',
      CREATE_GUEST: 'Create Guest',
      GROUP_PROFILE: 'Group Profile',
      ADD_MEETING: 'Start New Meeting',
      EDIT_GROUP: 'Edit Group',
      GAME_VARIATIONS: 'Game Variations',
    },
    CONFIRM: {
      DELETE: 'Are you sure you want to delete this {{name}}?',
      CREATE: 'Are you sure you want to create new {{name}}?',
      EDIT: 'Are you sure you want to edit this {{name}}?',
      CHANGE: 'Are you sure you want to save changes?',
      ACTIVATE: 'Are you sure you want to activate this user?',
      ACTIVATE_ORGANIZATION:
        'Are you sure you want to activate this organization?',
      DEACTIVATE: 'Are you sure you want to deactivate this user?',
      DEACTIVATE_ORGANIZATION:
        'Are you sure you want to deactivate this organization?',
      INVITATION:
        'Are you sure you want to resend the invitation for this user?',
      INVITATION_ORGANIZATION:
        'Are you sure you want to resend the invitation for this organization?',
      BOOK: 'Are you sure you want to book this {{name}}?',
      CANCEL_BOOKING:
        'Are you sure you want to cancel the booking with this user?',
      UPDATE_MAIL_WARNING:
        'Are you sure that you want to change your email? Be aware that your username is going to be your new email.',
      ACTIVATE_GAME: 'Are you sure you want to activate this game?',
      ACTIVATE_GAME_TEMPLATE:
        'Are you sure you want to activate this category of games?',
      DEACTIVATE_GAME: 'Are you sure you want to deactivate this game?',
      DEACTIVATE_GAME_WARNING:
        'This game is currently assigned in {{sessions}} sessions, {{beneficiaries}} beneficiaries, {{sessionTemplates}} session templates, {{systemAssignedSessions}} sessions by Eligence, {{systemSessionTemplates}} session templates by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'This category of games is currently assigned in {{sessions}} sessions, {{beneficiaries}} beneficiaries, {{sessionTemplates}} session templates, {{systemAssignedSessions}} sessions by Eligence, {{systemSessionTemplates}} session templates by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'This game is currently assigned in {{sessions}} active sessions, {{systemAssignedSessions}} sessions by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      REMOVE_PATIENT:
        'Are you sure you want to remove this kid from this tutor?',
      DELETE_PATIENT: 'Are you sure you want to delete this {{name}}',
      CLOSE_SESSION: 'Are you sure you want to close this quest?',
      DELETE_SESSION: 'Are you sure you want to delete this quest?',
      DELETE_QUESTIONNAIRE:
        'Are you sure you want to delete this questionnaire?',
      REMOVE_HEALTH_PROFESSIONAL:
        'Are you sure you want to remove this tutor from this kid?',
      DELETE_HEALTH_PROFESSIONAL:
        'Are you sure you want to delete this tutor?;',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        'Are the games in the preferred order of appearance? Have you chosen the desired difficulty level per game?',
      CANCEL: 'Are you sure you want to cancel this {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Deleting a section will also delete all questions in this section. Are you sure you want to continue?',
    },
    SUCCESS: {
      CREATE: '{{name}} created successfully',
      EDIT: '{{name}} edited successfully',
      UPDATE: '{{name}} updated successfully',
      DELETE: '{{name}} deleted successfully',
      ADD: '{{name}} added successfully',
      ASSIGN: '{{name}} assigned successfully',
      ACTIVATE: '{{name}} activated successfully',
      REQUEST: '{{name}} request sent successfully',
      DEACTIVATE: '{{name}} deactivated successfully',
      REGISTER:
        'You registered successfully. An e-mail will be sent to your e-mail address to set your password',
      CLONE: '{{name}} cloned successfully',
      CLOSE: '{{name}} closed successfully',
      CANCEL: '{{name}} cancelled successfully',
      INVITE: '{{name}} invited successfully',
      RESET: 'Your password has been reset successfully',
      FORGOT:
        'An email has been sent to your e-mail address. Follow the instructions to reset your password',
      REMOVE: '{{name}} removed successfully',
      PASSWORD_CHANGE: 'Your password has been changed successfully',
      AMEND: '{{name}} amended successfully',
      RESEND: '{{name}} resent successfully',
      RESET_OTP: 'One-Time-Password reset successfully.',
      UPGRADE: '{{name}} upgraded successfully',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Add Organization',
      ADD_PATIENT: 'Add Kid',
      ADD_HEALTH_PROFESSIONAL: 'Add Tutor',
      ADD_ORGANIZATION_ADMIN: 'Add Organization Admin',
      ADD_MEMBER: 'Add Member',
      INVITE_MEMBER: 'Invite Member',
      ADD_GUEST: 'Add Guest',
      ORGANIZATION: 'Organization',
      HEALTH_PROFESSIONAL: 'Tutor',
      ASSIGN_PATIENTS: 'Assign Kids',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Tutors',
      ASSIGN_MEMBERS: 'Assign Members',
      ASSIGN_GUESTS: 'Assign Guests',
      PATIENT: 'Kid',
      EDIT_PROFILE: 'Edit Profile',
      SELECT_ORGANIZATION: 'Select Organization',
      UPLOAD_FILE: 'Upload a file for ',
      GAME_FILE: 'Game File',
      ALLOWED_FILE_TYPES: 'Allowed file types: zip',
      UPDATE_PASSWORD: 'Update Password',
      CREATE_SESSION: 'Create Quest',
      ASSIGN_SESSION_TEMPLATE: 'Assign Quest Template',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      INACTIVE_SUBSCRIPTION: 'Inactive Subscription',
      EDIT_INFORMATION: 'Edit Information',
      INVOICE_INFO: 'Invoice Info',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Add Questionnaire Template',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire Template',
      WARNING: 'Warning',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'To assign a questionnaire, you need to create at least one question.',
      ADD_NOTE: 'Create Note',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Assign Questionnaire Template',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'To preview a questionnaire, it must have at least one section and one question.',
      RESET_PASSWORD: 'Reset One-Time Password (OTP)',
      GENERATE_REPORT: 'Generate Report',
      ACTIVITY_DISPLAY_OPTIONS: 'Activity Display Options',
      UPGRADE_ORGANIZATION: 'Upgrade Organization',
      ADD_RESELLER_ADMIN: 'Add Admin',
      GAME_VARIATIONS: 'Game Variations',
      ASSIGN_PRIVATE_GAME: 'Assign Private Game',
      ASSIGN_PUBLIC_GAME: 'Assign Public Game',
      MEETING_MEMBERS: 'Meeting Members',
    },
    ERROR: {
      IMAGE: 'The file you selected is not image',
      RESOURCE:
        'You cannot access this resource when you are already logged in',
      GENERAL:
        'Sorry, looks like there are some errors detected, please try again',
      FILE: 'The file you selected is not supported',
      PAGE_NOT_FOUND: 'Page not found',
      PAGE_NOT_FOUND_BODY: 'The requested URL was not found',
      USERNAME_UNAVAILABLE: 'Username is unavailable',
    },
    BUTTONS: {
      CREATE: 'Create New',
      CONFIRM_ACTION: 'Confirm Action',
      ADD_EXERCISES: 'Add Games',
      DELETE: 'Delete',
      VIEW: 'View',
      APPLY: 'Apply',
      EDIT: 'Edit',
      BACK: 'Back',
      CANCEL: 'Cancel',
      CONTINUE: 'Continue',
      LOGIN: 'Login',
      REGISTER: 'Register',
      SAVE: 'Save',
      SUBMIT: 'Submit',
      ACTIVATE: 'Activate',
      DEACTIVATE: 'Deactivate',
      PLAY: 'Play',
      CONFIRM: 'Confirm',
      ACCEPT: 'Accept',
      DECLINE: 'Decline',
      NEXT_STEP: 'Next Step',
      PREVIOUS_STEP: 'Previous',
      ADD: 'Add New',
      RESET: 'Reset',
      UPLOAD_PHOTO: 'Upload Photo',
      EDIT_PHOTO: 'Edit Photo',
      RESEND_INVITATION: 'Resend Invitation',
      ASSIGN: 'Assign',
      EDIT_PROFILE: 'Edit Profile',
      DISCARD: 'Discard',
      DONE: 'Done',
      ADD_ORGANIZATION: 'Add Organization',
      ADD_PATIENT: 'Add Kid',
      ADD_HEALTH_PROFESSIONAL: 'Add Tutor',
      ADD_ORGANIZATION_ADMIN: 'Add Organization Admin',
      ADD_SESSION: 'Add Quest',
      ASSIGN_PATIENTS: 'Assign Kids',
      ADD_MEMBER: 'Add Member',
      ADD_GUEST: 'Add Guest',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Tutors',
      ASSIGN_MEMBERS: 'Assign Members',
      ASSIGN_GUESTS: 'Assign Guests',
      ACTIONS: 'Actions',
      LOADING: 'Loading...',
      GO_TO_HOMEPAGE: 'Go to homepage',
      ASSIGN_NEW_SESSION: 'Assign New Quest',
      ASSIGN_NEW_QUESTIONNAIRE: 'Assign New Questionnaire',
      CLOSE: 'Close',
      SHOW_MORE: 'Show More',
      SHOW_LESS: 'Show Less',
      CONFIRM_SUBSCRIPTION: 'Confirm Subscription',
      REJECT_SUBSCRIPTION: 'Reject Subscription',
      NEW_SUBSCRIPTION: 'New Subscription',
      ADD_QUESTIONNAIRE: 'Add Questionnaire',
      PREVIEW: 'Preview',
      ADD_ANSWER: 'Add Option',
      GOT_IT: 'Got it',
      ADD_NOTE: 'Add Note',
      EXPORT_RESULTS: 'Export Results',
      SAVE_AND_CONTINUE: 'Save and Continue',
      RESET_ONE_TIME_PASSWORD: 'Reset One-Time Password',
      CREATE_BENEFICIARY: 'Create Kid Account',
      CREATE_MEMBER: 'Create Member',
      CREATE_GUEST: 'Create Guest',
      CHANGE_PASSWORD: 'Change Password',
      COMPLETE: 'Complete',
      START_SESSION: 'Start quest',
      REPLAY: 'Replay',
      START_NOW: 'Start Now!',
      GENERATE_REPORT: 'Generate Report',
      START_QUESTIONNAIRE: 'Start',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Add Admin',
      CREATE_GROUP: 'Create Group',
      ADD_MEETING: 'Start New Meeting',
      STOP: 'End Meeting',
      START_MEETING: 'Start Meeting',
    },
    INPUT: {
      NAME: 'Name',
      EMAIL: 'Email',
      EMAIL_USERNAME: 'Email (Username)',
      PLACE: 'Place',
      VAT: 'VAT',
      FIRST_NAME: 'First Name',
      STREET_ADDRESS: 'Street Address',
      LAST_NAME: 'Last Name',
      FULL_NAME: 'Full Name',
      PASSWORD: 'Password',
      PATIENT_LIST: 'List of beneficiaries',
      HEALTH_PROFESSIONAL_LIST: 'List of health professionals',
      ORGANIZATION_NAME: 'Organization Name',
      ORGANIZATION_EMAIL: 'Company Billing Contact Email',
      ORGANIZATION_ACTIVITY: 'Activity',
      CONFIRM_PASSWORD: 'Confirm Password',
      CITY: 'City',
      HEALTH_PROFESSIONAL: 'Tutor',
      POSTAL_CODE: 'Post Code',
      COUNTRY: 'Country',
      ADDRESS: 'Address',
      COMPANY: 'Company',
      BIRTH_DATE: 'Birth Date',
      WEBSITE: 'Website',
      PHONE: 'Phone Number',
      ROLE: 'Role',
      SERVICE: 'Service',
      PREFERRED_LANGUAGE: 'Preferred Language',
      PREFERRED_ACCOUNT_TYPE: 'Preferred Account Type',
      ADDRESS_INFO: 'Address Info',
      COMPANY_NAME: 'Company Name',
      DESCRIPTION: 'Description',
      TYPE: 'Type',
      PRICE: 'Price',
      FEATURES: 'Features',
      TITLE: 'Title',
      TAGS: 'Tags',
      ACCOUNT_STATUS: 'Account Status',
      IMAGE: 'Image',
      VERSION: 'Version',
      ACTIVITY: 'Activity',
      OLD_PASSWORD: 'Old Password',
      NEW_PASSWORD: 'New Password',
      CONFIRM_NEW_PASSWORD: 'Confirm New Password',
      SESSION_NAME: 'Quest Name',
      INFO: 'Info',
      HEALTH_PROFESSIONAL_INFO: 'Tutor Info',
      PATIENT_INFO: 'Kid Info',
      AGREE_THE: 'I accept the',
      TERMS_AND_CONDITIONS: 'terms and conditions',
      SESSION_TEMPLATE_LIST: 'Quest Template List',
      SAVE_AS_TEMPLATE: 'Save as Template',
      BIRTH_YEAR: 'Year of Birth',
      SEX: 'Gender',
      ACCOUNT_TYPE: 'Account Type',
      HEALTH_PROFESSIONALS: 'Tutors',
      BENEFICIARIES: 'Kids',
      SUBSCRIPTION_DURATION: 'Subscription Duration',
      START_DATE: 'Start Date',
      EXTENSION_DURATION: 'Extension Duration',
      STARTING_LICENSE: 'Starting License',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Support Services',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Kid',
      NOTES: 'Some info for us',
      LATEST_OCCUPATION: 'Latest Occupation',
      EDUCATION_YEARS: 'Education in Years',
      QUESTIONNAIRE_NAME: 'Questionnaire Name',
      WRITE_YOUR_ANSWER: 'Write your answer',
      REQUIRED: 'Required',
      SECTION_NAME: 'Section Name',
      QUESTION: 'Question',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Written answer...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'The answer must only contain numbers.',
      HEALTH_PROFESSIONAL_NOTES: 'Tutor notes',
      NOTE_TEXT: 'Note text',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Questionnaire Template List',
      PATIENT: 'Kid',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'One-Time Password (OTP)',
      CREATE_BENEFICIARY_CONSENT:
        'I have the consent of the parent/guardian of the kid to proceed with the registration of their personal data and enrollment on the Junior Eligence platform.',
      I_HAVE_THE_BENEFICIARY_CONSENT:
        "I have the kid's consent to proceed with the change of their password",
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Describe your current living situation',
      SELECT_TIME_PERIOD: 'Select Time Period',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Select Time Period',
      CURRENT_PASSWORD: 'Current Password',
      ACTIVITY_DISPLAY_OPTION: 'Activity display option',
      GROUP_NAME: 'Group Name',
      MEETING_NAME: 'Meeting Name',
    },
    PLACEHOLDERS: {
      ALL: 'All',
      TOTAL_ELEMENTS: 'Total Elements',
      SELECT_RESELLERS: 'Select Reseller',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Search',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'First Name',
      NOTES: 'Notes',
      LAST_NAME: 'Last Name',
      PATIENTS: 'Kids',
      SESSIONS: 'Quests',
      USER: 'User',
      EMAIL: 'Email',
      JOINED_DATE: 'Joined Date',
      COMPANY: 'Company',
      NAME: 'Name',
      STATUS: 'Status',
      EXECUTIONS: 'Executions',
      COMPLETE_SESSIONS: 'Completed Quests',
      LAST_LOGIN: 'Last Login',
      ACCOUNT_TYPE: 'Account Type',
      ID: 'Id',
      CATEGORY: 'Category',
      PRODUCT: 'Product',
      ACTIONS: 'Actions',
      DESCRIPTION: 'Description',
      CREATED: 'Created',
      COMPLETED: 'Completed',
      COUNTRY: 'Country',
      LANGUAGE: 'Language',
      ROLE: 'Role',
      ADDRESS: 'Address',
      POSTAL_CODE: 'Postal Code',
      CITY: 'City',
      ESCORT: 'Escort',
      ADMIN: 'Admin',
      DATE: 'Date',
      TIME: 'Time',
      DURATION: 'Duration',
      ADDED: 'Added',
      ORGANIZATION: 'Organization',
      EXERCISE: 'Game',
      VERSION: 'Version',
      LEVELS: 'Levels',
      COGNITIVE: 'Cognitive Skill',
      CATEGORIES: 'Categories',
      ENGINE: 'Engine',
      HEALTH_PROFESSIONAL: 'Tutor',
      ASSIGNED_PATIENTS: 'Assigned Kids',
      PATIENT: 'Kid',
      OPEN_SESSIONS: 'Open Quests',
      SESSION: 'Quest',
      ORDER: 'Order',
      GAMES: 'Games',
      LAST_EDIT: 'Last Edit',
      CREATOR: 'Creator',
      ADDED_EXERCISES: 'Added Games',
      DIFFICULTY: 'Difficulty',
      ASSIGNED_BY: 'Assigned by',
      GAME: 'Game',
      SCORE: 'Score',
      PROGRESS: 'Progress',
      BENEFICIARIES: 'Kids',
      LATEST_EXECUTION: 'Latest Execution',
      TYPE: 'Type',
      STARTED: 'Started',
      ENDS: 'Ends',
      HEALTH_PROFESSIONALS: 'Tutors',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Assigned Tutors',
      QUESTIONNAIRE: 'Questionnaire',
      DATE_ASSIGNED: 'Date Assigned',
      DATE_COMPLETED: 'Date Completed',
      SECTIONS: 'Sections',
      START_DATE: 'Start Date',
      EXTENSION_DAYS: 'Extension Days',
      END_DATE: 'End Date',
      EXTENSION_DATE: 'Extension Date',
      TOTAL_COST_OF_SUBSCRIPTION: 'Total Cost of Subscription',
      DURATION_OF_SUBSCRIPTION: 'Duration of Subscription',
      TERMINATION_DATE: 'Termination Date',
      INVITATION_SENT: 'Invitation Sent',
      SUBSCRIPTION_SENT: 'Subscription Sent',
      ACTIVITY_DISPLAY_OPTION: 'Activity Display Option',
      INVITED_BY: 'Invited By',
      GROUP: 'Group',
      MEMBERS: 'Members',
      GUESTS: 'Επισκέπτες',
      MEETINGS: 'Meetings',
      MEETING: 'Meeting',
      VARIATIONS: 'Variations',
      ACTIVATED: 'Activated',
      ASSIGNMENT: 'Assignment',
      INDIVIDUAL_EXECUTIONS: 'Executions (Individual)',
      GROUP_EXECUTIONS: 'Executions (Groups)',
    },
    VALIDATION: {
      INVALID: '{{name}} is invalid',
      REQUIRED: '{{name}} is required',
      MIN_LENGTH: '{{name}} should have at least 3 symbols',
      MAX_LENGTH: '{{name}} should have maximum 256 symbols',
      MAX_LENGTH_NOTES: '{{name}} should have maximum 480 symbols',
      MIN_LENGTH_PASS: '{{name}} should have minimum 8 symbols',
      AGREEMENT_REQUIRED: 'Accepting terms & conditions are required',
      NOT_FOUND: 'The requested {{name}} is not found',
      INVALID_LOGIN: 'The login detail is incorrect',
      REQUIRED_FIELD: 'Required field',
      MIN_LENGTH_FIELD: 'Minimum field length:',
      MAX_LENGTH_FIELD: 'Maximum field length:',
      INVALID_FIELD: 'Field is not valid',
      MUST_MATCH: 'Password and Confirm Password fields do not match',
      MUST_MATCH_PIN: 'Pin and Confirm Pin fields do not match',
      NO_PRIMARY: 'You have not set a primary {{name}}',
      NO_STATUS: 'You have not set {{name}} status',
      MANY_PRIMARY: 'You have set more than one primary {{name}}',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Dashboard',
        SYSTEM: 'System',
      },
      HOME: 'Home',
      USER_PROFILE: 'My Profile',
      ACCOUNT_SETTINGS: 'Account Settings',
      LANGUAGE: 'Language',
      LOGOUT: 'Logout',
      NOTIFICATIONS: 'Notifications',
      SUBSCRIPTIONS: 'Subscriptions',
      ORGANIZATION: 'Organization',
      SESSIONS: 'Quests',
      GAMES: 'Games',
      GAMES_MANAGEMENT: 'Games Management',
      PATIENTS: 'Kids',
      GUESTS: 'Guests',
      MEMBERS: 'Members',
      ORGANIZATIONS: 'Organizations',
      MY_ORGANIZATION: 'Organization Management',
      ADMINS: 'Admins',
      HEALTH_PROFESSIONALS: 'Tutors',
      SIGN_OUT: 'Sign Out',
      QUESTIONNAIRES: 'Questionnaires',
      ELIGENCE_SESSION_TEMPLATES: 'Sessions',
      TEMPLATES: 'Templates',
      BY_ELIGENCE: 'By Eligence',
      RESELLERS: 'Resellers',
      HELP: 'Help',
      GROUPS: 'Groups',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Privacy Policy',
      TERMS_AND_CONDITIONS: 'Terms and Conditions',
      COOKIE_POLICY: 'Cookie Policy',
      CONTACT: 'Contact',
    },
    GAME_DIFFICULTY: {
      EASY: 'Easy',
      INTERMEDIATE: 'Intermediate',
      HARD: 'Hard',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Individual',
      GROUP_MEETING: 'Group Meeting',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Today',
      THIS_WEEK: 'This Week',
      THIS_MONTH: 'This Month',
      LAST_7_DAYS: 'Last 7 Days',
      LAST_30_DAYS: 'Last 30 Days',
      CUSTOM: 'Custom',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Memory',
      LANGUAGE: 'Language',
      ATTENTION: 'Attention',
      CONSTRUCTIVE_ABILITY: 'Constructive Ability',
      EXECUTIVE_FUNCTIONS: 'Executive Functions',
      LOGICAL_REASONING: 'Logical Reasoning',
      ORIENTATION: 'Orientation',
      SPATIAL_AWARENESS: 'Spatial Awareness',
      MOTOR_SKILLS: 'Motor Skills',
      COORDINATION: 'Coordination',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Guests',
      NON_GUEST: 'Members',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Account Type',
      ACCOUNT_TYPE_DESCRIPTION: 'Choose your Account type',
      ORGANIZATION_INFO: 'Organization Info',
      ORGANIZATION_INFO_DESCRIPTION: 'Setup Organization Info',
      INVOICING_DETAILS: 'Invoicing Details',
      INVOICING_DETAILS_DESCRIPTION: 'Setup Invoice Details',
      SETUP_ACCOUNT: 'Setup Account',
      SETUP_ACCOUNT_DESCRIPTION: 'Setup your account details',
      COMPLETED: 'Completed',
      CHOOSE_ACCOUNT_TYPE: 'Choose Account Type',
      SMALL_ORGANIZATION: 'Small Organization',
      SMALL_ORG_HEALTH_PROF_PATIENTS: '1 Tutor / 1-10 Kids',
      MEDIUM_ORGANIZATION: 'Medium Organization',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS: '1-10 Tutors / 1-50 Kids',
      BIG_ORGANIZATION: 'Big Organization',
      BIG_ORG_HEALTH_PROF_PATIENTS: '1-50 Tutors / 1-200 Kids',
      REGISTRATION:
        'An e-mail has been sent to the user in order to activate their account',
      DONE: 'Your account has been activated.',
      DONE_DESCRIPTION: 'Please click the button below to login!',
      MERGE_DONE:
        'You are already registered in another organization. Whenever you log in, you can choose which organization you want to interact with',
      SESSION_INFO: 'Quest Info',
      SESSION_INFO_STEPPER: 'Name your Quest',
      EXERCISES: 'Games',
      EXERCISES_STEPPER: 'Add games',
      COMPLETION: 'Completion',
      COMPLETION_STEPPER: 'Wrap up!',
      SESSION_INFO_DESCRIPTION:
        'Name your quest and keep some notes if you wish!',
      SESSION_EXERCISES: 'Games',
      SESSION_EXERCISES_DESCRIPTION:
        'Add Exercises to your quest and modify it',
      ADD_EXERCISES: 'Add Games',
      ADDED_EXERCISES: 'Added Games',
      CREATE_SESSION_COMPLETION: 'One last step!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Wrap up!',
      OVERVIEW: 'Overview',
      OVERVIEW_BENEFICIARIES: 'Beneficiaries Overview',
      OVERVIEW_SESSIONS: 'Sessions Overview',
      HEALTH_PROFESSIONAL_INFO: 'Tutor Info',
      PATIENT_INFO: 'Kid Info',
      SESSION_NOTES: 'Notes',
      SESSION_NOTES_DESCRIPTION: 'Add some info!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Choose your Account type',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Setup Subscription Details',
      NOTES: 'Notes',
      NOTES_DESCRIPTION: 'Add notes',
      OVERVIEW_DESCRIPTION: 'Have a last look',
      GROUP_INFO: 'Group Info',
      BENEFICIARIES: 'Beneficiaries',
      GROUP_INFO_DESCRIPTION:
        'Name your group and keep some notes if you wish!',
      GROUP_BENEFICIARIES_DESCRIPTION: 'Add Beneficiaries to your group',
      ADD_BENEFICIARIES: 'Add Beneficiaries',
      ADDED_BENEFICIARIES: 'Added Beneficiaries',
      CREATE_GROUP_COMPLETION: 'One last step!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Wrap up!',
      MEETING_INFO: 'Meeting Info',
      MEMBERS: 'Members',
      SESSIONS: 'Sessions',
      MEETING_INFO_DESCRIPTION:
        'Name your meeting and keep some notes if you wish!',
      MEETING_SESSIONS_DESCRIPTION: 'Meeting Sessions Description',
      ADD_SESSIONS: 'Add Sessions',
      ADDED_SESSIONS: 'Added Sessions',
      GAMES: 'Games',
      ASSIGN_GAMES: 'Assign Games',
    },
    INFO: {
      INFO: 'If you need more info, please check out',
      HELP: 'Help Page',
    },
    ACTIONS: {
      ACTIONS: 'Actions',
      VIEW: 'View',
      VIEW_PROFILE: 'View Profile',
      ACTIVATE: 'Activate',
      DEACTIVATE: 'Deactivate',
      DELETE: 'Delete',
      ASSIGN_PATIENTS: 'Assign Kids',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Tutors',
      RESEND_INVITATION: 'Resend Invitation',
      PREVIEW: 'Preview',
      UPLOAD_FILE: 'Upload Game',
      REMOVE_PATIENT: 'Remove Kid',
      SET_TO_ACTIVE: 'Set to Active',
      EDIT: 'Edit',
      REMOVE: 'Remove',
      FROM_TEMPALTE: 'From Template',
      CREATE_NEW: 'Create New',
      CLONE: 'Clone',
      CLOSE: 'Close',
      CANNOT:
        'You cannot perform actions on this quest since it is assigned by another tutor',
      AMENDMENT: 'Amendment',
      TERMINATE: 'Terminate',
      NEW_SUBSCRIPTION: 'New Subscription',
      RESEND_EMAIL: 'Resend email',
      REMOVE_HEALTH_PROFESSIONAL: 'Remove Tutor',
      RENEW: 'Renew',
      ASSIGN: 'Assign',
      UNASSIGN: 'Unassign',
      CANCEL: 'Cancel',
      INVITE: 'Invite',
      CREATE: 'Create',
      RESET_PASSWORD: 'Reset Password',
      ACTIVITY_DISPLAY_OPTIONS: 'Activity Display Options',
      UPGRADE: 'Upgrade',
      VIEW_MEMBERS: 'View Members',
      START_MEETING: 'Start Meeting',
    },
    AUTH: {
      SIGN_IN: 'Sign in',
      NEW_HERE: 'New Here?',
      SIGNUP: 'Sign Up',
      FORGOT_BUTTON: 'Forgot Password?',
      ABOUT: 'About',
      CONTACT: 'Contact',
      CONTACT_US: 'Contact Us',
      FORGOT_PASSWORD: 'Forgot Password',
      RESET_PASSWORD: 'Reset Password',
      SET_PASSWORD: 'Set Password',
      SETUP_YOUR_NEW_PASSWORD: 'Setup your new password',
      AN_EMAIL_IS_REQUIRED: 'An Email is required.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'If your account was created with a Username, please contact your tutor or your administrator.',
    },
    PROFILE: {
      OVERVIEW: 'Overview',
      SETTINGS: 'Settings',
      NOTES: 'Notes',
      EDIT_PROFILE: 'Edit Profile',
      DETAILS: 'Details',
      INFORMATION: 'Information',
      NAME: 'Name',
      FULL_NAME: 'Full Name',
      ROLE: 'Role',
      CONTACT_PHONE: 'Contact Phone',
      EMAIL: 'Email',
      COUNTRY: 'Country',
      POSTAL_CODE: 'Postal Code',
      ADDRESS: 'Address',
      TAX_ID: 'Tax ID',
      STATUS: 'Status',
      EDIT: 'Edit',
      PASSWORD_RESET: 'Password Reset',
      RESEND_PASSWORD_INVITATION: 'Resend Password Invitation',
      ASSIGNED_PATIENTS: 'Assigned Kids',
      ASSIGNED_MEMBERS: 'Assigned Members',
      ASSIGNED_GUESTS: 'Assigned Guests',
      ACCOUNT_ID: 'Account ID',
      BILLING_EMAIL: 'Billing Email',
      LAST_EDIT: 'Last Edit',
      CREATED_BY: 'Created By',
      BILLING_ADDRESS: 'Billing Address',
      ADMINS: 'Admins',
      PAYMENT_RECORDS: 'Payment Records',
      PAYMENT_METHODS: 'Payment Methods',
      PERFORMANCE: 'Performance',
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      PHONE_NUMBER: 'Phone Number',
      PREFERRED_LANGUAGE: 'Preferred Language',
      VAT: 'VAT',
      ACTIVITY: 'Activity',
      WEBSITE: 'Website',
      CREATED_SESSIONS: 'Created Quests',
      EMAIL_UPDATE_TOOLTIP:
        'Be aware that your username is going to be your new email',
      CHANGE_PASSWORD: 'Change Password',
      SESSIONS: 'Quests',
      ADDED_EXERCISES: 'Added Games',
      SESSION_EXECUTIONS_TOOLTIP:
        'This quest has been executed {{number}} times',
      BIRTH_YEAR: 'Year of Birth',
      SEX: 'Gender',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Assigned Tutors',
      SUBSCRIPTIONS: 'Subscriptions',
      CURRENT_SUBSCRIPTION: 'Current Subscription',
      SUBSCRIPTIONS_HISTORY: 'Subscriptions History',
      SUBSCRIPTION: 'Subscription',
      UPCOMING_SUBSCRIPTION: 'Upcoming subscription',
      LATEST_OCCUPATION: 'Latest Occupation',
      EDUCATION_YEARS: 'Education in Years',
      EMAIL_USERNAME: 'Email (Username)',
      INVOICE_INFO: 'Invoice Info',
      EXECUTIONS: 'Executions',
      MEMBER_SINCE: 'Member Since',
      QUESTIONNAIRES: 'Questionnaires',
      ASSIGNED: 'Assigned',
      COMPLETED: 'Completed',
      ANSWERS: 'Answers',
      PASSWORD: 'Password',
      USERNAME: 'Username',
      STAYING_STATUS: 'Describe your current living situation',
      ACTIVITY_DISPLAY_OPTION: 'Activity display option',
      GAMES: 'Games',
      MEETINGS: 'Meetings',
      MEMBERS: 'Members',
      PUBLIC: 'Public',
      PRIVATE: 'Private',
    },
    GENERAL: {
      USER: 'User',
      PATIENT: 'Kid',
      MEMBER: 'Member',
      GUEST: 'Guest',
      HEALTH_PROFESSIONAL: 'Tutor',
      GAME: 'Game',
      PROFILE: 'Profile',
      ORGANIZATION: 'Organization',
      ORGANIZATION_ADMIN: 'Organization Admin',
      NO_ENTRIES: 'No entries found',
      SESSION: 'Quest',
      GAMES: 'Games',
      SESSION_TEMPLATE: 'Quest',
      SUBSCRIPTION: 'Subscription',
      SUBSCRIPTION_EMAIL: 'Subscription email',
      ASSIGNED_QUESTIONNAIRE: 'Assigned Questionnaire',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire Template',
      NOTE: 'Note',
      COPIED: 'Copied!',
      SESSION_NAME: 'Quest Name',
      CONGRATULATIONS: 'Congratulations',
      ACTIVITY_DISPLAY_OPTION: 'Activity display option',
      DESCRIPTION: 'Description',
      SAME_COGNITIVE_GAMES: 'Games that exercise the same cognitive skill',
      SELECT_DIFFICULTY: 'Select difficulty level',
      GROUP: 'Group',
      MEETING: 'Meeting',
    },
    GRAPHS: {
      SCORE: 'Score',
      TIME: 'Time',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Executions per Cognitive Skill & Difficulty',
      EXECUTIONS_PER_GAME_TITLE: 'Executions per Game',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Average Score per Game',
      EXECUTIONS_PER_DAY_TITLE: 'Executions per Day',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE: 'Evolution of Average Score',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Total Activity Time per Day (minutes)',
      GAME: 'Game',
      TOTAL: 'Total',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Activity Logs',
      EXECUTED_GAME: 'Executed Game',
      ADDED: 'Added: ',
      EXECUTED_SESSION: 'Executed Quest',
    },
    SESSION: {
      MY_SESSIONS: 'My Quests',
      SESSION_COMPLETE: 'You completed the quest',
      ABANDONED: 'Abandoned',
      SKIPPED: 'Skipped',
      PLAYED: 'Played',
      PENDING: 'Pending',
      ASSIGNED_SESSIONS: 'Assigned Quests',
      DEFAULT_PUBLIC_INFO:
        'Hello! This is a quest created just for you! Please complete it or contact your tutor if you have further questions.',
      DOCTOR_NOTES: 'Message',
      SAMPLE_DOCTOR_NOTES:
        'Dear {{name}}, this is a quest created just for you! Please complete it or contact your tutor if you have further questions.',
      QUESTS: 'Quests',
    },
    STATUS: {
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
      INVITED: 'Invited',
    },
    SESSION_STATUS: {
      ACTIVE: 'Active',
      ASSIGNED: 'Assigned',
      CLOSED: 'Closed',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Reseller',
      DEMO: 'Demo',
      PAID: 'Paid',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'System Admin',
      ROLE_ORGANIZATION_OWNER: 'Organization Owner',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Organization Admin',
      ROLE_HEALTH_PROFESSIONAL: 'Tutor',
      ROLE_PATIENT: 'Kid',
      ROLE_INTERNAL_CONTACT: 'Internal Contact',
      ROLE_EXTERNAL_CONTACT: 'External Contact',
      ROLE_HEALTH_PROFESSIONAL_OWNER: 'Organization Owner/Tutor',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR: 'Organization Admin/Tutor',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Male',
      FEMALE: 'Female',
      OTHER: 'Other',
      NO_ANSWER: 'Prefer not to indicate',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Hello Admin',
      OVERVIEW_DESCRIPTION: 'Have a look at your numbers',
      EXECUTIONS: 'Executions',
      HOURS: 'Hours',
      BENEFICIARIES: 'Kids',
      HEALTH_PROFESSIONALS: 'Tutors',
      MOST_PLAYED: 'Most Played',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Latest Updates on Games',
      LEAST_PLAYED: 'Least Played',
      ACTIVE_LAST_30_DAYS: 'Active last 30 days',
      GAMES_ACTIVITY: 'Games Activity',
      GAMES_ACTIVITY_DESCRIPTION:
        'Total Executions per Game and Cognitive Skill',
      AVERAGE: 'Total',
      LAST_UPDATE: 'Last Update: ',
      HOUR_SHORT: 'h',
      MINUTE_SHORT: 'm',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Number of Tutors',
      NUMBER_OF_BENEFICIARIES: 'Number of Kids',
      DURATION: 'Duration',
      START_DATE: 'Start Date',
      EXTENSION_DAYS: 'Extension Days',
      END_DATE: 'End Date',
      EXTENSION_DATE: 'Extension Date',
      STARTING_LICENSE: 'Starting License',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Support Services',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Kid',
      TOTAL_COST_OF_BENEFICIARIES: 'Total Cost of Kids',
      TOTAL_COST_OF_SUBSCRIPTION: 'Total Cost of Subscription',
      ORGANIZATION_TYPE: 'Organization Type',
      SUBSCRIPTION_TYPE: 'Subscription Type',
      MONTHS: 'Months',
      DAYS: 'Days',
      REMAINING_DAYS: 'Remaining Days',
      HEALTH_PROFESSIONALS: 'Tutors',
      BENEFICIARIES: 'Kids',
      NOTES: 'Notes',
      DURATION_OF_SUBSCRIPTION: 'Duration of Subscription',
      COSTS_VAT_DISCLAIMER: 'All costs do not include VAT, where applicable.',
      ACCEPT_MODAL_FOOTER:
        'If you do not want to confirm the subscription, please ignore or email us for more info at ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        "You cannot access Eligence, since your organization's subscription is not active. For more information, contact the Eligence team.",
      DAYS_LEFT: 'days left',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'New',
      AMENDMENT: 'Amendment',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Active',
      EXPIRED: 'Expired',
      PENDING_CONSENT: 'Pending Consent',
      PENDING_AUTOMATION: 'Pending Automation',
      REJECTED: 'Rejected',
      TERMINATED: 'Terminated',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Assigned Questionnaires',
      SECTION: 'Section',
      QUESTION: 'Question',
      NOTE: 'Note',
      BY: 'by',
      NEW_MISSION: 'Hello again!',
      QUESTIONNAIRE_NOTE:
        'Before you go on playing, would you like to join me on a special mission?',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Platform Generated',
      USER_GENERATED: 'User Generated',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Assigned',
      IN_PROGRESS: 'In Progress',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Free Text',
      INTEGER: 'Numeric',
      CHECKBOX: 'Multiple Choice',
      RADIO: 'Single Choice',
      DROPDOWN: 'Dropdown',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Questionnaire is a recommended tool provided to you by the Junior Eligence platform. Through the Questionnaire you can collect information regarding a kid or ask for information to assess the status of the specific kid.',
      PROMPT:
        'When the questionnaire is assigned to the kid, all free activities and quests will be disabled until the child completes it.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Create Kid Account',
      TITLE_MEMBER: 'Create Member',
      TITLE_GUEST: 'Create Guest',
      CREDENTIALS: 'Credentials',
      PERSONAL_DETAILS: 'Personal Details',
      COMPLETION: 'Completion',
      CHECK_AVAILABILITY: 'Check availability',
      USERNAME_AVAILABLE: 'Username available',
      USERNAME_UNAVAILABLE: 'Unavailable, try again',
      OTP_SAVE_WARNING: 'Save the password to use later.',
      DONE: 'You’re all set!',
      DONE_DESCRIPTION:
        'A new user account has been created. During the first login, the parent/guardian of the kid will be asked to change the password to protect their personal data.',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'For Groups',
      FOR_TWO: 'For Two',
      INTERGENERATION: 'Between Generations',
      CHALLENGING: 'Challenging',
    },
    GAMES: {
      MY_GAMES: 'My Games',
      ALL_GAMES: 'All',
    },

    STAYING_STATUS: {
      ALONE: 'I live alone',
      WITH_HUSBAND_WIFE: 'I live with my partner',
      WITH_KIDS_GRANDKIDS: 'I live with my children/grandchildren',
      WITH_CARER: 'I live with my caregiver',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'View all',
      ONLY_SESSIONS: 'Only quests',
      ONLY_GAMES: 'Only games',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Assigned',
      UNASSIGNED: 'Unassigned',
    },
    GAME_ACCESS: {
      PUBLIC: 'Public',
      PRIVATE: 'Private',
    },
    PRIVACY_POLICY: {
      CONTENT: privacy_policy_GR,
    },
    TERMS: {
      TEST: terms_GR,
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h2>Cookie Policy</h2><br><h2>Cookie List</h2><p>A cookie is a small piece of data (text file) that a website – when visited by a user – asks your browser to store on your device in order to remember information about you, such as your language preference or login information. Those cookies are set by us and called first-party cookies. We also use third-party cookies – which are cookies from a domain different than the domain of the website you are visiting – for our advertising and marketing efforts.</p><h2>Manage cookie settings</h2><p>On any page of the site, by clicking on the button on the bottom left corner the cookie banner will open and it will be possible to modify and reset your preferences; selecting “accept all cookies” you give the consent to use of all types of cookies, while you can withdraw your consent by clicking on “Refuse all cookies”. By deciding to close the banner, the preferences previously given will be kept until further modification. Opening the banner you can manage consents for the various types of cookies on the basis your preferences.</p><h2>Necessary Cookies</h2><p>These cookies are necessary for the website to function and cannot be switched off in our systems. Any Cookies or other tracking tools used by this Service, or by Other Providers of third-party services used by or through this Service, serve the purpose of providing the service required by the User, in addition to any other purposes described in the Privacy Policy.</p><h2>Analytics cookies</h2><p>Analytics cookies are cookies that track how users navigate and interact with this Service. The information collected is used to help the Service ‘s owner improve the Service.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, quest and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
