export const locale = {
  lang: 'en',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE: 'Please contact support or try again later',
      USERNAME_NOT_FOUND_EXCEPTION: 'Username could not be found',
      USER_LOGIN_EXCEPTION: 'Username or password are not valid',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION: 'Invalid email or password',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'User already exists in the Organization',
      USER_REGISTRATION_EXCEPTION: 'Error encountered when registrating user',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Error encountered when generating reset password link',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'The account with this information has not been activated yet. Reset password cannot be enabled',
      PASSWORD_RESET_EXCEPTION:
        'Error encountered when resetting your password',
      MAIL_SEND_EXCEPTION: 'Error encountered when sending email',
      UPDATE_PASSWORD_EXCEPTION: 'Invalid current password',
      TOKEN_REFRESH_EXCEPTION: 'Could not refresh your authorization token',
      USER_LOGOUT_EXCEPTION: 'Error encountered when logging you out',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'You are not authorized to access this resource',
      FORBIDDEN_EXCEPTION: 'You are not authorized to access this resource',
      UNAUTHORIZED_EXCEPTION: 'You are not authorized to access this resource',
      IP_BLOCKED_EXCEPTION:
        'You have been temporarily blocked due to multiple login attempts',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'The email address you provided is already in use',
      FILE_GENERIC_EXCEPTION:
        'File error. Please contact support or try again later',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Argument not valid. Please contact support or try again later',
      APP_EXCEPTION:
        'Something went wrong. Please contact support or try again later',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'Resource already in use. Please contact support or try again later',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Resource not found. Please contact support or try again later',
      FILE_NOT_FOUND_EXCEPTION:
        'File not found. Please contact support or try again later',
      BAD_REQUEST_EXCEPTION:
        'Bad request. Please contact support or try again later',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Media type not acceptable. Please contact support or try again later',
      SESSION_EXPIRED_EXCEPTION: 'Your session has expired. Please login again',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'You are not active in any Organizations. This means that one of your Organization Administrators have deactivated you. Please contact them directly',
      PASSWORD_MISMATCH_EXCEPTION: 'Passwords do not match.',
      ORGANIZATION_NAME_CONFLICT:
        'There is already an organization with this name.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'There is already an organization with this website.',
      ORGANIZATION_PHONE_CONFLICT:
        'There is already an organization with this phone.',
      ORGANIZATION_EMAIL_CONFLICT:
        'There is already an organization with this email.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        "You cannot invite a Health Professional. You have reached your subscription's limit.",
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        "You cannot invite a Beneficiary. You have reached your subscription's limit.",
      ORGANIZATION_VAT_CONFLICT:
        'There is already an organization with this VAT.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'The organization has not accepted the subscription.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'The organization does not have active or pending subscription.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'The organization is inactive.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'The user is not verified in the organization',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'A subscription already exists for these dates.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'You cannot perform actions on this questionnaire because it was not created by your organization.',
      BENEFICIARY_ALREADY_HAS_QUESTIONNAIRE:
        'There is already a Questionnaire for this Beneficiary.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'There is already a Questionnaire for this user.',
      QUESTIONNAIRE_IS_EMPTY:
        'To assign a questionnaire, you need to create at least one question',
      SESSION_ALREADY_IN_USE:
        'It appears there was a simultaneous login attempt, prompting a security logout. Please log in again to resume accessing your account securely.',
    },
    ROUTES_TITLE: {
      HOME: 'Home',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'System Admins',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      BENEFICIARIES: 'Beneficiaries',
      MEMBERS: 'Members',
      MEMBER_PROFILE: 'Member Profile',
      GUESTS: 'Guests',
      GUEST_PROFILE: 'Guest Profile',
      MY_PROFILE: 'My profile',
      USER_PROFILE: 'User profile',
      ORGANIZATIONS: 'Organizations',
      ORGANIZATION_PROFILE: 'Organization Profile',
      GAMES: 'Games',
      GAME_MANAGEMENT: 'Game Management',
      GAME_OVERVIEW: 'Game Overview',
      SESSION_TEMPLATES: 'Session templates',
      SESSIONS_BY_ELIGENCE: 'Sessions by Eligence',
      SESSION_TEMPLATE: 'Session template',
      QUESTIONNAIRE_TEMPLATES: 'Questionnaire templates',
      QUESTIONNAIRES_BY_ELIGENCE: 'Questionnaires by Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire template',
      ASSIGNED_SESSION: 'Assigned Session',
      ASSIGNED_QUESTIONNAIRE: 'Assigned Questionnaire',
      ADD_SESSION: 'Add Session',
      CREATE_BENEFICIARY: 'Create Beneficiary',
      CREATE_MEMBER: 'Create Member',
      CREATE_GUEST: 'Create Guest',
      SUBSCRIPTIONS_MANAGEMENT: 'Subscriptions Management',
      ELIGENCE_SESSION_TEMPLATES: 'Sessions',
      RESELLERS: 'Resellers',
      RESELLER_PROFILE: 'Reseller Profile',
      GROUPS: 'Groups',
      CREATE_GROUP: 'Create Group',
      GROUP_PROFILE: 'Group Profile',
      ADD_MEETING: 'Start New Meeting',
      EDIT_GROUP: 'Edit Group',
      GAME_VARIATIONS: 'Game Variations',
    },
    CONFIRM: {
      DELETE: 'Are you sure you want to delete this {{name}}?',
      CREATE: 'Are you sure you want to create new {{name}}?',
      EDIT: 'Are you sure you want to edit this {{name}}?',
      CHANGE: 'Are you sure you want to save changes?',
      ACTIVATE: 'Are you sure you want to activate this user?',
      ACTIVATE_ORGANIZATION:
        'Are you sure you want to activate this organization?',
      DEACTIVATE: 'Are you sure you want to deactivate this user?',
      DEACTIVATE_ORGANIZATION:
        'Are you sure you want to deactivate this organization?',
      INVITATION:
        'Are you sure you want to resend the invitation for this user?',
      INVITATION_ORGANIZATION:
        'Are you sure you want to resend the invitation for this organization?',
      BOOK: 'Are you sure you want to book this {{name}}?',
      CANCEL_BOOKING:
        'Are you sure you want to cancel the booking with this user?',
      UPDATE_MAIL_WARNING:
        'Are you sure that you want to change your email? Be aware that your username is going to be your new email.',
      ACTIVATE_GAME: 'Are you sure you want to activate this game?',
      ACTIVATE_GAME_TEMPLATE:
        'Are you sure you want to activate this category of games?',
      DEACTIVATE_GAME: 'Are you sure you want to deactivate this game?',
      DEACTIVATE_GAME_WARNING:
        'This game is currently assigned in {{sessions}} sessions, {{beneficiaries}} beneficiaries, {{sessionTemplates}} session templates, {{systemAssignedSessions}} sessions by Eligence, {{systemSessionTemplates}} session templates by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'This category of games is currently assigned in {{sessions}} sessions, {{beneficiaries}} beneficiaries, {{sessionTemplates}} session templates, {{systemAssignedSessions}} sessions by Eligence, {{systemSessionTemplates}} session templates by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'This game is currently assigned in {{sessions}} active sessions, {{systemAssignedSessions}} sessions by Eligence, {{groupAssignedSessions}} group sessions. Are you sure you want to deactivate it?',
      REMOVE_PATIENT:
        'Are you sure you want to remove this beneficiary from this health professional?',
      CLOSE_SESSION: 'Are you sure you want to close this session?',
      DELETE_SESSION: 'Are you sure you want to delete this session?',
      DELETE_QUESTIONNAIRE:
        'Are you sure you want to delete this questionnaire?',
      REMOVE_HEALTH_PROFESSIONAL:
        'Are you sure you want to remove this health professional from this beneficiary?',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        'Are the games in the preferred order of appearance? Have you chosen the desired difficulty level per game?',
      CANCEL: 'Are you sure you want to cancel this {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Deleting a section will also delete all questions in this section. Are you sure you want to continue?',
    },
    SUCCESS: {
      CREATE: '{{name}} created successfully',
      EDIT: '{{name}} edited successfully',
      UPDATE: '{{name}} updated successfully',
      DELETE: '{{name}} deleted successfully',
      ADD: '{{name}} added successfully',
      ASSIGN: '{{name}} assigned successfully',
      ACTIVATE: '{{name}} activated successfully',
      REQUEST: '{{name}} request sent successfully',
      DEACTIVATE: '{{name}} deactivated successfully',
      REGISTER:
        'You registered successfully. An e-mail will be sent to your e-mail address to set your password',
      CLONE: '{{name}} cloned successfully',
      CLOSE: '{{name}} closed successfully',
      CANCEL: '{{name}} cancelled successfully',
      INVITE: '{{name}} invited successfully',
      RESET: 'Your password has been reset successfully',
      FORGOT:
        'An email has been sent to your e-mail address. Follow the instructions to reset your password',
      REMOVE: '{{name}} removed successfully',
      PASSWORD_CHANGE: 'Your password has been changed successfully',
      AMEND: '{{name}} amended successfully',
      RESEND: '{{name}} resent successfully',
      RESET_OTP: 'One-Time-Password reset successfully.',
      UPGRADE: '{{name}} upgraded successfully',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Add Organization',
      ADD_PATIENT: 'Add Beneficiary',
      ADD_MEMBER: 'Add Member',
      INVITE_MEMBER: 'Invite Member',
      ADD_GUEST: 'Add Guest',
      ADD_HEALTH_PROFESSIONAL: 'Add Health Professional',
      ADD_ORGANIZATION_ADMIN: 'Add Organization Admin',
      ORGANIZATION: 'Organization',
      HEALTH_PROFESSIONAL: 'Health Professional',
      ASSIGN_PATIENTS: 'Assign Beneficiaries',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Health Professionals',
      ASSIGN_MEMBERS: 'Assign Members',
      ASSIGN_GUESTS: 'Assign Guests',
      PATIENT: 'Beneficiary',
      EDIT_PROFILE: 'Edit Profile',
      SELECT_ORGANIZATION: 'Select Organization',
      UPLOAD_FILE: 'Upload a file for ',
      GAME_FILE: 'Game File',
      ALLOWED_FILE_TYPES: 'Allowed file types: zip',
      UPDATE_PASSWORD: 'Update Password',
      CREATE_SESSION: 'Create Session',
      ASSIGN_SESSION_TEMPLATE: 'Assign Session Template',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      INACTIVE_SUBSCRIPTION: 'Inactive Subscription',
      EDIT_INFORMATION: 'Edit Information',
      INVOICE_INFO: 'Invoice Info',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Add Questionnaire Template',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire Template',
      WARNING: 'Warning',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'To assign a questionnaire, you need to create at least one question.',
      ADD_NOTE: 'Create Note',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Assign Questionnaire Template',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'To preview a questionnaire, it must have at least one section and one question.',
      RESET_PASSWORD: 'Reset One-Time Password (OTP)',
      GENERATE_REPORT: 'Generate Report',
      ACTIVITY_DISPLAY_OPTIONS: 'Activity Display Options',
      UPGRADE_ORGANIZATION: 'Upgrade Organization',
      ADD_RESELLER_ADMIN: 'Add Admin',
      GAME_VARIATIONS: 'Game Variations',
      ASSIGN_PRIVATE_GAME: 'Assign Private Game',
      ASSIGN_PUBLIC_GAME: 'Assign Public Game',
      MEETING_MEMBERS: 'Meeting Members',
    },
    ERROR: {
      IMAGE: 'The file you selected is not image',
      RESOURCE:
        'You cannot access this resource when you are already logged in',
      GENERAL:
        'Sorry, looks like there are some errors detected, please try again',
      FILE: 'The file you selected is not supported',
      PAGE_NOT_FOUND: 'Page not found',
      PAGE_NOT_FOUND_BODY: 'The requested URL was not found',
      USERNAME_UNAVAILABLE: 'Username is unavailable',
    },
    BUTTONS: {
      CREATE: 'Create New',
      CONFIRM_ACTION: 'Confirm Action',
      ADD_EXERCISES: 'Add Games',
      DELETE: 'Delete',
      VIEW: 'View',
      APPLY: 'Apply',
      EDIT: 'Edit',
      BACK: 'Back',
      CANCEL: 'Cancel',
      CONTINUE: 'Continue',
      LOGIN: 'Login',
      REGISTER: 'Register',
      SAVE: 'Save',
      SUBMIT: 'Submit',
      ACTIVATE: 'Activate',
      DEACTIVATE: 'Deactivate',
      PLAY: 'Play',
      CONFIRM: 'Confirm',
      ACCEPT: 'Accept',
      DECLINE: 'Decline',
      NEXT_STEP: 'Next Step',
      PREVIOUS_STEP: 'Previous',
      ADD: 'Add New',
      RESET: 'Reset',
      UPLOAD_PHOTO: 'Upload Photo',
      EDIT_PHOTO: 'Edit Photo',
      RESEND_INVITATION: 'Resend Invitation',
      ASSIGN: 'Assign',
      EDIT_PROFILE: 'Edit Profile',
      DISCARD: 'Discard',
      DONE: 'Done',
      ADD_ORGANIZATION: 'Add Organization',
      ADD_PATIENT: 'Add Beneficiary',
      ADD_HEALTH_PROFESSIONAL: 'Add Health Professional',
      ADD_ORGANIZATION_ADMIN: 'Add Organization Admin',
      ADD_SESSION: 'Add Session',
      ADD_MEMBER: 'Add Member',
      ADD_GUEST: 'Add Guest',
      ASSIGN_PATIENTS: 'Assign Beneficiaries',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Health Professionals',
      ASSIGN_MEMBERS: 'Assign Members',
      ASSIGN_GUESTS: 'Assign Guests',
      ACTIONS: 'Actions',
      LOADING: 'Loading...',
      GO_TO_HOMEPAGE: 'Go to homepage',
      ASSIGN_NEW_SESSION: 'Assign New Session',
      ASSIGN_NEW_QUESTIONNAIRE: 'Assign New Questionnaire',
      CLOSE: 'Close',
      SHOW_MORE: 'Show More',
      SHOW_LESS: 'Show Less',
      CONFIRM_SUBSCRIPTION: 'Confirm Subscription',
      REJECT_SUBSCRIPTION: 'Reject Subscription',
      NEW_SUBSCRIPTION: 'New Subscription',
      ADD_QUESTIONNAIRE: 'Add Questionnaire',
      PREVIEW: 'Preview',
      ADD_ANSWER: 'Add Option',
      GOT_IT: 'Got it',
      ADD_NOTE: 'Add Note',
      EXPORT_RESULTS: 'Export Results',
      SAVE_AND_CONTINUE: 'Save and Continue',
      RESET_ONE_TIME_PASSWORD: 'Reset One-Time Password',
      CREATE_BENEFICIARY: 'Create Beneficiary',
      CREATE_MEMBER: 'Create Member',
      CREATE_GUEST: 'Create Guest',
      CHANGE_PASSWORD: 'Change Password',
      COMPLETE: 'Complete',
      START_SESSION: 'Start session',
      REPLAY: 'Replay',
      START_NOW: 'Start Now!',
      GENERATE_REPORT: 'Generate Report',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Add Admin',
      CREATE_GROUP: 'Create Group',
      ADD_MEETING: 'Start New Meeting',
      STOP: 'End Meeting',
      START_MEETING: 'Start Meeting',
    },
    INPUT: {
      NAME: 'Name',
      EMAIL: 'Email',
      EMAIL_USERNAME: 'Email (Username)',
      PLACE: 'Place',
      VAT: 'VAT',
      FIRST_NAME: 'First Name',
      STREET_ADDRESS: 'Street Address',
      LAST_NAME: 'Last Name',
      FULL_NAME: 'Full Name',
      PASSWORD: 'Password',
      PATIENT_LIST: 'List of beneficiaries',
      HEALTH_PROFESSIONAL_LIST: 'List of health professionals',
      ORGANIZATION_NAME: 'Organization Name',
      ORGANIZATION_EMAIL: 'Company Billing Contact Email',
      ORGANIZATION_ACTIVITY: 'Activity',
      CONFIRM_PASSWORD: 'Confirm Password',
      CITY: 'City',
      HEALTH_PROFESSIONAL: 'Health Professional',
      POSTAL_CODE: 'Post Code',
      COUNTRY: 'Country',
      ADDRESS: 'Address',
      COMPANY: 'Company',
      BIRTH_DATE: 'Birth Date',
      WEBSITE: 'Website',
      PHONE: 'Phone Number',
      ROLE: 'Role',
      SERVICE: 'Service',
      PREFERRED_LANGUAGE: 'Preferred Language',
      PREFERRED_ACCOUNT_TYPE: 'Preferred Account Type',
      ADDRESS_INFO: 'Address Info',
      COMPANY_NAME: 'Company Name',
      DESCRIPTION: 'Description',
      TYPE: 'Type',
      PRICE: 'Price',
      FEATURES: 'Features',
      TITLE: 'Title',
      TAGS: 'Tags',
      ACCOUNT_STATUS: 'Account Status',
      IMAGE: 'Image',
      VERSION: 'Version',
      ACTIVITY: 'Activity',
      OLD_PASSWORD: 'Old Password',
      NEW_PASSWORD: 'New Password',
      CONFIRM_NEW_PASSWORD: 'Confirm New Password',
      SESSION_NAME: 'Session Name',
      INFO: 'Info',
      HEALTH_PROFESSIONAL_INFO: 'Health Professional Info',
      PATIENT_INFO: 'Beneficiary Info',
      AGREE_THE: 'I accept the',
      TERMS_AND_CONDITIONS: 'terms and conditions',
      SESSION_TEMPLATE_LIST: 'Session Template List',
      SAVE_AS_TEMPLATE: 'Save as Template',
      BIRTH_YEAR: 'Year of Birth',
      SEX: 'Gender',
      ACCOUNT_TYPE: 'Account Type',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      BENEFICIARIES: 'Beneficiaries',
      SUBSCRIPTION_DURATION: 'Subscription Duration',
      START_DATE: 'Start Date',
      EXTENSION_DURATION: 'Extension Duration',
      STARTING_LICENSE: 'Starting License',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Support Services',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Beneficiary',
      NOTES: 'Some info for us',
      LATEST_OCCUPATION: 'Latest Occupation',
      EDUCATION_YEARS: 'Education in Years',
      QUESTIONNAIRE_NAME: 'Questionnaire Name',
      WRITE_YOUR_ANSWER: 'Write your answer',
      REQUIRED: 'Required',
      SECTION_NAME: 'Section Name',
      QUESTION: 'Question',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Written answer...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'The answer must only contain numbers.',
      HEALTH_PROFESSIONAL_NOTES: 'Health Professional notes',
      NOTE_TEXT: 'Note text',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Questionnaire Template List',
      PATIENT: 'Beneficiary',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'One-Time Password (OTP)',
      CREATE_BENEFICIARY_CONSENT:
        "I have the beneficiary's consent to proceed with the registration of their personal data and their enrollment on the Eligence platform.",
      I_HAVE_THE_BENEFICIARY_CONSENT:
        "I have the beneficiary's consent to proceed with the change of their password",
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Describe your current living situation',
      SELECT_TIME_PERIOD: 'Select Time Period',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Select Time Period',
      CURRENT_PASSWORD: 'Current Password',
      ACTIVITY_DISPLAY_OPTION: 'Activity display option',
      GROUP_NAME: 'Group Name',
      MEETING_NAME: 'Meeting Name',
    },
    PLACEHOLDERS: {
      ALL: 'All',
      TOTAL_ELEMENTS: 'Total Elements',
      SELECT_RESELLERS: 'Select Reseller',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Search',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'First Name',
      NOTES: 'Notes',
      LAST_NAME: 'Last Name',
      PATIENTS: 'Beneficiaries',
      SESSIONS: 'Sessions',
      USER: 'User',
      EMAIL: 'Email',
      JOINED_DATE: 'Joined Date',
      COMPANY: 'Company',
      NAME: 'Name',
      STATUS: 'Status',
      EXECUTIONS: 'Executions',
      COMPLETE_SESSIONS: 'Completed Sessions',
      LAST_LOGIN: 'Last Login',
      ACCOUNT_TYPE: 'Account Type',
      ID: 'Id',
      CATEGORY: 'Category',
      PRODUCT: 'Product',
      ACTIONS: 'Actions',
      DESCRIPTION: 'Description',
      CREATED: 'Created',
      COMPLETED: 'Completed',
      COUNTRY: 'Country',
      LANGUAGE: 'Language',
      ROLE: 'Role',
      ADDRESS: 'Address',
      POSTAL_CODE: 'Postal Code',
      CITY: 'City',
      ESCORT: 'Escort',
      ADMIN: 'Admin',
      DATE: 'Date',
      TIME: 'Time',
      DURATION: 'Duration',
      ADDED: 'Added',
      ORGANIZATION: 'Organization',
      EXERCISE: 'Game',
      VERSION: 'Version',
      LEVELS: 'Levels',
      COGNITIVE: 'Cognitive Skill',
      CATEGORIES: 'Categories',
      ENGINE: 'Engine',
      HEALTH_PROFESSIONAL: 'Health Professional',
      ASSIGNED_PATIENTS: 'Assigned Beneficiaries',
      PATIENT: 'Beneficiary',
      OPEN_SESSIONS: 'Open Sessions',
      SESSION: 'Session',
      ORDER: 'Order',
      GAMES: 'Games',
      LAST_EDIT: 'Last Edit',
      CREATOR: 'Creator',
      ADDED_EXERCISES: 'Added Games',
      DIFFICULTY: 'Difficulty',
      ASSIGNED_BY: 'Assigned by',
      GAME: 'Game',
      SCORE: 'Score',
      PROGRESS: 'Progress',
      BENEFICIARIES: 'Beneficiaries',
      LATEST_EXECUTION: 'Latest Execution',
      TYPE: 'Type',
      STARTED: 'Started',
      ENDS: 'Ends',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Assigned Health Professionals',
      QUESTIONNAIRE: 'Questionnaire',
      DATE_ASSIGNED: 'Date Assigned',
      DATE_COMPLETED: 'Date Completed',
      SECTIONS: 'Sections',
      START_DATE: 'Start Date',
      EXTENSION_DAYS: 'Extension Days',
      END_DATE: 'End Date',
      EXTENSION_DATE: 'Extension Date',
      TOTAL_COST_OF_SUBSCRIPTION: 'Total Cost of Subscription',
      DURATION_OF_SUBSCRIPTION: 'Duration of Subscription',
      TERMINATION_DATE: 'Termination Date',
      INVITATION_SENT: 'Invitation Sent',
      SUBSCRIPTION_SENT: 'Subscription Sent',
      ACTIVITY_DISPLAY_OPTION: 'Activity Display Option',
      INVITED_BY: 'Invited By',
      GROUP: 'Group',
      MEMBERS: 'Members',
      GUESTS: 'Guests',
      MEETINGS: 'Meetings',
      MEETING: 'Meeting',
      VARIATIONS: 'Variations',
      ACTIVATED: 'Activated',
      ASSIGNMENT: 'Assignment',
      INDIVIDUAL_EXECUTIONS: 'Executions (Individual)',
      GROUP_EXECUTIONS: 'Executions (Groups)',
    },
    VALIDATION: {
      INVALID: '{{name}} is invalid',
      REQUIRED: '{{name}} is required',
      MIN_LENGTH: '{{name}} should have at least 3 symbols',
      MAX_LENGTH: '{{name}} should have maximum 256 symbols',
      MAX_LENGTH_NOTES: '{{name}} should have maximum 480 symbols',
      MIN_LENGTH_PASS: '{{name}} should have minimum 8 symbols',
      AGREEMENT_REQUIRED: 'Accepting terms & conditions are required',
      NOT_FOUND: 'The requested {{name}} is not found',
      INVALID_LOGIN: 'The login detail is incorrect',
      REQUIRED_FIELD: 'Required field',
      MIN_LENGTH_FIELD: 'Minimum field length:',
      MAX_LENGTH_FIELD: 'Maximum field length:',
      INVALID_FIELD: 'Field is not valid',
      MUST_MATCH: 'Password and Confirm Password fields do not match',
      MUST_MATCH_PIN: 'Pin and Confirm Pin fields do not match',
      NO_PRIMARY: 'You have not set a primary {{name}}',
      NO_STATUS: 'You have not set {{name}} status',
      MANY_PRIMARY: 'You have set more than one primary {{name}}',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Dashboard',
        SYSTEM: 'System',
      },
      HOME: 'Home',
      USER_PROFILE: 'My Profile',
      ACCOUNT_SETTINGS: 'Account Settings',
      LANGUAGE: 'Language',
      LOGOUT: 'Logout',
      NOTIFICATIONS: 'Notifications',
      SUBSCRIPTIONS: 'Subscriptions',
      ORGANIZATION: 'Organization',
      SESSIONS: 'Sessions',
      GAMES: 'Games',
      GAMES_MANAGEMENT: 'Games Management',
      PATIENTS: 'Beneficiaries',
      GUESTS: 'Guests',
      MEMBERS: 'Members',
      ORGANIZATIONS: 'Organizations',
      MY_ORGANIZATION: 'Organization Management',
      ADMINS: 'Admins',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      SIGN_OUT: 'Sign Out',
      QUESTIONNAIRES: 'Questionnaires',
      ELIGENCE_SESSION_TEMPLATES: 'Sessions',
      TEMPLATES: 'Templates',
      BY_ELIGENCE: 'By Eligence',
      RESELLERS: 'Resellers',
      HELP: 'Help',
      GROUPS: 'Groups',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Privacy Policy',
      TERMS_AND_CONDITIONS: 'Terms and Conditions',
      COOKIE_POLICY: 'Cookies Policy',
      CONTACT: 'Contact',
    },
    GAME_DIFFICULTY: {
      EASY: 'Easy',
      INTERMEDIATE: 'Intermediate',
      HARD: 'Hard',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Individual',
      GROUP_MEETING: 'Group Meeting',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Today',
      THIS_WEEK: 'This Week',
      THIS_MONTH: 'This Month',
      LAST_7_DAYS: 'Last 7 Days',
      LAST_30_DAYS: 'Last 30 Days',
      CUSTOM: 'Custom',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Memory',
      LANGUAGE: 'Language',
      ATTENTION: 'Attention',
      CONSTRUCTIVE_ABILITY: 'Constructive Ability',
      EXECUTIVE_FUNCTIONS: 'Executive Functions',
      LOGICAL_REASONING: 'Logical Reasoning',
      ORIENTATION: 'Orientation',
      SPATIAL_AWARENESS: 'Spatial Awareness',
      MOTOR_SKILLS: 'Motor Skills',
      COORDINATION: 'Coordination',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Guests',
      NON_GUEST: 'Members',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Account Type',
      ACCOUNT_TYPE_DESCRIPTION: 'Choose your Account type',
      ORGANIZATION_INFO: 'Organization Info',
      ORGANIZATION_INFO_DESCRIPTION: 'Setup Organization Info',
      INVOICING_DETAILS: 'Invoicing Details',
      INVOICING_DETAILS_DESCRIPTION: 'Setup Invoice Details',
      SETUP_ACCOUNT: 'Setup Account',
      SETUP_ACCOUNT_DESCRIPTION: 'Setup your account details',
      COMPLETED: 'Completed',
      CHOOSE_ACCOUNT_TYPE: 'Choose Account Type',
      SMALL_ORGANIZATION: 'Small Organization',
      SMALL_ORG_HEALTH_PROF_PATIENTS:
        '1 Health Professional / 1-10 Beneficiaries',
      MEDIUM_ORGANIZATION: 'Medium Organization',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS:
        '1-10 Health Professionals / 1-50 Beneficiaries',
      BIG_ORGANIZATION: 'Big Organization',
      BIG_ORG_HEALTH_PROF_PATIENTS:
        '1-50 Health Professionals / 1-200 Beneficiaries',
      REGISTRATION:
        'An e-mail has been sent to the user in order to activate their account',
      DONE: 'Your account has been activated.',
      DONE_DESCRIPTION: 'Please click the button below to login!',
      MERGE_DONE:
        'You are already registered in another organization. Whenever you log in, you can choose which organization you want to interact with',
      SESSION_INFO: 'Session Info',
      SESSION_INFO_STEPPER: 'Name your Session',
      EXERCISES: 'Games',
      EXERCISES_STEPPER: 'Add games',
      COMPLETION: 'Completion',
      COMPLETION_STEPPER: 'Wrap up!',
      SESSION_INFO_DESCRIPTION:
        'Name your session and keep some notes if you wish!',
      SESSION_EXERCISES: 'Games',
      SESSION_EXERCISES_DESCRIPTION:
        'Add Exercises to your session and modify it',
      ADD_EXERCISES: 'Add Games',
      ADDED_EXERCISES: 'Added Games',
      CREATE_SESSION_COMPLETION: 'One last step!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Wrap up!',
      OVERVIEW: 'Overview',
      OVERVIEW_BENEFICIARIES: 'Beneficiaries Overview',
      OVERVIEW_SESSIONS: 'Sessions Overview',
      HEALTH_PROFESSIONAL_INFO: 'Health Professional Info',
      PATIENT_INFO: 'Beneficiary Info',
      SESSION_NOTES: 'Notes',
      SESSION_NOTES_DESCRIPTION: 'Add some info!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Choose your Account type',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Setup Subscription Details',
      NOTES: 'Notes',
      NOTES_DESCRIPTION: 'Add notes',
      OVERVIEW_DESCRIPTION: 'Have a last look',
      GROUP_INFO: 'Group Info',
      BENEFICIARIES: 'Beneficiaries',
      GROUP_INFO_DESCRIPTION:
        'Name your group and keep some notes if you wish!',
      GROUP_BENEFICIARIES_DESCRIPTION: 'Add Beneficiaries to your group',
      ADD_BENEFICIARIES: 'Add Beneficiaries',
      ADDED_BENEFICIARIES: 'Added Beneficiaries',
      CREATE_GROUP_COMPLETION: 'One last step!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Wrap up!',
      MEETING_INFO: 'Meeting Info',
      MEMBERS: 'Members',
      SESSIONS: 'Sessions',
      MEETING_INFO_DESCRIPTION:
        'Name your meeting and keep some notes if you wish!',
      MEETING_SESSIONS_DESCRIPTION: 'Meeting Sessions Description',
      ADD_SESSIONS: 'Add Sessions',
      ADDED_SESSIONS: 'Added Sessions',
      GAMES: 'Games',
      ASSIGN_GAMES: 'Assign Games',
    },
    INFO: {
      INFO: 'If you need more info, please check out',
      HELP: 'Help Page',
    },
    ACTIONS: {
      ACTIONS: 'Actions',
      VIEW: 'View',
      VIEW_PROFILE: 'View Profile',
      ACTIVATE: 'Activate',
      DEACTIVATE: 'Deactivate',
      DELETE: 'Delete',
      ASSIGN_PATIENTS: 'Assign Beneficiaries',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assign Health Professionals',
      RESEND_INVITATION: 'Resend Invitation',
      PREVIEW: 'Preview',
      UPLOAD_FILE: 'Upload Game',
      REMOVE_PATIENT: 'Remove Beneficiary',
      SET_TO_ACTIVE: 'Set to Active',
      EDIT: 'Edit',
      REMOVE: 'Remove',
      FROM_TEMPALTE: 'From Template',
      CREATE_NEW: 'Create New',
      CLONE: 'Clone',
      CLOSE: 'Close',
      CANNOT:
        'You cannot perform actions on this session since it is assigned by another health professional',
      AMENDMENT: 'Amendment',
      TERMINATE: 'Terminate',
      NEW_SUBSCRIPTION: 'New Subscription',
      RESEND_EMAIL: 'Resend email',
      REMOVE_HEALTH_PROFESSIONAL: 'Remove Health Professional',
      RENEW: 'Renew',
      ASSIGN: 'Assign',
      UNASSIGN: 'Unassign',
      CANCEL: 'Cancel',
      INVITE: 'Invite',
      CREATE: 'Create',
      RESET_PASSWORD: 'Reset Password',
      ACTIVITY_DISPLAY_OPTIONS: 'Activity Display Options',
      UPGRADE: 'Upgrade',
      VIEW_MEMBERS: 'View Members',
      START_MEETING: 'Start Meeting',
    },
    AUTH: {
      SIGN_IN: 'Sign in',
      NEW_HERE: 'New Here?',
      SIGNUP: 'Sign Up',
      FORGOT_BUTTON: 'Forgot Password?',
      ABOUT: 'About',
      CONTACT: 'Contact',
      CONTACT_US: 'Contact Us',
      FORGOT_PASSWORD: 'Forgot Password',
      RESET_PASSWORD: 'Reset Password',
      SET_PASSWORD: 'Set Password',
      SETUP_YOUR_NEW_PASSWORD: 'Setup your new password',
      AN_EMAIL_IS_REQUIRED: 'An Email is required.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'If your account was created with a Username, please contact your health professional or your organization administrator.',
    },
    PROFILE: {
      OVERVIEW: 'Overview',
      SETTINGS: 'Settings',
      NOTES: 'Notes',
      EDIT_PROFILE: 'Edit Profile',
      DETAILS: 'Details',
      INFORMATION: 'Information',
      NAME: 'Name',
      FULL_NAME: 'Full Name',
      ROLE: 'Role',
      CONTACT_PHONE: 'Contact Phone',
      EMAIL: 'Email',
      COUNTRY: 'Country',
      POSTAL_CODE: 'Postal Code',
      ADDRESS: 'Address',
      TAX_ID: 'Tax ID',
      STATUS: 'Status',
      EDIT: 'Edit',
      PASSWORD_RESET: 'Password Reset',
      RESEND_PASSWORD_INVITATION: 'Resend Password Invitation',
      ASSIGNED_PATIENTS: 'Assigned Beneficiaries',
      ASSIGNED_MEMBERS: 'Assigned Members',
      ASSIGNED_GUESTS: 'Assigned Guests',
      ACCOUNT_ID: 'Account ID',
      BILLING_EMAIL: 'Billing Email',
      LAST_EDIT: 'Last Edit',
      CREATED_BY: 'Created By',
      BILLING_ADDRESS: 'Billing Address',
      ADMINS: 'Admins',
      PAYMENT_RECORDS: 'Payment Records',
      PAYMENT_METHODS: 'Payment Methods',
      PERFORMANCE: 'Performance',
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      PHONE_NUMBER: 'Phone Number',
      PREFERRED_LANGUAGE: 'Preferred Language',
      VAT: 'VAT',
      ACTIVITY: 'Activity',
      WEBSITE: 'Website',
      CREATED_SESSIONS: 'Created Sessions',
      EMAIL_UPDATE_TOOLTIP:
        'Be aware that your username is going to be your new email',
      CHANGE_PASSWORD: 'Change Password',
      SESSIONS: 'Sessions',
      ADDED_EXERCISES: 'Added Games',
      SESSION_EXECUTIONS_TOOLTIP:
        'This session has been executed {{number}} times',
      BIRTH_YEAR: 'Year of Birth',
      SEX: 'Gender',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Assigned Health Professionals',
      SUBSCRIPTIONS: 'Subscriptions',
      CURRENT_SUBSCRIPTION: 'Current Subscription',
      SUBSCRIPTIONS_HISTORY: 'Subscriptions History',
      SUBSCRIPTION: 'Subscription',
      UPCOMING_SUBSCRIPTION: 'Upcoming subscription',
      LATEST_OCCUPATION: 'Latest Occupation',
      EDUCATION_YEARS: 'Education in Years',
      EMAIL_USERNAME: 'Email (Username)',
      INVOICE_INFO: 'Invoice Info',
      EXECUTIONS: 'Executions',
      MEMBER_SINCE: 'Member Since',
      QUESTIONNAIRES: 'Questionnaires',
      ASSIGNED: 'Assigned',
      COMPLETED: 'Completed',
      ANSWERS: 'Answers',
      PASSWORD: 'Password',
      USERNAME: 'Username',
      STAYING_STATUS: 'Describe your current living situation',
      ACTIVITY_DISPLAY_OPTION: 'Activity display option',
      GAMES: 'Games',
      MEETINGS: 'Meetings',
      MEMBERS: 'Members',
      PUBLIC: 'Public',
      PRIVATE: 'Private',
    },
    GENERAL: {
      USER: 'User',
      PATIENT: 'Beneficiary',
      MEMBER: 'Member',
      GUEST: 'Guest',
      HEALTH_PROFESSIONAL: 'Health Professional',
      GAME: 'Game',
      PROFILE: 'Profile',
      ORGANIZATION: 'Organization',
      ORGANIZATION_ADMIN: 'Organization Admin',
      NO_ENTRIES: 'No entries found',
      SESSION: 'Session',
      GAMES: 'Games',
      SESSION_TEMPLATE: 'Session Template',
      SUBSCRIPTION: 'Subscription',
      SUBSCRIPTION_EMAIL: 'Subscription email',
      ASSIGNED_QUESTIONNAIRE: 'Assigned Questionnaire',
      QUESTIONNAIRE_TEMPLATE: 'Questionnaire Template',
      NOTE: 'Note',
      COPIED: 'Copied!',
      SESSION_NAME: 'Session Name',
      CONGRATULATIONS: 'Congratulations',
      DESCRIPTION: 'Description',
      SAME_COGNITIVE_GAMES: 'Games that exercise the same cognitive skill',
      SELECT_DIFFICULTY: 'Select difficulty level',
      GROUP: 'Group',
      MEETING: 'Meeting',
    },
    GRAPHS: {
      SCORE: 'Score',
      TIME: 'Time',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Executions per Cognitive Skill & Difficulty',
      EXECUTIONS_PER_GAME_TITLE: 'Executions per Game',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Average Score per Game',
      EXECUTIONS_PER_DAY_TITLE: 'Executions per Day',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE: 'Evolution of Average Score',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Total Activity Time per Day (minutes)',
      GAME: 'Game',
      TOTAL: 'Total',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Activity Logs',
      EXECUTED_GAME: 'Executed Game',
      ADDED: 'Added: ',
      EXECUTED_SESSION: 'Executed Session',
    },
    SESSION: {
      MY_SESSIONS: 'My Sessions',
      SESSION_COMPLETE: 'You completed the session',
      ABANDONED: 'Abandoned',
      SKIPPED: 'Skipped',
      PLAYED: 'Played',
      PENDING: 'Pending',
      ASSIGNED_SESSIONS: 'Assigned Sessions',
      DEFAULT_PUBLIC_INFO:
        'Hello! This is a session created just for you! Please complete it or contact your health practitioner if you have further questions.',
      DOCTOR_NOTES: "Health Professional's Message",
      SAMPLE_DOCTOR_NOTES:
        'Dear {{name}}, this is a session created just for you! Please complete it or contact your health practitioner if you have further questions.',
      QUESTS: 'Quests',
    },
    STATUS: {
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
      INVITED: 'Invited',
    },
    SESSION_STATUS: {
      ACTIVE: 'Active',
      ASSIGNED: 'Assigned',
      CLOSED: 'Closed',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Reseller',
      DEMO: 'Demo',
      PAID: 'Paid',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'System Admin',
      ROLE_ORGANIZATION_OWNER: 'Organization Owner',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Organization Admin',
      ROLE_HEALTH_PROFESSIONAL: 'Health Professional',
      ROLE_PATIENT: 'Beneficiary',
      ROLE_INTERNAL_CONTACT: 'Internal Contact',
      ROLE_EXTERNAL_CONTACT: 'External Contact',
      ROLE_HEALTH_PROFESSIONAL_OWNER: 'Organization Owner/Health Professional',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Organization Admin/Health Professional',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Male',
      FEMALE: 'Female',
      OTHER: 'Other',
      NO_ANSWER: 'Prefer not to indicate',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Hello Admin',
      OVERVIEW_DESCRIPTION: 'Have a look at your numbers',
      EXECUTIONS: 'Executions',
      HOURS: 'Hours',
      BENEFICIARIES: 'Beneficiaries',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      MOST_PLAYED: 'Most Played',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Latest Updates on Games',
      LEAST_PLAYED: 'Least Played',
      ACTIVE_LAST_30_DAYS: 'Active last 30 days',
      GAMES_ACTIVITY: 'Games Activity',
      GAMES_ACTIVITY_DESCRIPTION:
        'Total Executions per Game and Cognitive Skill',
      AVERAGE: 'Total',
      LAST_UPDATE: 'Last Update: ',
      HOUR_SHORT: 'h',
      MINUTE_SHORT: 'm',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Number of Health Professionals',
      NUMBER_OF_BENEFICIARIES: 'Number of Beneficiaries',
      DURATION: 'Duration',
      START_DATE: 'Start Date',
      EXTENSION_DAYS: 'Extension Days',
      END_DATE: 'End Date',
      EXTENSION_DATE: 'Extension Date',
      STARTING_LICENSE: 'Starting License',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Support Services',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Beneficiary',
      TOTAL_COST_OF_BENEFICIARIES: 'Total Cost of Beneficiaries',
      TOTAL_COST_OF_SUBSCRIPTION: 'Total Cost of Subscription',
      ORGANIZATION_TYPE: 'Organization Type',
      SUBSCRIPTION_TYPE: 'Subscription Type',
      MONTHS: 'Months',
      DAYS: 'Days',
      REMAINING_DAYS: 'Remaining Days',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      BENEFICIARIES: 'Beneficiaries',
      NOTES: 'Notes',
      DURATION_OF_SUBSCRIPTION: 'Duration of Subscription',
      COSTS_VAT_DISCLAIMER: 'All costs do not include VAT, where applicable.',
      ACCEPT_MODAL_FOOTER:
        'If you do not want to confirm the subscription, please ignore or email us for more info at ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        "You cannot access Eligence, since your organization's subscription is not active. For more information, contact the Eligence team.",
      DAYS_LEFT: 'days left',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'New',
      AMENDMENT: 'Amendment',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Active',
      EXPIRED: 'Expired',
      PENDING_CONSENT: 'Pending Consent',
      PENDING_AUTOMATION: 'Pending Automation',
      REJECTED: 'Rejected',
      TERMINATED: 'Terminated',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Assigned Questionnaires',
      SECTION: 'Section',
      QUESTION: 'Question',
      NOTE: 'Note',
      BY: 'by',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Platform Generated',
      USER_GENERATED: 'User Generated',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Assigned',
      IN_PROGRESS: 'In Progress',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Free Text',
      INTEGER: 'Numeric',
      CHECKBOX: 'Multiple Choice',
      RADIO: 'Single Choice',
      DROPDOWN: 'Dropdown',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Questionnaire is a recommended tool provided to you by the Eligence platform. Through the Questionnaire you can collect information regarding a beneficiary or ask for information to assess the status of the beneficiary.',
      PROMPT:
        'When the questionnaire is assigned to the beneficiary, all free games and sessions will be disabled until the beneficiary completes it.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Create Beneficiary',
      TITLE_MEMBER: 'Create Member',
      TITLE_GUEST: 'Create Guest',
      CREDENTIALS: 'Credentials',
      PERSONAL_DETAILS: 'Personal Details',
      COMPLETION: 'Completion',
      CHECK_AVAILABILITY: 'Check availability',
      USERNAME_AVAILABLE: 'Username available',
      USERNAME_UNAVAILABLE: 'Unavailable, try again',
      OTP_SAVE_WARNING: 'Save the password to use later.',
      DONE: 'You’re all set!',
      DONE_DESCRIPTION:
        'A new beneficiary account has been created. During the first login, the beneficiary will be asked to change the password generated.',
      DONE_DESCRIPTION_GUEST: 'A new guest has been created.',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'For Groups',
      FOR_TWO: 'For Two',
      INTERGENERATION: 'Between Generations',
      CHALLENGING: 'Challenging',
    },
    GAMES: {
      MY_GAMES: 'My Games',
      ALL_GAMES: 'All',
    },
    STAYING_STATUS: {
      ALONE: 'I live alone',
      WITH_HUSBAND_WIFE: 'I live with my partner',
      WITH_KIDS_GRANDKIDS: 'I live with my children/grandchildren',
      WITH_CARER: 'I live with my caregiver',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'View all',
      ONLY_SESSIONS: 'Only sessions',
      ONLY_GAMES: 'Only games',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Assigned',
      UNASSIGNED: 'Unassigned',
    },
    GAME_ACCESS: {
      PUBLIC: 'Public',
      PRIVATE: 'Private',
    },
    PRIVACY_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Privacy Policy</h2><br><h2>Introduction</h2><p>The software service “Eligence” (“Service”) is operated by “Maggioli SPA – Greek Branch (“Provider”) on resources provided by “Maggioli SPA – Greek Branch”.</p><p>“Maggioli SPA – Greek Branch” (“Provider”) is a software private Company with full name Maggioli SPA – Greek Branch est. in Marousi on 21 Sep 2020, its headquarters located Andrea Papandreou 19 Marousi, 15124, Attica, Greece.</p><p>Protecting your personal data is very important to us. Our Privacy Policy is intended to help you understand why we collect your personal information and how we use it. It provides detailed information about when and why we collect your personal information, how we use and process it, how long we keep it, and finally, under what terms we can share it with others.</p><h2>1. Scope</h2><p>This policy applies to all of you who access and use our Service.</p><p>This Privacy Policy applies solely to personal data and information that the Service collects through its usage or through any electronic communication of the User with the Provider, as indicated on the Service (herein referred to as “Personal Data”).</p><p>We may also collect information from you in other ways, including information collected during technical support contacts. If we provide a separate or supplemental notice when we collect personal data from you, that notice will control to the extent of any conflict.</p><h2>2. Information Collected</h2><p>The Service manages different types of data, all in compliance with the current European legislation on Data Protection. Any Data concerning the User is collected to allow the Provider to provide the services.</p><h2>Required Data</h2><u>Personal Data</u><br><br><p>The provision of the Service requires that certain pieces of personally identifiable information are processed. Personal data of yours we process:</p><ul><li>name</li><li>address</li><li>email address</li><li>telephone number</li></ul><u>Cookies</u><br><br><p>Any Cookies or other tracking tools used by this Service, or by Other Providers of third-party services used by or through this Service, serve the purpose of providing the service required by the User, in addition to any other purposes described in the present document and in the specific Policy for Cookies, if such a document is made available.</p><h2>3.	Child use</h2><p>If you are aged 16 or under, please get your parent/guardian’s permission before you provide any personal information to us. Children may use Eligence with the consent of their parents or guardians. </p><p>All information provided by all children under the age of 16 will be treated with respect to their rights. </p><p>We recognize the need to provide further privacy protections with respect to children’s personal information we may collect. When we intend to collect information from children, we take additional steps to protect children’s privacy, including: </p>    <ul><li>In accordance with applicable law, and our practices, obtaining consent from parents for the collection and use of their children’s personal information;</li><li>Notifying parents about our information practices with regard to children;</li><li>Limiting our collection of personal information about children to no more than what is reasonably necessary.</li><li>Giving parents access or the ability to request access to personal information we have collected about their children and the ability to request the personal information be changed or deleted.</li></ul><p>If we learn that we have inadvertently collected the personal information of a child under 16, or equivalent minimum age depending on the jurisdiction, we will take steps to delete the information as soon as possible. </p><h2>4. Use of Personal Data</h2><p>The Service uses Personal Data for the following purposes:</p><ul><li><b>Fulfilment of requests:</b> The Service uses Personal Data to deal with inquiries, register to third-party Services, contact the user, deliver notifications, charge and bill the user etc.</li><li><b>Service operation:</b> The Service uses cookies to identify users, get information about location and client device in order to adapt / grant its capabilities, grant access to specific Service areas, grant access to relevant information, filter content etc.</li><li><b>Statistical analysis:</b> Aggregated data about Service usage (which do not identify a specific user), such as the number of users who have visited certain pages of the Service, or how long users are spending on a particular page, are used to feed statistics as to the use of the Service.</li><li><b>Internal business purposes:</b> The Provider uses the collected information for internal business purposes, such as for audits or to track service feature use and behaviour, justification of resource usage and funding, extraction of business KPIs etc.</li><li><i><strong>Service and products design:</strong></i> Aggregated and Personal Data are used by the Provider so that improvements, adjustments and refinements are performed, as well as new Services and Products are designed to address general or user-specific needs.</li><li><i><strong>Displaying User information:</strong></i> Data concerning the User are presented by the service to allow Users to identify ownership, provenance and allocation of various resources.</li></ul><p>Our Service guarantees that your personal data will not be used for purposes other than those set forth in this policy, without prior notice and where your approval is required.</p><p>The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated.</p><p>The Provider considers User Personal Data as an asset that is not for sale and will never sell User Personal Data to any third-party.</p><h2>5. Recipients of personal data</h2><p>Access to personal data and transaction information is only authorized by employees, affiliates and third parties who process the above data at the Provider’s discretion and only when and to the extent necessary for the above purposes. Personal data may only be transmitted, for the purposes of the above processing, to specific recipients who are employees, and generally affiliates as well as third parties affiliated with the Provider. In addition, the Provider may, without prior notice, disclose your information to the competent judicial and/or administrative authorities to the extent required by applicable laws and regulations, or by judicial decision and/or administrative act.</p><p>The Provider makes every effort to control and evaluate when selecting its affiliates to whom it transmits the personal data of those concerned. There is a written agreement between the Provider and any third party, according to which the processing of personal data is carried out under the control of the Provider and only on its order and is subject to the same data protection policy.</p><h2>6. Data retention time</h2><p>The time period for storing data is decided on the basis of the following specific criteria, as appropriate:</p><ul><li>Where processing is required by provisions of the applicable legal framework, your personal data will be stored for as long as the relevant provisions require</li><li>When processed on a contract basis, your personal data is stored for as long as necessary for the performance of the contract and for the foundation, exercise, and/or support of legal claims under the contract.</li><li>For other purposes, your personal information is kept until your consent is withdrawn. This can be done at any time. Withdrawal of consent does not affect the legality of the consent-based treatment during the period prior to its withdrawal. You can revoke your consent at any time by selecting the link provided in the emails we send to you.</li></ul><h2>7. Your Rights and Choices</h2><p>As defined in the Regulation (EU) 2016/679 (General Data Protection Regulation), User (data subject) has the following Rights:</p><ul><li><b>Right to have access</b> to the Personal Data that is held about you by the Provider – what data we have collected, for what purpose, how it is processed and how long it is stored (article 15).</li><li><b>Right to rectification</b> (article 16). You have the right to obtain from the Provider the rectification of inaccurate personal data and to have incomplete personal data completed.</li><li><b>Right to erasure</b> (‘right to be forgotten’) (article 17). You have the right to obtain from the Provider the erasure of personal data concerning you.</li><li><b>Right to restriction of processing</b> (article 18). You shall have the right to obtain from the Provider restriction of processing where one of the following applies: (a) the accuracy of the personal data is contested (b) the processing is unlawful (c) the Provider no longer needs the personal data for the purposes of the processing.</li><li><b>Notification obligation regarding rectification or erasure of personal data or restriction of processing by the controller</b> (article 19). The Provider will communicate any rectification or erasure of personal data or restriction of processing carried out to each recipient to whom the personal data have been disclosed, unless this proves impossible or involves disproportionate effort. The Provider shall inform you about those recipients if you requests it.</li><li><b>Right to data portability</b> (article 20). You have the right to receive the personal data concerning you, in a structured, commonly used and machine-readable format and have the right to transmit those data to another Party without hindrance from the Provider.</li><li><b>Right to object</b> (article 21). You have the right to object to processing of your personal data. The Provider shall no longer process the personal data unless the Provider demonstrates compelling legitimate grounds for the processing which override the interests, rights and freedoms of the data subject or for the establishment, exercise or defence of legal claims.</li></ul><p>Before we are able to provide you with any information or correct any inaccuracies, we may ask you to verify your identity and/or provide other details to help us respond to your request.</p><p>The Provider reserves the right not to respond to requests generated through third-party applications or automated processes without direct validation of the requests by data subjects using the resources provided by the Service for the exercise of these rights as described in this Policy.</p><h2>8. Data security</h2><p>The Provider takes care to guard the security of your personal data. We apply appropriate physical, technical and organizational measures that are reasonably designed to protect personal data against accidental or unlawful destruction, loss, alteration, unauthorized disclosure or access, and against all other unlawful forms of processing. We maintain a security program that is proportionate to the risks associated with the processing.</p><h2>9. Location of Personal Data Storage</h2><p>The Service is provided via its project managed instance, whose servers are located in Greece, and provided by “Maggioli SPA – Greek Branch”.</p><h2>10. Law enforcement – compliance</h2><p>The Provider may use or disclose Personal Data to any third-party (a) if required to do so by law; (b) to comply with legal processes or respond to requests from governmental or public authorities; (c) to prevent, investigate, detect, or prosecute criminal offenses or attacks on the technical integrity of the Service or network; (d) to enforce Terms and Conditions; or (e) to protect the rights, privacy, property, business, or safety of the Provider, its business partners, employees, members, Service Users, or the public. Unless prohibited by applicable law, the Provider shall inform the User if a third-party requests access to Personal Data about the User.</p><h2>11. Policy modification</h2><p>This privacy policy may be modified. We will be sure to keep you informed of any changes, but in any event we invite you to visit our website regularly, where the most up-to-date Privacy Policy will be posted.</p><h2>12. Exercise of your Rights, Inquiries, Objections, Complaints</h2><p>For exercising your rights, or for any questions, comments, objections or complaints, regarding this Privacy Policy or privacy, security or data protection practices applied, please contact the Provider by email via its designated Data Protection Officer (dpo@eligence.eu).</p><p>We handle your requests with the utmost care to ensure that your rights are protected. For any requests that may require assumption or disclosure of Personal Data, the User will have to demonstrate legitimate grounds for making the respective requests, as well as provide sufficient evident for the identity of the User.</p><p>In some cases we may not be able to process your request directly. However, in any event we will inform you of the progress of your request within one month of the submission of your original request.</p><p>You always have the right to complain to the “Hellenic Data Protection Authority (www.dpa.gr)”, if you are concerned about how we have processed your personal data.</p>',
    },
    TERMS: {
      TEST: '<h1>Eligence</h1><h2>Terms of Use</h2><br><h2>Disclaimer</h2><p>Welcome to “Eligence”. “Eligence” (hereinafter referred to as “Service”) is a web-platform with specialized content (games) aiming to reinforce mental capabilities and cognitive function. Together with health professionals it can provide exercises to people at the early stages of dementia, as well as for logotherapy or ergotherapy purposes. </p><p>Please read and understand these Terms (the “Terms”) before using this Service. By using this Service, you accept and agree to be bound and abide by the following Terms. If you do not agree with these Terms, you should not access or use this Service.  </p><p>Users are individuals who uses and operates the Service.</p><p>To make use of the service you have to 1) be an adult with full legal capacity, or 2) a minor (<18 years old) who has obtained written consent by your parent or legal guardian, or 3) if you lack full legal capacity to have/produce the approval of your legal guardian.</p><p>“Eligence” reserves the right to change, edit, or delete any documents, information, or other content appearing on these Terms from time to time without notice and in its sole discretion. All changes are effective immediately when posted and apply to all access to, and use of, this Service thereafter. Every time you wish to use the Service, please review these Terms to ensure that you understand the terms that may apply to you at that time.</p><p>This Service is operated by “Maggioli SPA – Greek Branch” (“Provider”) on resources provided by Maggioli. Elements of the Service (“Service Elements”), such as technology, algorithms, documents, data, other services, processes and other resources, may have been or may be currently provided by the Provider or by third parties (“Other Providers”). The Provider and Other Providers shall be collectively called “Providers”.</p><p>The Service itself, as well as any data or information or other elements that may become accessible through the Service, are provided on an "as is" and "as available" basis. The Provider puts effort to ensure the accuracy, completeness or authenticity of the processes, data and information managed and provided by the Service.</p><p>The Provider reserves the right to alter, limit or discontinue any part of this Service at its discretion. The same applies to Other Providers, unless otherwise explicitly declared. </p><p>The Provider does not claim any ownership and does not undertake any responsibility on data, information, content, comments, code, processes, or other elements uploaded or embedded into the Service by other Users, if such functionalities are offered by the Service. The Users are responsible for protecting their assets and personal data from any such Element present in the Service.</p><p>To the best of Provider’s intention reasonable security measures consistent with practice applicable to the domain of Service operation are applied to protect sensitive information under its control against loss, misuse, and alteration. However, the Provider cannot guarantee the security of physical locations, the hardware, software and networks, the means by which sensitive information is handled and transmitted between computers and applications, or any sensitive information that may be received through or in connection with the Service. </p><h2>Copyright</h2><p>The Provider reserves all rights of the elements it provides.</p><p>Elements of the Service (“Service Elements”) have been provided by third parties (“Other Providers”) without restrictions of rights.</p><p>The GODOT software is provided "as is", without warranty of any kind, expressed or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damage, or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.</p><h2>License</h2><p>Users granted access via the process established by the Provider, are licensed to use of the Service under the terms of the license.</p><p>The Provider grants license to use this Service freely to its Users, under the terms of this document. Access to the Service though may be limited due to availability of underlying resources. The Provider may revoke this License or change its terms at its own discretion without prior notice to the Users.  It is to the best of Provider’s intention to try to timely inform Users accessing the Service before such an action, however this is not guaranteed.</p><p>Users are required to make a clear reference to the Service use for any products or services that may be created on top of results or use of this Service.</p><p>At any time and without prior notice, the Provider may limit access to the Service to any person, geographic area, or jurisdiction that the Provider chooses, at Provider’s sole discretion.</p><h2>Use of Service</h2><p>The Provider does not represent or warrant that the Service is appropriate or available for use in any particular jurisdiction. Users who subscribe to the Service do so on their own initiative and at their own risk, and are responsible for complying with all local laws, rules, and regulations that apply to them.</p><p>By using the Service, the User agrees to all terms of the “Terms of Use” document as this may be formed and applies at any point in time. </p><p>By using the Service, the Users agree that they are entitled to use the Service under the terms presented by the Provider upon request for access to the Service or as those may be presented explicitly in the section of the document “License”.</p><p>Under no circumstances shall a User use the Service for conducting any malicious activity, which may indicatively and not exclusively refer to: access to or exposure of personal or confidential data of other parties or Users, delivery of malicious code to other Users or systems, intentional overloading of Service or Providers’ resources, any action causing denial-of-service for the Service or any third party service or resource, impersonation of Provider, its personnel or any Users, inflict impact on financial or social status of Provider, its personnel or Users etc.</p><p>The User commits to use resources provided by the Service, and the Service itself for no other reason and by no other means than the ones intended by the Service. In case of uncertainty of the validity of a use, the User commits to request further information from the Provider before performing such a use.</p><p>The Users commit to promptly inform the Provider about any vulnerabilities or issues they have identified or have been informed about, during the use of the Service.</p><p>The Users commit to promptly inform the Provider of any malicious, or otherwise inappropriate data, information, comments, code, processes, or other element made available on the Service that they become aware off.</p><p>The Users are responsible for managing their own credentials and the safety of his/her account. The Users shall notify the Provider as soon as they become aware of unauthorized use of their account.</p><p>The Provider reserves the right to take any legal action upon Service misuse to protect the interests of itself as well as of its Users. The Provider may proactively terminate a User’s account and associated access to the Service without any warning, to prevent the Service, its resources or other Users from suspected erroneous or malicious actions from the User or anyone impersonating the User.</p><p>The Provider may alter the “Terms of Use” of the Service, without prior notice. It is to the best of the Provider’s intentions to notify the User for essential changes in this document or documents that that may be addressed by it, however this is not guaranteed.</p><p>The User will be held liable for compensating the Provider if any claims to the Provider rise from breaching any term of this “Terms of Use” document by the User. Such compensation may include and is not limited to penalties that may apply, third party damage claims, Provider’s ethical and financial damage, Provider’s effort and legal expenses and any other related costs.</p><h2>Effectiveness</h2><p>If any part of this “Terms of Use” document is ineffective for any reason (e.g. unlawful or overridden by other document), the rest of the agreement remains valid excluding the ineffective part.</p><p>This “Terms of Use” document is between the Provider and the User and under no circumstances may it be transferred to any third party by the User.</p><p>Neither the User nor the Provider may be held liable for any breach of the terms of this License occurring due to conditions outside their respective reasonable control (“Force Majeure”).</p><p>The Provider may refrain from exercising rights of this “Terms of Use” document for any reason the Provider may choose, at any situation and point in time. This shall not be assumed as a withdrawal from the right to exercise its respective rights in the future for the same, similar or different cases.</p><h2>Your Agreement to the Terms</h2><p><b><u>Your access or use of the Service or/and any resource provided by or accessed through it, in any way signifies that you have read, understood and agreed to be bound by the terms of this document.</u></b></p>',
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Cooke Policy</h2><br><h2>Cookie List</h2><p>A cookie is a small piece of data (text file) that a website – when visited by a user – asks your browser to store on your device in order to remember information about you, such as your language preference or login information. Those cookies are set by us and called first-party cookies. We also use third-party cookies – which are cookies from a domain different than the domain of the website you are visiting – for our advertising and marketing efforts.</p><h2>Manage cookie settings</h2><p>On any page of the site, by clicking on the button on the bottom left corner the cookie banner will open and it will be possible to modify and reset your preferences; selecting “accept all cookies” you give the consent to use of all types of cookies, while you can withdraw your consent by clicking on “Refuse all cookies”. By deciding to close the banner, the preferences previously given will be kept until further modification. Opening the banner you can manage consents for the various types of cookies on the basis your preferences.</p><h2>Necessary Cookies</h2><p>These cookies are necessary for the website to function and cannot be switched off in our systems. Any Cookies or other tracking tools used by this Service, or by Other Providers of third-party services used by or through this Service, serve the purpose of providing the service required by the User, in addition to any other purposes described in the Privacy Policy.</p><h2>Analytics cookies</h2><p>Analytics cookies are cookies that track how users navigate and interact with this Service. The information collected is used to help the Service ‘s owner improve the Service.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
