export const locale = {
  lang: 'es',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE:
        'Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      USERNAME_NOT_FOUND_EXCEPTION: 'No se pudo encontrar el nombre de usuario',
      USER_LOGIN_EXCEPTION:
        'El nombre de usuario o la contraseña no son válidos',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION:
        'Correo electrónico o contraseña no válidos',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        'El usuario ya existe en la organización',
      USER_REGISTRATION_EXCEPTION:
        'Se ha producido un error al registrar al usuario',
      PASSWORD_RESET_LINK_EXCEPTION:
        'Se ha producido un error al generar el enlace para restablecer la contraseña',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        'La cuenta con esta información aún no se ha activado. No se puede activar el restablecimiento de contraseña',
      PASSWORD_RESET_EXCEPTION:
        'Se ha producido un error al restablecer su contraseña',
      MAIL_SEND_EXCEPTION:
        'Se ha producido un error al enviar el correo electrónico',
      UPDATE_PASSWORD_EXCEPTION: 'Contraseña actual no válida',
      TOKEN_REFRESH_EXCEPTION:
        'No se ha podido actualizar su token de autorización',
      USER_LOGOUT_EXCEPTION: 'Se ha producido un error al cerrar su sesión',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        'No tiene autorización para acceder a este recurso',
      FORBIDDEN_EXCEPTION: 'No tiene autorización para acceder a este recurso',
      UNAUTHORIZED_EXCEPTION:
        'No tiene autorización para acceder a este recurso',
      IP_BLOCKED_EXCEPTION:
        'Se le ha bloqueado temporalmente debido a múltiples intentos de inicio de sesión',
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        'La dirección de correo electrónico que ha facilitado ya está en uso',
      FILE_GENERIC_EXCEPTION:
        'Error de archivo. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        'Argumento no válido. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      APP_EXCEPTION:
        'Algo salió mal. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        'El recurso ya está en uso. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      RESOURCE_NOT_FOUND_EXCEPTION:
        'Recurso no encontrado. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      FILE_NOT_FOUND_EXCEPTION:
        'Archivo no encontrado. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      BAD_REQUEST_EXCEPTION:
        'Solicitud incorrecta. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        'Tipo de soporte no aceptable. Póngase en contacto con el servicio técnico o inténtelo de nuevo más tarde',
      SESSION_EXPIRED_EXCEPTION:
        'Su sesión ha caducado. Vuelva a iniciar sesión',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        'No está activo en ninguna organización. Significa que uno de los administradores de su organización le ha desactivado. Contacte con esa persona directamente',
      PASSWORD_MISMATCH_EXCEPTION: 'Las contraseñas no coinciden.',
      ORGANIZATION_NAME_CONFLICT: 'Ya existe una organización con este nombre.',
      ORGANIZATION_WEBSITE_CONFLICT:
        'Ya existe una organización con este sitio web.',
      ORGANIZATION_PHONE_CONFLICT:
        'Ya existe una organización con este teléfono.',
      ORGANIZATION_EMAIL_CONFLICT:
        'Ya existe una organización con este correo electrónico.',
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        'No puede invitar a ningún profesional sanitario. Ha alcanzado el límite de su suscripción.',
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        'No puede invitar a ningún beneficiario. Ha alcanzado el límite de su suscripción.',
      ORGANIZATION_VAT_CONFLICT: 'Ya existe una organización con este IVA.',
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'La organización no ha aceptado la suscripción.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'La organización no tiene ninguna suscripción activa o pendiente.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'La organización está inactiva.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'El usuario no está verificado en la organización',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'Ya existe una suscripción para estas fechas.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'No puede realizar ninguna acción en este cuestionario porque no fue creado por su organización.',
      BENEFICIARY_ALREADY_HAS_QUESTIONNAIRE:
        'Ya existe un cuestionario para este beneficiario.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        'Ya existe un cuestionario para este usuario.',
      QUESTIONNAIRE_IS_EMPTY:
        'Para asignar un cuestionario, debe crear al menos una pregunta',
    },
    ROUTES_TITLE: {
      HOME: 'Inicio',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'Administradores del sistema',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      BENEFICIARIES: 'Beneficiarios',
      MEMBERS: 'Miembros',
      MEMBER_PROFILE: 'Perfil de miembro',
      GUESTS: 'Invitados',
      GUEST_PROFILE: 'Perfil de invitado',
      MY_PROFILE: 'Mi perfil',
      USER_PROFILE: 'Perfil de usuario',
      ORGANIZATIONS: 'Organizaciones',
      ORGANIZATION_PROFILE: 'Perfil de la organización',
      GAMES: 'Juegos',
      GAME_MANAGEMENT: 'Administración del juego',
      GAME_OVERVIEW: 'Visión general de los juegos',
      SESSION_TEMPLATES: 'Plantillas de sesiones',
      SESSIONS_BY_ELIGENCE: 'Sesiones de Eligence',
      SESSION_TEMPLATE: 'Plantilla de sesión',
      QUESTIONNAIRE_TEMPLATES: 'Plantillas de cuestionarios',
      QUESTIONNAIRES_BY_ELIGENCE: 'Cuestionarios de Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Plantilla de cuestionario',
      ASSIGNED_SESSION: 'Sesión asignada',
      ASSIGNED_QUESTIONNAIRE: 'Cuestionario asignado',
      ADD_SESSION: 'Añadir sesión',
      CREATE_BENEFICIARY: 'Crear beneficiario',
      CREATE_MEMBER: 'Crear miembro',
      CREATE_GUEST: 'Crear invitado',
      SUBSCRIPTIONS_MANAGEMENT: 'Administración de suscripciones',
      ELIGENCE_SESSION_TEMPLATES: 'Sesiones',
      RESELLERS: 'Distribuidores',
      RESELLER_PROFILE: 'Perfil de distribuidor',
      GROUPS: 'Grupos',
      CREATE_GROUP: 'Crear grupo',
      GROUP_PROFILE: 'Perfil de grupo',
      ADD_MEETING: 'Iniciar nueva reunión',
      EDIT_GROUP: 'Editar grupo',
      GAME_VARIATIONS: 'Variaciones de juego',
    },
    CONFIRM: {
      DELETE: '¿Desea realmente borrar este {{name}}?',
      CREATE: '¿Desea realmente crear un nuevo {{name}}?',
      EDIT: '¿Desea realmente editar este {{name}}?',
      CHANGE: '¿Desea realmente guardar los cambios?',
      ACTIVATE: '¿Desea realmente activar este usuario?',
      ACTIVATE_ORGANIZATION: '¿Desea realmente activar esta organización?',
      DEACTIVATE: '¿Desea realmente desactivar este usuario?',
      DEACTIVATE_ORGANIZATION: '¿Desea realmente desactivar esta organización?',
      INVITATION: '¿Desea realmente reenviar la invitación para este usuario?',
      INVITATION_ORGANIZATION:
        '¿Desea realmente reenviar la invitación para esta organización?',
      BOOK: '¿Desea realmente reservar este {{name}}?',
      CANCEL_BOOKING: '¿Desea realmente cancelar la reserva con este usuario?',
      UPDATE_MAIL_WARNING:
        '¿Desea realmente cambiar su dirección de correo electrónico? Tenga en cuenta que su nombre de usuario será su nuevo correo electrónico.',
      ACTIVATE_GAME: '¿Desea realmente activar este juego?',
      ACTIVATE_GAME_TEMPLATE:
        '¿Desea realmente activar esta categoría de juegos?',
      DEACTIVATE_GAME: '¿Desea realmente desactivar este juego?',
      DEACTIVATE_GAME_WARNING:
        'Este juego está actualmente asignado en {{sessions}} sesiones, {{beneficiaries}} beneficiarios, {{sessionTemplates}} plantillas de sesiones, {{systemAssignedSessions}} sesiones de Eligence, {{systemSessionTemplates}} plantillas de sesiones de Eligence, {{groupAssignedSessions}} sesiones de grupo. ¿Desea realmente desactivarlo?',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'Esta categoría de juegos está actualmente asignada en {{sessions}} sesiones, {{beneficiaries}} beneficiarios, {{sessionTemplates}} plantillas de sesiones, {{systemAssignedSessions}} sesiones de Eligence, {{systemSessionTemplates}} plantillas de sesiones de Eligence, {{groupAssignedSessions}} sesiones de grupo. ¿Desea realmente desactivarlo?',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'Este juego está actualmente asignado en {{sessions}} sesiones activas, {{systemAssignedSessions}} sesiones de Eligence, {{groupAssignedSessions}} sesiones de grupo. ¿Desea realmente desactivarlo?',
      REMOVE_PATIENT:
        '¿Desea realmente eliminar a este beneficiario de este profesional sanitario?',
      CLOSE_SESSION: '¿Desea realmente cerrar esta sesión?',
      DELETE_SESSION: '¿Desea realmente borrar esta sesión?',
      DELETE_QUESTIONNAIRE: '¿Desea realmente borrar este cuestionario?',
      REMOVE_HEALTH_PROFESSIONAL:
        '¿Desea realmente eliminar a este profesional sanitario de este beneficiario?',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        '¿Están los juegos en el orden de aparición preferido? ¿Ha elegido el nivel de dificultad deseado por juego?',
      CANCEL: '¿Desea realmente cancelar este {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Al borrar una sección también se borrarán todas las preguntas de dicha sección. ¿Desea realmente continuar?',
    },
    SUCCESS: {
      CREATE: '{{name}} se creó correctamente',
      EDIT: '{{name}} se editó correctamente',
      UPDATE: '{{name}} se actualizó correctamente',
      DELETE: '{{name}} se borró correctamente',
      ADD: '{{name}} se añadió correctamente',
      ASSIGN: '{{name}} se asignó correctamente',
      ACTIVATE: '{{name}} se activó correctamente',
      REQUEST: 'La solicitud {{name}} se envió correctamente',
      DEACTIVATE: '{{name}} se desactivó correctamente',
      REGISTER:
        'Se ha registrado correctamente. Se le enviará un correo electrónico a su dirección de correo electrónico para definir su contraseña',
      CLONE: '{{name}} se clonó correctamente',
      CLOSE: '{{name}} se cerró correctamente',
      CANCEL: '{{name}} se canceló correctamente',
      INVITE: 'Se invitó a {{name}} correctamente',
      RESET: 'Su contraseña se ha restablecido correctamente',
      FORGOT:
        'Se ha enviado un correo a su dirección de correo electrónico. Siga las instrucciones para restablecer su contraseña',
      REMOVE: '{{name}} se eliminó correctamente',
      PASSWORD_CHANGE: 'Su contraseña se ha cambiado correctamente',
      AMEND: '{{name}} se modificó correctamente',
      RESEND: '{{name}} se reenvió correctamente',
      RESET_OTP: 'Contraseña de un solo uso restablecida correctamente.',
      UPGRADE: '{{name}} se actualizó correctamente',
      GAME_CACHE_CLEAR: 'La memoria caché del juego se borró correctamente',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Añadir organización',
      ADD_PATIENT: 'Añadir beneficiario',
      ADD_MEMBER: 'Añadir miembro',
      INVITE_MEMBER: 'Invitar a un miembro',
      ADD_GUEST: 'Añadir invitado',
      ADD_HEALTH_PROFESSIONAL: 'Añadir profesional sanitario',
      ADD_ORGANIZATION_ADMIN: 'Añadir administrador de la organización',
      ORGANIZATION: 'Organización',
      HEALTH_PROFESSIONAL: 'Profesional sanitario',
      ASSIGN_PATIENTS: 'Asignar beneficiarios',
      ASSIGN_HEALTH_PROFESSIONALS: 'Asignar profesionales sanitarios',
      ASSIGN_MEMBERS: 'Asignar miembros',
      ASSIGN_GUESTS: 'Asignar invitados',
      PATIENT: 'Beneficiario',
      EDIT_PROFILE: 'Editar perfil',
      SELECT_ORGANIZATION: 'Seleccionar organización',
      UPLOAD_FILE: 'Cargar un archivo para ',
      GAME_FILE: 'Archivo de juego',
      ALLOWED_FILE_TYPES: 'Tipos de archivo permitidos: zip',
      UPDATE_PASSWORD: 'Actualizar contraseña',
      CREATE_SESSION: 'Crear sesión',
      ASSIGN_SESSION_TEMPLATE: 'Asignar plantilla de sesión',
      SUBSCRIPTION_DETAILS: 'Detalles de la suscripción',
      INACTIVE_SUBSCRIPTION: 'No activar suscripción',
      EDIT_INFORMATION: 'Editar información',
      INVOICE_INFO: 'Información de facturación',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Añadir plantilla de cuestionario',
      QUESTIONNAIRE_TEMPLATE: 'Plantilla de cuestionario',
      WARNING: 'Advertencia',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'Para asignar un cuestionario, debe crear al menos una pregunta.',
      ADD_NOTE: 'Crear nota',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Asignar plantilla de cuestionario',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        'Para previsualizar un cuestionario, debe tener al menos una sección y una pregunta.',
      RESET_PASSWORD: 'Restablecer contraseña de un solo uso (OTP)',
      GENERATE_REPORT: 'Generar informe',
      ACTIVITY_DISPLAY_OPTIONS: 'Opciones de visualización de actividades',
      UPGRADE_ORGANIZATION: 'Actualizar organización',
      ADD_RESELLER_ADMIN: 'Añadir administrador',
      GAME_VARIATIONS: 'Variaciones de juego',
      ASSIGN_PRIVATE_GAME: 'Asignar juego privado',
      ASSIGN_PUBLIC_GAME: 'Asignar juego público',
      MEETING_MEMBERS: 'Miembros de la reunión',
    },
    ERROR: {
      IMAGE: 'El archivo que ha seleccionado no es una imagen',
      RESOURCE: 'No puede acceder a este recurso si ya ha iniciado sesión',
      GENERAL:
        'Lo sentimos, parece que se han detectado algunos errores, inténtelo de nuevo',
      FILE: 'El archivo que ha seleccionado no es compatible',
      PAGE_NOT_FOUND: 'Página no encontrada',
      PAGE_NOT_FOUND_BODY: 'No se encontró la URL solicitada',
      USERNAME_UNAVAILABLE: 'El nombre de usuario no está disponible',
    },
    BUTTONS: {
      CREATE: 'Crear nuevo',
      CONFIRM_ACTION: 'Confirmar acción',
      ADD_EXERCISES: 'Añadir juegos',
      DELETE: 'Borrar',
      VIEW: 'Ver',
      APPLY: 'Aplicar',
      EDIT: 'Editar',
      BACK: 'Atrás',
      CANCEL: 'Cancelar',
      CONTINUE: 'Continuar',
      LOGIN: 'Iniciar sesión',
      REGISTER: 'Registro',
      SAVE: 'Guardar',
      SUBMIT: 'Enviar',
      ACTIVATE: 'Activar',
      DEACTIVATE: 'Desactivar',
      PLAY: 'Jugar',
      CONFIRM: 'Confirmar',
      ACCEPT: 'Aceptar',
      DECLINE: 'Rechazar',
      NEXT_STEP: 'Siguiente paso',
      PREVIOUS_STEP: 'Anterior',
      ADD: 'Añadir nuevo',
      RESET: 'Restablecer',
      UPLOAD_PHOTO: 'Cargar foto',
      EDIT_PHOTO: 'Editar foto',
      RESEND_INVITATION: 'Reenviar invitación',
      ASSIGN: 'Asignar',
      EDIT_PROFILE: 'Editar perfil',
      DISCARD: 'Descartar',
      DONE: 'Hecho',
      ADD_ORGANIZATION: 'Añadir organización',
      ADD_PATIENT: 'Añadir beneficiario',
      ADD_HEALTH_PROFESSIONAL: 'Añadir profesional sanitario',
      ADD_ORGANIZATION_ADMIN: 'Añadir administrador de la organización',
      ADD_SESSION: 'Añadir sesión',
      ADD_MEMBER: 'Añadir miembro',
      ADD_GUEST: 'Añadir invitado',
      ASSIGN_PATIENTS: 'Asignar beneficiarios',
      ASSIGN_HEALTH_PROFESSIONALS: 'Asignar profesionales sanitarios',
      ASSIGN_MEMBERS: 'Asignar miembros',
      ASSIGN_GUESTS: 'Asignar invitados',
      ACTIONS: 'Acciones',
      LOADING: 'Cargando...',
      GO_TO_HOMEPAGE: 'Ir a la página de inicio',
      ASSIGN_NEW_SESSION: 'Asignar nueva sesión',
      ASSIGN_NEW_QUESTIONNAIRE: 'Asignar nuevo cuestionario',
      CLOSE: 'Cerrar',
      SHOW_MORE: 'Mostrar más',
      SHOW_LESS: 'Mostrar menos',
      CONFIRM_SUBSCRIPTION: 'Confirmar suscripción',
      REJECT_SUBSCRIPTION: 'Rechazar suscripción',
      NEW_SUBSCRIPTION: 'Nueva suscripción',
      ADD_QUESTIONNAIRE: 'Añadir cuestionario',
      PREVIEW: 'Vista previa',
      ADD_ANSWER: 'Añadir opción',
      GOT_IT: 'Vale',
      ADD_NOTE: 'Añadir nota',
      EXPORT_RESULTS: 'Exportar resultados',
      SAVE_AND_CONTINUE: 'Guardar y continuar',
      RESET_ONE_TIME_PASSWORD: 'Restablecer contraseña de un solo uso',
      CREATE_BENEFICIARY: 'Crear beneficiario',
      CREATE_MEMBER: 'Crear miembro',
      CREATE_GUEST: 'Crear invitado',
      CHANGE_PASSWORD: 'Cambiar contraseña',
      COMPLETE: 'Completar',
      START_SESSION: 'Iniciar sesión',
      REPLAY: 'Reproducir',
      START_NOW: '¡Empezar ya!',
      GENERATE_REPORT: 'Generar informe',
      CLEAR_GAME_CACHE: 'Borrar memoria caché del juego',
      ADD_RESELLER_ADMIN: 'Añadir administrador',
      CREATE_GROUP: 'Crear grupo',
      ADD_MEETING: 'Iniciar nueva reunión',
      STOP: 'Finalizar reunión',
      START_MEETING: 'Iniciar reunión',
    },
    INPUT: {
      NAME: 'Nombre',
      EMAIL: 'Correo electrónico',
      EMAIL_USERNAME: 'Correo electrónico (nombre de usuario)',
      PLACE: 'Lugar',
      VAT: 'IVA',
      FIRST_NAME: 'Nombre de pila',
      STREET_ADDRESS: 'Dirección postal',
      LAST_NAME: 'Apellidos',
      FULL_NAME: 'Nombre completo',
      PASSWORD: 'Contraseña',
      PATIENT_LIST: 'Lista de beneficiarios',
      HEALTH_PROFESSIONAL_LIST: 'Lista de profesionales sanitarios',
      ORGANIZATION_NAME: 'Nombre de la organización',
      ORGANIZATION_EMAIL:
        'Correo electrónico de contacto de facturación de la empresa',
      ORGANIZATION_ACTIVITY: 'Actividad',
      CONFIRM_PASSWORD: 'Confirmar contraseña',
      CITY: 'Municipio',
      HEALTH_PROFESSIONAL: 'Profesional sanitario',
      POSTAL_CODE: 'Código postal',
      COUNTRY: 'País',
      ADDRESS: 'Dirección',
      COMPANY: 'Empresa',
      BIRTH_DATE: 'Fecha de nacimiento',
      WEBSITE: 'Sitio web',
      PHONE: 'Número de teléfono',
      ROLE: 'Rol',
      SERVICE: 'Servicio',
      PREFERRED_LANGUAGE: 'Idioma preferido',
      PREFERRED_ACCOUNT_TYPE: 'Tipo de cuenta preferido',
      ADDRESS_INFO: 'Información de dirección',
      COMPANY_NAME: 'Razón social',
      DESCRIPTION: 'Descripción',
      TYPE: 'Tipo',
      PRICE: 'Precio',
      FEATURES: 'Características',
      TITLE: 'Título',
      TAGS: 'Etiquetas',
      ACCOUNT_STATUS: 'Estado de la cuenta',
      IMAGE: 'Imagen',
      VERSION: 'Versión',
      ACTIVITY: 'Actividad',
      OLD_PASSWORD: 'Contraseña antigua',
      NEW_PASSWORD: 'Contraseña nueva',
      CONFIRM_NEW_PASSWORD: 'Confirmar contraseña nueva',
      SESSION_NAME: 'Nombre de la sesión',
      INFO: 'Información',
      HEALTH_PROFESSIONAL_INFO: 'Información del profesional sanitario',
      PATIENT_INFO: 'Información del beneficiario',
      AGREE_THE: 'Acepto los',
      TERMS_AND_CONDITIONS: 'términos y condiciones',
      SESSION_TEMPLATE_LIST: 'Lista de plantillas de sesiones',
      SAVE_AS_TEMPLATE: 'Guardar como plantilla',
      BIRTH_YEAR: 'Año de nacimiento',
      SEX: 'Género',
      ACCOUNT_TYPE: 'Tipo de cuenta',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      BENEFICIARIES: 'Beneficiarios',
      SUBSCRIPTION_DURATION: 'Duración de la suscripción',
      START_DATE: 'Fecha de inicio',
      EXTENSION_DURATION: 'Duración de la ampliación',
      STARTING_LICENSE: 'Licencia de inicio',
      ANNUAL_FEE: 'Cuota anual',
      SUPPORT_SERVICES: 'Servicios de apoyo',
      MONTHLY_COST_PER_BENEFICIARY: 'Coste mensual por beneficiario',
      NOTES: 'Algunos datos para nosotros',
      LATEST_OCCUPATION: 'Última profesión',
      EDUCATION_YEARS: 'Estudios en años',
      QUESTIONNAIRE_NAME: 'Nombre del cuestionario',
      WRITE_YOUR_ANSWER: 'Escriba su respuesta',
      REQUIRED: 'Obligatorio',
      SECTION_NAME: 'Nombre de sección',
      QUESTION: 'Pregunta',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Respuesta escrita...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'La respuesta solo debe contener números.',
      HEALTH_PROFESSIONAL_NOTES: 'Notas del profesional sanitario',
      NOTE_TEXT: 'Texto de la nota',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Lista de plantillas de cuestionarios',
      PATIENT: 'Beneficiario',
      USERNAME: 'Nombre de usuario',
      ONE_TIME_PASSWORD: 'Contraseña de un solo uso (OTP)',
      CREATE_BENEFICIARY_CONSENT:
        'Tengo el consentimiento del beneficiario para proceder al registro de sus datos personales y a su inscripción en la plataforma Eligence.',
      I_HAVE_THE_BENEFICIARY_CONSENT:
        'Tengo el consentimiento del beneficiario para proceder al cambio de su contraseña',
      LOGIN_EMAIL_USERNAME: 'Correo electrónico / nombre de usuario',
      STAYING_STATUS: 'Describa su situación de vida actual',
      SELECT_TIME_PERIOD: 'Seleccionar periodo de tiempo',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Seleccionar periodo de tiempo',
      CURRENT_PASSWORD: 'Contraseña actual',
      ACTIVITY_DISPLAY_OPTION: 'Opción de visualización de actividad',
      GROUP_NAME: 'Nombre de grupo',
      MEETING_NAME: 'Nombre de reunión',
    },
    PLACEHOLDERS: {
      ALL: 'Todo',
      TOTAL_ELEMENTS: 'Elementos totales',
      SELECT_RESELLERS: 'Seleccionar distribuidor',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Buscar',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'Nombre de pila',
      NOTES: 'Notas',
      LAST_NAME: 'Apellidos',
      PATIENTS: 'Beneficiarios',
      SESSIONS: 'Sesiones',
      USER: 'Usuario',
      EMAIL: 'Correo electrónico',
      JOINED_DATE: 'Fecha de incorporación',
      COMPANY: 'Empresa',
      NAME: 'Nombre',
      STATUS: 'Estado',
      EXECUTIONS: 'Ejecuciones',
      COMPLETE_SESSIONS: 'Sesiones completadas',
      LAST_LOGIN: 'Último acceso',
      ACCOUNT_TYPE: 'Tipo de cuenta',
      ID: 'ID',
      CATEGORY: 'Categoría',
      PRODUCT: 'Producto',
      ACTIONS: 'Acciones',
      DESCRIPTION: 'Descripción',
      CREATED: 'Creado',
      COMPLETED: 'Completado',
      COUNTRY: 'País',
      LANGUAGE: 'Idioma',
      ROLE: 'Rol',
      ADDRESS: 'Dirección',
      POSTAL_CODE: 'Código postal',
      CITY: 'Municipio',
      ESCORT: 'Acompañante',
      ADMIN: 'Administrador',
      DATE: 'Fecha',
      TIME: 'Hora',
      DURATION: 'Duración',
      ADDED: 'Añadido',
      ORGANIZATION: 'Organización',
      EXERCISE: 'Juego',
      VERSION: 'Versión',
      LEVELS: 'Niveles',
      COGNITIVE: 'Habilidad cognitiva',
      CATEGORIES: 'Categorías',
      ENGINE: 'Motor',
      HEALTH_PROFESSIONAL: 'Profesional sanitario',
      ASSIGNED_PATIENTS: 'Beneficiarios asignados',
      PATIENT: 'Beneficiario',
      OPEN_SESSIONS: 'Sesiones abiertas',
      SESSION: 'Sesión',
      ORDER: 'Orden',
      GAMES: 'Juegos',
      LAST_EDIT: 'Última edición',
      CREATOR: 'Creador/a',
      ADDED_EXERCISES: 'Juegos añadidos',
      DIFFICULTY: 'Dificultad',
      ASSIGNED_BY: 'Asignado por',
      GAME: 'Juego',
      SCORE: 'Puntuación',
      PROGRESS: 'Progreso',
      BENEFICIARIES: 'Beneficiarios',
      LATEST_EXECUTION: 'Ejecución más reciente',
      TYPE: 'Tipo',
      STARTED: 'Iniciado',
      ENDS: 'Termina',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Profesionales sanitarios asignados',
      QUESTIONNAIRE: 'Cuestionario',
      DATE_ASSIGNED: 'Fecha asignada',
      DATE_COMPLETED: 'Fecha de finalización',
      SECTIONS: 'Secciones',
      START_DATE: 'Fecha de inicio',
      EXTENSION_DAYS: 'Días de ampliación',
      END_DATE: 'Fecha de finalización',
      EXTENSION_DATE: 'Fecha de ampliación',
      TOTAL_COST_OF_SUBSCRIPTION: 'Coste total de la suscripción',
      DURATION_OF_SUBSCRIPTION: 'Duración de la suscripción',
      TERMINATION_DATE: 'Fecha de finalización',
      INVITATION_SENT: 'Invitación enviada',
      SUBSCRIPTION_SENT: 'Suscripción enviada',
      ACTIVITY_DISPLAY_OPTION: 'Opción de visualización de actividad',
      INVITED_BY: 'Invitado/a por',
      GROUP: 'Grupo',
      MEMBERS: 'Miembros',
      GUESTS: 'Invitados',
      MEETINGS: 'Reuniones',
      MEETING: 'Reunión',
      VARIATIONS: 'Variaciones',
      ACTIVATED: 'Activado',
      ASSIGNMENT: 'Asignación',
    },
    VALIDATION: {
      INVALID: '{{name}} no es válido',
      REQUIRED: '{{name}} es obligatorio',
      MIN_LENGTH: '{{name}} debe tener al menos 3 símbolos',
      MAX_LENGTH: '{{name}} debe tener un máximo de 256 símbolos',
      MAX_LENGTH_NOTES: '{{name}} debe tener un máximo de 480 símbolos',
      MIN_LENGTH_PASS: '{{name}} debe tener un mínimo de 8 símbolos',
      AGREEMENT_REQUIRED: 'Es obligatorio aceptar las condiciones',
      NOT_FOUND: 'No se encontró el {{name}} solicitado',
      INVALID_LOGIN: 'Los datos de acceso son incorrectos',
      REQUIRED_FIELD: 'Campo obligatorio',
      MIN_LENGTH_FIELD: 'Longitud mínima del campo:',
      MAX_LENGTH_FIELD: 'Longitud máxima del campo:',
      INVALID_FIELD: 'El campo no es válido',
      MUST_MATCH: 'Los campos Contraseña y Confirmar contraseña no coinciden',
      MUST_MATCH_PIN: 'Los campos Pin y Confirmar pin no coinciden',
      NO_PRIMARY: 'No ha definido ningún {{name}} principal',
      NO_STATUS: 'No ha definido ningún estado {{name}}',
      MANY_PRIMARY: 'Ha definido más de un {{name}} principal',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Cuadro de mando',
        SYSTEM: 'Sistema',
      },
      HOME: 'Inicio',
      USER_PROFILE: 'Mi perfil',
      ACCOUNT_SETTINGS: 'Configuración de la cuenta',
      LANGUAGE: 'Idioma',
      LOGOUT: 'Cerrar sesión',
      NOTIFICATIONS: 'Notificaciones',
      SUBSCRIPTIONS: 'Suscripciones',
      ORGANIZATION: 'Organización',
      SESSIONS: 'Sesiones',
      GAMES: 'Juegos',
      GAMES_MANAGEMENT: 'Administración de juegos',
      PATIENTS: 'Beneficiarios',
      GUESTS: 'Invitados',
      MEMBERS: 'Miembros',
      ORGANIZATIONS: 'Organizaciones',
      MY_ORGANIZATION: 'Administración de la organización',
      ADMINS: 'Administradores',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      SIGN_OUT: 'Finalizar sesión',
      QUESTIONNAIRES: 'Cuestionarios',
      ELIGENCE_SESSION_TEMPLATES: 'Sesiones',
      TEMPLATES: 'Plantillas',
      BY_ELIGENCE: 'Por Eligence',
      RESELLERS: 'Distribuidores',
      HELP: 'Ayuda',
      GROUPS: 'Grupos',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Política de privacidad',
      TERMS_AND_CONDITIONS: 'Términos y condiciones',
      COOKIE_POLICY: 'Política de cookies',
      CONTACT: 'Contacto',
    },
    GAME_DIFFICULTY: {
      EASY: 'Fácil',
      INTERMEDIATE: 'Intermedio',
      HARD: 'Difícil',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Individual',
      GROUP_MEETING: 'Reunión de grupo',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Hoy',
      THIS_WEEK: 'Esta semana',
      THIS_MONTH: 'Este mes',
      LAST_7_DAYS: 'Últimos 7 días',
      LAST_30_DAYS: 'Últimos 30 días',
      CUSTOM: 'Personalizado',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Memoria',
      LANGUAGE: 'Idioma',
      ATTENTION: 'Atención',
      CONSTRUCTIVE_ABILITY: 'Habilidad de construcción',
      EXECUTIVE_FUNCTIONS: 'Funciones ejecutivas',
      LOGICAL_REASONING: 'Razonamiento lógico',
      ORIENTATION: 'Orientación',
      SPATIAL_AWARENESS: 'Conciencia espacial',
      MOTOR_SKILLS: 'Habilidades motoras',
      COORDINATION: 'Coordinación',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Invitados',
      NON_GUEST: 'Miembros',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Tipo de cuenta',
      ACCOUNT_TYPE_DESCRIPTION: 'Elija su tipo de cuenta',
      ORGANIZATION_INFO: 'Información de la organización',
      ORGANIZATION_INFO_DESCRIPTION:
        'Configurar información de la organización',
      INVOICING_DETAILS: 'Detalles de facturación',
      INVOICING_DETAILS_DESCRIPTION: 'Configurar detalles de facturación',
      SETUP_ACCOUNT: 'Configurar cuenta',
      SETUP_ACCOUNT_DESCRIPTION: 'Configurar los datos de su cuenta',
      COMPLETED: 'Completado',
      CHOOSE_ACCOUNT_TYPE: 'Elegir tipo de cuenta',
      SMALL_ORGANIZATION: 'Organización pequeña',
      SMALL_ORG_HEALTH_PROF_PATIENTS:
        '1 profesional sanitario / 1-10 beneficiarios',
      MEDIUM_ORGANIZATION: 'Organización mediana',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS:
        '1-10 profesionales sanitarios / 1-50 beneficiarios',
      BIG_ORGANIZATION: 'Organización grande',
      BIG_ORG_HEALTH_PROF_PATIENTS:
        '1-50 Profesionales sanitarios / 1-200 beneficiarios',
      REGISTRATION:
        'Se ha enviado un correo electrónico al usuario para activar su cuenta',
      DONE: 'Se ha activado su cuenta.',
      DONE_DESCRIPTION:
        '¡Haga clic en el botón que aparece a continuación para iniciar sesión!',
      MERGE_DONE:
        'Ya está registrado/a en otra organización. Cada vez que se conecte, podrá elegir con qué organización desea interactuar',
      SESSION_INFO: 'Información de la sesión',
      SESSION_INFO_STEPPER: 'Asigne un nombre a su sesión',
      EXERCISES: 'Juegos',
      EXERCISES_STEPPER: 'Añadir juegos',
      COMPLETION: 'Finalización',
      COMPLETION_STEPPER: '¡Terminamos!',
      SESSION_INFO_DESCRIPTION:
        'Asigne un nombre a su sesión y tome algunas notas si lo desea.',
      SESSION_EXERCISES: 'Juegos',
      SESSION_EXERCISES_DESCRIPTION:
        'Añada ejercicios a su sesión y modifíquela',
      ADD_EXERCISES: 'Añadir juegos',
      ADDED_EXERCISES: 'Juegos añadidos',
      CREATE_SESSION_COMPLETION: '¡Un último paso!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: '¡Terminamos!',
      OVERVIEW: 'Visión general',
      OVERVIEW_BENEFICIARIES: 'Visión general de beneficiarios',
      OVERVIEW_SESSIONS: 'Visión general de sesiones',
      HEALTH_PROFESSIONAL_INFO: 'Información del profesional sanitario',
      PATIENT_INFO: 'Información del beneficiario',
      SESSION_NOTES: 'Notas',
      SESSION_NOTES_DESCRIPTION: '¡Añada algo de información!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Elija su tipo de cuenta',
      SUBSCRIPTION_DETAILS: 'Detalles de la suscripción',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Configurar detalles de la suscripción',
      NOTES: 'Notas',
      NOTES_DESCRIPTION: 'Añadir notas',
      OVERVIEW_DESCRIPTION: 'Echar un último vistazo',
      GROUP_INFO: 'Información de grupo',
      BENEFICIARIES: 'Beneficiarios',
      GROUP_INFO_DESCRIPTION:
        'Asigne un nombre a su grupo y tome algunas notas si lo desea.',
      GROUP_BENEFICIARIES_DESCRIPTION: 'Añada beneficiarios a su grupo',
      ADD_BENEFICIARIES: 'Añadir beneficiarios',
      ADDED_BENEFICIARIES: 'Beneficiarios añadidos',
      CREATE_GROUP_COMPLETION: '¡Un último paso!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: '¡Terminamos!',
      MEETING_INFO: 'Información de la reunión',
      MEMBERS: 'Miembros',
      SESSIONS: 'Sesiones',
      MEETING_INFO_DESCRIPTION:
        'Asigne un nombre a su reunión y tome algunas notas si lo desea.',
      MEETING_SESSIONS_DESCRIPTION: 'Descripción de las sesiones de la reunión',
      ADD_SESSIONS: 'Añadir sesiones',
      ADDED_SESSIONS: 'Sesiones añadidas',
      GAMES: 'Juegos',
      ASSIGN_GAMES: 'Asignar juegos',
    },
    INFO: {
      INFO: 'Si necesita más información, consulte',
      HELP: 'Página de ayuda',
    },
    ACTIONS: {
      ACTIONS: 'Acciones',
      VIEW: 'Ver',
      VIEW_PROFILE: 'Ver perfil',
      ACTIVATE: 'Activar',
      DEACTIVATE: 'Desactivar',
      DELETE: 'Borrar',
      ASSIGN_PATIENTS: 'Asignar beneficiarios',
      ASSIGN_HEALTH_PROFESSIONALS: 'Asignar profesionales sanitarios',
      RESEND_INVITATION: 'Reenviar invitación',
      PREVIEW: 'Vista previa',
      UPLOAD_FILE: 'Cargar juego',
      REMOVE_PATIENT: 'Eliminar beneficiario',
      SET_TO_ACTIVE: 'Cambiar a activo',
      EDIT: 'Editar',
      REMOVE: 'Eliminar',
      FROM_TEMPALTE: 'Desde plantilla',
      CREATE_NEW: 'Crear nuevo',
      CLONE: 'Clonar',
      CLOSE: 'Cerrar',
      CANNOT:
        'No puede realizar acciones en esta sesión, ya que está asignada a otro profesional sanitario',
      AMENDMENT: 'Modificación',
      TERMINATE: 'Finalizar',
      NEW_SUBSCRIPTION: 'Nueva suscripción',
      RESEND_EMAIL: 'Reenviar correo electrónico',
      REMOVE_HEALTH_PROFESSIONAL: 'Eliminar profesional sanitario',
      RENEW: 'Renovar',
      ASSIGN: 'Asignar',
      UNASSIGN: 'Desasignar',
      CANCEL: 'Cancelar',
      INVITE: 'Invitar',
      CREATE: 'Crear',
      RESET_PASSWORD: 'Restablecer contraseña',
      ACTIVITY_DISPLAY_OPTIONS: 'Opciones de visualización de actividades',
      UPGRADE: 'Actualizar',
      VIEW_MEMBERS: 'Ver miembros',
      START_MEETING: 'Iniciar reunión',
    },
    AUTH: {
      SIGN_IN: 'Iniciar sesión',
      NEW_HERE: '¿Acaba de llegar por aquí?',
      SIGNUP: 'Registrarse',
      FORGOT_BUTTON: '¿Olvidó la contraseña?',
      ABOUT: 'Sobre nosotros',
      CONTACT: 'Contacto',
      CONTACT_US: 'Contáctenos',
      FORGOT_PASSWORD: 'Contraseña olvidada',
      RESET_PASSWORD: 'Restablecer contraseña',
      SET_PASSWORD: 'Definir contraseña',
      SETUP_YOUR_NEW_PASSWORD: 'Configure su nueva contraseña',
      AN_EMAIL_IS_REQUIRED: 'Se necesita un correo electrónico.',
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        'Si su cuenta se creó con un nombre de usuario, póngase en contacto con su profesional sanitario o con el administrador de su organización.',
    },
    PROFILE: {
      OVERVIEW: 'Visión general',
      SETTINGS: 'Configuración',
      NOTES: 'Notas',
      EDIT_PROFILE: 'Editar perfil',
      DETAILS: 'Detalles',
      INFORMATION: 'Información',
      NAME: 'Nombre',
      FULL_NAME: 'Nombre completo',
      ROLE: 'Rol',
      CONTACT_PHONE: 'Teléfono de contacto',
      EMAIL: 'Correo electrónico',
      COUNTRY: 'País',
      POSTAL_CODE: 'Código postal',
      ADDRESS: 'Dirección',
      TAX_ID: 'N.º identificación fiscal',
      STATUS: 'Estado',
      EDIT: 'Editar',
      PASSWORD_RESET: 'Restablecimiento de contraseña',
      RESEND_PASSWORD_INVITATION: 'Reenviar invitación de contraseña',
      ASSIGNED_PATIENTS: 'Beneficiarios asignados',
      ASSIGNED_MEMBERS: 'Miembros asignados',
      ASSIGNED_GUESTS: 'Invitados asignados',
      ACCOUNT_ID: 'ID de cuenta',
      BILLING_EMAIL: 'Correo electrónico de facturación',
      LAST_EDIT: 'Última edición',
      CREATED_BY: 'Creado por',
      BILLING_ADDRESS: 'Dirección de facturación',
      ADMINS: 'Administradores',
      PAYMENT_RECORDS: 'Registros de pagos',
      PAYMENT_METHODS: 'Formas de pago',
      PERFORMANCE: 'Desempeño',
      FIRST_NAME: 'Nombre de pila',
      LAST_NAME: 'Apellidos',
      PHONE_NUMBER: 'Número de teléfono',
      PREFERRED_LANGUAGE: 'Idioma preferido',
      VAT: 'IVA',
      ACTIVITY: 'Actividad',
      WEBSITE: 'Sitio web',
      CREATED_SESSIONS: 'Sesiones creadas',
      EMAIL_UPDATE_TOOLTIP:
        'Tenga en cuenta que su nombre de usuario será su nuevo correo electrónico.',
      CHANGE_PASSWORD: 'Cambiar contraseña',
      SESSIONS: 'Sesiones',
      ADDED_EXERCISES: 'Juegos añadidos',
      SESSION_EXECUTIONS_TOOLTIP:
        'Esta sesión se ha ejecutado {{number}} veces',
      BIRTH_YEAR: 'Año de nacimiento',
      SEX: 'Género',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Profesionales sanitarios asignados',
      SUBSCRIPTIONS: 'Suscripciones',
      CURRENT_SUBSCRIPTION: 'Suscripción actual',
      SUBSCRIPTIONS_HISTORY: 'Historial de suscripciones',
      SUBSCRIPTION: 'Suscripción',
      UPCOMING_SUBSCRIPTION: 'Próxima suscripción',
      LATEST_OCCUPATION: 'Última profesión',
      EDUCATION_YEARS: 'Estudios en años',
      EMAIL_USERNAME: 'Correo electrónico (nombre de usuario)',
      INVOICE_INFO: 'Información de facturación',
      EXECUTIONS: 'Ejecuciones',
      MEMBER_SINCE: 'Miembro desde',
      QUESTIONNAIRES: 'Cuestionarios',
      ASSIGNED: 'Asignado',
      COMPLETED: 'Completado',
      ANSWERS: 'Respuestas',
      PASSWORD: 'Contraseña',
      USERNAME: 'Nombre de usuario',
      STAYING_STATUS: 'Describa su situación de vida actual',
      ACTIVITY_DISPLAY_OPTION: 'Opción de visualización de actividad',
      GAMES: 'Juegos',
      MEETINGS: 'Reuniones',
      MEMBERS: 'Miembros',
      PUBLIC: 'Público',
      PRIVATE: 'Privado',
    },
    GENERAL: {
      USER: 'Usuario',
      PATIENT: 'Beneficiario',
      MEMBER: 'Miembro',
      GUEST: 'Invitado',
      HEALTH_PROFESSIONAL: 'Profesional sanitario',
      GAME: 'Juego',
      PROFILE: 'Perfil',
      ORGANIZATION: 'Organización',
      ORGANIZATION_ADMIN: 'Administración de la organización',
      NO_ENTRIES: 'No se encontraron entradas',
      SESSION: 'Sesión',
      GAMES: 'Juegos',
      SESSION_TEMPLATE: 'Plantilla de sesión',
      SUBSCRIPTION: 'Suscripción',
      SUBSCRIPTION_EMAIL: 'Correo electrónico de suscripción',
      ASSIGNED_QUESTIONNAIRE: 'Cuestionario asignado',
      QUESTIONNAIRE_TEMPLATE: 'Plantilla de cuestionario',
      NOTE: 'Nota',
      COPIED: '¡Copiado!',
      SESSION_NAME: 'Nombre de la sesión',
      CONGRATULATIONS: 'Enhorabuena',
      DESCRIPTION: 'Descripción',
      SAME_COGNITIVE_GAMES: 'Juegos que ejercitan la misma habilidad cognitiva',
      SELECT_DIFFICULTY: 'Seleccionar nivel de dificultad',
      GROUP: 'Grupo',
      MEETING: 'Reunión',
    },
    GRAPHS: {
      SCORE: 'Puntuación',
      TIME: 'Hora',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Ejecuciones por habilidad cognitiva y dificultad',
      EXECUTIONS_PER_GAME_TITLE: 'Ejecuciones por juego',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Puntuación media por juego',
      EXECUTIONS_PER_DAY_TITLE: 'Ejecuciones por día',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE:
        'Evolución de la puntuación media',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Tiempo total de actividad al día (minutos)',
      GAME: 'Juego',
      TOTAL: 'Total',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Registros de actividad',
      EXECUTED_GAME: 'Juego ejecutado',
      ADDED: 'Añadido: ',
      EXECUTED_SESSION: 'sesión ejecutada',
    },
    SESSION: {
      MY_SESSIONS: 'Mis sesiones',
      SESSION_COMPLETE: 'Ha completado la sesión',
      ABANDONED: 'Abandonado',
      SKIPPED: 'Omitido',
      PLAYED: 'Jugado',
      PENDING: 'Pendiente',
      ASSIGNED_SESSIONS: 'Sesiones asignadas',
      DEFAULT_PUBLIC_INFO:
        '¡Hola! ¡Esta sesión se ha creado solo para usted! Complétela o póngase en contacto con su profesional sanitario si tiene más preguntas.',
      DOCTOR_NOTES: 'Mensaje del profesional sanitario',
      SAMPLE_DOCTOR_NOTES:
        'Estimado/a {{name}}: ¡esta sesión se ha creado solo para usted! Complétela o póngase en contacto con su profesional sanitario si tiene más preguntas.',
      QUESTS: 'Misiones',
    },
    STATUS: {
      ACTIVE: 'Activa',
      INACTIVE: 'Inactiva',
      INVITED: 'Invitado',
    },
    SESSION_STATUS: {
      ACTIVE: 'Activa',
      ASSIGNED: 'Asignada',
      CLOSED: 'Cerrada',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Distribuidor',
      DEMO: 'Demostración',
      PAID: 'Pagado',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'Administrador del sistema',
      ROLE_ORGANIZATION_OWNER: 'Propietario de la organización',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Administración de la organización',
      ROLE_HEALTH_PROFESSIONAL: 'Profesional sanitario',
      ROLE_PATIENT: 'Beneficiario',
      ROLE_INTERNAL_CONTACT: 'Contacto interno',
      ROLE_EXTERNAL_CONTACT: 'Contacto externo',
      ROLE_HEALTH_PROFESSIONAL_OWNER:
        'Profesional sanitario / propietario de la organización',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Profesional sanitario / administrador de la organización',
      ROLE_RESELLER_OWNER: 'Propietario de empresa distribuidora',
      ROLE_RESELLER_ADMINISTRATOR: 'Distribuidor administrador',
    },
    SEX: {
      MALE: 'Hombre',
      FEMALE: 'Mujer',
      OTHER: 'Otro',
      NO_ANSWER: 'Prefiero no contestar',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Hola, administrador',
      OVERVIEW_DESCRIPTION: 'Eche un vistazo a sus cifras',
      EXECUTIONS: 'Ejecuciones',
      HOURS: 'Horas',
      BENEFICIARIES: 'Beneficiarios',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      MOST_PLAYED: 'Más jugados',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Actualizaciones más recientes de juegos',
      LEAST_PLAYED: 'Menos jugados',
      ACTIVE_LAST_30_DAYS: 'Activo los últimos 30 días',
      GAMES_ACTIVITY: 'Actividad de juegos',
      GAMES_ACTIVITY_DESCRIPTION:
        'Total de ejecuciones por juego y habilidad cognitiva',
      AVERAGE: 'Total',
      LAST_UPDATE: 'Última actualización: ',
      HOUR_SHORT: 'h',
      MINUTE_SHORT: 'm',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Número de profesionales sanitarios',
      NUMBER_OF_BENEFICIARIES: 'Número de beneficiarios',
      DURATION: 'Duración',
      START_DATE: 'Fecha de inicio',
      EXTENSION_DAYS: 'Días de ampliación',
      END_DATE: 'Fecha de finalización',
      EXTENSION_DATE: 'Fecha de ampliación',
      STARTING_LICENSE: 'Licencia de inicio',
      ANNUAL_FEE: 'Cuota anual',
      SUPPORT_SERVICES: 'Servicios de apoyo',
      MONTHLY_COST_PER_BENEFICIARY: 'Coste mensual por beneficiario',
      TOTAL_COST_OF_BENEFICIARIES: 'Coste total de los beneficiarios',
      TOTAL_COST_OF_SUBSCRIPTION: 'Coste total de la suscripción',
      ORGANIZATION_TYPE: 'Tipo de organización',
      SUBSCRIPTION_TYPE: 'Tipo de suscripción',
      MONTHS: 'Meses',
      DAYS: 'Días',
      REMAINING_DAYS: 'Días restantes',
      HEALTH_PROFESSIONALS: 'Profesionales sanitarios',
      BENEFICIARIES: 'Beneficiarios',
      NOTES: 'Notas',
      DURATION_OF_SUBSCRIPTION: 'Duración de la suscripción',
      COSTS_VAT_DISCLAIMER:
        'Ningún coste incluye el IVA, siempre que sea pertinente.',
      ACCEPT_MODAL_FOOTER:
        'Si no desea confirmar la suscripción, ignore este mensaje o envíenos un correo electrónico para obtener más información a ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        'No puede acceder a Eligence, ya que la suscripción de su organización no está activa. Para obtener más información, póngase en contacto con el equipo de Eligence.',
      DAYS_LEFT: 'días restantes',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'Nueva',
      AMENDMENT: 'Modificación',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Activa',
      EXPIRED: 'Caducada',
      PENDING_CONSENT: 'Consentimiento pendiente',
      PENDING_AUTOMATION: 'Automatización pendiente',
      REJECTED: 'Rechazada',
      TERMINATED: 'Finalizada',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Cuestionarios asignados',
      SECTION: 'Sección',
      QUESTION: 'Pregunta',
      NOTE: 'Nota',
      BY: 'por',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Plataforma generada',
      USER_GENERATED: 'Usuario generado',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Asignado',
      IN_PROGRESS: 'En curso',
      COMPLETED: 'Completado',
      CANCELLED: 'Cancelado',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Texto libre',
      INTEGER: 'Numérico',
      CHECKBOX: 'Selección múltiple',
      RADIO: 'Opción única',
      DROPDOWN: 'Desplegable',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'El cuestionario es una herramienta recomendada que le proporciona la plataforma Eligence. Gracias al cuestionario puede recopilar información relativa a un beneficiario o solicitar información para evaluar la situación del beneficiario.',
      PROMPT:
        'Cuando se asigne el cuestionario al beneficiario, todos los juegos y sesiones gratuitos aparecerán deshabilitados hasta que el beneficiario lo complete.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Crear beneficiario',
      TITLE_MEMBER: 'Crear miembro',
      TITLE_GUEST: 'Crear invitado',
      CREDENTIALS: 'Credenciales',
      PERSONAL_DETAILS: 'Datos personales',
      COMPLETION: 'Finalización',
      CHECK_AVAILABILITY: 'Comprobar disponibilidad',
      USERNAME_AVAILABLE: 'Nombre de usuario disponible',
      USERNAME_UNAVAILABLE: 'No disponible, inténtelo de nuevo',
      OTP_SAVE_WARNING: 'Guardar la contraseña para utilizarla más tarde.',
      DONE: '¡Ya está todo listo!',
      DONE_DESCRIPTION:
        'Se ha creado una nueva cuenta de beneficiario. En el primer inicio de sesión, se pedirá al beneficiario que cambie la contraseña generada.',
      DONE_DESCRIPTION_GUEST: 'Se ha creado un nuevo invitado.',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'Para grupos',
      FOR_TWO: 'Para dos personas',
      INTERGENERATION: 'Entre generaciones',
      CHALLENGING: 'Desafiante',
    },
    GAMES: {
      MY_GAMES: 'Mis juegos',
      ALL_GAMES: 'Todo',
    },
    STAYING_STATUS: {
      ALONE: 'No vivo con nadie',
      WITH_HUSBAND_WIFE: 'Vivo con mi pareja',
      WITH_KIDS_GRANDKIDS: 'Vivo con mis hijos / nietos',
      WITH_CARER: 'Vivo con la persona que me cuida',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'Ver todo',
      ONLY_SESSIONS: 'Solo sesiones',
      ONLY_GAMES: 'Solo juegos',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Asignado',
      UNASSIGNED: 'Sin asignar',
    },
    GAME_ACCESS: {
      PUBLIC: 'Público',
      PRIVATE: 'Privado',
    },
    COOKIE_POLICY: {
      COOKIE: 'Cookie',
      DOMAIN: 'Dominio',
      DESCRIPTION: 'Descripción',
      DURATION: 'Duración',
      TYPE: 'Tipo',
      PLL_LANGUAGE_DESCRIPTION:
        'La cookie pll _language es utilizada por Polylang para recordar el idioma seleccionado durante el uso al volver al sitio web, y también para obtener la información sobre el idioma cuando no esté disponible de otra forma.',
      GA_STAR_DESCRIPTION:
        'Google Analytics coloca esta cookie para almacenar y contar las páginas vistas.',
      GA_DESCRIPTION:
        'La cookie _ga, instalada por Google Analytics, calcula los datos de visitantes, sesiones y campañas y también realiza un seguimiento del uso del sitio para el informe de análisis del sitio. Esta cookie almacena la información de forma anónima y asigna un número generado aleatoriamente para reconocer a los visitantes únicos.',
      ELEMENTOR_DESCRIPTION:
        'Esta cookie es utilizada por el tema de WordPress del sitio web. Permite al propietario del sitio web implementar o cambiar en tiempo real el contenido del sitio web.',
      ONE_YEAR: '1 año',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 año, 1 mes, 4 días',
      NEVER: 'nunca',
      FUNCTIONAL: 'Funcional',
      ANALYTICS: 'Análisis',
      NECESSARY: 'Técnica',
    },
  },
};
