export const locale = {
  lang: 'it',
  data: {
    EXCEPTION: {
      GENERIC_MESSAGE: "Contattare l'assistenza o riprovare più tardi.",
      USERNAME_NOT_FOUND_EXCEPTION: 'Il name utente non è stato trovato.',
      USER_LOGIN_EXCEPTION: 'Il name utente o la password non sono validi.',
      BAD_CREDENTIALS_ATTEMPTS_EXCEPTION: 'Email o password non valide.',
      USER_ALREADY_EXISTS_IN_ORGANIZATION_EXCEPTION:
        "L'utente esiste già nell'organizzazione",
      USER_REGISTRATION_EXCEPTION:
        "Errore riscontrato durante la registrazione dell'utente.",
      PASSWORD_RESET_LINK_EXCEPTION:
        'Errore riscontrato durante la generazione del link per la reimpostazione della password.',
      PASSWORD_RESET_UNVERIFIED_EXCEPTION:
        "L'account con queste informazioni non è ancora stato attivato. La reimpostazione della password non può essere attivata.",
      PASSWORD_RESET_EXCEPTION:
        'Errore riscontrato durante la reimpostazione della password.',
      MAIL_SEND_EXCEPTION: "Errore riscontrato durante l'invio della posta.",
      UPDATE_PASSWORD_EXCEPTION: 'Password attuale non valida',
      TOKEN_REFRESH_EXCEPTION:
        'Impossibile aggiornare il token di autorizzazione.',
      USER_LOGOUT_EXCEPTION: 'Errore riscontrato durante la disconnessione.',
      INVALID_TOKEN_REQUEST_EXCEPTION:
        "L'utente non è autorizzato ad accedere a questa risorsa.",
      FORBIDDEN_EXCEPTION:
        "L'utente non è autorizzato ad accedere a questa risorsa.",
      UNAUTHORIZED_EXCEPTION:
        "L'utente non è autorizzato ad accedere a questa risorsa.",
      IP_BLOCKED_EXCEPTION:
        "L'utente è stato temporaneamente bloccato a causa di più tentativi di accesso.",
      EMAIL_ALREADY_IN_USE_EXCEPTION:
        "L'indirizzo e-mail fornito è già in uso.",
      FILE_GENERIC_EXCEPTION:
        "Errore di file. Contattare l'assistenza o riprovare più tardi.",
      METHOD_ARGUMENT_NOT_VALID_EXCEPTION:
        "Argomento non valido. Contattare l'assistenza o riprovare più tardi.",
      APP_EXCEPTION:
        "Qualcosa è andato storto. Contattare l'assistenza o riprovare più tardi",
      RESOURCE_ALREADY_IN_USE_EXCEPTION:
        "Risorsa già in uso. Contattare l'assistenza o riprovare più tardi.",
      RESOURCE_NOT_FOUND_EXCEPTION:
        "Risorsa non trovata. Contattare l'assistenza o riprovare più tardi.",
      FILE_NOT_FOUND_EXCEPTION:
        "File non trovato. Contattare l'assistenza o riprovare più tardi.",
      BAD_REQUEST_EXCEPTION:
        "Richiesta errata. Contattare l'assistenza o riprovare più tardi.",
      HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION:
        "Tipo di supporto non accettabile. Contattare l'assistenza o riprovare più tardi.",
      SESSION_EXPIRED_EXCEPTION:
        'La sessione è scaduta. Si prega di effettuare nuovamente il login.',
      USER_NOT_ACTIVE_IN_ANY_ORGANIZATION_EXCEPTION:
        "L'utente non è attivo in nessuna organizzazione. Ciò significa che uno degli amministratori dell'organizzazione l'ha disattivata. Si prega di contattarli direttamente.",
      PASSWORD_MISMATCH_EXCEPTION: 'Le passwords non corrispondono.',
      ORGANIZATION_NAME_CONFLICT:
        "Esiste già un'organizzazione con questo nome.",
      ORGANIZATION_WEBSITE_CONFLICT:
        "Esiste già un'organizzazione con questo sito web.",
      ORGANIZATION_PHONE_CONFLICT:
        "Esiste già un'organizzazione con questo telefono.",
      ORGANIZATION_EMAIL_CONFLICT:
        "Esiste già un'organizzazione con questa email.",
      HEALTH_PROFESSIONALS_EXCEEDED_EXCEPTION:
        "You cannot invite a Health Professional. You have reached your subscription's limit.",
      BENEFICIARIES_EXCEEDED_EXCEPTION:
        "You cannot invite a Beneficiary. You have reached your subscription's limit.",
      ORGANIZATION_VAT_CONFLICT: "Esiste già un'organizzazione con questa IVA.",
      ORGANIZATION_HAS_NOT_ACCEPTED_SUBSCRIPTION_EXCEPTION:
        'The organization has not accepted the subscription.',
      ORGANIZATION_HAS_NOT_ACTIVE_OR_PENDING_SUBSCRIPTION_EXCEPTION:
        'The organization does not have active or pending subscription.',
      ORGANIZATION_IS_INACTIVE_EXCEPTION: 'The organization is inactive.',
      USER_NOT_VERIFIED_IN_ORGANIZATION_EXCEPTION:
        'The user is not verified in the organization',
      SUBSCRIPTION_ALREADY_EXISTS_FOR_DATES:
        'Esiste già un abbonamento per queste date.',
      QUESTIONNAIRE_NOT_IN_ORGANIZATION:
        'Non è possibile eseguire azioni su questo questionario perché non è stato creato dalla tua organizzazione.',
      USER_ORGANIZATION_ALREADY_HAS_QUESTIONNAIRE:
        "C'è già un questionario per questo utente.",
      QUESTIONNAIRE_IS_EMPTY:
        'Per assegnare un modello di questionario, è necessario creare almeno una domanda.',
      SESSION_ALREADY_IN_USE:
        "C'è stato un tentativo di accesso simultaneo, pertanto sei stato disconnesso per motivi di sicurezza. Per favore, effettua nuovamente la procedura di accesso, per continuare al tuo account.",
    },
    ROUTES_TITLE: {
      HOME: 'Home',
      ELIGENCE: ' - Eligence',
      SYSTEM_ADMINS: 'System Admins',
      HEALTH_PROFESSIONALS: 'Professionisti della salute',
      BENEFICIARIES: 'Utenti',
      MEMBERS: 'Membri',
      MEMBER_PROFILE: 'Profilo del Membro',
      GUESTS: 'Ospiti',
      GUEST_PROFILE: 'Profilo del Ospite',
      MY_PROFILE: 'Profilo personale',
      USER_PROFILE: 'Profilo Utente',
      ORGANIZATIONS: 'Organizzazioni',
      ORGANIZATION_PROFILE: 'Profilo Organizzazione',
      GAMES: 'Giochi',
      GAME_MANAGEMENT: 'Giochi',
      GAME_OVERVIEW: 'Panoramica del gioco',
      SESSION_TEMPLATES: 'Modelli di Sessione',
      SESSIONS_BY_ELIGENCE: 'Sessioni da Eligence',
      SESSION_TEMPLATE: 'Modello di sessione',
      QUESTIONNAIRE_TEMPLATES: 'Modelli di questionario',
      QUESTIONNAIRES_BY_ELIGENCE: 'Questionari per Eligence',
      QUESTIONNAIRE_TEMPLATE: 'Modelli di questionario',
      ASSIGNED_SESSION: 'Assigned Session',
      ASSIGNED_QUESTIONNAIRE: 'Questionari assegnati',
      ADD_SESSION: 'Aggiungi Sessione',
      CREATE_BENEFICIARY: 'Creare un Utente',
      ELIGENCE_SESSION_TEMPLATES: 'Sessioni',
      RESELLERS: 'Rivenditori',
      RESELLER_PROFILE: 'Profilo del rivenditore',
      GROUPS: 'Gruppi',
      CREATE_GROUP: 'Creare un gruppo',
      CREATE_MEMBER: 'Creare Membro',
      CREATE_GUEST: 'Creare Ospite',
      GROUP_PROFILE: 'Profilo di gruppo',
      ADD_MEETING: 'Avviare una nuova riunione',
      EDIT_GROUP: 'Modifica Gruppo',
      GAME_VARIATIONS: 'Variazioni di gioco',
    },
    CONFIRM: {
      DELETE: 'Sei sicuro di voler cancellare questo {{name}}?',
      CREATE: 'Sei sicuro di voler creare un nuovo {{name}}?',
      EDIT: 'Sei sicuro di voler modificare questo {{name}}?',
      CHANGE: 'Sei sicuro di voler salvare le modifiche?',
      ACTIVATE: 'Sei sicuro di voler attivare questo utente?',
      ACTIVATE_ORGANIZATION:
        'Sei sicuro di voler attivare questa organizzazione?',
      DEACTIVATE: 'Sei sicuro di voler disattivare questo utente?',
      DEACTIVATE_ORGANIZATION:
        'Sei sicuro di voler disattivare questa organizzazione?',
      INVITATION:
        "Siete sicuri di voler inviare nuovamente l'invito per questo utente?",
      INVITATION_ORGANIZATION:
        "Sei sicuro di voler inviare nuovamente l'invito per questa organizzazione?",
      BOOK: 'Sei sicuro di voler prenotare questo {{name}}?',
      CANCEL_BOOKING:
        'Sei sicuro di voler cancellare la prenotazione con questo utente?',
      UPDATE_MAIL_WARNING:
        'Sei sicuro di voler cambiare la tua e-mail? Tieni presente che il tuo name utente sarà il tuo nuovo indirizzo e-mail.',
      ACTIVATE_GAME: 'Sei sicuro di voler attivare questo gioco?',
      ACTIVATE_GAME_TEMPLATE:
        'Sei sicuro di voler attivare questa categoria di giochi?',
      DEACTIVATE_GAME: 'Sei sicuro di voler disattivare questo gioco?',
      DEACTIVATE_GAME_WARNING:
        'Questo gioco è attualmente assegnato a {{sessions}} sessioni, {{beneficiaries}} beneficiari, {{sessionTemplates}} modelli di sessione, {{systemAssignedSessions}} sessioni da Eligence, {{systemSessionTemplates}} modelli di sessione da Eligence, {{groupAssignedSessions}} sessioni di gruppo. Siete sicuri di volerlo disattivare?',
      DEACTIVATE_GAME_TEMPLATE_WARNING:
        'Questa categoria di giochi è attualmente assegnata a {{sessions}} sessioni, {{beneficiaries}} beneficiari, {{sessionTemplates}} modelli di sessione, {{systemAssignedSessions}} sessioni da Eligence, {{systemSessionTemplates}} modelli di sessione da Eligence, {{groupAssignedSessions}} sessioni di gruppo. Siete sicuri di volerla disattivare?',
      DEACTIVATE_GAME_BENEFICIARY_WARNING:
        'Questo gioco è attualmente assegnato a {{sessions}} sessioni attive, {{systemAssignedSessions}} sessioni da Eligence, {{groupAssignedSessions}} sessioni di gruppo. Siete sicuri di volerlo disattivare?',
      REMOVE_PATIENT:
        'Sei sicuro di voler rimuovere questo utente da questo professionista della salute?',
      CLOSE_SESSION: 'Siete sicuri di voler chiudere la sessione?',
      DELETE_SESSION: 'Siete sicuri di voler eliminare la sessione?',
      DELETE_QUESTIONNAIRE:
        'Sei sicuro di voler eliminare questo questionario?',
      REMOVE_HEALTH_PROFESSIONAL:
        'Sei sicuro di voler rimuovere questo professionista della salute da questo utente?',
      PROCEED_TO_CREATE_SESSION_STEP_3:
        "Sono nell'ordine in cui si vuole che appaiano nel utente? Avete selezionato il livello di difficoltà desiderato per ogni gioco?",
      CANCEL: 'Are you sure you want to cancel this {{name}}?',
      DELETE_QUESTIONNAIRE_SECTION:
        'Eliminando una sezione si eliminano anche tutte le domande di questa sezione. Sei sicuro di voler continuare?',
    },
    SUCCESS: {
      CREATE: '{{name}} creato con successo',
      EDIT: '{{name}} modificato con successo',
      UPDATE: '{{name}} aggiornato con successo',
      DELETE: '{{name}} cancellato con successo',
      ADD: '{{name}} aggiunto con successo',
      ASSIGN: '{{name}} assegnato con successo',
      ACTIVATE: '{{name}} attivato con successo',
      REQUEST: 'Richiesta di {{name}} inviata con successo',
      DEACTIVATE: '{{name}} disattivato con successo',
      REGISTER:
        "La registrazione è avvenuta con successo. Verrà inviata un'e-mail al tuo indirizzo di posta elettronica per impostare la password",
      CLONE: '{{name}} clonato con successo',
      CANCEL: '{{name}} cancellato con successo',
      INVITE: '{{name}} invitato con successo',
      RESET: 'La password è stata resettata con successo',
      FORGOT:
        "È stata inviata un'e-mail al vostro indirizzo di posta elettronica. Seguire le istruzioni per reimpostare la password",
      REMOVE: '{{name}} rimosso con successo',
      PASSWORD_CHANGE: 'La password è stata modificata con successo',
      AMEND: '{{name}} amended successfully',
      RESEND: '{{name}} resent successfully',
      RESET_OTP: 'La password una tantum è stata resettata con successo.',
      GAME_CACHE_CLEAR: 'Successfully cleared game cache',
      UPGRADE: '{{name}} aggiornato con successo',
    },
    MODALS: {
      ADD_ORGANIZATION: 'Aggiungi organizzazione',
      ADD_PATIENT: 'Aggiungi utente',
      ADD_HEALTH_PROFESSIONAL: 'Aggiungi professionista sanitario',
      ADD_ORGANIZATION_ADMIN: "Aggiungi amministratore dell'organizzazione",
      ADD_MEMBER: 'Aggiungi Membro',
      INVITE_MEMBER: 'Invita Membro',
      ADD_GUEST: 'Aggiungi Ospite',
      ORGANIZATION: 'Organizzazione',
      HEALTH_PROFESSIONAL: 'Professionista sanitario',
      ASSIGN_PATIENTS: 'Assegna utenti',
      ASSIGN_HEALTH_PROFESSIONALS:
        'Assegnazione di professionisti della salute',
      ASSIGN_MEMBERS: 'Assegnare Membri',
      ASSIGN_GUESTS: 'Assegnare Ospiti',
      PATIENT: 'Utente',
      EDIT_PROFILE: 'Modifica profilo',
      SELECT_ORGANIZATION: 'Seleziona organizzazione',
      UPLOAD_FILE: 'Carica un file per',
      GAME_FILE: 'File di gioco',
      ALLOWED_FILE_TYPES: 'Tipi di file consentiti: zip',
      UPDATE_PASSWORD: 'Cambia la password',
      CREATE_SESSION: 'Crea Sessione',
      ASSIGN_SESSION_TEMPLATE: 'Assegna modello di sessione',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      INACTIVE_SUBSCRIPTION: 'Inactive Subscription',
      EDIT_INFORMATION: 'Modifica informazioni',
      INVOICE_INFO: 'Info fattura',
      ADD_QUESTIONNAIRE_TEMPLATE: 'Aggiungi modello di questionario',
      QUESTIONNAIRE_TEMPLATE: 'Modello di questionario',
      WARNING: 'Attenzione',
      ASSIGN_QUESTIONNAIRE_TEMPLATE_WARNING:
        'Per assegnare un questionario, è necessario creare almeno una domanda.',
      ADD_NOTE: 'Create Note',
      ASSIGN_QUESTIONNAIRE_TEMPLATE: 'Assegnazione del modello di questionario',
      QUESTIONNAIRE_TEMPLATE_PREVIEW_WARNING:
        "Per visualizzare l'anteprima di un questionario, questo deve avere almeno una sezione e una domanda.",
      RESET_PASSWORD: 'Rigenerare la Password Unica',
      GENERATE_REPORT: 'Genera Report',
      ACTIVITY_DISPLAY_OPTIONS: 'Opzioni visualizzazione attività',
      UPGRADE_ORGANIZATION: 'Organizzazione di Aggiornamento',
      ADD_RESELLER_ADMIN: 'Aggiungi amministratore',
      GAME_VARIATIONS: 'Variazioni di gioco',
      ASSIGN_PRIVATE_GAME: 'Assegnazione del gioco privato',
      ASSIGN_PUBLIC_GAME: 'Assegnazione del gioco pubblico',
      MEETING_MEMBERS: 'Meeting Members',
    },
    ERROR: {
      IMAGE: "Il file selezionato non è un'immagine",
      RESOURCE:
        "Non è possibile accedere a questa risorsa se si è già effettuato l'accesso",
      GENERAL:
        'Spiacente, sembra che siano stati rilevati degli errori, si prega di riprovare',
      FILE: 'Il file selezionato non è supportato',
      PAGE_NOT_FOUND: 'Pagina non trovata',
      PAGE_NOT_FOUND_BODY: "L'URL richiesto non è stato trovato",
    },
    BUTTONS: {
      CREATE: 'Crea nuovo',
      CONFIRM_ACTION: 'Conferma Azione',
      ADD_EXERCISES: 'Aggiungi Giochi',
      DELETE: 'Elimina',
      VIEW: 'Vista',
      APPLY: 'Applica',
      EDIT: 'Modifica',
      BACK: 'Indietro',
      CANCEL: 'Annullare',
      CONTINUE: 'Continua',
      LOGIN: 'Accesso',
      REGISTER: 'Registrazione',
      SAVE: 'Salvare',
      SUBMIT: 'Invia',
      ACTIVATE: 'Attiva',
      DEACTIVATE: 'Disattivare',
      PLAY: 'Riproduci',
      CONFIRM: 'Conferma',
      ACCEPT: 'Accetta',
      DECLINE: 'Declina',
      NEXT_STEP: 'Passo successivo',
      PREVIOUS_STEP: 'Precedente',
      ADD: 'Aggiungi nuovo',
      RESET: 'Reset',
      UPLOAD_PHOTO: 'Carica foto',
      EDIT_PHOTO: 'Modifica foto',
      RESEND_INVITATION: 'Reinvio invito',
      ASSIGN: 'Assegnazione',
      EDIT_PROFILE: 'Modifica profilo',
      DISCARD: 'Scarta',
      DONE: 'Fatto',
      ADD_ORGANIZATION: 'Aggiungi organizzazione',
      ADD_PATIENT: 'Aggiungi utente',
      ADD_MEMBER: 'Aggiungi Membro',
      ADD_GUEST: 'Aggiungi Ospite',
      ADD_HEALTH_PROFESSIONAL: 'Aggiungi professionista sanitario',
      ADD_ORGANIZATION_ADMIN: 'Aggiungi amministratore organizzazione',
      ADD_SESSION: 'Aggiungi Sessione',
      ASSIGN_PATIENTS: 'Assegna utenti',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assegna professionisti della salute',
      ASSIGN_MEMBERS: 'Assegnare Membri',
      ASSIGN_GUESTS: 'Assegnare Ospiti',
      ACTIONS: 'Azioni',
      LOADING: 'Caricamento...',
      GO_TO_HOMEPAGE: 'Vai Alla Pagina Principale',
      ASSIGN_NEW_SESSION: 'Assegna New Session',
      ASSIGN_NEW_QUESTIONNAIRE: 'Assegnazione di un nuovo questionario',
      CLOSE: 'Chiusura',
      SHOW_MORE: 'Mostra di più',
      SHOW_LESS: 'Mostra meno',
      CONFIRM_SUBSCRIPTION: 'Confirm Subscription',
      REJECT_SUBSCRIPTION: 'Reject Subscription',
      NEW_SUBSCRIPTION: 'Nuova Sottoscrizione',
      ADD_QUESTIONNAIRE: 'Aggiungi questionario',
      PREVIEW: 'Anteprima',
      ADD_ANSWER: 'Aggiungi Opzione',
      GOT_IT: 'Fatto',
      ADD_NOTE: 'Aggiungi nota',
      EXPORT_RESULTS: 'Εsportare i risultati',
      SAVE_AND_CONTINUE: 'Salvare e Continuare',
      RESET_ONE_TIME_PASSWORD: 'Rigenerare la Password Unica',
      CREATE_BENEFICIARY: 'Creare un Utente',
      CREATE_MEMBER: 'Creare un Membro',
      CREATE_GUEST: 'Creare un Ospite',
      CHANGE_PASSWORD: 'Cambia la Password',
      COMPLETE: 'Completo',
      START_NOW: 'Parti Ora!',
      REPLAY: 'Rigiocare',
      START_SESSION: 'Avvia sessione',
      GENERATE_REPORT: 'Genera Report',
      CLEAR_GAME_CACHE: 'Clear Game Cache',
      ADD_RESELLER_ADMIN: 'Aggiungi amministratore',
      CREATE_GROUP: 'Creare un gruppo',
      ADD_MEETING: 'Avviare una nuova riunione',
      STOP: 'Fine Riunione',
      START_MEETING: 'Avviare Riunione',
    },
    INPUT: {
      NAME: 'Nome',
      EMAIL: 'Email',
      EMAIL_USERNAME: 'Email (Nome utente)',
      PLACE: 'Luogo',
      VAT: 'IVA',
      FIRST_NAME: 'Nome',
      STREET_ADDRESS: 'Indirizzo stradale',
      LAST_NAME: 'Cognome',
      FULL_NAME: 'Nome completo',
      PASSWORD: 'Password',
      PATIENT_LIST: 'Elenco dei utenti',
      HEALTH_PROFESSIONAL_LIST: 'Elenco dei professionisti della salute',
      ORGANIZATION_NAME: "Nome dell'organizzazione",
      ORGANIZATION_EMAIL: "Email di contatto per la fatturazione dell'azienda",
      ORGANIZATION_ACTIVITY: 'Attività',
      CONFIRM_PASSWORD: 'Conferma Password',
      CITY: 'Città',
      HEALTH_PROFESSIONAL: 'Professionista sanitario',
      POSTAL_CODE: 'Codice postale',
      COUNTRY: 'Paese',
      ADDRESS: 'Indirizzo',
      COMPANY: 'Azienda',
      BIRTH_DATE: 'Data di nascita',
      WEBSITE: 'Sito web',
      PHONE: 'Numero di telefono',
      ROLE: 'Ruolo',
      SERVICE: 'Servizio',
      PREFERRED_LANGUAGE: 'Lingua preferita',
      PREFERRED_ACCOUNT_TYPE: 'Tipo di Account Preferito',
      ADDRESS_INFO: "Informazioni sull'indirizzo",
      COMPANY_NAME: 'Nome della società',
      DESCRIPTION: 'Descrizione',
      TYPE: 'Tipologia',
      PRICE: 'Prezzo',
      FEATURES: 'Caratteristiche',
      TITLE: 'Titolo',
      TAGS: 'Tag',
      ACCOUNT_STATUS: "Stato dell'account",
      IMAGE: 'Immagine',
      VERSION: 'Versione',
      ACTIVITY: 'Attività',
      OLD_PASSWORD: 'Vecchia Password',
      NEW_PASSWORD: 'Nuova Password',
      CONFIRM_NEW_PASSWORD: 'Conferma la nuova Password',
      SESSION_NAME: 'Nome Sessione',
      INFO: 'Info',
      HEALTH_PROFESSIONAL_INFO: 'Informazioni sul professionista della salute',
      PATIENT_INFO: 'Info Utente',
      AGREE_THE: 'Accetto',
      TERMS_AND_OCNDITIONS: 'Termini e condizioni',
      SESSION_TEMPLATE_LIST: 'Elenco modelli di sessione',
      SAVE_AS_TEMPLATE: 'Salva come modello',
      BIRTH_YEAR: 'Αnno di Νascita',
      SEX: 'Genere',
      ACCOUNT_TYPE: 'Tipo di account',
      HEALTH_PROFESSIONALS: 'Professionisti della salute',
      BENEFICIARIES: 'Utenti',
      SUBSCRIPTION_DURATION: 'Subscription Duration',
      START_DATE: 'Date Inizio',
      EXTENSION_DURATION: 'Extension Duration',
      STARTING_LICENSE: 'Licenza Iniziale',
      ANNUAL_FEE: 'Annual Fee',
      SUPPORT_SERVICES: 'Servizi di supporto',
      MONTHLY_COST_PER_BENEFICIARY: 'Monthly Cost per Beneficiary',
      NOTES: 'Note',
      LATEST_OCCUPATION: 'Ultima occupazione',
      EDUCATION_YEARS: 'Istruzione in anni',
      QUESTIONNAIRE_NAME: 'Nome del questionario',
      WRITE_YOUR_ANSWER: 'Write your answer',
      REQUIRED: 'Obbligatorio',
      SECTION_NAME: 'Nome della sezione',
      QUESTION: 'Domanda',
      QUESTIONNAIRE_QUESTION_TEXT_PLACEHOLDER: 'Risposta scritta...',
      QUESTIONNAIRE_QUESTION_INTEGER_PLACEHOLDER:
        'La risposta deve contenere solo numeri.',
      HEALTH_PROFESSIONAL_NOTES: 'Health Professional notes',
      NOTE_TEXT: 'Note text',
      QUESTIONNAIRE_TEMPLATE_LIST: 'Elenco dei modelli di questionario',
      USERNAME: 'Username',
      ONE_TIME_PASSWORD: 'Password Unica',
      CREATE_BENEFICIARY_CONSENT:
        "Ho il consenso dell'utente per procedere con la registrazione dei suoi dati personali e la sua iscrizione alla piattaforma Eligence",
      I_HAVE_THE_BENEFICIARY_CONSENT:
        "Ho il consenso dell'utente per procedere alla modifica della sua password",
      LOGIN_EMAIL_USERNAME: 'Email / Username',
      STAYING_STATUS: 'Descrivete la vostra attuale situazione abitativa',
      SELECT_TIME_PERIOD: 'Periodo di tempo',
      SELECT_TIME_PERIOD_PLACEHOLDER: 'Periodo di tempo',
      CURRENT_PASSWORD: 'Password attuale',
      ACTIVITY_DISPLAY_OPTION: 'Opzione visualizzazione attività',
      GROUP_NAME: 'Nome del Gruppo',
      MEETING_NAME: 'Nome della Riunione',
    },
    PLACEHOLDERS: {
      ALL: 'Tutti',
      TOTAL_ELEMENTS: 'Elementi Totali',
      SELECT_RESELLERS: 'Seleziona Rivenditore',
    },
    SEARCH_HEADERS: {
      SEARCH: 'Cerca',
    },
    TABLE_HEADERS: {
      FIRST_NAME: 'Nome',
      LAST_NAME: 'Cognome',
      NOTE: 'Note',
      PATIENTS: 'Utenti',
      SESSIONS: 'Sessioni',
      USER: 'Utente',
      EMAIL: 'Email',
      JOINED_DATE: 'Data di adesione',
      COMPANY: 'Azienda',
      NAME: 'Nome',
      STATUS: 'Stato',
      EXECUTIONS: 'Esecuzioni',
      COMPLETE_SESSIONS: 'Sessioni complete',
      LAST_LOGIN: 'Ultimo accesso',
      ACCOUNT_TYPE: 'Tipo di account',
      ID: 'ID',
      CATEGORY: 'Categoria',
      PRODUCT: 'Prodotto',
      ACTIONS: 'Azioni',
      DESCRIPTION: 'Descrizione',
      CREATED: 'Creato',
      COMPLETED: 'Completato',
      COUNTRY: 'Paese',
      LANGUAGE: 'Lingua',
      ROLE: 'Ruolo',
      ADDRESS: 'Indirizzo',
      POSTAL_CODE: 'Codice postale',
      CITY: 'Città',
      ESCORT: 'Escort',
      ADMIN: 'Amministratore',
      DATE: 'Data',
      TIME: 'Ora',
      DURATION: 'Durata',
      ADDED: 'Aggiunto',
      ORGANIZATION: 'Organizzazione',
      EXERCISE: 'Gioco',
      VERSION: 'Versione',
      LEVELS: 'Livelli',
      COGNITIVE: 'Abilità Cognitive',
      CATEGORIES: 'Categorie',
      ENGINE: 'Motore',
      HEALTH_PROFESSIONAL: 'Professionista della salute',
      ASSIGNED_PATIENTS: 'Utenti assegnati',
      PATIENT: 'Utente',
      OPEN_SESSIONS: 'Sessioni aperte',
      SESSION: 'Sessione',
      ORDER: 'Ordine',
      GAMES: 'Giochi',
      LAST_EDIT: 'Ultima Modifica',
      CREATOR: 'Creatore',
      ADDED_EXERCISES: 'Giochi Aggiunti',
      DIFFICULTY: 'Difficoltà',
      ASSIGNED_BY: 'Assegnato da',
      GAME: 'Gioco',
      SCORE: 'Punteggio',
      PROGRESS: 'Progressi',
      BENEFICIARIES: 'Utenti',
      LATEST_EXECUTION: 'Ultima Esecuzione',
      TYPE: 'Tipologia',
      STARTED: 'Data inizio',
      ENDS: 'Data fine',
      HEALTH_PROFESSIONALS: 'Professionisti della salute',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Professionisti della salute assegnati',
      QUESTIONNAIRE: 'Modelli di questionario',
      DATE_ASSIGNED: 'Data Assegnata',
      DATE_COMPLETED: 'Data di Completamento',
      SECTIONS: 'Sezioni',
      START_DATE: 'Data di inizio',
      EXTENSION_DAYS: 'Giorni di estensione',
      END_DATE: 'Data di fine',
      EXTENSION_DATE: 'Data di estensione',
      TOTAL_COST_OF_SUBSCRIPTION: "Costo totale dell'abbonamento",
      DURATION_OF_SUBSCRIPTION: "Durata dell'abbonamento",
      TERMINATION_DATE: 'Data di terminazione',
      INVITATION_SENT: 'Invito inviato',
      SUBSCRIPTION_SENT: 'Abbonamento inviato',
      ACTIVITY_DISPLAY_OPTION: 'Opzione visualizzazione attività',
      INVITED_BY: 'Ιnvitato da',
      GROUP: 'Gruppo',
      MEMBERS: 'Membri',
      GUESTS: 'Ospiti',
      MEETINGS: 'Riunioni',
      MEETING: 'Riunione',
      VARIATIONS: 'Variazioni',
      ACTIVATED: 'Attivati',
      ASSIGNMENT: 'Assegnazione',
      INDIVIDUAL_EXECUTIONS: 'Esecuzioni (individuali)',
      GROUP_EXECUTIONS: 'Esecuzioni (Gruppi)',
    },
    VALIDATION: {
      INVALID: '{{name}} non è valido',
      REQUIRED: '{{name}} è obbligatorio',
      MIN_LENGTH: '{{name}} deve avere almeno 3 simboli',
      MAX_LENGTH: '{{name}} deve avere al massimo 256 simboli',
      MAX_LENGTH_NOTES: '{{name}} deve avere al massimo 480 simboli',
      MIN_LENGTH_PASS: '{{name}} deve avere almeno 8 simboli',
      AGREEMENT_REQUIRED: "È richiesta l'accettazione di termini e condizioni",
      NOT_FOUND: 'Il {{name}} richiesto non è stato trovato',
      INVALID_LOGIN: 'I dati di accesso non sono corretti',
      REQUIRED_FIELD: 'Campo obbligatorio',
      MIN_LENGTH_FIELD: 'Lunghezza minima del campo:',
      MAX_LENGTH_FIELD: 'Lunghezza massima del campo:',
      INVALID_FIELD: 'Campo non valido',
      MUST_MATCH: 'La password e la conferma della password non corrispondono',
      MUST_MATCH_PIN: 'I campi Pin e Conferma Pin non corrispondono',
      NO_PRIMARY: 'Non è stato impostato un {{name}} primario',
      NO_STATUS: 'Non è stato impostato lo stato di {{name}}',
      MANY_PRIMARY: 'Hai impostato più di un {{name}} primario',
    },
    MENU: {
      SECTION: {
        DASHBOARD: 'Dashboard',
        SYSTEM: 'Sistema',
      },
      HOME: 'Home',
      USER_PROFILE: 'Profilo personale',
      ACCOUNT_SETTINGS: 'Impostazioni account',
      LANGUAGE: 'Lingua',
      LOGOUT: 'Logout',
      NOTIFICATIONS: 'Notifiche',
      SUBSCRIPTIONS: 'Sottoscrizioni',
      ORGANIZATION: 'Organizzazione',
      SESSIONS: 'Sessioni',
      GAMES: 'Giochi',
      GAMES_MANAGEMENT: 'Gestione dei giochi',
      PATIENTS: 'Utenti',
      GUESTS: 'Ospiti',
      MEMBERS: 'Membri',
      ORGANIZATIONS: 'Organizzazioni',
      MY_ORGANIZATION: "Gestione dell'organizzazione",
      ADMINS: 'Amministratori',
      HEALTH_PROFESSIONALS: 'Professionisti della salute',
      SIGN_OUT: 'Esci',
      QUESTIONNAIRES: 'Questionari',
      ELIGENCE_SESSION_TEMPLATES: 'Sessioni',
      TEMPLATES: 'Modelli',
      BY_ELIGENCE: 'Da Eligence',
      RESELLERS: 'Rivenditori',
      HELP: 'Aiuto',
      GROUPS: 'Gruppi',
    },
    FOOTER: {
      PRIVACY_POLICY: 'Privacy Policy',
      CONTACT: 'Contatto',
      TERMS_AND_CONDITIONS: 'Termini e condizioni',
      COOKIE_POLICY: 'Cookie Policy',
      PURCHASE: 'Acquisto',
    },
    GAME_DIFFICULTY: {
      EASY: 'Facile',
      INTERMEDIATE: 'Intermedio',
      HARD: 'Difficile',
    },
    GAME_ACTIVITY_TYPE: {
      SOLO: 'Individuale',
      GROUP_MEETING: 'Riunione di Gruppo',
    },
    GAME_TIME_PERIOD: {
      TODAY: 'Oggi',
      THIS_WEEK: 'Questa settimana',
      THIS_MONTH: 'Questo mese',
      LAST_7_DAYS: 'Ultimi 7 Giorni',
      LAST_30_DAYS: 'Ultimi 30 Giorni',
      CUSTOM: 'Αltro',
    },
    GAME_COGNITIVE_SKILL: {
      MEMORY: 'Memoria',
      LANGUAGE: 'Linguaggio',
      ATTENTION: 'Attenzione',
      CONSTRUCTIVE_ABILITY: 'Abilità costruttiva',
      EXECUTIVE_FUNCTIONS: 'Funzioni esecutive',
      LOGICAL_REASONING: 'Ragionamento Logico',
      ORIENTATION: 'Orientamento',
    },
    GROUP_BENEFICIARY_TYPE: {
      GUEST: 'Ospiti',
      NON_GUEST: 'Membri',
    },
    WIZARD: {
      ACCOUNT_TYPE: 'Tipo di account',
      ACCOUNT_TYPE_DESCRIPTION: 'Scegli il tipo di account',
      ORGANIZATION_INFO: "Informazioni sull'organizzazione",
      ORGANIZATION_INFO_DESCRIPTION:
        'Imposta le informazioni sulla tua organizzazione',
      INVOICING_DETAILS: 'Dettagli fatturazione',
      INVOICING_DETAILS_DESCRIPTION: 'Imposta i dettagli della fattura',
      SETUP_ACCOUNT: 'Imposta account',
      SETUP_ACCOUNT_DESCRIPTION: 'Imposta i dettagli del tuo account',
      COMPLETED: 'Completato',
      CHOOSE_ACCOUNT_TYPE: 'Scegliere il tipo di conto',
      SMALL_ORGANIZATION: 'Piccola organizzazione',
      SMALL_ORG_HEALTH_PROF_PATIENTS:
        '1 professionista della salute / 1-10 utenti',
      MEDIUM_ORGANIZATION: 'Organizzazione media',
      MEDIUM_ORG_HEALTH_PROF_PATIENTS:
        '1-10 professionisti della salute / 1-50 utenti',
      BIG_ORGANIZATION: 'Grande organizzazione',
      BIG_ORG_HEALTH_PROF_PATIENTS:
        '1-50 professionisti della salute / 1-200 utenti',
      REGISTRATION:
        "All'utente è stata inviata un'e-mail per attivare il suo account",
      DONE: "L'account è stato attivato.",
      DONE_DESCRIPTION:
        'Fare clic sul pulsante sottostante per effettuare il login!',
      MERGE_DONE:
        "Sei già registrato in un'altra organizzazione. Ogni volta che si accede, si può scegliere con quale organizzazione interagire",
      SESSION_INFO: 'Informazioni sulla sessione',
      SESSION_INFO_STEPPER: 'Nome della sessione',
      EXERCISES: 'Giochi',
      EXERCISES_STEPPER: 'Aggiungi Giochi',
      COMPLETION: 'Completamento',
      COMPLETION_STEPPER: 'Conclusione!',
      SESSION_INFO_DESCRIPTION:
        'Date un nome alla sessione e prendete appunti, se volete!',
      SESSION_EXERCISES: 'Esercizi',
      SESSION_EXERCISES_DESCRIPTION:
        'Aggiungere giochi alla sessione e modificarla',
      ADD_EXERCISES: 'Aggiungi Giochi',
      ADDED_EXERCISES: 'Giochi aggiunti',
      CREATE_SESSION_COMPLETION: 'Un ultimo passo!',
      CREATE_SESSION_COMPLETION_DESCRIPTION: 'Conclusione!',
      OVERVIEW: 'Panoramica',
      OVERVIEW_BENEFICIARIES: 'Panoramica dei Beneficiari',
      OVERVIEW_SESSIONS: 'Panoramica delle Sessioni',
      HEALTH_PROFESSIONAL_INFO: 'Informazioni sul professionista della salute',
      PATIENT_INFO: 'Informazioni sul utente',
      SESSION_NOTES: 'Note',
      SESSION_NOTES_DESCRIPTION: 'Aggiungi Informazioni!',
      ADD_ORGANIZATION_INFO_DESCRIPTION: 'Choose your Account type',
      SUBSCRIPTION_DETAILS: 'Subscription Details',
      SUBSCRIPTION_DETAILS_DESCRIPTION: 'Setup Subscription Details',
      NOTES: 'Note',
      NOTES_DESCRIPTION: 'Add notes',
      OVERVIEW_DESCRIPTION: 'Have a last look',
      GROUP_INFO: 'Info sul gruppo',
      BENEFICIARIES: 'Utenti',
      GROUP_INFO_DESCRIPTION:
        'Date un nome al vostro gruppo e aggiungete eventuali note, se volete!',
      GROUP_BENEFICIARIES_DESCRIPTION: 'Aggiungi Utenti al tuo gruppo',
      ADD_BENEFICIARIES: 'Aggiungi Utenti',
      ADDED_BENEFICIARIES: 'Utenti aggiunti',
      CREATE_GROUP_COMPLETION: 'Un ultimo passo!',
      CREATE_GROUP_COMPLETION_DESCRIPTION: 'Conclusione!',
      MEETING_INFO: 'Informazioni sulla Riunione',
      MEMBERS: 'Membri',
      SESSIONS: 'Sessioni',
      MEETING_INFO_DESCRIPTION:
        'Date un nome al vostro meeting e aggiungete eventuali note, se volete',
      MEETING_SESSIONS_DESCRIPTION: 'Descrizione delle Sessioni della Riunione',
      ADD_SESSIONS: 'Aggiungi Sessioni',
      ADDED_SESSIONS: 'Sessioni Aggiunte',
      GAMES: 'Giochi',
      ASSIGN_GAMES: 'Assegnazione di giochi',
    },
    INFO: {
      INFO: 'Se avete bisogno di ulteriori informazioni, consultate',
      HELP: 'Pagina di aiuto',
    },
    ACTIONS: {
      ACTIONS: 'Azioni',
      VIEW: 'Visualizza',
      VIEW_PROFILE: 'Visualizza Profilo',
      ACTIVATE: 'Attiva',
      DEACTIVATE: 'Disattiva',
      DELETE: 'Elimina',
      ASSIGN_PATIENTS: 'Assegna utenti',
      ASSIGN_HEALTH_PROFESSIONALS: 'Assegnazione di professionisti sanitari',
      RESEND_INVITATION: "Reinvio dell'invito",
      PREVIEW: 'Anteprima',
      UPLOAD_FILE: 'Carica partita',
      REMOVE_PATIENT: 'Rimuovi utente',
      SET_TO_ACTIVE: 'Imposta su attivo',
      EDIT: 'Modifica',
      REMOVE: 'Rimuovi',
      DA_TEMPALTE: 'Da Modello',
      CREATE_NEW: 'Crea Nuovo',
      CLONE: 'Clona',
      CLOSE: 'Chiudi',
      CANNOT:
        'Non è possibile eseguire azioni su questa sessione poiché è assegnata da un altro professionista sanitario',
      REMOVE_HEALTH_PROFESSIONAL: 'Rimuovi Professionista Sanitario',
      AMENDMENT: 'Amendment',
      TERMINATE: 'Terminate',
      NEW_SUBSCRIPTION: 'New Subscription',
      RESEND_EMAIL: 'Resend email',
      RENEW: 'Renew',
      ASSIGN: 'Assegna',
      UNASSIGN: 'Disassegnare',
      CANCEL: 'Cancel',
      INVITE: 'Invita',
      CREATE: 'Crea',
      RESET_PASSWORD: 'Rigenerare la Password Unica',
      ACTIVITY_DISPLAY_OPTIONS: 'Opzioni visualizzazione attività',
      UPGRADE: 'Aggiornamento',
      VIEW_MEMBERS: 'Visualizza i membri',
      START_MEETING: 'Avvia Riunione',
    },
    AUTH: {
      SIGN_IN: 'Accedi',
      NEW_HERE: 'Nuovo qui?',
      SIGNUP: 'Iscriviti',
      FORGOT_BUTTON: 'Password dimenticata?',
      ABOUT: 'Informazioni',
      CONTACT: 'Contatto',
      CONTACT_US: 'Contattaci',
      FORGOT_PASSWORD: 'Password dimenticata',
      RESET_PASSWORD: 'Reimposta password',
      SET_PASSWORD: 'Imposta password',
      SETUP_YOUR_NEW_PASSWORD: 'Impostazione della nuova password',
      AN_EMAIL_IS_REQUIRED: "È richiesta un'e-mail.",
      AN_EMAIL_IS_REQUIRED_DESCRIPTION:
        "Se il vostro account è stato creato con un nome utente, contattate il vostro operatore sanitario o l'amministratore della vostra organizzazione.",
    },
    PROFILE: {
      OVERVIEW: 'Panoramica',
      SETTINGS: 'Impostazioni',
      NOTES: 'Note',
      EDIT_PROFILE: 'Modifica profilo',
      DETAILS: 'Dettagli',
      INFORMATION: 'Informazioni',
      NAME: 'Nome',
      FULL_NAME: 'Nome completo',
      ROLE: 'Ruolo',
      CONTACT_PHONE: 'Telefono di contatto',
      EMAIL: 'Email',
      COUNTRY: 'Paese',
      POSTAL_CODE: 'Codice postale',
      ADDRESS: 'Indirizzo',
      TAX_ID: 'Codice fiscale',
      STATUS: 'Stato',
      EDIT: 'Modifica',
      PASSWORD_RESET: 'Reset password',
      RESEND_PASSWORD_INVITATION: 'Invito a reinviare la password',
      ASSIGNED_PATIENTS: 'Utenti assegnati',
      ACCOUNT_ID: 'ID account',
      BILLING_EMAIL: 'Email di fatturazione',
      LAST_EDIT: 'Ultima Modifica',
      CREATED_BY: 'Creato da',
      BILLING_ADDRESS: 'Indirizzo di fatturazione',
      ADMINS: 'Amministratori',
      PAYMENT_RECORDS: 'Record di pagamento',
      PAYMENT_METHODS: 'Metodi di pagamento',
      PERFORMANCE: 'Prestazioni',
      FIRST_NAME: 'Nome',
      LAST_NAME: 'Cognome',
      PHONE_NUMBER: 'Numero di telefono',
      PREFERRED_LANGUAGE: 'Lingua preferita',
      VAT: 'IVA',
      ACTIVITY: 'Attività',
      WEBSITE: 'Sito web',
      CREATED_SESSIONS: 'Sessioni create',
      EMAIL_UPDATE_TOOLTIP:
        'Siate consapevoli che il vostro nome utente sarà la vostra nuova e-mail',
      CHANGE_PASSWORD: 'Cambia la password',
      SESSIONS: 'Sessioni',
      ADDED_EXERCISES: 'Giochi aggiunti',
      SESSION_EXECUTIONS_TOOLTIP:
        'Questa sessione è stata eseguita {{number}} volte',
      BIRTH_YEAR: 'Αnno di Νascita',
      SEX: 'Genere',
      ASSIGNED_HEALTH_PROFESSIONALS: 'Professionisti della salute assegnati',
      ASSIGNED_MEMBERS: 'Membri Assegnati',
      ASSIGNED_GUESTS: 'Ospiti Assegnati',
      SUBSCRIPTIONS: 'Sottoscrizioni',
      CURRENT_SUBSCRIPTION: 'Sottoscrizione corrente',
      SUBSCRIPTIONS_HISTORY: 'Cronologia Sottoscrizioni',
      SUBSCRIPTION: 'Sottoscrizione',
      UPCOMING_SUBSCRIPTION: 'Sottoscrizione imminente',
      LATEST_OCCUPATION: 'Ultima occupazione',
      EDUCATION_YEARS: 'Istruzione in anni',
      EMAIL_USERNAME: 'Email (Nome utente)',
      INVOICE_INFO: 'Info fattura',
      EXECUTIONS: 'Esecuzioni',
      MEMBER_SINCE: 'Membro dal',
      QUESTIONNAIRES: 'Questionari',
      ASSIGNED: 'Assigned',
      COMPLETED: 'Completed',
      ANSWERS: 'Answers',
      PASSWORD: 'Password',
      USERNAME: 'Username',
      STAYING_STATUS: 'Descrivete la vostra attuale situazione abitativa',
      ACTIVITY_DISPLAY_OPTION: 'Opzione visualizzazione attività',
      GAMES: 'Giochi',
      MEETINGS: 'Riunioni',
      MEMBERS: 'Membri',
      PUBLIC: 'Pubblico',
      PRIVATE: 'Privato',
    },
    GENERAL: {
      USER: 'Utente',
      PATIENT: 'Utente',
      MEMBER: 'Membro',
      GUEST: 'Ospite',
      HEALTH_PROFESSIONAL: 'Professionista della salute',
      GAME: 'Gioco',
      PROFILE: 'Profilo',
      ORGANIZATION: 'Organizzazione',
      ORGANIZATION_ADMIN: "Amministratore dell'organizzazione",
      NO_ENTRIES: 'Nessuna voce trovata',
      SESSION: 'Sessione',
      GAMES: 'Giochi',
      SESSION_TEMPLATE: 'Modello di Sessione',
      SUBSCRIPTION: 'Sottoscrizione',
      SUBSCRIPTION_EMAIL: 'Subscription email',
      ASSIGNED_QUESTIONNAIRE: 'Questionari assegnati',
      QUESTIONNAIRE_TEMPLATE: 'Modello di questionario',
      NOTE: 'Note',
      COPIED: 'Copiato!',
      CONGRATULATIONS: 'Congratulazioni',
      DESCRIPTION: 'Descrizione',
      SAME_COGNITIVE_GAMES: 'Giochi che esercitano la stessa abilità cognitiva',
      SELECT_DIFFICULTY: 'Seleziona livello di difficoltà',
      GROUP: 'Gruppo',
      MEETING: 'Riunione',
    },
    GRAPHS: {
      SCORE: 'Punto',
      TIME: 'Volta',
      EXECUTIONS_PER_GAME_COGNITIVE_SKILL_AND_DIFFICULTY:
        'Esecuzioni per Abilità Cognitive e Difficoltà',
      EXECUTIONS_PER_GAME_TITLE: 'Esecuzioni per Gioco',
      AVERAGE_SCORE_PER_GAME_TITLE: 'Punteggio Medio per Gioco',
      EXECUTIONS_PER_DAY_TITLE: 'Esecuzioni al Giorno',
      COGNITIVE_SKILL_AVERAGE_SCORE_PER_DAY_TITLE:
        'Evoluzione del Punteggio Medio',
      TOTAL_ACTIVITY_TIME_PER_DAY_TITLE:
        'Tempo totale di attività al giorno (minuti)',
      GAME: 'Gioco',
      TOTAL: 'Totale',
    },
    ACTIVITY: {
      ACTIVITY_LOGS: 'Registri attività',
      EXECUTED_GAME: 'Gioco eseguito',
      ADDED: 'Aggiunt: ',
      EXECUTED_SESSION: 'Sessione eseguita',
    },
    SESSION: {
      MY_SESSIONS: 'Le mie Sessioni',
      SESSION_COMPLETE: 'La sessione è stata completata',
      ABANDONED: 'Abbandonato',
      SKIPPED: 'Saltata',
      PLAYED: 'Riprodotto',
      PENDING: 'In Attesa',
      ASSIGNED_SESSIONS: 'Sessioni Assegnate',
      DEFAULT_PUBLIC_INFO:
        'Ciao! Questa è una sessione creata appositamente per lei! La preghiamo di completarla o di contattare il suo medico curante se ha ulteriori domande.',
      DOCTOR_NOTES: 'Μessaggio del professionista della salute',
      SAMPLE_DOCTOR_NOTES:
        'Gentile {{name}}, questa è una sessione creata appositamente per lei! La preghiamo di completarla o di contattare il suo medico curante se ha ulteriori domande.',
    },
    STATUS: {
      ACTIVE: 'Attivo',
      INACTIVE: 'Inattivo',
      INVITED: 'Invitato',
    },
    SESSION_STATUS: {
      ACTIVE: 'Attivo',
      ASSIGNED: 'Assegnato',
      CLOSED: 'Chiuso',
    },
    ACCOUNT_TYPE: {
      BUSINESS_TO_BUSINESS: 'B2B',
      BUSINESS_TO_PROFESSIONAL: 'B2P',
      RESELLER: 'Rivenditore',
      DEMO: 'Demo',
      PAID: 'Pagato',
    },
    ROLE: {
      ROLE_SYSTEM_ADMINISTRATOR: 'Amministratore di sistema',
      ROLE_ORGANIZATION_OWNER: 'Proprietario Organizzazione',
      ROLE_ORGANIZATION_ADMINISTRATOR: 'Amministratore Organizzazione',
      ROLE_HEALTH_PROFESSIONAL: 'Professionista sanitario',
      ROLE_PATIENT: 'Utente',
      ROLE_INTERNAL_CONTACT: 'Contatto interno',
      ROLE_EXTERNAL_CONTACT: 'Contatto esterno',
      ROLE_HEALTH_PROFESSIONAL_OWNER:
        'Proprietario Organizzazione/Professionista sanitario',
      ROLE_HEALTH_PROFESSIONAL_ADMINISTRATOR:
        'Amministratore Organizzazione/Professionista sanitario',
      ROLE_RESELLER_OWNER: 'Reseller Owner',
      ROLE_RESELLER_ADMINISTRATOR: 'Administrator Reseller',
    },
    SEX: {
      MALE: 'Μaschio',
      FEMALE: 'Femmina',
      OTHER: 'Altro',
      NO_ANSWER: 'Preferisco non indicare',
    },
    ANALYTICS: {
      OVERVIEW_TITLE: 'Ciao Admin',
      OVERVIEW_DESCRIPTION: "Dai un'occhiata ai tuoi numeri",
      EXECUTIONS: 'Esecuzioni',
      HOURS: 'Ore',
      BENEFICIARIES: 'Utenti',
      HEALTH_PROFESSIONALS: 'Professionisti Sanitario',
      MOST_PLAYED: 'Più giocato',
      MOST_LEAST_PLAYED_DESCRIPTION: 'Ultimi Aggiornamenti sui Giochi',
      LEAST_PLAYED: 'Meno giocato',
      ACTIVE_LAST_30_DAYS: 'Attivi negli ultimi 30 giorni',
      GAMES_ACTIVITY: 'Attività di Gioco',
      GAMES_ACTIVITY_DESCRIPTION: 'Esecuzioni Totali per Gioco e Categoria',
      AVERAGE: 'Totale',
      LATEST_UPDATE: 'Ultimo Aggiornamento: ',
      HOUR_SHORT: 'h',
      MINUTE_SHORT: 'm',
    },
    SUBSCRIPTION: {
      NUMBER_OF_HEALTH_PROFESSIONALS: 'Numero Professionisti Sanitari',
      NUMBER_OF_BENEFICIARIES: 'Numero Utenti',
      DURATION: 'Duration',
      START_DATE: 'Data Inizio',
      EXTENSION_DAYS: 'Giorni di estensione',
      END_DATE: 'Data fine',
      EXTENSION_DATE: 'Extension Date',
      STARTING_LICENSE: 'Licenza Iniziale',
      ANNUAL_FEE: 'Quota annuale',
      SUPPORT_SERVICES: 'Servizi di support',
      MONTHLY_COST_PER_BENEFICIARY: 'Costo mensile per utente',
      TOTAL_COST_OF_BENEFICIARIES: 'Costo totale Utenti',
      TOTAL_COST_OF_SUBSCRIPTION: 'Costo Totale Sottoscrizione',
      ORGANIZATION_TYPE: 'Tipologia di Organizzazione',
      SUBSCRIPTION_TYPE: 'Tipologia di Sottoscrizione',
      MONTHS: 'Mesi',
      DAYS: 'Days',
      REMAINING_DAYS: 'Remaining Days',
      HEALTH_PROFESSIONALS: 'Health Professionals',
      BENEFICIARIES: 'Utenties',
      NOTES: 'Note',
      DURATION_OF_SUBSCRIPTION: 'Durata Sottoscrizione',
      COSTS_VAT_DISCLAIMER: 'All costs do not include VAT, where applicable.',
      ACCEPT_MODAL_FOOTER:
        'If you do not want to confirm the subscription, please ignore or email us for more info at ',
      INACTIVE_SUBSCRIPOTION_MESSAGE:
        "You cannot access Eligence, since your organization's subscription is not active. For more information, contact the Eligence team.",
      DAYS_LEFT: 'Tempo residuo (in giorni)',
    },
    SUBSCRIPTION_TYPE: {
      NEW: 'Nuova',
      AMENDMENT: 'Amendment',
    },
    SUBSCRIPTION_STATUS: {
      ACTIVE: 'Attivo',
      EXPIRED: 'Scaduto',
      PENDING_CONSENT: 'In Attesa di Consenso',
      PENDING_AUTOMATION: "In attesa dell'automazione",
      REJECTED: 'Rifiutato',
      TERMINATED: 'Terminato',
    },
    QUESTIONNAIRE: {
      ASSIGNED_QUESTIONNAIRES: 'Questionari assegnati',
      SECTION: 'Sezione',
      QUESTION: 'Domanda',
      NOTE: 'Note',
      BY: 'by',
    },
    QUESTIONNAIRE_TEMPLATE_TYPE: {
      PLATFORM_GENERATED: 'Platform Generated',
      USER_GENERATED: 'User Generated',
    },
    ASSIGNED_QUESTIONNAIRE_STATUS: {
      ASSIGNED: 'Assegnato',
      IN_PROGRESS: 'In Progress',
      COMPLETED: 'Compilato',
      CANCELLED: 'Annullato',
    },
    QUESTIONNAIRE_QUESTION_TYPE: {
      TEXT: 'Testo Libero',
      INTEGER: 'Numerico',
      CHECKBOX: 'Scelta Multipla',
      RADIO: 'Scelta Singola',
      DROPDOWN: 'Menù a tendina',
    },
    ASSIGNED_QUESTIONNAIRE: {
      INFO: 'Il questionario è uno strumento consigliato dalla piattaforma Eligence. Attraverso il questionario è possibile raccogliere informazioni su un beneficiario o chiedere informazioni per valutare lo stato del beneficiario.',
      PROMPT:
        'Quando il questionario viene assegnato al beneficiario, tutti i giochi e le sessioni gratuite saranno disabilitati finché il beneficiario non lo avrà completato.',
    },
    CREATE_BENEFICIARY_WIZARD: {
      TITLE: 'Creare un utente',
      TITLE_MEMBER: 'Creare Membro',
      TITLE_GUEST: 'Creare Ospite',
      CREDENTIALS: 'Credenziali',
      PERSONAL_DETAILS: 'Informazioni',
      COMPLETION: 'Completamento',
      CHECK_AVAILABILITY: 'Verifica disponibilità',
      USERNAME_AVAILABLE: 'Username disponibile',
      USERNAME_UNAVAILABLE: 'Non disponibile, riprovare',
      OTP_SAVE_WARNING: 'Salvare la password per utilizzarla in seguito.',
      DONE: 'Siete pronti!',
      DONE_DESCRIPTION:
        'È stato creato un nuovo account per il utente. Durante il primo accesso, al utente verrà chiesto di cambiare la password generata.',
    },
    GAMES: {
      MY_GAMES: 'I miei giochi',
      ALL_GAMES: 'Tutti',
    },
    GAME_CATEGORY: {
      FOR_GROUPS: 'Per Gruppi',
      FOR_TWO: 'Per Due',
      INTERGENERATION: 'Intergenerazionale',
      CHALLENGING: 'Impegnativo',
    },

    STAYING_STATUS: {
      ALONE: 'Vivo da solo',
      WITH_HUSBAND_WIFE: 'Vivo con il mio partner',
      WITH_KIDS_GRANDKIDS: 'Vivo con i miei figli/nipoti',
      WITH_CARER: 'Vivo con la mia badante',
    },
    ACTIVITY_DISPLAY: {
      ALL: 'Vedi tutti',
      ONLY_SESSIONS: 'Solo sessioni',
      ONLY_GAMES: 'Solo giochi',
    },
    GAME_ASSIGN: {
      ASSIGNED: 'Assegnato',
      UNASSIGNED: 'Non Assegnato',
    },
    GAME_ACCESS: {
      PUBLIC: 'Pubblico',
      PRIVATE: 'Privato',
    },
    TERMS: {
      TEST: "<h1>Eligence</h1><h2>Condizioni di utilizzo</h2><br><h2>Avviso di esclusione di responsabilità (Disclaimer)</h2><p>Benvenuti in “Eligence”. “Eligence” (di seguito denominato “Servizio”) è una piattaforma web con contenuti specializzati (giochi) volti a rafforzare le capacità mentali e le funzioni cognitive. In collaborazione con i professionisti della salute può fornire esercizi a persone nelle prime fasi della demenza, così come per attività di logoterapia o ergoterapia.</p><p>Si prega di leggere e comprendere le presenti Condizioni (le “Condizioni”) prima di utilizzare questo Servizio. Utilizzando questo Servizio, l'utente accetta di essere vincolato e di rispettare i seguenti Termini. Se l'utente non è d'accordo con questi Termini, non deve accedere o utilizzare questo Servizio.   </p><p>Gli utenti sono gli individui che utilizzano e gestiscono il Servizio.</p><p>Per usufruire del servizio è necessario 1) essere un adulto con piena capacità giuridica, oppure 2) un minorenne (<18 anni) che abbia ottenuto il consenso scritto del proprio genitore o tutore legale, oppure 3) se non si ha piena capacità giuridica avere/produrre l'approvazione del proprio tutore legale.</p><p>“Eligence” si riserva il diritto di cambiare, modificare o cancellare qualsiasi documento, Informazioni o altro contenuto che compaia in questi Termini di volta in volta senza preavviso e a sua esclusiva discrezione. Tutte le modifiche hanno effetto immediato al momento della pubblicazione e si applicano a tutti gli accessi e all'utilizzo di questo Servizio da quel momento in poi. Ogni volta che si desidera utilizzare il Servizio, si prega di rivedere i presenti Termini per assicurarsi di aver compreso i termini che possono essere applicati in quel momento. </p><p>Il presente Servizio è gestito da “Maggioli SPA - Filiale di Grecia” (“Fornitore”) su risorse fornite da Maggioli. Gli elementi del Servizio (“Elementi del Servizio”), quali tecnologia, algoritmi, documenti, dati, altri servizi, processi e altre risorse, possono essere stati o essere attualmente forniti dal Fornitore o da terzi (“Altri Fornitori”). Il Fornitore e gli Altri Fornitori saranno chiamati collettivamente “Fornitori”.</p><p>Il Servizio stesso, così come i dati o le informazioni o altri elementi che possono diventare accessibili attraverso il Servizio, sono forniti “così come sono” e “come disponibili”. Il Fornitore si impegna a garantire l'accuratezza, la completezza o l'autenticità dei processi, dei dati e delle informazioni gestite e fornite dal Servizio. </p><p>l Fornitore si riserva il diritto di modificare, limitare o interrompere qualsiasi parte del Servizio a sua discrezione. Lo stesso vale per gli Altri Fornitori, a meno che non sia esplicitamente dichiarato il contrario.  </p><p>Il Fornitore non rivendica alcuna proprietà e non si assume alcuna responsabilità su dati, informazioni, contenuti, commenti, codici, processi o altri elementi caricati o incorporati nel Servizio da altri Utenti, se tali funzionalità sono offerte dal Servizio. Gli Utenti sono responsabili della protezione dei loro beni e dei loro dati personali da tali elementi presenti nel Servizio.</p><p>Al meglio delle intenzioni del Fornitore, vengono applicate misure di sicurezza ragionevoli e coerenti con la prassi applicabile al dominio di funzionamento del Servizio per proteggere le informazioni sensibili sotto il suo controllo da perdita, uso improprio e alterazione. Tuttavia, il Fornitore non può garantire la sicurezza dei luoghi fisici, dell'hardware, del software e delle reti, dei mezzi con cui le informazioni sensibili vengono gestite e trasmesse tra i computer e le applicazioni, o di qualsiasi Informazioni sensibile che possa essere ricevuta attraverso o in connessione con il Servizio.  </p><h2>Copyright</h2><p>Il Fornitore si riserva tutti i diritti sugli elementi che fornisce.</p><p>Alcuni Elementi del Servizio (Elementi di Servizio) sono stati forniti da terze parti (“Altri fornitori”) senza restrizione dei diritti. Il software GODOT è fornito “as is” – così com’è – senza garanzie di alcun tipo, esplicite o implicite, tra le quali garanzia di commerciabilità, idoneità a uno scopo particolare e non violazione. In nessun evento gli autori o detentori dei diritti d’autore saranno responsabili per qualsiasi reclamo, danno, o altra responsabilità, sia in un’azione contrattuale, che in un’azione illecita o altro, che derivi, scaturisca o sia relativa al software al suo utilizzo o ad altre operazioni relative allo stesso.</p><h2>Licenza</h2><p>Gli utenti a cui è stato concesso l'accesso tramite la procedura stabilita dal Fornitore, sono autorizzati a utilizzare il Servizio secondo i termini della licenza.</p><p>Il Fornitore garantisce la licenza d'uso di questo Servizio ai suoi Utenti, secondo i termini di questo Documento. L'accesso al Servizio può tuttavia essere limitato a causa della disponibilità delle risorse sottostanti. Il Fornitore può revocare questa licenza o modificarne i termini a propria discrezione senza preavviso agli Utenti.  È intenzione del Fornitore cercare di informare tempestivamente gli Utenti che accedono al Servizio prima di tale azione, tuttavia ciò non è garantito.</p><p>Gli utenti sono tenuti a fare un chiaro riferimento all'uso del Servizio per qualsiasi prodotto o servizio che possa essere creato in base ai risultati o all'uso di questo Servizio.</p><p>In qualsiasi momento e senza preavviso, il Fornitore può limitare l'accesso al Servizio a qualsiasi persona, area geografica o giurisdizione scelta dal Fornitore, a sua esclusiva discrezione.</p><h2>Utilizzo del Servizio</h2><p>Il Fornitore non dichiara né garantisce che il Servizio sia appropriato o disponibile per l'uso in una particolare giurisdizione. Gli utenti che si iscrivono al Servizio lo fanno di propria iniziativa e a proprio rischio, e sono responsabili del rispetto di tutte le leggi, le norme e i regolamenti locali a loro applicabili.</p><p>Utilizzando il Servizio, l'Utente accetta tutti i termini del documento “Condizioni d'uso” così come questo può essere redatto e applicato in qualsiasi momento.  </p><p>Utilizzando il Servizio, gli Utenti accettano di avere il diritto di utilizzare il Servizio secondo i termini presentati dal Fornitore al momento della richiesta di accesso al Servizio o come questi possono essere presentati esplicitamente nella sezione del documento “Licenza”.</p><p>In nessun caso un Utente potrà utilizzare il Servizio per svolgere attività dannose, che possono indicativamente e non esclusivamente riferirsi a: accesso o esposizione di dati personali o confidenziali di altre parti o Utenti, invio di codici dannosi ad altri Utenti o sistemi, sovraccarico intenzionale del Servizio o delle risorse del Fornitore, qualsiasi azione che provochi un impedimento del servizio per il Servizio o per qualsiasi servizio o risorsa di terze parti, impersonificazione del Fornitore, del suo personale o di qualsiasi Utente, impatto sullo stato finanziario o sociale del Fornitore, del suo personale o degli Utenti, ecc.</p><p>L'Utente si impegna a utilizzare le risorse fornite dal Servizio e il Servizio stesso per nessun altro motivo e con nessun altro mezzo se non quelli previsti dal Servizio. In caso di incertezza sulla validità di un utilizzo, l'Utente si impegna a richiedere ulteriori informazioni al Fornitore prima di effettuare tale utilizzo.</p><p>Gli Utenti si impegnano a informare tempestivamente il Fornitore di qualsiasi vulnerabilità o problema che abbiano identificato o di cui siano stati informati, durante l'utilizzo del Servizio. </p><p>Gli Utenti si impegnano a informare tempestivamente il Fornitore di qualsiasi dato, Informazioni, commento, codice, processo o altro elemento dannoso o comunque inappropriato reso disponibile sul Servizio di cui siano venuti a conoscenza.</p><p>Gli Utenti sono responsabili della gestione delle proprie credenziali e della sicurezza del proprio account. Gli Utenti sono tenuti a informare il Fornitore non appena vengono a conoscenza di un uso non autorizzato del proprio account.</p><p>Il Fornitore si riserva il diritto di intraprendere qualsiasi azione legale in caso di abuso del Servizio per proteggere gli interessi propri e dei propri Utenti. Il Fornitore può chiudere proattivamente l'account di un Utente e il relativo accesso al Servizio senza alcun preavviso, per evitare che il Servizio, le sue risorse o gli altri Utenti siano sospettati di azioni erronee o dannose da parte dell'Utente o di chiunque si spacci per tale.</p><p>Il Fornitore può modificare le “Condizioni d'uso” del Servizio, senza preavviso. Il Fornitore si impegna a notificare all'Utente i cambiamenti essenziali di questo documento o dei documenti che possono essere trattati, tuttavia ciò non è garantito.</p><p>L'Utente sarà tenuto a risarcire il Fornitore nel caso in cui eventuali richieste di risarcimento al Fornitore derivino dalla violazione di qualsiasi termine del presente documento “Condizioni d'uso” da parte dell'Utente. Tale risarcimento può includere e non è limitato alle sanzioni applicabili, alle richieste di danni da parte di terzi, ai danni etici e finanziari del Fornitore, agli sforzi e alle spese legali del Fornitore e a qualsiasi altro costo correlato.</p><h2>Validità (Effectiveness)</h2><p>Se una parte di questo documento “Termini d'uso” è privo di validità per qualsiasi motivo (ad esempio, illegale o sovrastato da un altro documento), il resto dell'accordo rimane valido ad esclusione della parte inefficace.</p><p>Il presente documento “Condizioni d'uso” è stipulato tra il Fornitore e l'Utente e non può in nessun caso essere trasferito a terzi dall'Utente.</p><p>Né l'Utente né il Fornitore possono essere ritenuti responsabili per qualsiasi violazione dei termini della presente Licenza che si verifichi a causa di condizioni al di fuori del loro ragionevole controllo (“Forza maggiore”).</p><p>Il Fornitore può astenersi dall'esercitare i diritti previsti dal presente documento “Condizioni d'uso” per qualsiasi motivo a sua scelta, in qualsiasi situazione e momento. Ciò non sarà considerato come una rinuncia al diritto di esercitare i rispettivi diritti in futuro per lo stesso caso, per casi simili o diversi.</p><h2>Il vostro consenso ai Termini</h2><p>L'accesso o l'utilizzo del Servizio e/o di qualsiasi risorsa fornita o a cui si accede attraverso di esso, in qualsiasi modo, implica che l'utente abbia letto, compreso e accettato di essere vincolato dai termini del presente documento.</p>",
    },
    COOKIE_POLICY: {
      CONTENT:
        '<h1>Eligence</h1><h2>Cooke Policy</h2><br><h2>Cookie List</h2><p>A cookie is a small piece of data (text file) that a website – when visited by a user – asks your browser to store on your device in order to remember information about you, such as your language preference or login information. Those cookies are set by us and called first-party cookies. We also use third-party cookies – which are cookies from a domain different than the domain of the website you are visiting – for our advertising and marketing efforts.</p><h2>Manage cookie settings</h2><p>On any page of the site, by clicking on the button on the bottom left corner the cookie banner will open and it will be possible to modify and reset your preferences; selecting “accept all cookies” you give the consent to use of all types of cookies, while you can withdraw your consent by clicking on “Refuse all cookies”. By deciding to close the banner, the preferences previously given will be kept until further modification. Opening the banner you can manage consents for the various types of cookies on the basis your preferences.</p><h2>Necessary Cookies</h2><p>These cookies are necessary for the website to function and cannot be switched off in our systems. Any Cookies or other tracking tools used by this Service, or by Other Providers of third-party services used by or through this Service, serve the purpose of providing the service required by the User, in addition to any other purposes described in the Privacy Policy.</p><h2>Analytics cookies</h2><p>Analytics cookies are cookies that track how users navigate and interact with this Service. The information collected is used to help the Service ‘s owner improve the Service.</p>',
      COOKIE: 'Cookie',
      DOMAIN: 'Domain',
      DESCRIPTION: 'Description',
      DURATION: 'Duration',
      TYPE: 'Type',
      PLL_LANGUAGE_DESCRIPTION:
        'The pll _language cookie is used by Polylang to remember the language selected by the user when returning to the website, and also to get the language information when not available in another way.',
      GA_STAR_DESCRIPTION:
        'Google Analytics sets this cookie to store and count page views.',
      GA_DESCRIPTION:
        'The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site’s analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.',
      ELEMENTOR_DESCRIPTION:
        'This cookie is used by the website’s WordPress theme. It allows the website owner to implement or change the website’s content in real-time.',
      ONE_YEAR: '1 year',
      ONE_YEAR_ONE_MONTH_4_DAYS: '1 year 1 month 4 days',
      NEVER: 'never',
      FUNCTIONAL: 'Functional',
      ANALYTICS: 'Analytics',
      NECESSARY: 'Necessary',
    },
  },
};
